<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Are you sure to delete this item?' => '××× ××ª× ×××× ×©××ª× ×¨××¦× ×××××§ ××ª ××¨×©××× ××××ª?',
  'Delete' => '×××§',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => '××¦×× {start}-{end} ××ª×× {count} ×ª××¦×××ª.',
  'No' => '××',
  'No results found.' => '×× × ××¦×× ×¨×©××××ª.',
  'Not set' => '×× ×××××¨',
  'Please specify the "attributes" property.' => '×× × ××××¨ ××ª ××××¤××× "attributes".',
  'Please specify the "model" property.' => '×× × ××××¨ ××ª ××××¤××× "model".',
  'Sort by: ' => '×××× ×¢"×¤:',
  'The "dataProvider" property cannot be empty.' => '××××¤××× "dataProvider" ×× ×××× ×××××ª ×¨××§.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => '××××¤××× ×¦×¨×× ×××××ª ×××××¨ ××¤××¨×× "Name:Type:Label", ××© "Type" × "Label" ×× ×××¤×¦××× ×××.',
  'The property "itemView" cannot be empty.' => '××××¤××× "itemView" ×× ×××× ×××××ª ×¨××§.',
  'Total 1 result.|Total {count} results.' => '×¡× ××× {count} ×ª××¦×××ª',
  'Unknown type "{type}".' => '×¡×× ×× ××××¢ "{type}".',
  'Update' => '×¢×××',
  'View' => '×¦×¤×',
  'Yes' => '××',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} ×××× ××××××¨ ××ª ××××¤××× ×× "model" × "attribute" ×× "name".',
);