<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Home' => 'ÐÐ¾Ð»Ð¾Ð²Ð½Ð°',
  'The button type "{type}" is not supported.' => 'Ð¢Ð¸Ð¿ ÐºÐ½Ð¾Ð¿ÐºÐ¸ "{type}" Ð½Ðµ Ð¿ÑÐ´ÑÑÐ¸Ð¼ÑÑÑÑÑÑ.',
  'Are you sure you want to delete this item?' => 'ÐÐ¸ Ð²Ð¿ÐµÐ²Ð½ÐµÐ½Ñ, ÑÐ¾ ÑÐ¾ÑÐµÑÐµ Ð²Ð¸Ð´Ð°Ð»Ð¸ÑÐ¸ ÑÐµÐ¹ ÐµÐ»ÐµÐ¼ÐµÐ½Ñ?',
  'Delete' => 'ÐÐ¸Ð´Ð°Ð»Ð¸ÑÐ¸',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'ÐÐ»ÐµÐ¼ÐµÐ½ÑÐ¸ {start}â{end} ÑÐ· {count}.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'ÐÐ»Ñ CDataColumn Ð½ÐµÐ¾Ð±ÑÑÐ´Ð½Ð¾ Ð²ÐºÐ°Ð·Ð°ÑÐ¸ Ð°Ð±Ð¾ "name" Ð°Ð±Ð¾ "value".',
  'No results found.' => 'ÐÐµÐ¼Ð°Ñ ÑÐµÐ·ÑÐ»ÑÑÐ°ÑÑÐ².',
  'Not set' => 'ÐÐµ Ð·Ð°Ð´Ð°Ð½Ð¸Ð¹',
  'Please specify the "attributes" property.' => 'ÐÐ¸Ð·Ð½Ð°ÑÑÐµ Ð²Ð»Ð°ÑÑÐ¸Ð²ÑÑÑÑ "attributes".',
  'Please specify the "data" property.' => 'ÐÐ¸Ð·Ð½Ð°ÑÑÐµ Ð²Ð»Ð°ÑÑÐ¸Ð²ÑÑÑÑ "data".',
  'Sort by: ' => 'Ð¡Ð¾ÑÑÑÐ²Ð°Ð½Ð½Ñ: ',
  'The "dataProvider" property cannot be empty.' => 'ÐÐ»Ð°ÑÑÐ¸Ð²ÑÑÑÑ "dataProvider" Ð½Ðµ Ð¼Ð¾Ð¶Ðµ Ð±ÑÑÐ¸ Ð¿Ð¾ÑÐ¾Ð¶Ð½ÑÐ¾Ñ.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'ÐÑÑÐ¸Ð±ÑÑ Ð¿Ð¾Ð²Ð¸Ð½ÐµÐ½ Ð±ÑÑÐ¸ Ð·Ð°Ð´Ð°Ð½Ð¸Ð¹ Ñ ÑÐ¾ÑÐ¼Ð°ÑÑ "ÐÐ¼Ê¼Ñ:Ð¢Ð¸Ð¿:ÐÐ°Ð³Ð¾Ð»Ð¾Ð²Ð¾Ðº". "Ð¢Ð¸Ð¿" ÑÐ° "ÐÐ°Ð³Ð¾Ð»Ð¾Ð²Ð¾Ðº" Ð½Ðµ Ð¾Ð±Ð¾Ð²Ê¼ÑÐ·ÐºÐ¾Ð²Ñ.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Ð¡ÑÐ¾Ð²Ð¿ÐµÑÑ Ð¿Ð¾Ð²Ð¸Ð½ÐµÐ½ Ð±ÑÑÐ¸ Ð·Ð°Ð´Ð°Ð½Ð¸Ð¹ Ñ ÑÐ¾ÑÐ¼Ð°ÑÑ "Name:Type:Label". "Ð¢Ð¸Ð¿" ÑÐ° "ÐÐ°Ð³Ð¾Ð»Ð¾Ð²Ð¾Ðº" Ð½Ðµ Ð¾Ð±Ð¾Ð²Ê¼ÑÐ·ÐºÐ¾Ð²Ñ.',
  'The property "itemView" cannot be empty.' => 'ÐÐ»Ð°ÑÑÐ¸Ð²ÑÑÑÑ "itemView" Ð½Ðµ Ð¼Ð¾Ð¶Ðµ Ð±ÑÑÐ¸ Ð¿Ð¾ÑÐ¾Ð¶Ð½ÑÐ¾Ñ.',
  'Total 1 result.|Total {count} results.' => 'ÐÑÑÐ¾Ð³Ð¾ {count} ÑÐµÐ·ÑÐ»ÑÑÐ°Ñ.|ÐÑÑÐ¾Ð³Ð¾ {count} ÑÐµÐ·ÑÐ»ÑÑÐ°ÑÐ°.|ÐÑÑÐ¾Ð³Ð¾ {count} ÑÐµÐ·ÑÐ»ÑÑÐ°ÑÑÐ².|ÐÑÑÐ¾Ð³Ð¾ {count} ÑÐµÐ·ÑÐ»ÑÑÐ°ÑÐ°.',
  'Update' => 'Ð ÐµÐ´Ð°Ð³ÑÐ²Ð°ÑÐ¸',
  'View' => 'ÐÐµÑÐµÐ³Ð»ÑÐ½ÑÑÐ¸',
  '{class} must specify "model" and "attribute" or "name" property values.' => 'ÐÐ»Ð°Ñ {class} Ð¿Ð¾Ð²Ð¸Ð½ÐµÐ½ Ð²Ð¸Ð·Ð½Ð°ÑÐ°ÑÐ¸ Ð·Ð½Ð°ÑÐµÐ½Ð½Ñ Ð²Ð»Ð°ÑÑÐ¸Ð²Ð¾ÑÑÐµÐ¹ "model" ÑÐ° "attribute", Ð°Ð±Ð¾ Ð·Ð½Ð°ÑÐµÐ½Ð½Ñ "name".',
);
