<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Are you sure you want to delete this item?' => 'Ð¡Ð¸Ð³ÑÑÐ½Ð¸ Ð»Ð¸ ÑÑÐµ ÑÐµ Ð¸ÑÐºÐ°ÑÐµ Ð´Ð° Ð¸Ð·ÑÑÐ¸ÐµÑÐµ ÑÐ¾Ð·Ð¸ ÐµÐ»ÐµÐ¼ÐµÐ½Ñ?',
  'Home' => 'ÐÐ°ÑÐ°Ð»Ð¾',
  'The button type "{type}" is not supported.' => 'ÐÐµ ÑÐµ Ð¿Ð¾Ð´Ð´ÑÑÐ¶Ð° Ð±ÑÑÐ¾Ð½ Ð¾Ñ ÑÐ¸Ð¿ "{type}"',
  'Delete' => 'ÐÐ·ÑÑÐ¸Ð¹',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'ÐÐ¾ÐºÐ°Ð·Ð²Ð°Ð½Ðµ Ð½Ð° {start}-{end} Ð¾Ñ {count}.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'ÐÐ»Ð¸ "name" Ð¸Ð»Ð¸ "value" ÑÑÑÐ±Ð²Ð° Ð´Ð° Ð±ÑÐ´Ð°Ñ Ð¿Ð¾ÑÐ¾ÑÐµÐ½Ð¸ Ð·Ð° CDataColumn.',
  'No results found.' => 'ÐÑÐ¼Ð° Ð½Ð°Ð¼ÐµÑÐµÐ½Ð¸ ÑÐµÐ·ÑÐ»ÑÐ°ÑÐ¸.',
  'Not set' => 'ÐÐµ Ðµ Ð¿Ð¾ÑÐ¾ÑÐµÐ½Ð¾',
  'Please specify the "attributes" property.' => 'ÐÐ¾Ð»Ñ, Ð¿Ð¾ÑÐ¾ÑÐµÑÐµ "attributes" ÑÐ²Ð¾Ð¹ÑÑÐ²Ð¾ÑÐ¾.',
  'Please specify the "data" property.' => 'ÐÐ¾Ð»Ñ, Ð¿Ð¾ÑÐ¾ÑÐµÑÐµ "data" ÑÐ²Ð¾Ð¹ÑÑÐ²Ð¾ÑÐ¾.',
  'Sort by: ' => 'Ð¡Ð¾ÑÑÐ¸ÑÐ°Ð½Ðµ Ð¿Ð¾:',
  'The "dataProvider" property cannot be empty.' => 'Ð¡Ð²Ð¾Ð¹ÑÑÐ²Ð¾ÑÐ¾ "dataProvider" Ð½Ðµ Ð¼Ð¾Ð¶Ðµ Ð´Ð° Ð±ÑÐ´Ðµ Ð¿ÑÐ°Ð·Ð½Ð¾.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Ð¡Ð²Ð¾Ð¹ÑÑÐ²Ð¾ÑÐ¾ ÑÑÑÐ±Ð²Ð° Ð´Ð° Ð±ÑÐ´Ðµ Ð²ÑÐ²ÐµÐ´ÐµÐ½Ð¾ Ð²ÑÐ² ÑÐ¾ÑÐ¼Ð°Ñ "Name:Type:Label", ÐºÑÐ´ÐµÑÐ¾ "Type" Ð¸ "Label" Ð½Ðµ ÑÐ° Ð·Ð°Ð´ÑÐ»Ð¶Ð¸ÑÐµÐ»Ð½Ð¸.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'ÐÐ¾Ð»Ð¾Ð½Ð°ÑÐ° ÑÑÑÐ±Ð²Ð° Ð´Ð° Ð±ÑÐ´Ðµ Ð¿Ð¾ÑÐ¾ÑÐµÐ½Ð° Ð²ÑÐ² ÑÐ¾ÑÐ¼Ð°Ñ "Name:Typ:Label", ÐºÑÐ´ÐµÑÐ¾ "Typ" Ð¸ "Label" Ð½Ðµ ÑÐ° Ð·Ð°Ð´ÑÐ»Ð¶Ð¸ÑÐµÐ»Ð½Ð¸.',
  'The property "itemView" cannot be empty.' => 'Ð¡Ð²Ð¾Ð¹ÑÑÐ²Ð¾ÑÐ¾ "itemView" Ð½Ðµ Ð¼Ð¾Ð¶Ðµ Ð´Ð° Ð±ÑÐ´Ðµ Ð¿ÑÐ°Ð·Ð½Ð¾.',
  'Total 1 result.|Total {count} results.' => 'ÐÐ±ÑÐ¾ {count} ÑÐµÐ·ÑÐ»ÑÐ°ÑÐ°',
  'Update' => 'Ð ÐµÐ´Ð°ÐºÑÐ¸ÑÐ°Ð½Ðµ',
  'View' => 'ÐÑÐµÐ³Ð»ÐµÐ´',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} ÑÑÑÐ±Ð²Ð° Ð´Ð° Ð¸Ð¼Ð° Ð¾ÑÐ±ÐµÐ»ÑÐ·Ð°Ð½Ð¸ "model" Ð¸Ð»Ð¸ "attribute" Ð¸Ð»Ð¸ "name" ÑÐ²Ð¾Ð¹ÑÑÐ²Ð°.',
);

?>
