<?php
/**
 * Message translations for [cs].
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Are you sure you want to delete this item?' => 'Odstranit zÃ¡znam?',
  'Delete' => 'Odstranit',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'ZobrazenÃ½ch {start}-{end} z celkovÄ {count} zÃ¡znamÅ¯.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'UveÄte prosÃ­m  "name" nebo "value" pro CDataColumn.',
  'Home' => 'DomÅ¯',
  'No results found.' => 'Nenalezeny Å¾Ã¡dnÃ© zÃ¡znamy.',
  'Not set' => 'NenÃ­ nastavenÃ½',
  'Please specify the "attributes" property.' => 'Zadejte prosÃ­m vlastnosti pro "attributes".',
  'Please specify the "data" property.' => 'Zadejte prosÃ­m vlastnosti pro "data".',
  'Sort by: ' => 'SeÅazenÃ© podle:',
  'The "dataProvider" property cannot be empty.' => 'Vlastnost "dataProvider" nesmÃ­ bÃ½t prÃ¡zdnÃ¡.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Atribut musÃ­ bÃ½t specifikovanÃ½ ve tvaru "Name:Type:Label", pÅiÄemÅ¾ "Type" a "Label" jsou nepovinnÃ©.',
  'The button type "{type}" is not supported.' => 'TlaÄÃ­tko typu "{type}" nenÃ­ podporovanÃ©.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Sloupec musÃ­ bÃ½t specifikovanÃ½ ve tvaru "Name:Type:Label", priÄemÅ¾ "Type" a "Label" jsou nepovinnÃ©.',
  'The property "itemView" cannot be empty.' => 'Vlastnost "itemView" nesmÃ­ bÃ½t prÃ¡zdnÃ¡.',
  'Total 1 result.|Total {count} results.' => 'Celkem nalezeno {count} zÃ¡znamÅ¯',
  'Update' => 'UloÅ¾it zmÄny',
  'View' => 'NÃ¡hled',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} musÃ­ mÃ­t specifikovanÃ© vlastnosti pro "model" a "attribute" nebo "name".',
);
