<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '{class} must specify "model" and "{attribute}" or "{name}" property values.' => 'Î ÎºÎ»Î¬ÏÎ· {class} ÏÏÎ­ÏÎµÎ¹ Î½Î± Î¿ÏÎ¯ÏÎµÎ¹ ÏÎ¹Ï Î¹Î´Î¹ÏÏÎ·ÏÎµÏ "model" ÎºÎ±Î¹ "{attribute}" Î® "{name}".',
  'Are you sure you want to delete this item?' => 'ÎÎ¯ÏÏÎµ ÏÎ¯Î³Î¿ÏÏÎ¿Ï ÏÏÎ¹ Î¸Î­Î»ÎµÏÎµ Î½Î± Î´Î¹Î±Î³ÏÎ¬ÏÎµÏÎµ ÏÎ¿ Î±Î½ÏÎ¹ÎºÎµÎ¯Î¼ÎµÎ½Î¿;',
  'Delete' => 'ÎÎ¹Î±Î³ÏÎ±ÏÎ®',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'ÎÎ¼ÏÎ¬Î½Î¹ÏÎ· {start}-{end} Î±ÏÏ 1 Î±ÏÎ¿ÏÎ­Î»ÎµÏÎ¼Î±.|ÎÎ¼ÏÎ¬Î½Î¹ÏÎ· {start}-{end} Î±ÏÏ {count} Î±ÏÎ¿ÏÎµÎ»Î­ÏÎ¼Î±ÏÎ±.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'Î ÏÎ­ÏÎµÎ¹ Î½Î± Î¿ÏÎ¹ÏÏÎµÎ¯ ÎµÎ¯ÏÎµ ÏÎ¿ "ÏÎ½Î¿Î¼Î±" ÎµÎ¯ÏÎµ Î· "ÏÎ¹Î¼Î®" Î³Î¹Î± ÏÎ¿ CDataColumn.',
  'Home' => 'ÎÏÏÎ¹ÎºÎ®',
  'No results found.' => 'ÎÎµ Î²ÏÎ­Î¸Î·ÎºÎ±Î½ Î±ÏÎ¿ÏÎµÎ»Î­ÏÎ¼Î±ÏÎ±.',
  'Not set' => 'ÎÎµÎ½ Î­ÏÎµÎ¹ Î¿ÏÎ¹ÏÏÎµÎ¯',
  'Please specify the "attributes" property.' => 'ÎÎ±Î¸Î¿ÏÎ¯ÏÏÎµ ÏÎ·Î½ Î¹Î´Î¹ÏÏÎ·ÏÎ± "attributes".',
  'Please specify the "data" property.' => 'ÎÎ±Î¸Î¿ÏÎ¯ÏÏÎµ ÏÎ·Î½ Î¹Î´Î¹ÏÏÎ·ÏÎ± "data".',
  'Sort by: ' => 'Î¤Î±Î¾Î¹Î½ÏÎ¼Î·ÏÎ· ÎºÎ±ÏÎ¬: ',
  'The "dataProvider" property cannot be empty.' => 'Î Î¹Î´Î¹ÏÏÎ·ÏÎ± "dataProvider" Î´ÎµÎ½ Î¼ÏÎ¿ÏÎµÎ¯ Î½Î± Î¼Î·Î½ Î­ÏÎµÎ¹ ÏÎ¹Î¼Î®.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Î Î¹Î´Î¹ÏÏÎ·ÏÎ± ÏÏÎ­ÏÎµÎ¹ Î½Î± Î¿ÏÎ¹ÏÏÎµÎ¯ ÏÏÎ· Î¼Î¿ÏÏÎ® "ÎÎ½Î¿Î¼Î±:Î¤ÏÏÎ¿Ï:ÎÏÎ¹ÎºÎ­ÏÎ±", ÏÏÎ¿Ï "Î¤ÏÏÎ¿Ï" ÎºÎ±Î¹ "ÎÏÎ¹ÎºÎ­ÏÎ±" ÎµÎ¯Î½Î±Î¹ ÏÏÎ¿Î±Î¹ÏÎµÏÎ¹ÎºÎ¬.',
  'The button type "{type}" is not supported.' => 'Î ÏÏÏÎ¿Ï ÎºÎ¿ÏÎ¼ÏÎ¹Î¿Ï "{type}" Î´ÎµÎ½ ÏÏÎ¿ÏÏÎ·ÏÎ¯Î¶ÎµÏÎ±Î¹.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Î ÏÏÎ®Î»Î· ÏÏÎ­ÏÎµÎ¹ Î½Î± Î¿ÏÎ¹ÏÏÎµÎ¯ ÏÏÎ· Î¼Î¿ÏÏÎ® "ÎÎ½Î¿Î¼Î±:Î¤ÏÏÎ¿Ï:ÎÏÎ¹ÎºÎ­ÏÎ±", ÏÏÎ¿Ï "Î¤ÏÏÎ¿Ï" ÎºÎ±Î¹ "ÎÏÎ¹ÎºÎ­ÏÎ±" ÎµÎ¯Î½Î±Î¹ ÏÏÎ¿Î±Î¹ÏÎµÏÎ¹ÎºÎ¬.',
  'The property "itemView" cannot be empty.' => 'Î Î¹Î´Î¹ÏÏÎ·ÏÎ± "itemView" Î´ÎµÎ½ Î¼ÏÎ¿ÏÎµÎ¯ Î½Î± Î¼Î·Î½ Î­ÏÎµÎ¹ ÏÎ¹Î¼Î®.',
  'The property filterSelector should be defined.' => 'Î ÏÎ­ÏÎµÎ¹ Î½Î± Î¿ÏÎ¹ÏÏÎµÎ¯ Î· Î¹Î´Î¹ÏÏÎ·ÏÎ± filterSelector.',
  'The property updateSelector should be defined.' => 'Î ÏÎ­ÏÎµÎ¹ Î½Î± Î¿ÏÎ¹ÏÏÎµÎ¯ Î· Î¹Î´Î¹ÏÏÎ·ÏÎ± updateSelector.',
  'Total 1 result.|Total {count} results.' => 'Î£ÏÎ½Î¿Î»Î¹ÎºÎ¬ 1 Î±ÏÎ¿ÏÎ­Î»ÎµÏÎ¼Î±.|Î£ÏÎ½Î¿Î»Î¹ÎºÎ¬ {count} Î±ÏÎ¿ÏÎµÎ»Î­ÏÎ¼Î±ÏÎ±.',
  'Update' => 'ÎÎ½Î·Î¼Î­ÏÏÏÎ·',
  'View' => 'ÎÎ¼ÏÎ¬Î½Î¹ÏÎ·',
);
