<?php
/**
 * Persian (Farsi) Translation
 * By : Bamdad Dashtban (bamdadd@gmail.com)
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Active record class "{class}" does not have a scope named "{scope}".' => 'Ø§Ú©ØªÛÙ Ø±Ú©ÙØ±Ø¯ Ø¨Ø§ ÙØ§Ù Ú©ÙØ§Ø³ {class} Ø§Ø³Ú©ÙÙ¾Û Ø¨Ø§ ÙØ§Ù  {scope} ÙØ¯Ø§Ø±Ø¯.',
  'Active record "{class}" has an invalid configuration for relation "{relation}". It must specify the relation type, the related active record class and the foreign key.' => 'Ø§Ú©ØªÛÙ Ø±Ú©ÙØ±Ø¯ "{class}" Ù¾ÛÚ©Ø±Ø¨ÙØ¯Û ÙØ¹ØªØ¨Ø± Ø¨Ø±Ø§Û Ø±Ø§Ø¨Ø·Ù "{relation}" Ø¯Ø§Ø±Ø¯.Ø¨Ø§ÛØ¯ ÙÙØ¹ Ø±Ø§Ø¨Ø·Ù Ø Ú©ÙØ§Ø³ Ø§Ú©ØªÛÙ Ø±Ú©ÙØ±Ø¯ ÙØ±ØªØ¨Ø· Ù Ú©ÙÛØ¯ Ø®Ø§Ø±Ø¬Û Ø±Ø§ ÙØ´Ø®Øµ Ú©ÙØ¯.',
  'Active record "{class}" is trying to select an invalid column "{column}". Note, the column must exist in the table or be an expression with alias.' => 'Ø§Ú©ØªÛÙ Ø±Ú©ÙØ±Ø¯ "{class}" Ø³Ø¹Û ÙÛ Ú©ÙØ¯ Ø³ØªÙÙ ÙØ§ÙØ¹ØªØ¨Ø± "{column}" Ø±Ø§ Ø§ÙØªØ®Ø§Ø¨ Ú©ÙØ¯.',
  'Active Record requires a "db" CDbConnection application component.' => ' Ø§Ú©ØªÛÙ Ø±Ú©ÙØ±Ø¯ ÙÛØ§Ø² Ø¨Ù ÛÚ© Ú©Ø§ÙÙ¾ÙÙÙØª Ø§Ù¾ÙÛÚ©ÛØ´Ù "db" CDbConnection Ø¯Ø§Ø±Ø¯.',
  'Alias "{alias}" is invalid. Make sure it points to an existing directory or file.' => 'Alias "{alias}" ÙØ§ÙØ¹ØªØ¨Ø± Ø§Ø³Øª .Ø§Ø·ÙÛÙØ§Ù Ø­Ø§ØµÙ Ú©ÙÛØ¯ Ø¨Ù ÛÚ© ÙØ§Ø¨Ù ÛØ§ Ø¯Ø§ÛØ±Ú©ØªÙØ±Û ÙÙØ¬Ù Ø§Ø´Ø§Ø±Ù ÙÛ Ú©ÙØ¯.',
  'Application base path "{path}" is not a valid directory.' => 'ÙØ³ÛØ± Ø¨ÛØ³ Ø§Ù¾ÙÛÚ©ÛØ´Ù "{path}" Ø¯Ø§ÛØ±Ú©ØªÙØ±Û ÙØ¹ØªØ¨Ø±Û ÙÙÛ Ø¨Ø§Ø´Ø¯.',
  'Application runtime path "{path}" is not valid. Please make sure it is a directory writable by the Web server process.' => 'ÙØ³ÛØ± Ø²ÙØ§Ù Ø§Ø¬Ø±Ø§ Ø§Ù¾ÙÛÚ©ÛØ´Ù ÙØ¹ØªØ¨Ø± ÙÛØ³Øª. Ø§Ø·ÙÛÙØ§Ù Ø­Ø§ØµÙ Ú©ÙÛØ¯ Ø§ÛÙ Ø¯Ø§ÛØ±Ú©ØªÙØ±Û ÙØ§Ø¨Ù ÙÙØ´ØªÙ ØªÙØ³Ø· ÙØ¨ Ø³Ø±ÙØ± ÙÛ Ø¨Ø§Ø´Ø¯.',
  '{attribute} cannot be blank.' => '{attribute} ÙÙÛ ØªÙØ§ÙØ¯ Ø®Ø§ÙÛ Ø¨Ø§Ø´Ø¯.',
  '{attribute} is invalid.' => '{attribute} ÙØ§ÙØ¹ØªØ¨Ø± Ø§Ø³Øª.',
  '{attribute} is not a valid email address.' => '{attribute} ÛÚ© Ø¢Ø¯Ø±Ø³ Ø§ÛÙÛÙ ÙØ¹ØªØ¨Ø± ÙÙÛ Ø¨Ø§Ø´Ø¯.',
  '{attribute} is not a valid URL.' => '{attribute} ÛÚ© URL ÙØ¹ØªØ¨Ø± ÙÙÛ Ø¨Ø§Ø´Ø¯.',
  '{attribute} is not in the list.' => '{attribute} Ø¯Ø± ÙÛØ³Øª ÙÛØ³Øª.',
  '{attribute} is of the wrong length (should be {length} characters).' => '{attribute} Ø¯Ø§Ø±Ø§Û Ø·ÙÙ Ø§Ø´ØªØ¨Ø§Ù Ø§Ø³Øª ( Ø¨Ø§Ø´Ø¯characters {length} Ø¨Ø§ÛØ¯)',
  '{attribute} is too big (maximum is {max}).' => '{attribute} Ø¨Ø³ÛØ§Ø± Ø¨Ø²Ø±Ú¯ Ø§Ø³Øª. ({max}Ø­Ø¯Ø§Ú©Ø«Ø±)',
  '{attribute} is too long (maximum is {max} characters).' => '{attribute} Ø¨Ø³ÛØ§Ø± Ø·ÙÛÙ Ø§Ø³Øª. (ÙÛ Ø¨Ø§Ø´Ø¯ {max}Ø­Ø¯Ø§Ú©Ø«Ø± Ú©Ø§Ø±Ø§Ú©ØªØ±)',
  '{attribute} is too short (minimum is {min} characters).' => '{attribute} Ø¨Ø³ÛØ§Ø± Ú©ÙØªØ§Ù Ø§Ø³Øª. (Ø­Ø¯Ø§ÙÙ {min} Ú©Ø§Ø±Ø§Ú©ØªØ± Ø¨Ø§ÛØ¯ ÙØ§Ø±Ø¯ Ø´ÙØ¯.)',
  '{attribute} is too small (minimum is {min}).' => '{attribute} Ø¨Ø³ÛØ§Ø± Ú©ÙÚÚ© Ø§Ø³Øª.(ÙÛ Ø¨Ø§Ø´Ø¯ {min}Ø­Ø¯Ø§ÙÙ)',
  '{attribute} must be an integer.' => '  integer Ø¨Ø§Ø´Ø¯Ø¨Ø§ÛØ¯ {attribute}.',
  '{attribute} must be a number.' => '{attribute} Ø¨Ø§ÛØ¯ Ø¹Ø¯Ø¯ Ø¨Ø§Ø´Ø¯.',
  '{attribute} must be either {true} or {false}.' => '{attribute} Ø¨Ø§ÛØ¯ {true} ÛØ§ {false} Ø¨Ø§Ø´Ø¯.',
  '{attribute} must be greater than "{compareValue}".' => '{attribute} Ø¨Ø§ÛØ¯ Ø§Ø² "{compareValue}" Ø¨Ø²Ø±Ú¯ØªØ± Ø¨Ø§Ø´Ø¯.',
  '{attribute} must be greater than or equal to "{compareValue}".' => '{attribute} Ø¨Ø§ÛØ¯ Ø¨Ø²Ø±Ú¯ØªØ± ÙØ³Ø§ÙÛ "{compareValue}" Ø¨Ø§Ø´Ø¯.',
  '{attribute} must be less than "{compareValue}".' => '{attribute} Ø¨Ø§ÛØ¯ Ú©ÙÚÚ©ØªØ± Ø§Ø² "{compareValue}" Ø¨Ø§Ø´Ø¯.',
  '{attribute} must be less than or equal to "{compareValue}".' => '{attribute} Ø¨Ø§ÛØ¯ Ú©ÙÚÚ©ØªØ± ÙØ³Ø§ÙÛ "{compareValue}" Ø¨Ø§Ø´Ø¯.',
  '{attribute} must be repeated exactly.' => '{attribute} Ø¨Ø§ÛØ¯ Ø¯ÙÛÙØ§ ØªÚ©Ø±Ø§Ø± Ø´ÙØ¯.',
  '{attribute} must be {type}.' => '{attribute} Ø¨Ø§ÛØ¯ {type} Ø¨Ø§Ø´Ø¯.',
  '{attribute} must be {value}.' => '{attribute} Ø¨Ø§ÛØ¯ {value} Ø¨Ø§Ø´Ø¯.',
  '{attribute} must not be equal to "{compareValue}".' => '{attribute} ÙØ¨Ø§ÛØ¯ ÙØ³Ø§ÙÛ "{compareValue}" Ø¨Ø§Ø´Ø¯.',
  '{attribute} "{value}" has already been taken.' => '{attribute} "{value}" Ø¯Ø± Ø­Ø§Ù Ø­Ø§Ø¶Ø± Ú¯Ø±ÙØªÙ Ø´Ø¯Ù Ø§Ø³Øª.',
  '{attribute} "{value}" is invalid.' => '{attribute} "{value}" ÙØ§ÙØ¹ØªØ¨Ø± Ø§Ø³Øª.',
  'Authorization item "{item}" has already been assigned to user "{user}".' => 'Ø¢ÛØªÙ ÙØ¬ÙØ² "{item}" ÙØ¨ÙØ§ Ø¨Ù Ú©Ø§Ø±Ø¨Ø± "{user}" Ø§Ø®ØªØµØ§Øµ ÛØ§ÙØªÙ Ø§Ø³Øª.',
  'Base path "{path}" is not a valid directory.' => 'Base path "{path}" Ø¯Ø§ÛØ±Ú©ØªÙØ±Û ÙØ¹ØªØ¨Ø±Û ÙÙÛ Ø¨Ø§Ø´Ø¯',
  'Cannot add an item of type "{child}" to an item of type "{parent}".' => ' ÙÙÛ ØªÙØ§Ù Ø¢ÛØªÙ Ø§Ø² ÙÙØ¹ "{child}" "{parent}" Ø§Ø¶Ø§ÙÙ Ú©Ø±Ø¯ Ø±Ø§ ÙÙÛ ØªÙØ§Ù Ø¨Ù Ø¢ÛØªÙ Ø§Ø² ÙÙØ¹  ',
  'Cannot add "{child}" as a child of "{name}". A loop has been detected.' => 'ÙÙÛ ØªÙØ§Ù "{child}" Ø±Ø§ Ø¨Ù Ø¹ÙÙØ§Ù ÚØ§ÛÙØ¯Û Ø§Ø² "{name}" Ø§Ø¶Ø§ÙÙ Ú©Ø±Ø¯. ÙÙÙ¾ Ø´ÙØ§Ø³Ø§ÛÛ Ø´Ø¯Ù Ø§Ø³Øª',
  'Cannot add "{child}" as a child of "{parent}". A loop has been detected.' => 'ÙÙÛ ØªÙØ§Ù "{child}" Ø±Ø§ Ø¨Ù Ø¹ÙÙØ§Ù ÚØ§ÛÙØ¯Û Ø§Ø² "{parent}" Ø§Ø¶Ø§ÙÙ Ú©Ø±Ø¯. ÙÙÙ¾ Ø´ÙØ§Ø³Ø§ÛÛ Ø´Ø¯',
  'Cannot add "{name}" as a child of itself.' => 'ÙÙÛ ØªÙØ§Ù "{name}" Ø±Ø§ Ø¨Ù Ø¹ÙÙØ§Ù ÚØ§ÛÙØ¯ Ø®ÙØ¯Ø´ Ø§Ø¶Ø§ÙÙ Ú©Ø±Ø¯',
  'CApcCache requires PHP apc extension to be loaded.' => 'CApcCache ÙÛØ§Ø² Ø¨Ù PHP apc extension Ø¯Ø§Ø±Ø¯ Ø¨Ø±Ø§Û ÙÙØ¯ Ø´Ø¯Ù',
  'CAssetManager.basePath "{path}" is invalid. Please make sure the directory exists and is writable by the Web server process.' => 'CAssetManager.basePath "{path}" ÙØ§ÙØ¹ØªØ¨Ø± ÙÛ Ø¨Ø§Ø´Ø¯.Ø§Ø·ÙÛÙØ§Ù Ø­Ø§ØµÙ Ú©ÙÛØ¯ Ú©Ù Ø¯Ø§ÛØ±Ú©ØªÙØ±Û ÙØ¬ÙØ¯ Ø¯Ø§Ø±Ø¯ Ù ÙØ§Ø¨Ù ÙÙØ´ØªÙ ØªÙØ³Ø· ÙØ¨ Ø³Ø±ÙØ± ÙÛ Ø¨Ø§Ø´Ø¯',
  'CCacheHttpSession.cacheID is invalid. Please make sure "{id}" refers to a valid cache application component.' => 'CCacheHttpSession.cacheID ÙØ§ÙØ¹ØªØ¨Ø± Ø§Ø³Øª.Ø§Ø·ÙÛÙØ§Ù Ø­Ø§ØµÙ Ú©ÙÛØ¯ ÙÙ "{id}" Ø¨Ù Ú©Ø§ÙÙ¾ÙÙÙØª Ø§Ù¾ÙÛÚ©ÛØ´Ù Ú©Ø´ ÙØ¹ØªØ¨Ø± Ø§Ø±Ø¬Ø§Ø¹ Ø¯Ø§Ø¯Ù ÙÛ Ø´ÙØ¯',
  'CCaptchaValidator.action "{id}" is invalid. Unable to find such an action in the current controller.' => 'CCaptchaValidator.action "{id}" ÙØ§ÙØ¹ØªØ¨Ø± Ø§Ø³Øª.ÙØ§Ø¯Ø± Ø¨Ù ÛØ§ÙØªÙ Ø§ÛÙ Ø¹ÙÙ Ø¯Ø± Ú©ÙØªØ±ÙØ± Ø¬Ø§Ø±Û ÙÙÛ Ø¨Ø§Ø´Ø¯',
  'CDbAuthManager.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbAuthManager.connectionID "{id}" ID Ø§Ø²ÙØ§ÙØ¹ØªØ¨Ø± Ø§Ø³Øª. Ø§Ø·ÙÛÙØ§Ù Ø­Ø§ØµÙ Ú©ÙÛØ¯ Ú©Ù Ø¨ÙCDbConnection application component Ø§Ø´Ø§Ø±Ù ÙÛ Ú©ÙØ¯ ',
  'CDbCache.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbCache.connectionID "{id}" ÙØ§ÙØ¹ØªØ¨Ø± Ø§Ø³Øª.',
  'CDbCacheDependency.sql cannot be empty.' => 'CDbCacheDependency.sql ÙÙÛ ØªÙØ§ÙØ¯ Ø®Ø§ÙÛ Ø¨Ø§Ø´Ø¯',
  'CDbCommand failed to execute the SQL statement: {error}' => 'Ø®Ø·Ø§Û CDbCommand Ø¯Ø± Ø§Ø¬Ø±Ø§Û SQL statement: {error}',
  'CDbCommand failed to prepare the SQL statement: {error}' => 'Ø®Ø·Ø§Û CDbCommand Ø¯Ø± Ø¢ÙØ§Ø¯Ù Ú©Ø±Ø¯Ù Ø§Ø³ØªÛØªÙÙØª SQL : {error}',
  'CDbConnection.connectionString cannot be empty.' => 'CDbConnection.connectionString ÙÙÛ ØªÙØ§ÙØ¯ Ø®Ø§ÙÛ Ø¨Ø§Ø´Ø¯',
  'CDbConnection does not support reading schema for {driver} database.' => 'CDbConnection Ø´ÙØ§Û Ø®ÙØ§ÙØ¯Ù Ø¨Ø±Ø§Û Ù¾Ø§ÛÚ¯Ø§Ù Ø¯Ø§Ø¯Ù {driver} Ø±Ø§ Ø­ÙØ§ÛØª ÙÙÛ Ú©ÙØ¯',
  'CDbConnection failed to open the DB connection: {error}' => 'Ø®Ø·Ø§Û CDbConnection Ø¯Ø± Ø¨Ø§Ø² Ú©Ø±Ø¯Ù DB connection: {error}',
  'CDbConnection is inactive and cannot perform any DB operations.' => 'CDbConnection ØºÛØ± ÙØ¹Ø§Ù Ø§Ø³Øª Ù ÙÙÛ ØªÙØ§ÙØ¯ ÙÛÚ Ø¹ÙÙÛØ§Øª ÙØ±Ø¨ÙØ· Ø¨Ù DB Ø±Ø§Ø§Ø¬Ø±Ø§ Ú©ÙØ¯',
  'CDbDataReader cannot rewind. It is a forward-only reader.' => 'CDbDataReader ÙÙÛ ØªÙØ§ÙØ¯ rewind Ú©ÙØ¯. forward-only reader ÙÛ Ø¨Ø§Ø´Ø¯.',
  'CDbHttpSession.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbHttpSession.connectionID "{id}" ÙØ¹ØªØ¨Ø± ÙÙÛ Ø¨Ø§Ø´Ø¯.Ø§Ø·ÙÛÙØ§Ù Ø­Ø§ØµÙ Ú©ÙÛØ¯ Ú©Ù Ø¨Ù ÛÚ© ID Ø§Ø²Ú©Ø§ÙÙ¾ÙÙÙØª Ø§Ù¾ÙÛÚ©ÛØ´Ù CDbConnection Ø§Ø´Ø§Ø±Ù ÙÛ Ú©ÙØ¯. ',
  'CDbLogRoute.connectionID "{id}" does not point to a valid CDbConnection application component.' => 'CDbLogRoute.connectionID "{id}" Ø¨Ù Ú©Ø§ÙÙ¾ÙÙÙØª Ø§Ù¾ÙÛÚ©ÛØ´Ù CDbConnection ÙØ¹ØªØ¨Ø± Ø§Ø´Ø§Ø±Ù ÙÙÛ Ú©ÙØ¯',
  'CDbMessageSource.connectionID is invalid. Please make sure "{id}" refers to a valid database application component.' => 'CDbMessageSource.connectionID ÙØ¹ØªØ¨Ø± ÙÛØ³Øª.Ø§Ø·ÙÛÙØ§Ù Ø­Ø§ØµÙ Ú©ÙÛØ¯ "{id}" Ø¨Ù ÛÚ© Ú©Ø§ÙÙ¾ÙÙÙØª Ø§Ù¾ÙÛÚ©ÛØ´Ù Ù¾Ø§ÛÚ¯Ø§Ù Ø¯Ø§Ø¯Ù Ø§Ø´Ø§Ø±Ù ÙÛ Ú©ÙØ¯',
  'CDbTransaction is inactive and cannot perform commit or roll back operations.' => 'CDbTransaction ØºÛØ± ÙØ¹Ø§Ù ÙÛ Ø¨Ø§Ø´Ø¯ Ù ÙÙÛ ØªÙØ§ÙØ¯ Ø¹ÙÙÛØ§Øª commit ÛØ§  roll back Ø±Ø§ Ø§Ø¬Ø±Ø§ Ú©ÙØ¯',
  'CDirectoryCacheDependency.directory cannot be empty.' => 'CDirectoryCacheDependency.directory ÙÙÛ ØªÙØ§ÙØ¯ Ø®Ø§ÙÛ Ø¨Ø§Ø´Ø¯',
  'CEAcceleratorCache requires PHP eAccelerator extension to be loaded, enabled or compiled with the "--with-eaccelerator-shared-memory" option.' => 'CEAcceleratorCache Ø¨Ù Ø§Ú©Ø³ØªÙØ´Ù PHP eAccelerator Ø§Ø­ØªÛØ§Ø¬ Ø¯Ø§Ø±Ø¯ Ø¨Ø±Ø§Û ÙÙØ¯ Ø´Ø¯ÙÙ ÙØ¹Ø§Ù Ø´Ø¯Ù Ø¨Ø§ Ú¯Ø²ÛÙÙ "--with-eaccelerator-shared-memory"',
  'CFileCacheDependency.fileName cannot be empty.' => 'CFileCacheDependency.fileName ÙÙÛ ØªÙØ§ÙØ¯ Ø®Ø§ÙÛ Ø¨Ø§Ø´Ø¯',
  'CFileLogRoute.logPath "{path}" does not point to a valid directory. Make sure the directory exists and is writable by the Web server process.' => 'CFileLogRoute.logPath "{path}" Ø¨Ù Ø¯Ø§ÛØ±Ú©ØªÙØ±Û ÙØ¹ØªØ¨Ø± Ø§Ø´Ø§Ø±Ù ÙÙÛ Ú©ÙØ¯.ÙØ·ÙØ¦Ù Ø´ÙÛØ¯ Ø¯Ø§ÛØ±Ú©ØªÙØ±Û ÙÙØ¬ÙØ¯ ÙÛ Ø¨Ø§Ø´Ø¯ Ù ÙØ§Ø¨Ù ÙÙØ´ØªÙ ØªÙØ³Ø· ÙØ¨ Ø³Ø±ÙØ± ÙÛ Ø¨Ø§Ø³Ø¯',
  'CFilterChain can only take objects implementing the IFilter interface.' => 'CFilterChain ÙÙØ· ÙÛ ØªÙØ§ÙØ¯ Ø§Ø¨Ø¬Ú©ØªÙØ§ÛÛ Ø±Ø§ Ø¨Ú¯ÛØ±Ø¯ Ú©Ù IFilter interface Ø±Ø§ Ø§Ø¬Ø±Ø§ ÙÛ Ú©ÙÙØ¯ ',
  'CFlexWidget.baseUrl cannot be empty.' => 'CFlexWidget.baseUrl ÙÙÛ ØªÙØ§ÙØ¯ Ø®Ø§ÙÛ Ø¨Ø§Ø´Ø¯',
  'CFlexWidget.name cannot be empty.' => 'CFlexWidget.name ÙÙÛ ØªÙØ§ÙØ¯ Ø®Ø§ÙÛ Ø¨Ø§Ø´Ø¯',
  'CGlobalStateCacheDependency.stateName cannot be empty.' => 'CGlobalStateCacheDependency.stateName ÙÙÛ ØªÙØ§ÙØ¯ Ø®Ø§ÙÛ Ø¨Ø§Ø´Ø¯',
  'CHttpCookieCollection can only hold CHttpCookie objects.' => 'CHttpCookieCollection ØªÙÙØ§ ÙÛ ØªÙØ§ÙØ¯ Ø§Ø¨Ø¬Ú©ØªÙØ§Û CHttpCookie Ø±Ø§ ÙÚ¯Ù Ø¯Ø§Ø±Ø¯',
  'CHttpRequest is unable to determine the entry script URL.' => 'CHttpRequest ÙÙÛ ØªÙØ§ÙØ¯ URL Ø§Ø³Ú©Ø±ÛÙ¾Øª ÙØ±ÙØ¯Û Ø±Ø§ ØªØ¹ÛÛÙ Ú©ÙØ¯',
  'CHttpRequest is unable to determine the path info of the request.' => 'CHttpRequest ÙÙÛ ØªÙØ§ÙØ¯ Ø§Ø·ÙØ§Ø¹Ø§Øª ÙØ³ÛØ± Ø¯Ø±Ø®ÙØ§Ø³Øª Ø±Ø§ ØªØ´Ø®ÛØµ Ø¯ÙØ¯',
  'CHttpRequest is unable to determine the request URI.' => 'CHttpRequest ÙÙÛ ØªÙØ§ÙØ¯ Ø¯Ø±Ø®ÙØ§Ø³Øª URL Ø±Ø§ ØªØ´Ø®ÛØµ Ø¯ÙØ¯',
  'CHttpSession.cookieMode can only be "none", "allow" or "only".' => 'CHttpSession.cookieMode ØªÙÙØ§ ÙÛ ØªÙØ§ÙØ¯ "none", "allow" ÛØ§ "only" Ø¨Ø§Ø´Ø¯',
  'CHttpSession.gcProbability "{value}" is invalid. It must be an integer between 0 and 100.' => 'CHttpSession.gcProbability "{value}" ÙØ¹ØªØ¨Ø± ÙÛØ³Øª.Ø¨Ø§ÛØ¯ integer Ø¨ÛÙ 0 ØªØ§ 100 Ø¨Ø§Ø´Ø¯.',
  'CHttpSession.savePath "{path}" is not a valid directory.' => 'CHttpSession.savePath "{path}" Ø¯Ø§ÛØ±Ú©ØªÙØ±Û ÙØ¹ØªØ¨Ø±Û ÙÛØ³Øª',
  '{class}.allowAutoLogin must be set true in order to use cookie-based authentication.' => '{class}.allowAutoLogin Ø¨Ø§ÛØ¯ true Ø¨Ø§Ø´Ø¯ Ø¨Ù ÙÙØ¸ÙØ± Ø§Ø³ØªÙØ§Ø¯Ù Ø§Ø² cookie-based authentication',
  '{class}::authenticate() must be implemented.' => '{class}::authenticate() Ø¨Ø§ÛØ¯ Ø§Ø¬Ø±Ø§ Ø´ÙØ¯',
  '{class} does not have a method named "{name}".' => '{class} ÙØªØ¯Û Ø¨Ø§ ÙØ§Ù "{name}" ÙØ¯Ø§Ø±Ø¯.',
  '{class} does not have relation "{name}".' => '{class}  Ø±Ø§Ø¨Ø·Ù "{name}" ÙØ¯Ø§Ø±Ø¯.',
  '{class} does not support fetching all table names.' => '{class} Ø¯Ø±ÛØ§ÙØª ÙÙÙ ÙØ§ÙÙØ§Û Ø¬Ø¯ÙÙ Ø±Ø§ Ø³Ø§Ù¾ÙØ±Øª ÙÙÛ Ú©ÙØ¯.',
  '{class} has an invalid validation rule. The rule must specify attributes to be validated and the validator name.' => '',
  '{class} must specify "model" and "attribute" or "name" property values.' => '',
  '{className} does not support add() functionality.' => '{className} Ø¹ÙÙÚ©Ø±Ø¯ add() Ø±Ø§ Ù¾Ø´ØªÛØ¨Ø§ÙÛ ÙÙÛ Ú©ÙØ¯',
  '{className} does not support delete() functionality.' => '{className} Ø¹ÙÙÚ©Ø±Ø¯ delete() Ø±Ø§ Ù¾Ø´ØªÛØ¨Ø§ÙÛ ÙÙÛ Ú©ÙØ¯',
  '{className} does not support flush() functionality.' => '{className} Ø¹ÙÙÚ©Ø±Ø¯ flush() Ø±Ø§ Ù¾Ø´ØªÛØ¨Ø§ÙÛ ÙÙÛ Ú©ÙØ¯',
  '{className} does not support get() functionality.' => '{className} Ø¹ÙÙÚ©Ø±Ø¯ get() Ø±Ø§ Ù¾Ø´ØªÛØ¨Ø§ÙÛ ÙÙÛ Ú©ÙØ¯',
  '{className} does not support set() functionality.' => '{className} Ø¹ÙÙÚ©Ø±Ø¯ set() Ø±Ø§ Ù¾Ø´ØªÛØ¨Ø§ÙÛ ÙÙÛ Ú©ÙØ¯',
  'CMemCache server configuration must be an array.' => 'Ù¾ÛÚ©Ø±Ø¨ÙØ¯Û Ø³Ø±ÙØ± CMemCache  Ø¨Ø§ÛØ¯ Ø¢Ø±Ø§ÛÙ Ø¨Ø§Ø´Ø¯',
  'CMemCache server configuration must have "host" value.' => 'Ù¾ÛÚ©Ø±Ø¨ÙØ¯Û Ø³Ø±ÙØ± CMemCache Ø¨Ø§ÛØ¯ ÙÙØ¯Ø§Ø± "host" Ø±Ø§ Ø¯Ø§Ø´ØªÙ Ø¨Ø§Ø´Ø¯',
  'CMultiFileUpload.name is required.' => 'CMultiFileUpload.name Ø¶Ø±ÙØ±Û Ø§Ø³Øª',
  'Column "{column} does not exist in table "{table}".' => 'Ø³ØªÙÙ "{column}" Ø¯Ø± Ø¬Ø¯ÙÙ "{table}" ÙØ¬ÙØ¯ ÙØ¯Ø§Ø±Ø¯',
  'Column name must be either a string or an array.' => 'ÙØ§Ù Ø³ØªÙÙ Ø¨Ø§ÛØ¯ string ÛØ§ array Ø¨Ø§Ø´Ø¯',
  '{controller} cannot find the requested view "{view}".' => '{controller} ÙÙÛ ØªÙØ§ÙØ¯ ÙÙØ§Û Ø¯Ø± Ø®ÙØ§Ø³Øª Ø´Ø¯Ù "{view}" Ø±Ø§ Ù¾ÛØ¯Ø§ Ú©ÙØ¯',
  '{controller} contains improperly nested widget tags in its view "{view}". A {widget} widget does not have an endWidget() call.' => '{controller} Ø´Ø§ÙÙ ØªÚ¯ÙØ§Û ÙØ§Ø¯Ø±Ø³Øª ÙÛØ¬Øª Ø¯Ø± ÙØ³ÙØª ÙÙØ§ÛØ´ Ø¢Ù "{view}" ÙÛ Ø¨Ø§Ø´Ø¯',
  '{controller} has an extra endWidget({id}) call in its view.' => '{controller} ÙØ±Ø§Ø®ÙØ§Ù Ø²ÛØ§Ø¯Û Ø¨Ø±Ø§Û endWidget({id}) Ø¯Ø± ÙØ³ÙØª ÙÙØ§ÛØ´ Ø¯Ø§Ø±Ø¯',
  'CProfileLogRoute found a mismatching code block "{token}". Make sure the calls to Yii::beginProfile() and Yii::endProfile() be properly nested.' => 'CProfileLogRoute found a mismatching code block "{token}". Make sure the calls to Yii::beginProfile() and Yii::endProfile() be properly nested.',
  'CProfileLogRoute.report "{report}" is invalid. Valid values include "summary" and "callstack".' => 'CProfileLogRoute.report "{report}" ÙØ§ÙØ¹ØªØ¨Ø± ÙÛ Ø¨Ø§Ø´Ø¯.ÙÙØ§Ø¯ÛØ± ÙØ¹ØªØ¨Ø± Ø´Ø§ÙÙ "summary" Ù "callstack" ÙÛ Ø¨Ø§Ø´Ø¯',
  'CSecurityManager.encryptionKey cannot be empty.' => 'CSecurityManager.encryptionKey ÙÙÛ ØªÙØ§ÙØ¯ Ø®Ø§ÙÛ Ø¨Ø§Ø´Ø¯',
  'CSecurityManager requires PHP mcrypt extension to be loaded in order to use data encryption feature.' => 'CSecurityManager Ø¨Ù Ø§Ú©Ø³ØªÙØ´Ù PHP mcrypt ÙÛØ§Ø² Ø¯Ø§Ø±Ø¯ Ú©Ù ÙÙØ¯ Ø´ÙØ¯ Ø¨Ù ÙÙØ¸ÙØ± Ø§Ø³ØªÙØ§Ø¯Ù Ø§Ø² Ø¯Ø§Ø¯Ù ÙØ§Û Ø±ÙØ²Ú¯Ø°Ø§Ø±Û Ø´Ø¯Ù',
  'CSecurityManager.validationKey cannot be empty.' => 'CSecurityManager.validationKey ÙÙÛ ØªÙØ§ÙØ¯ Ø®Ø§ÙÛ Ø¨Ø§Ø´Ø¯',
  'CSecurityManager.validation must be either "MD5" or "SHA1".' => 'CSecurityManager.validation Ø¨Ø§ÛØ¯ "MD5" ÛØ§ "SHA1" Ø¨Ø§Ø´Ø¯',
  'CTypedList<{type}> can only hold objects of {type} class.' => 'CTypedList<{type}> ØªÙÙØ§ ÙÛ ØªÙØ§ÙØ¯ Ø§Ø¨Ø¬Ú©ØªÙØ§ÛÛ Ø§Ø² Ú©ÙØ§Ø³ {type} Ø±Ø§ ÙÚ¯Ù Ø¯Ø§Ø±Ø¯',
  'CUrlManager.UrlFormat must be either "path" or "get".' => 'CUrlManager.UrlFormat Ø¨Ø§ÛØ¯ "path" ÛØ§ "get" Ø¨Ø§Ø´Ø¯',
  'CXCache requires PHP XCache extension to be loaded.' => 'CXCache Ø¨Ù Ø§Ú©Ø³ØªÙØ´Ù PHP XCache ÙÛØ§Ø² Ø¯Ø§Ø±Ø¯ Ú©Ù ÙÙØ¯ Ø´ÙØ¯',
  'CZendDataCache requires PHP Zend Data Cache extension to be loaded.' => 'CZendDataCache Ø¨Ù Ø§Ú©Ø³ØªÙØ´Ù PHP Zend Data Cache ÙÛØ§Ø² Ø¯Ø§Ø±Ø¯ Ú©Ù ÙÙØ¯ Ø´ÙØ¯',
  'Either "{parent}" or "{child}" does not exist.' => '"{parent}" ÛØ§ "{child}" ÙØ¬ÙØ¯ ÙØ¯Ø§Ø±Ø¯',
  'Error: Table "{table}" does not have a primary key.' => ' Ø¬Ø¯ÙÙ "{table}" Ú©ÙÛØ¯ Ø§ØµÙÛ ÙØ¯Ø§Ø±Ø¯: Ø®Ø·Ø§',
  'Error: Table "{table}" has a composite primary key which is not supported by crud command.' => 'Ø¬Ø¯ÙÙ "{table}" Ú©ÙÛØ¯ Ø§ØµÙÛ ÙØ±Ú©Ø¨ Ø¯Ø§Ø±Ø¯ Ú©Ù ØªÙØ³Ø·  : Ø®Ø·Ø§ crud command Ù¾Ø´ØªÛØ¨Ø§ÙÛ ÙÙÛ Ø´ÙØ¯',
  'Event "{class}.{event}" is attached with an invalid handler "{handler}".' => 'Ø§ÛÙÙØª "{class}.{event}" Ù¾ÛÙØ³Øª ÙÙØ¯ÙØ± ÙØ§ÙØ¹ØªØ¨Ø± "{handler}" Ø§Ø³Øª',
  'Event "{class}.{event}" is not defined.' => 'Ø§ÛÙÙØª "{class}.{event}" ØªØ¹Ø±ÛÙ Ø´Ø¯Ù ÙÛØ³Øª',
  'Extension path "{path}" does not exist.' => 'ÙØ³ÛØ± Ø§Ú©Ø³ØªÙØ´Ù "{path}" ÙØ¬ÙØ¯ ÙØ¯Ø§Ø±Ø¯',
  'Failed to write the uploaded file "{file}" to disk.' => 'Ø®Ø·Ø§ Ø¯Ø± ÙÙØ´ØªÙ ÙØ§ÛÙ Ø¢Ù¾ÙÙØ¯ Ø´Ø¯Ù "{file}" Ø¨Ø± Ø±ÙÛ Ø¯ÛØ³Ú©',
  'File upload was stopped by extension.' => 'Ø¢Ù¾ÙÙØ¯ ÙØ§ÛÙ ØªÙØ³Ø· Ø§Ú©Ø³ØªÙØ´Ù ÙØªÙÙÙ Ø´Ø¯',
  'Filter "{filter}" is invalid. Controller "{class}" does have the filter method "filter{filter}".' => 'ÙÛÙØªØ± "{filter}" ÙØ§ÙØ¹ØªØ¨Ø± Ø§Ø³Øª.Ú©ÙØªØ±ÙØ± "{class}" Ø¯Ø§Ø±Ø§Û ÙØªØ¯ ÙÛÙØªØ±  "filter{filter}" ÙÛ Ø¨Ø§Ø´Ø¯',
  'Get a new code' => 'Ú©Ø¯ Ø¬Ø¯ÛØ¯ Ø§ÛØ¬Ø§Ø¯ Ú©ÙÛØ¯',
  'Go to page: ' => 'Ø¨Ø±Ù Ø¨Ù ØµÙØ­Ù: ',
  'Invalid enumerable value "{value}". Please make sure it is among ({enum}).' => 'ÙÙØ¯Ø§Ø± Ø´ÙØ§Ø±Ø´ ÙØ§ÙØ¹ØªØ¨Ø± "{value}". Ø§Ø·ÙÛÙØ§Ù Ø­Ø§ØµÙ Ú©ÙÛØ¯ Ú©Ù Ø¯Ø± ÙÛØ§Ù ({enum}) ÙÛ Ø¨Ø§Ø´Ø¯.',
  'Invalid MO file: {file} (magic: {magic}).' => 'ÙØ§ÛÙ MO ÙØ§ÙØ¹ØªØ¨Ø± : {file} (magic: {magic})',
  'Invalid MO file revision: {revision}.' => 'ÙØ±ÚÙ ÙØ§ÛÙ MO ØºÛØ± ÙØ¹ØªØ¨Ø±:{revision}',
  'Invalid operator "{operator}".' => 'Ø§Ù¾Ø±Ø§ØªÙØ± ØºÛØ± ÙØ¹ØªØ¨Ø±"{operator}"',
  'Last &gt;&gt;' => 'Ø¢Ø®Ø±ÛÙ &gt;&gt;',
  'List data must be an array or an object implementing Traversable.' => 'List data Ø¨Ø§ÛØ¯ ÛÚ© array ÛØ§ object Ø¨Ø§Ø´Ø¯ Ø¨Ø±Ø§Û Ø§Ø¬Ø±Ø§Û Traversable',
  'List index "{index}" is out of bound.' => 'Ø§ÛÙØ¯Ú©Ø³ ÙÛØ³Øª Ø®Ø§Ø±Ø¬ Ø§Ø² ÙØ­Ø¯ÙØ¯Ù ÙÛØ¨Ø§Ø´Ø¯.',
  'Login Required' => 'ÙØ±ÙØ¯ Ø¨Ù Ø³ÛØ³ØªÙ ÙØ§Ø²Ù ÙÛ Ø¨Ø§Ø´Ø¯',
  '&lt;&lt; First' => '&lt;&lt;Ø§ÙÙ',
  '&lt; Previous' => '&lt;ÙØ¨ÙÛ',
  'Map data must be an array or an object implementing Traversable.' => 'Map data Ø¨Ø§ÛØ¯ ÛÚ© array ÛØ§ object Ø¨Ø§Ø´Ø¯ Ø¨Ø±Ø§Û Ø§Ø¬Ø±Ø§Û Traversable',
  'Missing the temporary folder to store the uploaded file "{file}".' => 'Ø§Ø² Ø¯Ø³Øª Ø¯Ø§Ø¯Ù  ÙÙÙØ¯Ø± ÙÙÙØª Ø¨Ø±Ø§Û Ø°Ø®ÛØ±Ù Ú©Ø±Ø¯Ù ÙØ§ÛÙ Ø¢Ù¾ÙÙØ¯ Ø´Ø¯Ù "{file}" ',
  'Next &gt;' => 'Ø¨Ø¹Ø¯Û &gt;',
  'No columns are being updated for table "{table}".' => 'ÙÛÚ Ø³ØªÙÙÛ Ø¨Ø±Ø§Û Ø¬Ø¯ÙÙ "{table}" Ø¢Ù¾Ø¯ÛØª ÙÙÛ Ø´ÙØ¯',
  'No counter columns are being updated for table "{table}".' => 'ÙÛÚ counter columns Ø¯Ø± Ø­Ø§Ù Ø¢Ù¾Ø¯ÛØª Ø¨Ø±Ø§Û Ø¬Ø¯ÙÙ counter columns ÙÙÛ Ø¨Ø§Ø´Ø¯',
  'Object configuration must be an array containing a "class" element.' => 'Ù¾ÛÚ©Ø±Ø¨ÙØ¯Û abject Ø¨Ø§ÛØ¯ Ø¢Ø±Ø§ÛÙ Ø§Û Ø´Ø§ÙÙ "class" Ø¨Ø§Ø´Ø¯',
  '"{path}" is not a valid directory.' => '"{path}" Ø¯Ø§ÛØ±Ú©ØªÙØ±Û ÙØ¹ØªØ¨Ø± ÙÛØ³Øª.',
  'Please fix the following input errors:' => 'ÙØ·ÙØ§ Ø®Ø·Ø§ÙØ§Û ÙØ±ÙØ¯Û Ø²ÛØ± Ø±Ø§ ØªØµØ­ÛØ­ Ú©ÙÛØ¯ :',
  'Property "{class}.{property}" is not defined.' => 'ÙÛÚÚ¯ÛÙØ§Û "{class}.{property}" ØªØ¹Ø±ÛÙ ÙØ´Ø¯Ù Ø§Ø³Øª.',
  'Property "{class}.{property}" is read only.' => 'ÙÛÚÚ¯ÛÙØ§Û "{class}.{property}" ÙÙØ· ÙØ§Ø¨Ù Ø®ÙØ§ÙØ¯Ù Ø§Ø³Øª.',
  'Queue data must be an array or an object implementing Traversable.' => '',
  'Relation "{name}" is not defined in active record class "{class}".' => 'Ø±Ø§Ø¨Ø·Ù "{name}" Ø¯Ø± Ú©ÙØ§Ø³ Ø§Ú©ØªÛÙ Ø±Ú©ÙØ±Ø¯ "{class}" ØªØ¹Ø±ÛÙ Ø´Ø¯Ù ÙÙÛ Ø¨Ø§Ø´Ø¯',
  'Stack data must be an array or an object implementing Traversable.' => '',
  'Table "{table}" does not exist.' => 'Ø¬Ø¯ÙÙ "{table}" ÙØ¬ÙØ¯ ÙØ¯Ø§Ø±Ø¯',
  'Table "{table}" does not have a column named "{column}".' => 'Ø¬Ø¯ÙÙ "{table}" Ø³ØªÙÙÛ Ø¨Ø§ ÙØ§Ù "{column}" ÙØ¯Ø§Ø±Ø¯',
  'The active record cannot be deleted because it is new.' => 'Ø§Ú©ØªÛÙ Ø±Ú©ÙØ±Ø¯ ÙÙÛ ØªÙØ§ÙØ¯ Ø­Ø°Ù Ø´ÙØ¯ ÚÙÙ Ø¬Ø¯ÛØ¯ Ø§Ø³Øª',
  'The active record cannot be inserted to database because it is not new.' => 'Ø§Ú©ØªÛÙ Ø±Ú©ÙØ±Ø¯ ÙÙÛ ØªÙØ§ÙØ¯ ÙØ§Ø±Ø¯ Ù¾Ø§ÛÚ¯Ø§Ù Ø¯Ø§Ø¯Ù Ø´ÙØ¯ ÚÙÙ Ø¬Ø¯ÛØ¯ ÙÛØ³Øª',
  'The active record cannot be updated because it is new.' => 'Ø§Ú©ØªÛÙ Ø±Ú©ÙØ±Ø¯ ÙÙÛ ØªÙØ§ÙØ¯ Ø¢Ù¾Ø¯ÛØª Ø´ÙØ¯ ÚÙÙ Ø¬Ø¯ÛØ¯ Ø§Ø³Øª',
  'The asset "{asset}" to be published does not exist.' => 'asset "{asset}" Ú©Ù ÙÙØªØ´Ø± Ø´Ø¯ ÙÙØ¬ÙØ¯ ÙÙÛ Ø¨Ø§Ø´Ø¯',
  'The command path "{path}" is not a valid directory.' => 'command path "{path}" Ø¯Ø§ÛØ±Ú©ØªÙØ±Û ÙØ¹ØªØ¨Ø± ÙÙÛ Ø¨Ø§Ø´Ø¯',
  'The controller path "{path}" is not a valid directory.' => 'controller path "{path}" Ø¯Ø§ÛØ±Ú©ØªÙØ±Û ÙØ¹ØªØ¨Ø±Û ÙÙÛ Ø¨Ø§Ø´Ø¯',
  'The CSRF token could not be verified.' => 'CSRF token ÙØ§Ø¨Ù ØªØ§ÛÛØ¯ ÙÙÛ Ø¨Ø§Ø´Ø¯',
  'The file "{file}" cannot be uploaded. Only files with these extensions are allowed: {extensions}.' => 'ÙØ§ÛÙ "{file}" ÙÙÛ ØªÙØ§ÙØ¯ Ø¢Ù¾ÙÙØ¯ Ø´ÙØ¯.ÙÙØ· ÙØ§ÛÙÙØ§ÛÛ Ú©Ù Ø§ÛÙ Ø§Ú©Ø³ØªÙØ´Ù Ø±Ø§ Ø¯Ø§Ø±ÙØ¯ ÙØ¬Ø§Ø² ÙÛ Ø¨Ø§Ø´ÙØ¯:{extensions}',
  'The file "{file}" is too large. Its size cannot exceed {limit} bytes.' => 'ÙØ§ÛÙ "{file}" Ø¨Ø³ÛØ§Ø± Ø¨Ø²Ø±Ú¯ Ø§Ø³Øª. Ø§ÛÙ Ø³Ø§ÛØ² ÙÙÛ ØªÙØ§ÙØ¯ Ø¨Ø²Ø±Ú¯ØªØ± Ø§Ø² {limit} bytes Ø¨Ø§Ø´Ø¯',
  'The file "{file}" is too small. Its size cannot be smaller than {limit} bytes.' => 'ÙØ§ÛÙ "{file}"  Ø¨Ø³ÛØ§Ø± Ú©ÙÚÚ© Ø§Ø³Øª.Ø§ÛÙ Ø³Ø§ÛØ² ÙÙÛ ØªÙØ§ÙØ¯ Ú©ÙÚÚ©ØªØ± Ø§Ø² {limit} bytes Ø¨Ø§Ø´Ø¯',
  'The file "{file}" was only partially uploaded.' => 'ÙØ§ÛÙ "{file}" Ø¢Ù¾ÙÙØ¯ Ø´Ø¯',
  'The "filter" property must be specified with a valid callback.' => 'Ø®ØµÙØµÛØ§Øª "filter" Ø¨Ø§ÛØ¯ Ø¨Ø§ Ú©Ø§Ù Ø¨Ú© ÙØ¹ØªØ¨Ø± ÙØ´Ø®Øµ Ø´ÙØ¯ ',
  'The first element in a filter configuration must be the filter class.' => 'Ø§ÙÙÛÙ Ø¹ÙØµØ± Ø¯Ø± Ù¾ÛÚ©Ø±Ø¨ÙØ¯Û  ÙÛÙØªØ± Ø¨Ø§ÛØ¯ Ú©ÙØ§Ø³ ÙÛÙØªØ± Ø¨Ø§Ø´Ø¯',
  'The item "{name}" does not exist.' => 'Ø¢ÛØªÙ "{name}" ÙÙØ¬ÙØ¯ ÙÙÛ Ø¨Ø§Ø´Ø¯',
  'The item "{parent}" already has a child "{child}".' => 'Ø¢ÛØªÙ "{parent}" Ø¯Ø± Ø­Ø§Ù Ø­Ø§Ø¶Ø± ÚØ§ÛÙØ¯ "{child}" Ø¯Ø§Ø±Ø¯',
  'The layout path "{path}" is not a valid directory.' => 'ÙØ³ÛØ± ÙÛ Ø§ÙØª Ø¯Ø§ÛØ±Ú©ØªÙØ±Û ÙØ¹ØªØ¨Ø±Û ÙÙÛ Ø¨Ø§Ø´Ø¯.',
  'The list is read only.' => 'ÙÛØ³Øª ÙÙØ· ÙØ§Ø¨Ù Ø®ÙØ§ÙØ¯Ù ÙÛ Ø¨Ø§Ø´Ø¯.',
  'The map is read only.' => 'ÙÙØ´Ù ÙÙØ· ÙØ§Ø¨Ù Ø®ÙØ§ÙØ¯Ù ÙÛ Ø¨Ø§Ø´Ø¯.',
  'Theme directory "{directory}" does not exist.' => 'Ø¯Ø§ÛØ±Ú©ØªÙØ±Û ØªÙ "{directory}" ÙØ¬ÙØ¯ ÙØ¯Ø§Ø±Ø¯.',
  'The module path "{path}" is not a valid directory.' => 'ÙØ³ÛØ± ÙØ§ÚÙÙ "{path}" Ø¯Ø§ÛØ±Ú©ØªÙØ±Û ÙØ¹ØªØ¨Ø± ÙÙÛ Ø¨Ø§Ø´Ø¯.',
  'The pattern for 12 hour format must be "h" or "hh".' => 'Ø§ÙÚ¯Ù Ø¨Ø±Ø§Û ÙØ±ÙØª 12 Ø³Ø§Ø¹Øª Ø¨Ø§ÛØ¯ "h" ÛØ§ "hh" Ø¨Ø§Ø´Ø¯.',
  'The pattern for 24 hour format must be "H" or "HH".' => 'Ø§ÙÚ¯Ù Ø¨Ø±Ø§Û 24 Ø³Ø§Ø¹Øª Ø¨Ø§ÛØ¯ "H" ÛØ§ "HH" Ø¨Ø§Ø´Ø¯.',
  'The pattern for AM/PM marker must be "a".' => 'Ø§ÙÚ¯Ù Ø¨Ø±Ø§Û AM/PM Ø¨Ø§ÛØ¯ "a" Ø¨Ø§Ø´Ø¯.',
  'The pattern for day in month must be "F".' => 'Ø§ÙÚ¯Ù Ø¨Ø±Ø§Û Ø±ÙØ² Ø¯Ø± ÙØ§Ù Ø¨Ø§ÛØ¯ "F" Ø¨Ø§Ø´Ø¯.',
  'The pattern for day in year must be "D", "DD" or "DDD".' => 'Ø§ÙÚ¯Ù Ø¨Ø±Ø§Û Ø±ÙØ² Ø¯Ø± Ø³Ø§Ù Ø¨Ø§ÛØ¯ "D", "DD" ÛØ§ "DDD" Ø¨Ø§Ø´Ø¯.',
  'The pattern for day of the month must be "d" or "dd".' => 'Ø§ÙÚ¯Ù Ø¨Ø±Ø§Û Ø±ÙØ² Ø¯Ø± ÙØ§Ù Ø¨Ø§ÛØ¯ "d" ÛØ§ "dd" Ø¨Ø§Ø´Ø¯.',
  'The pattern for day of the week must be "E", "EE", "EEE", "EEEE" or "EEEEE".' => 'Ø§ÙÚ¯Ù Ø¨Ø±Ø§Û Ø±ÙØ²Ø¯Ø± ÙÙØªÙ Ø¨Ø§ÛØ¯ "E", "EE", "EEE", "EEEE" ÛØ§ "EEEEE" Ø¨Ø§Ø´Ø¯.',
  'The pattern for era must be "G", "GG", "GGG", "GGGG" or "GGGGG".' => 'Ø§ÙÚ¯Ù Ø¨Ø±Ø§Û era Ø¨Ø§ÛØ¯ "G", "GG", "GGG", "GGGG" ÛØ§ "GGGGG" Ø¨Ø§Ø´Ø¯.',
  'The pattern for hour in AM/PM must be "K" or "KK".' => 'Ø§ÙÚ¯Ù Ø¨Ø§Ø±Û Ø³Ø§Ø¹Øª Ø¯Ø± AM/PM Ø¨Ø§ÛØ¯ "K" ÛØ§ "KK" Ø¨Ø§Ø´Ø¯.',
  'The pattern for hour in day must be "k" or "kk".' => 'Ø§ÙÚ¯Ù Ø¨Ø±Ø§Û Ø³Ø§Ø¹Øª  Ø¯Ø± Ø±ÙØ² Ø¨Ø§ÛØ¯ "k" ÛØ§ "kk" Ø¨Ø§Ø´Ø¯.',
  'The pattern for minutes must be "m" or "mm".' => 'Ø§ÙÚ¯Ù Ø¨Ø±Ø§Û Ø¯ÙÛÙÙ Ø¨Ø§ÛØ¯ "mm" ÛØ§ "m" Ø¨Ø§Ø´Ø¯.',
  'The pattern for month must be "M", "MM", "MMM", or "MMMM".' => 'Ø§ÙÚ¯Ù Ø¨Ø±Ø§Û ÙØ§Ù Ø¨Ø§ÛØ¯ "M", "MM", "MMM", Ø¨Ø§ "MMMM" Ø¨Ø§Ø´Ø¯.',
  'The pattern for seconds must be "s" or "ss".' => 'Ø§ÙÚ¯Ù Ø¨Ø±Ø§Û Ø«Ø§ÙÛÙ Ø¨Ø§ÛØ¯ "s" ÛØ§ "ss" Ø¨Ø§Ø´Ø¯.',
  'The pattern for time zone must be "z" or "v".' => 'Ø§ÙÚ¯Ù Ø¨Ø±Ø§Û ØªØ§ÛÙ Ø²ÙÙ Ø¨Ø§ÛØ¯ "z" ÛØ§ "v" Ø¨Ø§Ø´Ø¯.',
  'The pattern for week in month must be "W".' => 'Ø§ÙÚ¯ÙÛ Ø¨Ø±Ø§Û ÙÙØªÙ Ø¯Ø± ÙØ§Ù Ø¨Ø§ÛØ¯ "w" Ø¨Ø§Ø´Ø¯.',
  'The pattern for week in year must be "w".' => 'Ø§ÙÚ¯ÙÛ ÙÙØªÙ Ø¯Ø± Ø³Ø§Ù Ø¨Ø§ÛØ¯ "w" Ø¨Ø§Ø´Ø¯.',
  'The "pattern" property must be specified with a valid regular expression.' => 'Ø®ØµÙØµÛØ§Øª "pattern" Ø¨Ø§ÛØ¯ Ø¨Ø§ Ø¹Ø¨Ø§Ø±Øª Ø¨Ø§ ÙØ§Ø¹Ø¯Ù ÙØ´Ø®Øµ Ø´ÙØ¯.',
  'The queue is empty.' => 'Ú©ÛÙ Ø®Ø§ÙÛ Ø§Ø³Øª.',
  'The relation "{relation}" in active record class "{class}" is not specified correctly. The join table "{joinTable}" given in the foreign key cannot be found in the database.' => 'Ø±Ø§Ø¨Ø·Ù "{relation}" Ø¯Ø± Ø§Ú©ØªÛÙ Ø±Ú©ÙØ±Ø¯ Ú©ÙØ§Ø³ "{class}" Ø¨Ù Ø¯Ø±Ø³ØªÛ ÙØ´Ø®Øµ ÙØ´Ø¯Ù Ø§Ø³Øª. Ø¬ÙÛÙ ØªÛØ¨Ù "{joinTable}" Ø¯Ø§Ø¯Ù Ø´Ø¯Ù Ø¯Ø± Ú©ÙÛØ¯ Ø®Ø§Ø±Ø¬Û Ø¯Ø± Ù¾Ø§ÛÚ¯Ø§Ù Ø¯ Ø§Ø¯Ù ÛØ§ÙØª ÙÙÛ Ø´ÙØ¯',
  'The relation "{relation}" in active record class "{class}" is not specified correctly: the join table "{joinTable}" given in the foreign key cannot be found in the database.' => 'Ø±Ø§Ø¨Ø·Ù "{relation}" Ø¯Ø± Ø§Ú©ØªÛÙ Ø±Ú©ÙØ±Ø¯ Ú©ÙØ§Ø³ "{class}" Ø¨Ù Ø¯Ø±Ø³ØªÛ ÙØ´Ø®Øµ ÙØ´Ø¯Ù Ø§Ø³Øª. join table "{joinTable}" Ø¯Ø§Ø¯Ù Ø´Ø¯Ù Ø¯Ø± Ú©ÙÛØ¯ Ø®Ø§Ø±Ø¬Û Ø¯Ø± Ù¾Ø§ÛÚ¯Ø§Ù Ø¯Ø§Ø¯Ù ÛØ§ÙØª ÙÙÛ Ø´ÙØ¯',
  'The relation "{relation}" in active record class "{class}" is specified with a foreign key "{key}" that does not point to the parent table "{table}".' => 'Ø±Ø§Ø¨Ø·Ù "{relation}" Ø¯Ø± Ø§Ú©ØªÛÙ Ø±Ú©ÙØ±Ø¯ Ú©ÙØ§Ø³ "{class}" Ø¨Ø§ Ú©ÙÛØ¯ Ø®Ø§Ø±Ø¬Û "{key}"ÙØ´Ø®Øµ Ø´Ø¯Ù Ø§Ø³Øª Ú©Ù Ø¨Ù Ø¬Ø¯ÙÙ Ø§ØµÙÛ Ø§Ø´Ø§Ø±Ù ÙÙÛ Ú©ÙØ¯ "{table}"',
  'The relation "{relation}" in active record class "{class}" is specified with an incomplete foreign key. The foreign key must consist of columns referencing both joining tables.' => '',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key "{key}". The foreign key does not point to either joining table.' => 'Ø±Ø§Ø¨Ø·Ù "{relation}" Ø¯Ø± Ø§Ú©ØªÛÙ Ø±Ú©ÙØ±Ø¯ Ú©ÙØ§Ø³ "{class}" ØªÙØ³Ø· Ú©ÙÛØ¯ Ø®Ø§Ø±Ø¬Û "{key}" ÙØ´Ø®Øµ Ø´Ø¯Ù Ø§Ø³Øª.',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key "{key}". There is no such column in the table "{table}".' => 'Ø±Ø§Ø¨Ø·Ù "{relation}" Ø¯Ø± Ø§Ú©ØªÛÙ Ø±Ú©ÙØ±Ø¯ Ú©ÙØ§Ø³ "{class}" ØªÙØ³Ø· Ú©ÙÛØ¯ Ø®Ø§Ø±Ø¬Û "{key}" ÙØ´Ø®Øµ Ø´Ø¯Ù Ø§Ø³Øª.ÚÙÛÙ Ø³ØªÙÙÛ Ø¯Ø± Ø¬Ø¯ÙÙ "{table}"ÙÙØ¬ÙØ¯ ÙÙÛ Ø¨Ø§Ø´Ø¯',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key. The columns in the key must match the primary keys of the table "{table}".' => 'Ø±Ø§Ø¨Ø·Ù "{relation}" Ø¯Ø± Ø§Ú©ØªÛÙ Ø±Ú©ÙØ±Ø¯ Ú©ÙØ§Ø³ "{class}" ØªÙØ³Ø· Ú©ÙÛØ¯ Ø®Ø§Ø±Ø¬Û ÙØ´Ø®Øµ Ø´Ø¯Ù Ø§Ø³Øª. Ø³ØªÙÙÙØ§Û Ú©ÙÛØ¯ Ø¨Ø§ÛØ¯ ÙØ·Ø§Ø¨Ù Ø¨Ø§ Ú©ÙÛØ¯ Ø§ØµÙÛ Ø¬Ø¯ÙÙ "{table}" Ø¨Ø§Ø´Ø¯.',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key. The format of the foreign key must be "joinTable(fk1,fk2,...)".' => 'Ø±Ø§Ø¨Ø·Ù "{relation}" Ø¨Ø§ Ú©ÙØ§Ø³ Ø§Ú©ØªÛÙ Ø±Ú©ÙØ±Ø¯ "{class}"  Ø¨Ø§ Ú©ÙÛØ¯ Ø®Ø§Ø±Ø¬Û  ÙØ§ÙØ¹ØªØ¨Ø±Û ÙØ´Ø®Ø¶ Ø´Ø¯Ù Ø§Ø³Øª . ÙØ§ÙØ¨ Ú©ÙÛØ¯ Ø®Ø§Ø±Ø¬Û Ø¨Ø§ÛØ¯ Ø¨Ù ØµÙØ±Øª "joinTable(fk1,fk2,...)" Ø¨Ø§Ø´Ø¯.',
  'The requested view "{name}" is not found.' => 'ÙÙØ§Û Ø¯Ø± Ø®ÙØ§Ø³Øª Ø¯Ø§Ø¯Ù Ø´Ø¯Ù Ø¨Ø§ ÙØ§Ù "{name}" ÙÙØ¬ÙØ¯ ÙÙÛ Ø¨Ø§Ø´Ø¯.',
  'The stack is empty.' => 'Ø§Ø³ØªÚ© Ø®Ø§ÙÛ Ø§Ø³Øª.',
  'The STAT relation "{name}" cannot have child relations.' => 'Ø±Ø§Ø¨Ø·Ù STAT Ø¨Ø§ ÙØ§Ù "{name}"  Ø§ÙÚ©Ø§Ù Ø¯Ø§Ø´ØªÙ Ø±Ø§Ø¨Ø·Ù ÙØ±Ø²ÙØ¯Û Ø±Ø§ ÙØ¯Ø§Ø±Ø¯.',
  'The system is unable to find the requested action "{action}".' => 'Ø³ÛØ³ØªÙ ØªÙØ§ÙØ§ÛÛ ÛØ§ÙØªÙ Ø¹ÙÙ "{action}" Ø±Ø§ ÙØ¯Ø§Ø±Ø¯.',
  'The system view path "{path}" is not a valid directory.' => 'ÙØ³ÛØ± ÙÙØ§Û Ø³ÛØ³ØªÙ "{path}" Ø¯Ø§ÛØ±Ú©ØªÙØ±Û ÙØ¹ØªØ¨Ø±Û ÙÛØ³Øª.',
  'The table "{table}" for active record class "{class}" cannot be found in the database.' => 'Ø¬Ø¯ÙÙ "{table}" Ø¨Ø±Ø§Û Ø§Ú©ØªÛÙ Ø±Ú©ÙØ±Ø¯ Ú©ÙØ§Ø³ "{class}" Ø¯Ø± Ù¾Ø§ÛÚ¯Ø§Ù Ø§Ø·ÙØ§Ø¹Ø§ØªÛ ÛØ§ÙØª ÙÙÛ Ø´ÙØ¯',
  'The URL pattern "{pattern}" for route "{route}" is not a valid regular expression.' => 'Ø§ÙÚ¯ÙÛ URL"{pattern}" Ø¨Ø±Ø§Û ÙØ³ÛØ± ÛØ§Ø¨Û "{route}"   Ø¹Ø¨Ø§Ø±Øª Ø¨Ø§ ÙØ§Ø¹Ø¯Ù ÙØ¹ØªØ¨Ø±Û ÙÙÛ Ø¨Ø§Ø´Ø¯.',
  'The value for the column "{column}" is not supplied when querying the table "{table}".' => 'ÙÙØ¯Ø§Ø± Ø¨Ø§Ø²Ú¯Ø±Ø¯Ø§ÙÛ Ø´Ø¯Ù Ø§Ø² Ú©ÙØ¦Ø±Û Ø³ØªÙÙ "{column}" Ø¯Ø± Ø¬Ø¯ÙÙ "{table}" ØµØ­ÛØ­ ÙÙÛ Ø¨Ø§Ø´Ø¯.',
  'The verification code is incorrect.' => 'Ú©Ø¯ ØªØ£ÛÛØ¯ ÙØ¹ØªØ¨Ø± ÙÛØ³Øª.',
  'The view path "{path}" is not a valid directory.' => 'ÙØ³ÛØ± ÙÙØ§Û "{path}" ÙØ¹ØªØ¨Ø± ÙÙÛ Ø¨Ø§Ø´Ø¯.',
  'This content requires the <a href="http://www.adobe.com/go/getflash/">Adobe Flash Player</a>.' => 'ÙØ­ØªÙØ§Û Ø§ÛÙ ØµÙØ­Ù Ø§Ø­ØªÛØ§Ø¬ Ø¨Ù <a href="http://www.adobe.com/go/getflash/">Adobe Flash Player</a> Ø¯Ø§Ø±Ø¯.',
  'Unable to add an item whose name is the same as an existing item.' => 'Ø§ÙÚ©Ø§Ù Ø§Ø¶Ø§ÙÙ Ú©Ø±Ø¯Ù Ø¢ÛØªÙ Ø¬Ø¯ÛØ¯Û Ú©Ù ÙØ§ÙØ´ Ø¨Ø§ ÙØ§Ù Ø¢ÛØªÙ ÙÙØ¬ÙØ¯Û Ø¨Ø±Ø§Ø¨Ø± Ø§Ø³Øª ÙØ¬ÙØ¯ ÙØ¯Ø§Ø±Ø¯.',
  'Unable to change the item name. The name "{name}" is already used by another item.' => 'Ø§ÙÚ©Ø§Ù ØªØºÛÛØ± ÙØ§Ù Ø¨Ù "{name}" ÙØ¬ÙØ¯ ÙØ¯Ø§Ø±Ø¯ Ø Ø§ÛÙ ÙØ§Ù Ø¯Ø± Ø­Ø§Ù Ø­Ø§Ø¶Ø± ÙÙØ±Ø¯ Ø§Ø³ØªÙØ§Ø¯Ù Ø¢ÛØªÙ Ø¯ÛÚ¯Ø±Û ÙÛ Ø¨Ø§Ø´Ø¯.',
  'Unable to create application state file "{file}". Make sure the directory containing the file exists and is writable by the Web server process.' => 'ÙØ§Ø¯Ø± Ø¨Ù Ø§ÛØ¬Ø§Ø¯ Ø§Ù¾ÙÛÚ©ÛØ´Ù "{file}" ÙÙÛ Ø¨Ø§Ø´Ø¯.Ø§Ø·ÙÛÙØ§Ù Ø­Ø§ØµÙ Ú©ÙÛØ¯ Ú©Ù ÙØ§ÛÙ Ø¯Ø± Ø¯Ø§ÛØ±Ú©ØªÙØ±Û ÙÙØ¬ÙØ¯ ÙÛ Ø¨Ø§Ø´Ø¯ Ù ÙÙÚÙÛÙ ÙØ§Ø¨Ù ÙÙØ´ØªÙ ØªÙØ³Ø· ÙØ¨ Ø³Ø±ÙØ± ÙÛ Ø¨Ø§Ø´Ø¯.',
  'Unable to lock file "{file}" for reading.' => 'Ø§ÙÚ©Ø§Ù ÙÙÙ Ú©Ø±Ø¯Ù ÙØ§ÛÙ "{file}"  Ø¨Ø±Ø§Û Ø®ÙØ§ÙØ¯Ù ÙØ¬ÙØ¯ ÙØ¯Ø§Ø±Ø¯.',
  'Unable to lock file "{file}" for writing.' => 'Ø§ÙÚ©Ø§Ù ÙÙÙ Ú©Ø±Ø¯Ù ÙØ§ÛÙ "{file}" Ø¨Ø±Ø§Û ÙÙØ´ØªÙ ÙØ¬ÙØ¯ ÙØ¯Ø§Ø±Ø¯.',
  'Unable to read file "{file}".' => 'ØªÙØ§ÙØ§ÛÛ Ø®ÙØ§ÙØ¯Ù ÙØ§ÛÙ "{file}" ÙØ¬ÙØ¯ ÙØ¯Ø§Ø±Ø¯.',
  'Unable to replay the action "{object}.{method}". The method does not exist.' => 'Ø§ÙÚ©Ø§Ù Ù¾Ø§Ø³Ø® Ø¯ÙÛ Ø¨Ù "{object}.{method}" ÙØ¬ÙØ¯ ÙØ¯Ø§Ø±Ø¯.',
  'Unable to resolve the request "{route}".' => 'Ø§ÙÚ©Ø§Ù Ù¾Ø§Ø³Ø® Ø¨Ù Ø¯Ø±Ø®ÙØ§Ø³Øª "{route}" ÙØ¬ÙØ¯ ÙØ¯Ø§Ø±Ø¯',
  'Unable to write file "{file}".' => 'ØªÙØ§ÙØ§ÛÛ ÙÙØ´Øª ÙØ§ÛÙ "{file}" ÙÙØ¬ÙØ¯ ÙÙÛ Ø¨Ø§Ø´Ø¯.',
  'Unknown authorization item "{name}".' => 'Ø¢ÛØªÙ {name} ÙØ§ Ø´ØªØ§Ø®ØªÙ Ø§Ø³Øª.',
  'Unrecognized locale "{locale}".' => 'ÙØ­Ù"{locale}" Ø´ÙØ§Ø®ØªÙ Ø´Ø¯Ù Ø ÙÙÛ Ø¨Ø§Ø´Ø¯.',
  'View file "{file}" does not exist.' => 'ÙØ§ÛÙ ÙØ§ÙØ¨Û Ø¨Ø§ ÙØ§Ù "{file}" ÙØ¬ÙØ¯ ÙØ¯Ø§Ø±Ø¯.',
  '{widget} cannot find the view "{view}".' => '{widget} ÙÙÛØªÙØ§ÙØ¯ ÙØ§ÙØ¨ "{view}" Ø±Ø§ Ù¾ÛØ¯Ø§ Ú©ÙØ¯.',
  'Yii application can only be created once.' => 'Ø§Ù¾ÙÛÚ©ÛØ´Ù ÛÛ ØªÙÙØ§ ÛÚ© Ø¨Ø§Ø± ÙÛ ØªÙØ§ÙØ¯ Ø§ÛØ¬Ø§Ø¯ Ø´ÙØ¯.',
  'You are not authorized to perform this action.' => 'Ø´ÙØ§ Ø¯Ø³ØªØ±Ø³Û Ø§ÙØ¬Ø§Ù Ø§ÛÙ Ø¹ÙÙ Ø±Ø§ ÙØ¯Ø§Ø±ÛØ¯.',
  'Your request is not valid.' => 'Ø¯Ø±Ø®ÙØ§Ø³Øª Ø´ÙØ§ ÙØ¹ØªØ¨Ø± ÙÙÛ Ø¨Ø§Ø´Ø¯.',
  'The file "{file}" cannot be uploaded. Only files of these MIME-types are allowed: {mimeTypes}.' => 'Ø¢Ù¾ÙÙØ¯ ÙØ§ÛÙ "{file}" ÙÙÚ©Ù ÙÛØ³Øª. MIME-type ÙØ§Û ÙØ¬Ø§Ø² Ø¨Ø±Ø§Û Ø¢Ù¾ÙÙØ¯: {mimeTypes}',
  'The format of {attribute} is invalid.' => 'ÙØ§ÙØ¨ {attribute} ÙØ¹ØªØ¨Ø± ÙÛØ³Øª.',
  'The requested view "{name}" was not found.' => 'ÙÙØ§Û {name} Ù¾ÛØ¯Ø§ ÙØ´Ø¯.',
  'Your request is invalid.' => 'Ø¯Ø±Ø®ÙØ§Ø³Øª Ø´ÙØ§ ÙØ¹ØªØ¨Ø± ÙÛØ³Øª.',
  '{attribute} cannot accept more than {limit} files.' => '{attribute} ÙÙÛ ØªÙØ§ÙØ¯ Ø¨ÛØ´ØªØ± Ø§Ø² {limit} ÙØ§ÛÙ ÙØ¨ÙÙ Ú©ÙØ¯.',
  '{attribute} is in the list.' => '{attribute} Ø¯Ø± ÙÛØ³Øª ÙÙØ¬ÙØ¯ Ø§Ø³Øª.',
);
