<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Are you sure you want to delete this item?' => 'Haluatko varmasti poistaa tÃ¤mÃ¤n?',
  'Delete' => 'Poista',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'NÃ¤ytetÃ¤Ã¤n {start}-{end} kaikkiaan 1 tuloksesta.|NÃ¤ytetÃ¤Ã¤n {start}-{end} kaikkiaan {count} tuloksesta.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'Joko "name" tai "value" tulee olla mÃ¤Ã¤ritettynÃ¤ CDataColumn-luokalle.',
  'Home' => 'Koti',
  'No results found.' => 'Ei tuloksia.',
  'Not set' => 'Ei asetettu',
  'Please specify the "attributes" property.' => 'MÃ¤Ã¤ritÃ¤ "attributes"-ominaisuus.',
  'Please specify the "data" property.' => 'MÃ¤Ã¤ritÃ¤ "data"-ominaisuus.',
  'Sort by: ' => 'Lajittelu: ',
  'The "dataProvider" property cannot be empty.' => '"dataProvider"-ominaisuus ei voi olla tyhjÃ¤.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Attribuutti pitÃ¤Ã¤ mÃ¤Ã¤rittÃ¤Ã¤ muodossa "Name:Type:Label", jossa "Type" ja "Label" ovat valinnaisia.',
  'The button type "{type}" is not supported.' => 'Painikkeen tyyppiÃ¤ "{type}" ei tueta.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Sarake pitÃ¤Ã¤ mÃ¤Ã¤rittÃ¤Ã¤ muodossa "Name:Type:Label", jossa "Type" ja "Label" ovat valinnaisia.',
  'The property "itemView" cannot be empty.' => '"itemView"-ominaisuus ei voi olla tyhjÃ¤.',
  'The property filterSelector should be defined.' => 'filterSelector-ominaisuus tulisi olla mÃ¤Ã¤riteltynÃ¤.',
  'The property updateSelector should be defined.' => 'updateSelector-ominaisuus tulisi olla mÃ¤Ã¤riteltynÃ¤.',
  'Total 1 result.|Total {count} results.' => 'YhteensÃ¤ 1 tulos.|YhteensÃ¤ {count} tulosta.',
  'Update' => 'PÃ¤ivitÃ¤',
  'View' => 'NÃ¤ytÃ¤',
  '{class} must specify "model" and "{attribute}" or "{name}" property values.' => '{class}-luokan tÃ¤ytyy mÃ¤Ã¤rittÃ¤Ã¤ "model"- ja "{attribute}"- tai "{name}"-ominaisuuksien arvot.',
);
