<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Are you sure you want to delete this item?' => 'Bu Ã¶Äeyi silmek istediÄinizden emin misiniz?',
  'Delete' => 'Sil',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => '{count} sonuÃ§tan {start}-{end} arasÄ± gÃ¶steriliyor.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'CDataColumn deÄeri iÃ§in "name" veya "value" tanÄ±mlanmalÄ±dÄ±r.',
  'Home' => 'Anasayfa',
  'No results found.' => 'KayÄ±t bulunamadÄ±.',
  'Not set' => 'AyarlanmadÄ±',
  'Please specify the "attributes" property.' => 'LÃ¼tfen "attributes" deÄeri tanÄ±mlayÄ±n.',
  'Please specify the "data" property.' => 'LÃ¼tfen "data" deÄeri tanÄ±mlayÄ±n.',
  'Sort by: ' => 'SÄ±rala: ',
  'The "dataProvider" property cannot be empty.' => '"dataProvider" deÄeri boÅ bÄ±rakÄ±lamaz.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'DeÄer, "Type" ve "Label" \'Ä±n opsiyonel olduÄu durumda, "Name:Type:Label" formatÄ±nda tanÄ±mlanmalÄ±dÄ±r.',
  'The button type "{type}" is not supported.' => '"{type}" buton tipi desteklenmemektedir.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'SÃ¼tun, "Type" ve "Label" \'Ä±n opsiyonel olduÄu durumda, "Name:Type:Label" formatÄ±nda tanÄ±mlanmalÄ±dÄ±r.',
  'The property "itemView" cannot be empty.' => '"itemView" deÄeri boÅ bÄ±rakÄ±lamaz.',
  'Total 1 result.|Total {count} results.' => 'Toplam sonuÃ§: {count}.',
  'Update' => 'GÃ¼ncelle',
  'View' => 'GÃ¶rÃ¼ntÃ¼le',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} iÃ§in "model" ve "attribute" veya "name" deÄerleri tanÄ±mlanmalÄ±dÄ±r.',
);
