<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Are you sure to delete this item?' => 'Vai patieÅ¡Äm vÄlaties dzÄst Å¡o vienÄ«bu?',
  'Delete' => 'DzÄst',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'ï»¿AttÄlo no {start}. lÄ«dz {end}. no pavisam {count} ieraksta(-iem).',
  'Either "name" or "value" must be specified for CDataColumn.' => 'CDataColumn nepiecieÅ¡ams norÄdÄ«t "name" vai "value".',
  'No results found.' => 'Dati netika atrasti.',
  'Not set' => 'Nav uzstÄdÄ«ts',
  'Please specify the "attributes" property.' => 'NorÄdiet mainÄ«go "attributes".',
  'Please specify the "data" property.' => 'NorÄdiet mainÄ«go "data".',
  'Sort by: ' => 'KÄrtot pÄc: ',
  'The "dataProvider" property cannot be empty.' => 'MainÄ«gais "dataProvider" nedrÄ«kst bÅ«t tukÅ¡s.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'AtribÅ«tam ir jÄbÅ«t norÄdÄ«tam formÄtÄ "Nosaukums:Veids:Apraksts", kur "Veids" un "Apraksts" ir obligÄti.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Kolonnai ir jÄbÅ«t iformÄtÄ "Nosaukums:Veids:Apraksts", kur "Veids" un "Apraksts" ir obligÄti.',
  'The property "itemView" cannot be empty.' => 'MainÄ«gais "itemView" nedrÄ«kst bÅ«t tukÅ¡s.',
  'Total 1 result.|Total {count} results.' => 'KopÄ {count} ieraksts(-i).',
  'Update' => 'Labot',
  'View' => 'SkatÄ«ties',
  '{class} must specify "model" and "attribute" or "name" property values.' => 'Klasei {class} ir jÄbÅ«t norÄdÄ«tiem vienam no mainÄ«gajiem "attribute" vai "name".',
);
