<?php
/**
 * Locale data for 'ii'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright Â© 1991-2013 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in https://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2014 Yii Software LLC (https://www.yiiframework.com/license/)
 */
return array (
  'version' => '8245',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => 'â°',
    'infinity' => 'â',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => 'Â¤Â #,##0.00',
  'currencySymbols' => 
  array (
    'AUD' => 'A$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'Â¥',
    'EUR' => 'â¬',
    'GBP' => 'Â£',
    'HKD' => 'HK$',
    'ILS' => 'âª',
    'INR' => 'â¹',
    'JPY' => 'JPÂ¥',
    'KRW' => 'â©',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => 'à¸¿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => 'â«',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'êêª',
      2 => 'êêª',
      3 => 'êêª',
      4 => 'êêª',
      5 => 'ê¬êª',
      6 => 'êêª',
      7 => 'êêª',
      8 => 'êêª',
      9 => 'ê¬êª',
      10 => 'ê°êª',
      11 => 'ê°êªêª',
      12 => 'ê°êêª',
    ),
    'abbreviated' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'ê­êê',
      1 => 'êêê',
      2 => 'êêê',
      3 => 'êêê',
      4 => 'êêê',
      5 => 'êêê¬',
      6 => 'êêê',
    ),
    'abbreviated' => 
    array (
      0 => 'ê­ê',
      1 => 'êê',
      2 => 'êê',
      3 => 'êê',
      4 => 'êê',
      5 => 'êê¬',
      6 => 'êê',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'ê',
      1 => 'ê',
      2 => 'ê',
      3 => 'ê',
      4 => 'ê',
      5 => 'ê¬',
      6 => 'ê',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'êêê¿',
      1 => 'êêê',
    ),
    'wide' => 
    array (
      0 => 'êêê¿',
      1 => 'êêê',
    ),
    'narrow' => 
    array (
      0 => 'êêê¿',
      1 => 'êêê',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'y MMMM d, EEEE',
    'long' => 'y MMMM d',
    'medium' => 'y MMM d',
    'short' => 'y-MM-dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'ê¸ê',
  'pmName' => 'ê¯ê',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'de' => 'êê©ê',
    'en' => 'ê±ê©ê',
    'es' => 'ê­ê ê¸ê',
    'fr' => 'êê©ê',
    'ii' => 'êê ê',
    'it' => 'ê´êêºê',
    'ja' => 'êêªê',
    'pt' => 'êê¨ê¸ê',
    'pt_br' => 'ê êêê¨ê¸ê',
    'ru' => 'êê©ê',
    'und' => 'êêê êê·',
    'zh' => 'êê©ê',
    'zh_hans' => 'êê¯êê©ê',
    'zh_hant' => 'êêêê©ê',
  ),
  'scripts' => 
  array (
    'arab' => 'êêê¨ê±ê·',
    'cyrl' => 'êê¨ê¦êêê±ê·',
    'hans' => 'êê¯êê²ê±ê·',
    'hant' => 'êêêê²ê±ê·',
    'latn' => 'êêê±ê·',
    'yiii' => 'êê ê±ê·',
    'zxxx' => 'ê±êêê ',
    'zzzz' => 'êêêê ê±ê·',
  ),
  'territories' => 
  array (
    'br' => 'ê ê­',
    'cn' => 'êê©',
    'de' => 'êê©',
    'fr' => 'êê©',
    'gb' => 'ê±ê©',
    'in' => 'ê´ê',
    'it' => 'ê´êêº',
    'jp' => 'êêª',
    'ru' => 'êêê¦',
    'us' => 'ê°ê©',
    'zz' => 'êê·êêêê ',
  ),
);
