<?php
/**
 * Locale data for 'kaj'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright Â© 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in https://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2013 Yii Software LLC (https://www.yiiframework.com/license/)
 */
return array (
  'version' => '5798',
  'numberSymbols' => 
  array (
    'alias' => '',
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => 'â°',
    'infinity' => 'â',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => 'Â¤Â #,##0.00',
  'currencySymbols' => 
  array (
    'AUD' => 'AU$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CNÂ¥',
    'EUR' => 'â¬',
    'GBP' => 'Â£',
    'HKD' => 'HK$',
    'ILS' => 'âª',
    'INR' => 'â¹',
    'JPY' => 'JPÂ¥',
    'KRW' => 'â©',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => 'à¸¿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => 'â«',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
    'NGN' => 'â¦',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Hywan AÌ±yrnig',
      2 => 'Hywan AÌ±hwa',
      3 => 'Hywan AÌ±tat',
      4 => 'Hywan AÌ±naai',
      5 => 'Hywan AÌ±pfwon',
      6 => 'Hywan AÌ±kitat',
      7 => 'Hywan AÌ±tyirin',
      8 => 'Hywan AÌ±ninai',
      9 => 'Hywan AÌ±kumviriyin',
      10 => 'Hywan Swak',
      11 => 'Hywan Swak B\'aÌ±yrnig',
      12 => 'Hywan Swak B\'aÌ±hwa',
    ),
    'abbreviated' => 
    array (
      1 => 'AÌ±yr',
      2 => 'AÌ±hw',
      3 => 'AÌ±ta',
      4 => 'AÌ±na',
      5 => 'AÌ±pf',
      6 => 'AÌ±ki',
      7 => 'AÌ±ty',
      8 => 'AÌ±ni',
      9 => 'AÌ±ku',
      10 => 'Swa',
      11 => 'Sby',
      12 => 'Sbh',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Ladi',
      1 => 'Lintani',
      2 => 'Talata',
      3 => 'Larba',
      4 => 'Lamit',
      5 => 'Juma',
      6 => 'Asabar',
    ),
    'abbreviated' => 
    array (
      0 => 'Lad',
      1 => 'Lin',
      2 => 'Tal',
      3 => 'Lar',
      4 => 'Lam',
      5 => 'Jum',
      6 => 'Asa',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'G.M.',
      1 => 'M.',
    ),
    'wide' => 
    array (
      0 => 'Gabanin Miladi',
      1 => 'Miladi',
    ),
    'narrow' => 
    array (
      0 => 'G.M.',
      1 => 'M.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, y MMMM dd',
    'long' => 'y MMMM d',
    'medium' => 'y MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'A.M.',
  'pmName' => 'P.M.',
  'orientation' => 'ltr',
  'pluralRules' => 
  array (
    0 => 'n==1',
    1 => 'true',
  ),
);
