<?php
/**
 * Locale data for 'kkj'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright Â© 1991-2013 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in https://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2014 Yii Software LLC (https://www.yiiframework.com/license/)
 */
return array (
  'version' => '8245',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => 'â°',
    'infinity' => 'â',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => 'Â¤Â #,##0.00',
  'currencySymbols' => 
  array (
    'AUD' => 'A$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CNÂ¥',
    'EUR' => 'â¬',
    'GBP' => 'Â£',
    'HKD' => 'HK$',
    'ILS' => 'âª',
    'INR' => 'â¹',
    'JPY' => 'JPÂ¥',
    'KRW' => 'â©',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => 'à¸¿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => 'â«',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'pamba',
      2 => 'wanja',
      3 => 'mbiyÉ mÉndoÅgÉ',
      4 => 'NyÉlÉmbÉÅgÉ',
      5 => 'MÉnÉ Ågbanja',
      6 => 'NyaÅgwÉ Ågbanja',
      7 => 'kuÅgwÉ',
      8 => 'fÉ',
      9 => 'njapi',
      10 => 'nyukul',
      11 => '11',
      12 => 'ÉulÉusÉ',
    ),
    'abbreviated' => 
    array (
      1 => 'Month1',
      2 => 'Month2',
      3 => 'Month3',
      4 => 'Month4',
      5 => 'Month5',
      6 => 'Month6',
      7 => 'Month7',
      8 => 'Month8',
      9 => 'Month9',
      10 => 'Month10',
      11 => 'Month11',
      12 => 'Month12',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
    'wide' => 
    array (
      1 => 'pamba',
      2 => 'wanja',
      3 => 'mbiyÉ mÉndoÅgÉ',
      4 => 'NyÉlÉmbÉÅgÉ',
      5 => 'MÉnÉ Ågbanja',
      6 => 'NyaÅgwÉ Ågbanja',
      7 => 'kuÅgwÉ',
      8 => 'fÉ',
      9 => 'njapi',
      10 => 'nyukul',
      11 => '11',
      12 => 'ÉulÉusÉ',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'sÉndi',
      1 => 'lundi',
      2 => 'mardi',
      3 => 'mÉrkÉrÉdi',
      4 => 'yedi',
      5 => 'vaÅdÉrÉdi',
      6 => 'mÉnÉ sÉndi',
    ),
    'abbreviated' => 
    array (
      0 => 'sÉndi',
      1 => 'lundi',
      2 => 'mardi',
      3 => 'mÉrkÉrÉdi',
      4 => 'yedi',
      5 => 'vaÅdÉrÉdi',
      6 => 'mÉnÉ sÉndi',
    ),
    'narrow' => 
    array (
      0 => 'so',
      1 => 'lu',
      2 => 'ma',
      3 => 'mÉ',
      4 => 'ye',
      5 => 'va',
      6 => 'ms',
    ),
    'short' => 
    array (
      0 => 'sÉndi',
      1 => 'lundi',
      2 => 'mardi',
      3 => 'mÉrkÉrÉdi',
      4 => 'yedi',
      5 => 'vaÅdÉrÉdi',
      6 => 'mÉnÉ sÉndi',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'so',
      1 => 'lu',
      2 => 'ma',
      3 => 'mÉ',
      4 => 'ye',
      5 => 'va',
      6 => 'ms',
    ),
    'abbreviated' => 
    array (
      0 => 'sÉndi',
      1 => 'lundi',
      2 => 'mardi',
      3 => 'mÉrkÉrÉdi',
      4 => 'yedi',
      5 => 'vaÅdÉrÉdi',
      6 => 'mÉnÉ sÉndi',
    ),
    'short' => 
    array (
      0 => 'so',
      1 => 'lu',
      2 => 'ma',
      3 => 'mÉ',
      4 => 'ye',
      5 => 'va',
      6 => 'ms',
    ),
    'wide' => 
    array (
      0 => 'sÉndi',
      1 => 'lundi',
      2 => 'mardi',
      3 => 'mÉrkÉrÉdi',
      4 => 'yedi',
      5 => 'vaÅdÉrÉdi',
      6 => 'mÉnÉ sÉndi',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE dd MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'dd/MM y',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'en' => 'yaman',
    'fr' => 'numbu buy',
    'kkj' => 'kakÉ',
  ),
  'territories' => 
  array (
    'cm' => 'KamÉrun',
  ),
  'pluralRules' => 
  array (
    0 => 'n==1',
    1 => 'true',
  ),
);
