<?php
/**
 * Locale data for 'mgo'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright Â© 1991-2013 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in https://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2014 Yii Software LLC (https://www.yiiframework.com/license/)
 */
return array (
  'version' => '8245',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => 'â°',
    'infinity' => 'â',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => 'Â¤Â #,##0.00',
  'currencySymbols' => 
  array (
    'AUD' => 'A$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CNÂ¥',
    'EUR' => 'â¬',
    'GBP' => 'Â£',
    'HKD' => 'HK$',
    'ILS' => 'âª',
    'INR' => 'â¹',
    'JPY' => 'JPÂ¥',
    'KRW' => 'â©',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => 'à¸¿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => 'â«',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'imÉg mbegtug',
      2 => 'imeg Ã bÃ¹bÃ¬',
      3 => 'imeg mbÉÅchubi',
      4 => 'imÉg ngwÉÌt',
      5 => 'imÉg fog',
      6 => 'imÉg ichiibÉd',
      7 => 'imÉg Ã dÃ¹mbÉÌÅ',
      8 => 'imÉg ichika',
      9 => 'imÉg kud',
      10 => 'imÉg tÃ¨siÊ¼e',
      11 => 'imÉg zÃ²',
      12 => 'imÉg krizmed',
    ),
    'abbreviated' => 
    array (
      1 => 'mbegtug',
      2 => 'imeg Ã bÃ¹bÃ¬',
      3 => 'imeg mbÉÅchubi',
      4 => 'imÉg ngwÉÌt',
      5 => 'imÉg fog',
      6 => 'imÉg ichiibÉd',
      7 => 'imÉg Ã dÃ¹mbÉÌÅ',
      8 => 'imÉg ichika',
      9 => 'imÉg kud',
      10 => 'imÉg tÃ¨siÊ¼e',
      11 => 'imÉg zÃ²',
      12 => 'imÉg krizmed',
    ),
    'narrow' => 
    array (
      1 => 'M1',
      2 => 'A2',
      3 => 'M3',
      4 => 'N4',
      5 => 'F5',
      6 => 'I6',
      7 => 'A7',
      8 => 'I8',
      9 => 'K9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'M1',
      2 => 'A2',
      3 => 'M3',
      4 => 'N4',
      5 => 'F5',
      6 => 'I6',
      7 => 'A7',
      8 => 'I8',
      9 => 'K9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
    'abbreviated' => 
    array (
      1 => 'mbegtug',
      2 => 'imeg Ã bÃ¹bÃ¬',
      3 => 'imeg mbÉÅchubi',
      4 => 'imÉg ngwÉÌt',
      5 => 'imÉg fog',
      6 => 'imÉg ichiibÉd',
      7 => 'imÉg Ã dÃ¹mbÉÌÅ',
      8 => 'imÉg ichika',
      9 => 'imÉg kud',
      10 => 'imÉg tÃ¨siÊ¼e',
      11 => 'imÉg zÃ²',
      12 => 'imÉg krizmed',
    ),
    'wide' => 
    array (
      1 => 'imÉg mbegtug',
      2 => 'imeg Ã bÃ¹bÃ¬',
      3 => 'imeg mbÉÅchubi',
      4 => 'imÉg ngwÉÌt',
      5 => 'imÉg fog',
      6 => 'imÉg ichiibÉd',
      7 => 'imÉg Ã dÃ¹mbÉÌÅ',
      8 => 'imÉg ichika',
      9 => 'imÉg kud',
      10 => 'imÉg tÃ¨siÊ¼e',
      11 => 'imÉg zÃ²',
      12 => 'imÉg krizmed',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Aneg 1',
      1 => 'Aneg 2',
      2 => 'Aneg 3',
      3 => 'Aneg 4',
      4 => 'Aneg 5',
      5 => 'Aneg 6',
      6 => 'Aneg 7',
    ),
    'abbreviated' => 
    array (
      0 => 'Aneg 1',
      1 => 'Aneg 2',
      2 => 'Aneg 3',
      3 => 'Aneg 4',
      4 => 'Aneg 5',
      5 => 'Aneg 6',
      6 => 'Aneg 7',
    ),
    'narrow' => 
    array (
      0 => 'A1',
      1 => 'A2',
      2 => 'A3',
      3 => 'A4',
      4 => 'A5',
      5 => 'A6',
      6 => 'A7',
    ),
    'short' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'A1',
      1 => 'A2',
      2 => 'A3',
      3 => 'A4',
      4 => 'A5',
      5 => 'A6',
      6 => 'A7',
    ),
    'abbreviated' => 
    array (
      0 => 'Aneg 1',
      1 => 'Aneg 2',
      2 => 'Aneg 3',
      3 => 'Aneg 4',
      4 => 'Aneg 5',
      5 => 'Aneg 6',
      6 => 'Aneg 7',
    ),
    'short' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
    'wide' => 
    array (
      0 => 'Aneg 1',
      1 => 'Aneg 2',
      2 => 'Aneg 3',
      3 => 'Aneg 4',
      4 => 'Aneg 5',
      5 => 'Aneg 6',
      6 => 'Aneg 7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, y MMMM dd',
    'long' => 'y MMMM d',
    'medium' => 'y MMM d',
    'short' => 'y-MM-dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'mgo' => 'metaÊ¼',
    'und' => 'ngam tisÉÊ¼',
  ),
  'scripts' => 
  array (
    'latn' => 'ngam ÅwaÊ¼ri',
    'zxxx' => 'ngam choÊ¼',
    'zzzz' => 'abo ÅwaÊ¼ri tisÉÊ¼',
  ),
  'territories' => 
  array (
    'cm' => 'Kamalun',
    'zz' => 'aba aben tisÉÌ',
  ),
  'pluralRules' => 
  array (
    0 => 'n==1',
    1 => 'true',
  ),
);
