<?php
/**
 * Locale data for 'nnh'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright Â© 1991-2013 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in https://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2014 Yii Software LLC (https://www.yiiframework.com/license/)
 */
return array (
  'version' => '8245',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ',',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => 'â°',
    'infinity' => 'â',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => 'Â¤Â #,##0.00',
  'currencySymbols' => 
  array (
    'AUD' => 'A$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CNÂ¥',
    'EUR' => 'â¬',
    'GBP' => 'Â£',
    'HKD' => 'HK$',
    'ILS' => 'âª',
    'INR' => 'â¹',
    'JPY' => 'JPÂ¥',
    'KRW' => 'â©',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => 'à¸¿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => 'â«',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'saÅ tsetsÉÌÉ lÃ¹m',
      2 => 'saÅ kÃ g ngwÃ³Å',
      3 => 'saÅ lepyÃ¨ shÃºm',
      4 => 'saÅ cÃ¿Ã³',
      5 => 'saÅ tsÉÌÉ cÃ¿Ã³',
      6 => 'saÅ njÃ¿olÃ¡Ê¼',
      7 => 'saÅ tyÉÌb tyÉÌb mbÊÌ',
      8 => 'saÅ mbÊÌÅ',
      9 => 'saÅ ngwÉÌÊ¼ mbÃ¿É',
      10 => 'saÅ tÃ Åa tsetsÃ¡Ê¼',
      11 => 'saÅ mejwoÅÃ³',
      12 => 'saÅ lÃ¹m',
    ),
    'abbreviated' => 
    array (
      1 => 'saÅ tsetsÉÌÉ lÃ¹m',
      2 => 'saÅ kÃ g ngwÃ³Å',
      3 => 'saÅ lepyÃ¨ shÃºm',
      4 => 'saÅ cÃ¿Ã³',
      5 => 'saÅ tsÉÌÉ cÃ¿Ã³',
      6 => 'saÅ njÃ¿olÃ¡Ê¼',
      7 => 'saÅ tyÉÌb tyÉÌb mbÊÌ',
      8 => 'saÅ mbÊÌÅ',
      9 => 'saÅ ngwÉÌÊ¼ mbÃ¿É',
      10 => 'saÅ tÃ Åa tsetsÃ¡Ê¼',
      11 => 'saÅ mejwoÅÃ³',
      12 => 'saÅ lÃ¹m',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
    'abbreviated' => 
    array (
      1 => 'saÅ tsetsÉÌÉ lÃ¹m',
      2 => 'saÅ kÃ g ngwÃ³Å',
      3 => 'saÅ lepyÃ¨ shÃºm',
      4 => 'saÅ cÃ¿Ã³',
      5 => 'saÅ tsÉÌÉ cÃ¿Ã³',
      6 => 'saÅ njÃ¿olÃ¡Ê¼',
      7 => 'saÅ tyÉÌb tyÉÌb mbÊÌ',
      8 => 'saÅ mbÊÌÅ',
      9 => 'saÅ ngwÉÌÊ¼ mbÃ¿É',
      10 => 'saÅ tÃ Åa tsetsÃ¡Ê¼',
      11 => 'saÅ mejwoÅÃ³',
      12 => 'saÅ lÃ¹m',
    ),
    'wide' => 
    array (
      1 => 'saÅ tsetsÉÌÉ lÃ¹m',
      2 => 'saÅ kÃ g ngwÃ³Å',
      3 => 'saÅ lepyÃ¨ shÃºm',
      4 => 'saÅ cÃ¿Ã³',
      5 => 'saÅ tsÉÌÉ cÃ¿Ã³',
      6 => 'saÅ njÃ¿olÃ¡Ê¼',
      7 => 'saÅ tyÉÌb tyÉÌb mbÊÌ',
      8 => 'saÅ mbÊÌÅ',
      9 => 'saÅ ngwÉÌÊ¼ mbÃ¿É',
      10 => 'saÅ tÃ Åa tsetsÃ¡Ê¼',
      11 => 'saÅ mejwoÅÃ³',
      12 => 'saÅ lÃ¹m',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'lyÉÊ¼ÉÌ sáºÃ­ÅtÃ¨',
      1 => 'mvfÃ² lyÉÌÊ¼',
      2 => 'mbÉÌÉntÃ¨ mvfÃ² lyÉÌÊ¼',
      3 => 'tsÃ¨tsÉÌÉ lyÉÌÊ¼',
      4 => 'mbÉÌÉntÃ¨ tsetsÉÌÉ lyÉÌÊ¼',
      5 => 'mvfÃ² mÃ ga lyÉÌÊ¼',
      6 => 'mÃ ga lyÉÌÊ¼',
    ),
    'abbreviated' => 
    array (
      0 => 'lyÉÊ¼ÉÌ sáºÃ­ÅtÃ¨',
      1 => 'mvfÃ² lyÉÌÊ¼',
      2 => 'mbÉÌÉntÃ¨ mvfÃ² lyÉÌÊ¼',
      3 => 'tsÃ¨tsÉÌÉ lyÉÌÊ¼',
      4 => 'mbÉÌÉntÃ¨ tsetsÉÌÉ lyÉÌÊ¼',
      5 => 'mvfÃ² mÃ ga lyÉÌÊ¼',
      6 => 'mÃ ga lyÉÌÊ¼',
    ),
    'short' => 
    array (
      0 => 'lyÉÊ¼ÉÌ sáºÃ­ÅtÃ¨',
      1 => 'mvfÃ² lyÉÌÊ¼',
      2 => 'mbÉÌÉntÃ¨ mvfÃ² lyÉÌÊ¼',
      3 => 'tsÃ¨tsÉÌÉ lyÉÌÊ¼',
      4 => 'mbÉÌÉntÃ¨ tsetsÉÌÉ lyÉÌÊ¼',
      5 => 'mvfÃ² mÃ ga lyÉÌÊ¼',
      6 => 'mÃ ga lyÉÌÊ¼',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'S',
      1 => 'M',
      2 => 'T',
      3 => 'W',
      4 => 'T',
      5 => 'F',
      6 => 'S',
    ),
    'abbreviated' => 
    array (
      0 => 'lyÉÊ¼ÉÌ sáºÃ­ÅtÃ¨',
      1 => 'mvfÃ² lyÉÌÊ¼',
      2 => 'mbÉÌÉntÃ¨ mvfÃ² lyÉÌÊ¼',
      3 => 'tsÃ¨tsÉÌÉ lyÉÌÊ¼',
      4 => 'mbÉÌÉntÃ¨ tsetsÉÌÉ lyÉÌÊ¼',
      5 => 'mvfÃ² mÃ ga lyÉÌÊ¼',
      6 => 'mÃ ga lyÉÌÊ¼',
    ),
    'short' => 
    array (
      0 => 'lyÉÊ¼ÉÌ sáºÃ­ÅtÃ¨',
      1 => 'mvfÃ² lyÉÌÊ¼',
      2 => 'mbÉÌÉntÃ¨ mvfÃ² lyÉÌÊ¼',
      3 => 'tsÃ¨tsÉÌÉ lyÉÌÊ¼',
      4 => 'mbÉÌÉntÃ¨ tsetsÉÌÉ lyÉÌÊ¼',
      5 => 'mvfÃ² mÃ ga lyÉÌÊ¼',
      6 => 'mÃ ga lyÉÌÊ¼',
    ),
    'wide' => 
    array (
      0 => 'lyÉÊ¼ÉÌ sáºÃ­ÅtÃ¨',
      1 => 'mvfÃ² lyÉÌÊ¼',
      2 => 'mbÉÌÉntÃ¨ mvfÃ² lyÉÌÊ¼',
      3 => 'tsÃ¨tsÉÌÉ lyÉÌÊ¼',
      4 => 'mbÉÌÉntÃ¨ tsetsÉÌÉ lyÉÌÊ¼',
      5 => 'mvfÃ² mÃ ga lyÉÌÊ¼',
      6 => 'mÃ ga lyÉÌÊ¼',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'm.z.Y.',
      1 => 'm.g.n.Y.',
    ),
    'wide' => 
    array (
      0 => 'mÃ© zyÃ© YÄsÃ´',
      1 => 'mÃ© gÃ¿o ÅzyÃ© YÄsÃ´',
    ),
    'narrow' => 
    array (
      0 => 'm.z.Y.',
      1 => 'm.g.n.Y.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE , \'lyÉ\'ÌÊ¼ d \'na\' MMMM, y',
    'long' => '\'lyÉ\'ÌÊ¼ d \'na\' MMMM, y',
    'medium' => 'd MMM, y',
    'short' => 'dd/MM/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss a',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1},{0}',
  'amName' => 'mbaÊ¼Ã¡mbaÊ¼',
  'pmName' => 'ncwÃ²nzÃ©m',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'bas' => 'ShwÃ³ÅÃ² pÊa mbasÇ',
    'bax' => 'ShwÃ³ÅÃ² pamom',
    'bbj' => 'ShwÃ³ÅÃ² pÊa nzsekÃ Ê¼a',
    'bfd' => 'ShwÃ³ÅÃ² pafut',
    'bkm' => 'ShwÃ³ÅÃ² pÊÌa njinikom',
    'bss' => 'ShwÃ³ÅÃ² pakÉsi',
    'bum' => 'ShwÃ³ÅÃ² mbulu',
    'byv' => 'ShwÃ³ÅÃ² ngÃ¡ÅtÊÉÊ¼',
    'de' => 'nzÇmÉÌÉn',
    'en' => 'ngilÃ­sÃ¨',
    'ewo' => 'ShwÃ³ÅÃ² pÊa YÉÉnmendi',
    'ff' => 'ShwÃ³ÅÃ² menkesaÅ',
    'fr' => 'felaÅsÃ©e',
    'kkj' => 'ShwÃ³ÅÃ² pÊa shÃ¿Ã³ BÉgtÃ¹a',
    'nnh' => 'ShwÃ³ÅÃ² ngiembÉÉn',
    'yav' => 'ShwÃ³ÅÃ² pÊa shÃ¿Ã³ MbafÃ¬a',
    'ybb' => 'ShwÃ³ÅÃ² TsaÅ',
  ),
  'territories' => 
  array (
    'cm' => 'KÃ malÃ»m',
  ),
  'pluralRules' => 
  array (
    0 => 'n==1',
    1 => 'true',
  ),
);
