<?php
/**
 * Locale data for 'uz_Arab_AF'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright Â© 1991-2013 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in https://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2014 Yii Software LLC (https://www.yiiframework.com/license/)
 */
return array (
  'version' => '8245',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => 'â',
    'exponential' => 'E',
    'perMille' => 'â°',
    'infinity' => 'â',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00Â Â¤',
  'currencySymbols' => 
  array (
    'AUD' => 'A$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CNÂ¥',
    'EUR' => 'â¬',
    'GBP' => 'Â£',
    'HKD' => 'HK$',
    'ILS' => 'âª',
    'INR' => 'â¹',
    'JPY' => 'JPÂ¥',
    'KRW' => 'â©',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => 'à¸¿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => 'â«',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
    'UZS' => 'ÑÑÐ¼',
    'AFN' => 'Ø',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Ø¬ÙÙØ±Û',
      2 => 'ÙØ¨Ø±ÙØ±Û',
      3 => 'ÙØ§Ø±Ú',
      4 => 'Ø§Ù¾Ø±ÛÙ',
      5 => 'ÙÛ',
      6 => 'Ø¬ÙÙ',
      7 => 'Ø¬ÙÙØ§Û',
      8 => 'Ø§Ú¯Ø³Øª',
      9 => 'Ø³Ù¾ØªÙØ¨Ø±',
      10 => 'Ø§Ú©ØªÙØ¨Ø±',
      11 => 'ÙÙÙØ¨Ø±',
      12 => 'Ø¯Ø³ÙØ¨Ø±',
    ),
    'abbreviated' => 
    array (
      1 => 'Ø¬ÙÙ',
      2 => 'ÙØ¨Ø±',
      3 => 'ÙØ§Ø±',
      4 => 'Ø§Ù¾Ø±',
      5 => 'ÙÙÛ',
      6 => 'Ø¬ÙÙ',
      7 => 'Ø¬ÙÙ',
      8 => 'Ø§Ú¯Ø³',
      9 => 'Ø³Ù¾Øª',
      10 => 'Ø§Ú©Øª',
      11 => 'ÙÙÙ',
      12 => 'Ø¯Ø³Ù',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'Ð¯',
      2 => 'Ð¤',
      3 => 'Ð',
      4 => 'Ð',
      5 => 'Ð',
      6 => 'Ð',
      7 => 'Ð',
      8 => 'Ð',
      9 => 'Ð¡',
      10 => 'Ð',
      11 => 'Ð',
      12 => 'Ð',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'ÛÚ©Ø´ÙØ¨Ù',
      1 => 'Ø¯ÙØ´ÙØ¨Ù',
      2 => 'Ø³ÙâØ´ÙØ¨Ù',
      3 => 'ÚÙØ§Ø±Ø´ÙØ¨Ù',
      4 => 'Ù¾ÙØ¬Ø´ÙØ¨Ù',
      5 => 'Ø¬ÙØ¹Ù',
      6 => 'Ø´ÙØ¨Ù',
    ),
    'abbreviated' => 
    array (
      0 => 'Û.',
      1 => 'Ø¯.',
      2 => 'Ø³.',
      3 => 'Ú.',
      4 => 'Ù¾.',
      5 => 'Ø¬.',
      6 => 'Ø´.',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'Ð¯',
      1 => 'Ð',
      2 => 'Ð¡',
      3 => 'Ð§',
      4 => 'Ð',
      5 => 'Ð',
      6 => 'Ð¨',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'Ù.Ù.',
      1 => 'Ù.',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'y ÙÚÛ ÛÛÙ d ÙÚÛ MMMM EEEE Ú©ÙÙÛ',
    'long' => 'd ÙÚÛ MMMM y',
    'medium' => 'd MMM y',
    'short' => 'y/M/d',
  ),
  'timeFormats' => 
  array (
    'full' => 'H:mm:ss (zzzz)',
    'long' => 'H:mm:ss (z)',
    'medium' => 'H:mm:ss',
    'short' => 'H:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
  'orientation' => 'rtl',
  'languages' => 
  array (
    'ar' => 'ÐÑÐ°Ð±ÑÐ°',
    'de' => 'ÐÐ»Ð¼Ð¾Ð½ÑÐ°',
    'en' => 'ÐÐ½Ð³Ð»Ð¸Ð·ÑÐ°',
    'es' => 'ÐÑÐ¿Ð°Ð½ÑÐ°',
    'fr' => 'Ð¤ÑÐ°Ð½ÑÑÐ·ÑÐ°',
    'hi' => 'Ò²Ð¸Ð½Ð´ÑÐ°',
    'it' => 'ÐÑÐ°Ð»ÑÐ½ÑÐ°',
    'ja' => 'Ð¯Ð¿Ð¾Ð½ÑÐ°',
    'pt' => 'ÐÐ¾ÑÑÑÐ³Ð°Ð»ÑÐ°',
    'ru' => 'Ð ÑÑÑÐ°',
    'uz' => 'Ø§ÙØ²Ø¨ÛÚ©',
    'zh' => 'Ð¥Ð¸ÑÐ¾Ð¹ÑÐ°',
    'fa' => 'Ø¯Ø±Û',
    'ps' => 'Ù¾Ø´ØªÙ',
  ),
  'scripts' => 
  array (
    'arab' => 'ÐÑÐ°Ð±',
    'cyrl' => 'ÐÐ¸ÑÐ¸Ð»',
    'latn' => 'ÐÐ¾ÑÐ¸Ð½',
  ),
  'territories' => 
  array (
    'af' => 'Ø§ÙØºØ§ÙØ³ØªØ§Ù',
    'br' => 'ÐÑÐ°Ð·Ð¸Ð»Ð¸Ñ',
    'cn' => 'Ð¥Ð¸ÑÐ¾Ð¹',
    'de' => 'ÐÐ»Ð¼Ð¾Ð½Ð¸Ñ',
    'fr' => 'Ð¤ÑÐ°Ð½ÑÐ¸Ñ',
    'gb' => 'ÐÐ¸ÑÐ»Ð°ÑÐ³Ð°Ð½ ÒÐ¸ÑÐ¾Ð»Ð»Ð¸Ðº',
    'in' => 'Ò²Ð¸Ð½Ð´Ð¸ÑÑÐ¾Ð½',
    'it' => 'ÐÑÐ°Ð»Ð¸Ñ',
    'jp' => 'Ð¯Ð¿Ð¾Ð½Ð¸Ñ',
    'ru' => 'Ð Ð¾ÑÑÐ¸Ñ',
    'us' => 'ÒÑÑÐ¼Ð° Ð¨ÑÐ°ÑÐ»Ð°Ñ',
    'uz' => 'ÐÐ·Ð±ÐµÐºÐ¸ÑÑÐ¾Ð½',
  ),
);
