<?php
/**
 * Locale data for 'uz_Cyrl'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright Â© 1991-2013 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in https://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2014 Yii Software LLC (https://www.yiiframework.com/license/)
 */
return array (
  'version' => '8245',
  'numberSymbols' => 
  array (
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => 'â°',
    'infinity' => 'â',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => 'Â¤Â #,##0.00',
  'currencySymbols' => 
  array (
    'AUD' => 'A$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CNÂ¥',
    'EUR' => 'â¬',
    'GBP' => 'Â£',
    'HKD' => 'HK$',
    'ILS' => 'âª',
    'INR' => 'â¹',
    'JPY' => 'JPÂ¥',
    'KRW' => 'â©',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => 'à¸¿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => 'â«',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
    'UZS' => 'ÑÑÐ¼',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Ð¯Ð½Ð²Ð°Ñ',
      2 => 'Ð¤ÐµÐ²ÑÐ°Ð»',
      3 => 'ÐÐ°ÑÑ',
      4 => 'ÐÐ¿ÑÐµÐ»',
      5 => 'ÐÐ°Ð¹',
      6 => 'ÐÑÐ½',
      7 => 'ÐÑÐ»',
      8 => 'ÐÐ²Ð³ÑÑÑ',
      9 => 'Ð¡ÐµÐ½ÑÑÐ±Ñ',
      10 => 'ÐÐºÑÑÐ±Ñ',
      11 => 'ÐÐ¾ÑÐ±Ñ',
      12 => 'ÐÐµÐºÐ°Ð±Ñ',
    ),
    'abbreviated' => 
    array (
      1 => 'Ð¯Ð½Ð²',
      2 => 'Ð¤ÐµÐ²',
      3 => 'ÐÐ°Ñ',
      4 => 'ÐÐ¿Ñ',
      5 => 'ÐÐ°Ð¹',
      6 => 'ÐÑÐ½',
      7 => 'ÐÑÐ»',
      8 => 'ÐÐ²Ð³',
      9 => 'Ð¡ÐµÐ½',
      10 => 'ÐÐºÑ',
      11 => 'ÐÐ¾Ñ',
      12 => 'ÐÐµÐº',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'Ð¯',
      2 => 'Ð¤',
      3 => 'Ð',
      4 => 'Ð',
      5 => 'Ð',
      6 => 'Ð',
      7 => 'Ð',
      8 => 'Ð',
      9 => 'Ð¡',
      10 => 'Ð',
      11 => 'Ð',
      12 => 'Ð',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'ÑÐºÑÐ°Ð½Ð±Ð°',
      1 => 'Ð´ÑÑÐ°Ð½Ð±Ð°',
      2 => 'ÑÐµÑÐ°Ð½Ð±Ð°',
      3 => 'ÑÐ¾ÑÑÐ°Ð½Ð±Ð°',
      4 => 'Ð¿Ð°Ð¹ÑÐ°Ð½Ð±Ð°',
      5 => 'Ð¶ÑÐ¼Ð°',
      6 => 'ÑÐ°Ð½Ð±Ð°',
    ),
    'abbreviated' => 
    array (
      0 => 'Ð¯ÐºÑ',
      1 => 'ÐÑÑ',
      2 => 'Ð¡ÐµÑ',
      3 => 'Ð§Ð¾Ñ',
      4 => 'ÐÐ°Ð¹',
      5 => 'ÐÑÐ¼',
      6 => 'Ð¨Ð°Ð½',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'Ð¯',
      1 => 'Ð',
      2 => 'Ð¡',
      3 => 'Ð§',
      4 => 'Ð',
      5 => 'Ð',
      6 => 'Ð¨',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, y MMMM dd',
    'long' => 'y MMMM d',
    'medium' => 'y MMM d',
    'short' => 'yy/MM/dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'ar' => 'ÐÑÐ°Ð±ÑÐ°',
    'de' => 'ÐÐ»Ð¼Ð¾Ð½ÑÐ°',
    'en' => 'ÐÐ½Ð³Ð»Ð¸Ð·ÑÐ°',
    'es' => 'ÐÑÐ¿Ð°Ð½ÑÐ°',
    'fr' => 'Ð¤ÑÐ°Ð½ÑÑÐ·ÑÐ°',
    'hi' => 'Ò²Ð¸Ð½Ð´ÑÐ°',
    'it' => 'ÐÑÐ°Ð»ÑÐ½ÑÐ°',
    'ja' => 'Ð¯Ð¿Ð¾Ð½ÑÐ°',
    'pt' => 'ÐÐ¾ÑÑÑÐ³Ð°Ð»ÑÐ°',
    'ru' => 'Ð ÑÑÑÐ°',
    'uz' => 'ÐÐ·Ð±ÐµÐº',
    'zh' => 'Ð¥Ð¸ÑÐ¾Ð¹ÑÐ°',
  ),
  'scripts' => 
  array (
    'arab' => 'ÐÑÐ°Ð±',
    'cyrl' => 'ÐÐ¸ÑÐ¸Ð»',
    'latn' => 'ÐÐ¾ÑÐ¸Ð½',
  ),
  'territories' => 
  array (
    'af' => 'ÐÑÒÐ¾Ð½Ð¸ÑÑÐ¾Ð½',
    'br' => 'ÐÑÐ°Ð·Ð¸Ð»Ð¸Ñ',
    'cn' => 'Ð¥Ð¸ÑÐ¾Ð¹',
    'de' => 'ÐÐ»Ð¼Ð¾Ð½Ð¸Ñ',
    'fr' => 'Ð¤ÑÐ°Ð½ÑÐ¸Ñ',
    'gb' => 'ÐÐ¸ÑÐ»Ð°ÑÐ³Ð°Ð½ ÒÐ¸ÑÐ¾Ð»Ð»Ð¸Ðº',
    'in' => 'Ò²Ð¸Ð½Ð´Ð¸ÑÑÐ¾Ð½',
    'it' => 'ÐÑÐ°Ð»Ð¸Ñ',
    'jp' => 'Ð¯Ð¿Ð¾Ð½Ð¸Ñ',
    'ru' => 'Ð Ð¾ÑÑÐ¸Ñ',
    'us' => 'ÒÑÑÐ¼Ð° Ð¨ÑÐ°ÑÐ»Ð°Ñ',
    'uz' => 'ÐÐ·Ð±ÐµÐºÐ¸ÑÑÐ¾Ð½',
  ),
);
