<?php
/**
 * Locale data for 've_ZA'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright Â© 1991-2013 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in https://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2014 Yii Software LLC (https://www.yiiframework.com/license/)
 */
return array (
  'version' => '8245',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => 'Â ',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => 'â°',
    'infinity' => 'â',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => 'Â¤#,##0.00',
  'currencySymbols' => 
  array (
    'AUD' => 'A$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CNÂ¥',
    'EUR' => 'â¬',
    'GBP' => 'Â£',
    'HKD' => 'HK$',
    'ILS' => 'âª',
    'INR' => 'â¹',
    'JPY' => 'JPÂ¥',
    'KRW' => 'â©',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => 'à¸¿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => 'â«',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
    'ZAR' => 'R',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Phando',
      2 => 'Luhuhi',
      3 => 'á¹°hafamuhwe',
      4 => 'Lambamai',
      5 => 'Shundunthule',
      6 => 'Fulwi',
      7 => 'Fulwana',
      8 => 'á¹°hangule',
      9 => 'Khubvumedzi',
      10 => 'Tshimedzi',
      11 => 'á¸¼ara',
      12 => 'Nyendavhusiku',
    ),
    'abbreviated' => 
    array (
      1 => 'Pha',
      2 => 'Luh',
      3 => 'á¹°hf',
      4 => 'Lam',
      5 => 'Shu',
      6 => 'Lwi',
      7 => 'Lwa',
      8 => 'á¹°ha',
      9 => 'Khu',
      10 => 'Tsh',
      11 => 'á¸¼ar',
      12 => 'Nye',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Swondaha',
      1 => 'Musumbuluwo',
      2 => 'á¸¼avhuvhili',
      3 => 'á¸¼avhuraru',
      4 => 'á¸¼avhuá¹a',
      5 => 'á¸¼avhuá¹±anu',
      6 => 'Mugivhela',
    ),
    'abbreviated' => 
    array (
      0 => 'Swo',
      1 => 'Mus',
      2 => 'Vhi',
      3 => 'Rar',
      4 => 'á¹a',
      5 => 'á¹°an',
      6 => 'Mug',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'S',
      1 => 'M',
      2 => 'T',
      3 => 'W',
      4 => 'T',
      5 => 'F',
      6 => 'S',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'y MMMM d, EEEE',
    'long' => 'y MMMM d',
    'medium' => 'y MMM d',
    'short' => 'y-MM-dd',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
  'orientation' => 'ltr',
  'languages' => 
  array (
    've' => 'Tshivená¸a',
  ),
  'pluralRules' => 
  array (
    0 => 'n==1',
    1 => 'true',
  ),
);
