<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '"{path}" is not a valid directory.' => '{path} ã¯æå¹ãªãã£ã¬ã¯ããªã§ã¯ããã¾ããã',
  '&lt; Previous' => '&lt; å',
  '&lt;&lt; First' => '&lt;&lt; æå',
  'A PHP extension stopped the file upload.' => 'PHP ã®æ¡å¼µã¢ã¸ã¥ã¼ã«ããã¡ã¤ã«ã®ã¢ããã­ã¼ããä¸­æ­¢ãã¾ããã',
  'Action class {class} must implement the "run" method.' => 'ã¢ã¯ã·ã§ã³ã¯ã©ã¹{class}ã¯"run"ã¡ã½ãããå®è£ããå¿è¦ãããã¾ãã',
  'Active Record requires a "db" CDbConnection application component.' => 'Active Record ã¯ "db" ã¨ãã CDbConnection ã¢ããªã±ã¼ã·ã§ã³ã³ã³ãã¼ãã³ããå¿è¦ã¨ãã¾ãã',
  'Active record "{class}" has an invalid configuration for relation "{relation}". It must specify the relation type, the related active record class and the foreign key.' => 'ã¢ã¯ãã£ãã¬ã³ã¼ã "{class}" ã®ããªã¬ã¼ã·ã§ã³ {relation} ã®ã³ã³ãã£ã®ã¥ã¬ã¼ã·ã§ã³ã«èª¤ããããã¾ãããªã¬ã¼ã·ã§ã³ã¿ã¤ããé¢ä¿ããã¢ã¯ãã£ãã¬ã³ã¼ãã¯ã©ã¹ã¨å¤é¨ã­ã¼ãæå®ãã¦ä¸ããã',
  'Active record "{class}" is trying to select an invalid column "{column}". Note, the column must exist in the table or be an expression with alias.' => 'ã¢ã¯ãã£ãã¬ã³ã¼ã "{class}" ã¯èª¤ã£ãã«ã©ã  "{column}" ãé¸æãããã¨ãã¾ããããã¼ãã«ã«å­å¨ããã«ã©ã ãå¥åãæå®ããå¼ã§ãªããã°ããã¾ããã',
  'Adding a foreign key constraint to an existing table is not supported by SQLite.' => 'SQLiteã§ã¯æ¢å­ã®ãã¼ãã«ã«å¤é¨ã­ã¼å¶ç´ãä¸ãããã¾ããã',
  'Adding a primary key after table has been created is not supported by SQLite.' => 'SQLiteã§ã¯æ¢å­ã®ãã¼ãã«ã«ãã©ã¤ããªã­ã¼ãè¿½å ãããã¨ã¯ã§ãã¾ããã',
  'Alias "{alias}" is invalid. Make sure it points to an existing PHP file and the file is readable.' => '"{alias}"ã¯ç¡å¹ã§ããphpãã¡ã¤ã«ãå­å¨ããèª­ã¿è¾¼ã¿å¯è½ãç¢ºèªãã¦ãã ããã',
  'Alias "{alias}" is invalid. Make sure it points to an existing directory or file.' => 'ãã¹ã¨ã¤ãªã¢ã¹ "{alias}" ãééã£ã¦ãã¾ããå­å¨ãããã£ã¬ã¯ããªããã¡ã¤ã«ãæãã¦ããããç¢ºèªãã¦ãã ããã',
  'Altering a DB column is not supported by SQLite.' => 'SQLiteã§ã¯ãã¼ã¿ãã¼ã¹ã®ã«ã©ã ãå¤æ´ãããã¨ã¯ã§ãã¾ããã',
  'Application Log' => 'ã¢ããªã±ã¼ã·ã§ã³ã­ã°',
  'Application base path "{path}" is not a valid directory.' => 'ã¢ããªã±ã¼ã·ã§ã³ãã¼ã¹ãã¹ "{path}" ã¯æå¹ãªãã£ã¬ã¯ããªã§ã¯ããã¾ããã',
  'Application runtime path "{path}" is not valid. Please make sure it is a directory writable by the Web server process.' => 'ã¢ããªã±ã¼ã·ã§ã³ã©ã³ã¿ã¤ã ãã¹ "{path}" ã¯æ­£ããããã¾ãããã¦ã§ããµã¼ããã­ã»ã¹ãæ¸ãè¾¼ããããç¢ºèªãã¦ãã ããã',
  'Authorization item "{item}" has already been assigned to user "{user}".' => 'èªè¨¼é ç® "{item}" ã¯æ¢ã«ã¦ã¼ã¶ "{user}" ã«å²ãå½ã¦ããã¦ãã¾ãã',
  'Base path "{path}" is not a valid directory.' => 'ãã¼ã¹ãã¹"{path}"ã¯æå¹ãªãã£ã¬ã¯ããªã§ã¯ããã¾ããã',
  'CApcCache requires PHP apc extension to be loaded.' => 'CApcCache ã¯PHPã®APCæ¡å¼µãå¿è¦ã¨ãã¾ãã',
  'CAssetManager.basePath "{path}" is invalid. Please make sure the directory exists and is writable by the Web server process.' => 'CAssetManager.basePath "{path}" ã¯ç¡å¹ã§ãããã£ã¬ã¯ããªãå­å¨ãã¦ã¦ã§ããµã¼ããã­ã»ã¹ãæ¸ãè¾¼ããããç¢ºèªãã¦ãã ããã',
  'CCacheHttpSession.cacheID is invalid. Please make sure "{id}" refers to a valid cache application component.' => 'CCacheHttpSession.cacheID ãç¡å¹ã§ãã"{id}" ãæ­£ããã­ã£ãã·ã¥ã¢ããªã±ã¼ã·ã§ã³ã³ã³ãã¼ãã³ããåç§ãã¦ãããç¢ºèªãã¦ãã ããã',
  'CCaptchaValidator.action "{id}" is invalid. Unable to find such an action in the current controller.' => 'CCaptchaValidator.action "{id}" ãç¡å¹ã§ããç¾å¨ã®ã³ã³ãã­ã¼ã©ä¸­ã«ãã®ãããªã¢ã¯ã·ã§ã³ãå­å¨ãã¾ããã',
  'CDbAuthManager.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbAuthManager.connectionID "{id}" ãç¡å¹ã§ããCDbConnection ã¢ããªã±ã¼ã·ã§ã³ã³ã³ãã¼ãã³ãã®IDãåç§ãã¦ããããç¢ºèªãã¦ãã ããã',
  'CDbCache.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbCache.connectionID "{id}" ãç¡å¹ã§ããCDbConnection ã¢ããªã±ã¼ã·ã§ã³ã³ã³ãã¼ãã³ãã®IDãåç§ãã¦ããããç¢ºèªãã¦ãã ããã',
  'CDbCacheDependency.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbCacheDependency.connectionID "{id}"ã¯ç¡å¹ã§ããCDbConnectionã¢ããªã±ã¼ã·ã§ã³ã³ã³ãã¼ãã³ãã®IDãæãã¦ãããç¢ºèªãã¦ãã ããã',
  'CDbCacheDependency.sql cannot be empty.' => 'CDbCacheDependency.sql ã¯ç©ºç½ã§ã¯ããã¾ããã',
  'CDbCommand failed to execute the SQL statement: {error}' => 'CDbCommand ã¯SQLæãå®è¡ã§ãã¾ããã:{error}',
  'CDbCommand failed to prepare the SQL statement: {error}' => 'CDbCommand ã¯SQLæãæºåã§ãã¾ããã:{error}',
  'CDbCommand::execute() failed: {error}. The SQL statement executed was: {sql}.' => 'CDbCommand::execute()ã{error}ã§å¤±æãã¾ãããå®è¡ãããSQLæã¯: {sql}',
  'CDbCommand::{method}() failed: {error}. The SQL statement executed was: {sql}.' => 'CDbCommand::{method}() ã{error}ã§å¤±æãã¾ãããå®è¡ãããSQLæã¯: {sql}',
  'CDbConnection does not support reading schema for {driver} database.' => 'CDbConnection ã¯ {driver} ãã¼ã¿ãã¼ã¹ã«å¯¾ãã¦ã¹ã­ã¼ãã®èª­ã¿åãããµãã¼ããã¦ãã¾ããã',
  'CDbConnection failed to open the DB connection.' => 'CDbConnection ã DB æ¥ç¶ã«å¤±æãã¾ããã',
  'CDbConnection is unable to find PDO class "{className}". Make sure PDO is installed correctly.' => 'CDbConnection ã PDO ã®ã¯ã©ã¹ "{className}" ãè¦ã¤ãããã¨ãåºæ¥ã¾ãããPDO ãæ­£ããã¤ã³ã¹ãã¼ã«ããã¦ããããç¢ºèªãã¦ãã ããã',
  'CDbDataReader cannot rewind. It is a forward-only reader.' => 'CDbDataReader ã¯å·»ãæ»ãã§ãã¾ãããããã¯é æ¹åã®ã¿ã®ãªã¼ãã§ãã',
  'CDbHttpSession.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbHttpSession.connectionID "{id}" ãç¡å¹ã§ããCDbConnection ã¢ããªã±ã¼ã·ã§ã³ã³ã³ãã¼ãã³ãã®IDãåç§ãã¦ããããç¢ºèªãã¦ãã ããã',
  'CDbLogRoute.connectionID "{id}" does not point to a valid CDbConnection application component.' => 'CDbLogRoute.connectionID "{id}" ãæ­£ãã CDbConnection ã¢ããªã±ã¼ã·ã§ã³ã³ã³ãã¼ãã³ããåç§ãã¦ãã¾ãã',
  'CDbMessageSource.connectionID is invalid. Please make sure "{id}" refers to a valid database application component.' => 'CDbMessageSource.connectionID ãç¡å¹ã§ãã"{id}"ãæ­£ãããã¼ã¿ãã¼ã¹ã¢ããªã±ã¼ã·ã§ã³ã³ã³ãã¼ãã³ããåç§ãã¦ããããç¢ºèªãã¦ãã ããã',
  'CDbTestFixture.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbTestFixture.connectionID "{id}"ã¯ç¡å¹ã§ããCDbConnectionã¢ããªã±ã¼ã·ã§ã³ã³ã³ãã¼ãã³ãã®IDãæãã¦ãããç¢ºèªãã¦ãã ããã',
  'CDbTransaction is inactive and cannot perform commit or roll back operations.' => 'CDbTransaction ãã¢ã¯ãã£ãã§ã¯ãªããã³ããããã­ã¼ã«ããã¯æä½ãå®è¡ã§ãã¾ããã',
  'CDirectoryCacheDependency.directory cannot be empty.' => 'CDirectoryCacheDependency.directory ã¯ç©ºç½ã§ã¯ããã¾ããã',
  'CEAcceleratorCache requires PHP eAccelerator extension to be loaded, enabled or compiled with the "--with-eaccelerator-shared-memory" option.' => 'CEAcceleratorCache ã¯PHPã® eAccelerator æ¡å¼µãå¿è¦ã¨ãã¾ããæå¹ã«ãããã "--with-eaccelerator-shared-memory" ãªãã·ã§ã³ãã¤ãã¦ã³ã³ãã¤ã«ãã¦ãã ããã',
  'CFileCacheDependency.fileName cannot be empty.' => 'CFileCacheDependency.fileName ã¯ç©ºç½ã§ã¯ããã¾ããã',
  'CFileLogRoute.logPath "{path}" does not point to a valid directory. Make sure the directory exists and is writable by the Web server process.' => 'CFileLogRoute.logPath "{path}" ãæå¹ãªãã£ã¬ã¯ããªã§ã¯ããã¾ããããã£ã¬ã¯ããªãå­å¨ãã¦ã¦ã§ããµã¼ããã­ã»ã¹ãæ¸ãè¾¼ããããç¢ºèªãã¦ãã ããã',
  'CFilterChain can only take objects implementing the IFilter interface.' => 'CFilterChain ã¯ IFilter ã¤ã³ã¿ãã§ã¼ã¹ãå®è£ãããªãã¸ã§ã¯ãã®ã¿åãåãã¾ãã',
  'CFlexWidget.baseUrl cannot be empty.' => 'CFlexWidget.baseUrl ã¯ç©ºç½ã§ã¯ããã¾ããã',
  'CFlexWidget.name cannot be empty.' => 'CFlexWidget.name  ã¯ç©ºç½ã§ã¯ããã¾ããã',
  'CGlobalStateCacheDependency.stateName cannot be empty.' => 'CGlobalStateCacheDependency.stateName ã¯ç©ºç½ã§ã¯ããã¾ããã',
  'CHttpCacheFilter.lastModified contained a value that could not be understood by strtotime()' => 'CHttpCacheFilter.lastModified ã« strtotime() ãè§£éã§ããªãå¤ãå¥ã£ã¦ãã¾ããã',
  'CHttpCookieCollection can only hold CHttpCookie objects.' => 'CHttpCookieCollection ã¯ CHttpCookie ãªãã¸ã§ã¯ãã®ã¿ãæã¡ã¾ãã',
  'CHttpRequest is unable to determine the entry script URL.' => 'CHttpRequest ã¯ã¨ã³ããªã¹ã¯ãªããã®URLãæ±ºå®ã§ãã¾ããã',
  'CHttpRequest is unable to determine the path info of the request.' => 'CHttpRequest ã¯ãªã¯ã¨ã¹ãã®ãã¹æå ±ãæ±ºå®ã§ãã¾ããã',
  'CHttpRequest is unable to determine the request URI.' => 'CHttpRequest ã¯ãªã¯ã¨ã¹ãURIãæ±ºå®ã§ãã¾ããã',
  'CHttpSession.cookieMode can only be "none", "allow" or "only".' => 'CHttpSession.cookieMode ã®åãå¤ã¯"none"ã"allow"ãåã¯"only"ã§ãã',
  'CHttpSession.gcProbability "{value}" is invalid. It must be a float between 0 and 100.' => 'CHttpSession.gcProbability "{value}" ãç¡å¹ã§ãã0ãã100ã¾ã§ã®å®æ°ã«ãã¦ãã ããã',
  'CHttpSession.savePath "{path}" is not a valid directory.' => 'CHttpSession.savePath "{path}" ã¯ç¡å¹ãªãã£ã¬ã¯ããªã§ãã',
  'CMemCache requires PHP {extension} extension to be loaded.' => 'CMemCache ã¯ PHP {extension}æ¡å¼µã®ã­ã¼ããå¿è¦ã¨ãã¾ãã',
  'CMemCache server configuration must be an array.' => 'CMemCache ãµã¼ãã³ã³ãã£ã®ã¥ã¬ã¼ã·ã§ã³ã¯éåã«ãã¦ãã ããã',
  'CMemCache server configuration must have "host" value.' => 'CMemCache ãµã¼ãã³ã³ãã£ã®ã¥ã¬ã¼ã·ã§ã³ã«ã¯ host å¤ãå¿è¦ã§ãã',
  'CProfileLogRoute found a mismatching code block "{token}". Make sure the calls to Yii::beginProfile() and Yii::endProfile() be properly nested.' => 'CProfileLogRoute ãæ´åã®åããªãã³ã¼ããã­ãã¯ "{token}" ãè¦ã¤ãã¾ãããYii::beginProfile() ã¨ Yii::endProfile()ã®å¼ã³åºããæ­£ãããã¹ãããã¦ãããç¢ºèªãã¦ãã ããã',
  'CProfileLogRoute.report "{report}" is invalid. Valid values include "summary" and "callstack".' => 'CProfileLogRoute.report "{report}" ãç¡å¹ã§ããæ­£ããå¤ã¯ "summary" ã¨ "callstack" ãå«ã¿ã¾ãã',
  'CSecurityManager requires PHP mcrypt extension to be loaded in order to use data encryption feature.' => 'CSecurityManager ã®ãã¼ã¿æå·åæ©è½ãä½¿ç¨ããããã«ã¯PHPã®mcryptæ¡å¼µãå¿è¦ã¨ãã¾ãã',
  'CSecurityManager.encryptionKey cannot be empty.' => 'CSecurityManager.encryptionKey ã¯ç©ºç½ã§ã¯ããã¾ããã',
  'CSecurityManager.validationKey cannot be empty.' => 'CSecurityManager.validationKey ã¯ç©ºç½ã§ã¯ããã¾ããã',
  'CSecurityManager::generateRandomString() cannot generate random string in the current environment.' => 'CSecurityManager::generateRandomString() ã¯ç¾å¨ã®ç°å¢ã§ã¯ã©ã³ãã æå­åãçæã§ãã¾ããã',
  'CTypedList<{type}> can only hold objects of {type} class.' => 'CTypedList<{type}> ã¯ {type} ã¯ã©ã¹ã®ãªãã¸ã§ã¯ãããæã¦ã¾ããã',
  'CTypedMap<{type}> can only hold objects of {type} class.' => 'CTypedMap<{type}>ã¯{type}ã¯ã©ã¹ã®ãªãã¸ã§ã¯ãã®ã¿ãä¿æã§ãã¾ãã',
  'CUrlManager.UrlFormat must be either "path" or "get".' => 'CUrlManager.UrlFormat ã¯ "path" ã "get" ã®ããããã§ãã',
  'CWinCache requires PHP wincache extension to be loaded.' => 'CWinCacheã¯PHPã®wincacheæ¡å¼µãå¿è¦ã¨ãã¾ãã',
  'CWinCache user cache is disabled. Please set wincache.ucenabled to On in your php.ini.' => 'CWinCacheã¦ã¼ã¶ã­ã£ãã·ã¥ãç¡å¹åããã¦ãã¾ããphp.iniä¸­ã®wincache.ucenabledãOnã«è¨­å®ãã¦ãã ããã',
  'CXCache requires PHP XCache extension to be loaded.' => 'CXCache ã¯PHPã®XCacheæ¡å¼µãå¿è¦ã¨ãã¾ãã',
  'CZendDataCache requires PHP Zend Data Cache extension to be loaded.' => 'CZendDataCache ã¯ PHP Zend Data Cache æ¡å¼µãå¿è¦ã¨ãã¾ãã',
  'Cannot add "{child}" as a child of "{name}". A loop has been detected.' => '"{name}" ã®å­ä¾ã¨ãã¦ "{child}" ã¯è¿½å ã§ãã¾ãããã«ã¼ããæ¤åºããã¾ããã',
  'Cannot add "{child}" as a child of "{parent}". A loop has been detected.' => '"{parent}" ã®å­ä¾ã¨ãã¦ "{child}" ã¯è¿½å ã§ãã¾ãããã«ã¼ããæ¤åºããã¾ããã',
  'Cannot add "{name}" as a child of itself.' => '"{name}" ã®å­ä¾ã¨ãã¦èªåèªèº«ã¯è¿½å ã§ãã¾ããã',
  'Cannot add an item of type "{child}" to an item of type "{parent}".' => '"{parent}" åã®é ç®ã« "{child}" åã®é ç®ã¯è¿½å ã§ãã¾ããã',
  'Class name "{class}" does not match class file "{file}".' => 'ã¯ã©ã¹å "{class}" ãã¯ã©ã¹ãã¡ã¤ã« "{file}"ã¨ä¸è´ãã¾ããã',
  'Column name must be either a string or an array.' => 'ã«ã©ã åã¯æå­åã¾ãã¯éåã§ãªããã°ããã¾ããã',
  'Dropping DB column is not supported by SQLite.' => 'SQLiteã§ã¯ãã¼ã¿ãã¼ã¹ã«ã©ã ãåé¤ãããã¨ã¯ã§ãã¾ããã',
  'Dropping a foreign key constraint is not supported by SQLite.' => 'SQLiteã§ã¯å¤é¨ã­ã¼å¶ç´ãåé¤ãããã¨ã¯ã§ãã¾ããã',
  'Either "{parent}" or "{child}" does not exist.' => '"{parent}" ãããã¯ "{child}" ãå­å¨ãã¾ããã',
  'Error: Table "{table}" does not have a primary key.' => 'ã¨ã©ã¼: ãã¼ãã« "{table}" ã«ãã©ã¤ããªã­ã¼ãå­å¨ãã¾ããã',
  'Error: Table "{table}" has a composite primary key which is not supported by crud command.' => 'ã¨ã©ã¼: ãã¼ãã« "{table}" ã«è¤åãã©ã¤ããªã­ã¼ãå­å¨ãã¾ãããããã¯CRUDã³ãã³ãã§ãµãã¼ãããã¾ããã',
  'Event "{class}.{event}" is attached with an invalid handler "{handler}".' => 'ã¤ãã³ã "{class}.{event}" ã«ç¡å¹ãªãã³ãã© "{handler}" ãã¢ã¿ããããã¾ããã',
  'Event "{class}.{event}" is not defined.' => 'ã¤ãã³ã "{class}.{event}" ãå®ç¾©ããã¦ãã¾ããã',
  'Extension path "{path}" does not exist.' => 'ã¨ã¯ã¹ãã³ã·ã§ã³ãã¹"{path}"ã¯å­å¨ãã¾ããã',
  'Failed to initialize the mcrypt module.' => 'mcryptã¢ã¸ã¥ã¼ã«ã¯åæåã§ãã¾ããã§ããã',
  'Failed to set unsafe attribute "{attribute}" of "{class}".' => '"{class}" ã®å®å¨ã§ãªãå±æ§"{attribute}"ãã»ããã§ãã¾ããã§ããã',
  'Failed to start session.' => 'ã»ãã·ã§ã³ãéå§ã§ãã¾ããã§ããã',
  'Failed to write the uploaded file "{file}" to disk.' => 'ã¢ããã­ã¼ãããããã¡ã¤ã« "{file}" ããã£ã¹ã¯ã«æ¸ãè¾¼ãã¾ããã§ããã',
  'Filter "{filter}" is invalid. Controller "{class}" does not have the filter method "filter{filter}".' => '"{filter}"ã¨ãããã£ã«ã¿ã¯ç¡å¹ã§ããã³ã³ãã­ã¼ã©"{class}"ã«ã¯ãã£ã«ã¿ã¡ã½ãã"filter{filter}"ã¯å­å¨ãã¾ããã',
  'GD with FreeType or ImageMagick PHP extensions are required.' => 'GD ã¨ FreeTypeãã¾ãã¯ ImageMagick ã® PHP æ¡å¼µãå¿è¦ã§ãã',
  'Get a new code' => 'æ°ããã³ã¼ããåå¾',
  'Go to page: ' => 'ãã¼ã¸:',
  'In order to use MIME-type validation provided by CFileValidator fileinfo PECL extension should be installed.' => 'CFileValidator ãæä¾ãã MIME ã¿ã¤ãæ¤è¨¼ãä½¿ãããã«ã¯ãfileinfo PECL æ¡å¼µã®ã¤ã³ã¹ãã¼ã«ãå¿è¦ã§ãã',
  'Internal error while generating hash.' => 'ããã·ã¥çæä¸­ã«åé¨ã¨ã©ã¼ãçºçãã¾ããã',
  'Invalid MO file revision: {revision}.' => 'ç¡å¹ãª MO ãã¡ã¤ã«çæ°({revision})ã§ãã',
  'Invalid MO file: {file} (magic: {magic}).' => 'ç¡å¹ãª MO ãã¡ã¤ã«: {file} (magic: {magic})ã§ãã',
  'Invalid enumerable value "{value}". Please make sure it is among ({enum}).' => 'ç¡å¹ãªåæå¤("{value}")ã§ãã{enum} ã«å­å¨ãããç¢ºèªãã¦ãã ããã',
  'Invalid expression for CHttpCacheFilter.lastModifiedExpression: The evaluation result "{value}" could not be understood by strtotime()' => 'CHttpCacheFilter.lastModifiedExpression ã«ç¡å¹ãªå¼ãæå®ããã¦ãã¾ã : å¼ã®è©ä¾¡çµæã§ãã "{value}" ã strtotime() ã§è§£éã§ãã¾ããã§ããã',
  'Invalid operator "{operator}".' => 'ãªãã¬ã¼ã¿"{operator}"ãç¡å¹ã§ãã',
  'Last &gt;&gt;' => 'æå¾ &gt;&gt;',
  'List data must be an array or an object implementing Traversable.' => 'ãªã¹ããã¼ã¿ã¯éåãTraversableãå®è£ãããªãã¸ã§ã¯ãã§ãªããã°ããã¾ããã',
  'List index "{index}" is out of bound.' => 'ãªã¹ãã¤ã³ããã¯ã¹ "{index}" ã¯ç¯å²ãè¶ãã¦ãã¾ãã',
  'Login Required' => 'ã­ã°ã¤ã³ãå¿è¦ã§ãã',
  'Map data must be an array or an object implementing Traversable.' => 'ããããã¼ã¿ã¯éåãTraversableãå®è£ãããªãã¸ã§ã¯ãã§ãªããã°ããã¾ããã',
  'Missing the temporary folder to store the uploaded file "{file}".' => 'ã¢ããã­ã¼ããã¡ã¤ã« "{file}" ãä¿å­ããä¸æãã©ã«ããããã¾ããã',
  'Next &gt;' => 'æ¬¡ &gt;',
  'No' => 'ããã',
  'No columns are being updated for table "{table}".' => 'ãã¼ãã« "{table}" ã®ã«ã©ã ã¯ä½ãå¤æ´ããã¾ããã',
  'No counter columns are being updated for table "{table}".' => 'ãã¼ãã« "{table}" ã®ã«ã¦ã³ã¿ã¼ã«ã©ã ã¯ä½ãå¤æ´ããã¾ããã',
  'Object configuration must be an array containing a "class" element.' => 'ãªãã¸ã§ã¯ãã³ã³ãã£ã®ã¥ã¬ã¼ã·ã§ã³ã¯ "class" è¦ç´ ãå«ãéåã§ãªããã°ããã¾ããã',
  'Only SHA1 and MD5 hashing algorithms are supported when using PHP 5.1.1 or below.' => 'PHP 5.1.1 ä»¥ä¸ãä½¿ç¨ãã¦ããå ´åãããã·ã¥ã¢ã«ã´ãªãºã ã¨ãã¦ã¯ SHA1 ã¨ MD5 ã ãããµãã¼ãããã¦ãã¾ãã',
  'Please fix the following input errors:' => 'ä»¥ä¸ã®å¥åã¨ã©ã¼ãä¿®æ­£ãã¦ãã ãã:',
  'Powered by {yii}.' => '',
  'Property "{class}.{property}" is not defined.' => 'ãã­ããã£ "{class}.{property}" ãå®ç¾©ããã¦ãã¾ããã',
  'Property "{class}.{property}" is read only.' => 'ãã­ããã£ "{class}.{property}" ã¯èª­ã¿è¾¼ã¿å°ç¨ã§ãã',
  'Property CMaskedTextField.mask cannot be empty.' => 'CMaskedTextField.maskãã­ããã£ã¯ç©ºã§ã¯ããã¾ããã',
  'Queue data must be an array or an object implementing Traversable.' => 'ã­ã¥ã¼ãã¼ã¿ã¯éåãTraversableãå®è£ãããªãã¸ã§ã¯ãã§ãªããã°ããã¾ããã',
  'Relation "{name}" is not defined in active record class "{class}".' => 'ã¢ã¯ãã£ãã¬ã³ã¼ãã¯ã©ã¹ "{class}" ã«ãªã¬ã¼ã·ã§ã³ "{name}" ãå®ç¾©ããã¦ãã¾ããã',
  'Removing a primary key after table has been created is not supported by SQLite.' => 'SQLiteã§ã¯ãã¼ãã«ä½æå¾ã«ãã©ã¤ããªã­ã¼ãåé¤ãããã¨ã¯ã§ãã¾ããã',
  'Renaming a DB column is not supported by SQLite.' => 'SQLiteã§ã¯ãã¼ã¿ãã¼ã¹ã«ã©ã ããªãã¼ã ãããã¨ã¯ã§ãã¾ããã',
  'Script HTML options are not allowed for "CClientScript::POS_LOAD" and "CClientScript::POS_READY".' => 'ã¹ã¯ãªããã® HTML ãªãã·ã§ã³ã¯ã"CClientScript::POS_LOAD" ããã³ "CClientScript::POS_READY" ã«å¯¾ãã¦ã¯è¨±å¯ããã¦ãã¾ããã',
  'Stack data must be an array or an object implementing Traversable.' => 'ã¹ã¿ãã¯ãã¼ã¿ã¯éåãTraversableãå®è£ãããªãã¸ã§ã¯ãã§ãªããã°ããã¾ããã',
  'Table "{table}" does not exist.' => 'ãã¼ãã«"{table}"ã¯å­å¨ãã¾ããã',
  'Table "{table}" does not have a column named "{column}".' => 'ãã¼ãã« "{table}" ã«ã¯ "{column}" ã¨ããã«ã©ã ã¯å­å¨ãã¾ããã',
  'The "db" application component must be configured to be a CDbConnection object.' => '"db"ã¢ããªã±ã¼ã·ã§ã³ã³ã³ãã¼ãã³ãã¯CDbConnectionãªãã¸ã§ã¯ãã¨ãã¦æ§æãããå¿è¦ãããã¾ãã',
  'The "filter" property must be specified with a valid callback.' => '"filter"ãã­ããã£ã«ã¯æå¹ãªã³ã¼ã«ããã¯ãæå®ããå¿è¦ãããã¾ãã',
  'The "forceCopy" and "linkAssets" cannot be both true.' => '"foreceCopy" ã¨ "linkAssets" ãä¸¡æ¹ã¨ã true ã«ãããã¨ã¯åºæ¥ã¾ããã',
  'The "pattern" property must be specified with a valid regular expression.' => '"pattern" ãã­ããã£ã«ã¯æå¹ãªæ­£è¦è¡¨ç¾ãæå®ããå¿è¦ãããã¾ãã',
  'The "range" property must be specified with a list of values.' => '"range"ãã­ããã£ã¯å¤ã®ãªã¹ãã¨ãã¦æå®ãããå¿è¦ãããã¾ãã',
  'The $converter argument must be a valid callback or null.' => 'å¼æ° $converter ã¯æå¹ãªã³ã¼ã«ããã¯ã¾ãã¯ null ã§ãªããã°ãªãã¾ããã',
  'The CSRF token could not be verified.' => 'CSRFãã¼ã¯ã³ãæ¤è¨¼ã§ãã¾ããã§ããã',
  'The STAT relation "{name}" cannot have child relations.' => 'STATãªã¬ã¼ã·ã§ã³"{name}"ã¯å­ãªã¬ã¼ã·ã§ã³ãæã¤ãã¨ãã§ãã¾ããã',
  'The URL pattern "{pattern}" for route "{route}" is not a valid regular expression.' => 'ã«ã¼ã "{route}" ã«å¯¾ããURLãã¿ã¼ã³ "{pattern}" ã¯æå¹ãªæ­£è¦è¡¨ç¾ã§ã¯ããã¾ããã',
  'The active record cannot be deleted because it is new.' => 'æ°è¦ã®ããã¢ã¯ãã£ãã¬ã³ã¼ãã¯åé¤ã§ãã¾ããã',
  'The active record cannot be inserted to database because it is not new.' => 'æ°è¦ã§ãªãããã¢ã¯ãã£ãã¬ã³ã¼ãã¯ãã¼ã¿ãã¼ã¹ã«æ¿å¥ã§ãã¾ããã',
  'The active record cannot be updated because it is new.' => 'æ°è¦ã®ããã¢ã¯ãã£ãã¬ã³ã¼ãã¯æ´æ°ã§ãã¾ããã',
  'The asset "{asset}" to be published does not exist.' => 'ã¢ã»ãã"{asset}"ã¯å­å¨ãã¾ããã',
  'The command path "{path}" is not a valid directory.' => 'ã³ãã³ããã¹ "{path}" ã¯æå¹ãªãã£ã¬ã¯ããªã§ã¯ããã¾ããã',
  'The controller path "{path}" is not a valid directory.' => 'ã³ã³ãã­ã¼ã©ãã¹ "{path}" ã¯æå¹ãªãã£ã¬ã¯ããªã§ã¯ããã¾ããã',
  'The file "{file}" cannot be uploaded. Only files of these MIME-types are allowed: {mimeTypes}.' => 'ãã¡ã¤ã« "{file}" ã¯ã¢ããã­ã¼ãåºæ¥ã¾ãããä»¥ä¸ã® MIME ã¿ã¤ãã®ãã¡ã¤ã«ã ããè¨±å¯ããã¦ãã¾ã : {mimeTypes}',
  'The file "{file}" cannot be uploaded. Only files with these extensions are allowed: {extensions}.' => 'ãã¡ã¤ã« "{file}" ã¯ã¢ããã­ã¼ãåºæ¥ã¾ãããä»¥ä¸ã®æ¡å¼µå­ãæã¤ãã¡ã¤ã«ã ããè¨±å¯ããã¦ãã¾ã : {extensions}',
  'The file "{file}" is too large. Its size cannot exceed {limit} bytes.' => 'ãã¡ã¤ã« "{file}" ãå¤§ãããã¾ãããµã¤ãºã¯ {limit} ãã¤ããè¶ãããã¨ãã§ãã¾ããã',
  'The file "{file}" is too small. Its size cannot be smaller than {limit} bytes.' => 'ãã¡ã¤ã« "{file}" ãå°ãããã¾ãããµã¤ãºã¯ {limit} ãã¤ããä¸åããã¨ãã§ãã¾ããã',
  'The file "{file}" was only partially uploaded.' => 'ãã¡ã¤ã« "{file}" ã¯é¨åçã«ã¢ããã­ã¼ãããã¾ããã',
  'The first element in a filter configuration must be the filter class.' => 'ãã£ã«ã¿ã³ã³ãã£ã®ã¥ã¬ã¼ã·ã§ã³ã®æåã®è¦ç´ ã¯ãã£ã«ã¿ã¯ã©ã¹ã§ãªããã°ããã¾ããã',
  'The format of {attribute} is invalid.' => '{attribute}ã®ãã©ã¼ããããæ­£ããããã¾ããã',
  'The item "{name}" does not exist.' => 'è¦ç´  "{name}" ãå­å¨ãã¾ããã',
  'The item "{parent}" already has a child "{child}".' => 'è¦ç´  "{parent}" ã¯æ¢ã« "{child}" ãæã£ã¦ãã¾ãã',
  'The layout path "{path}" is not a valid directory.' => 'ã¬ã¤ã¢ã¦ããã¹ "{path}" ã¯æå¹ãªãã£ã¬ã¯ããªã§ã¯ããã¾ããã',
  'The list is read only.' => 'ãªã¹ãã¯èª­ã¿è¾¼ã¿å°ç¨ã§ãã',
  'The map is read only.' => 'ãããã¯èª­ã¿è¾¼ã¿å°ç¨ã§ãã',
  'The module path "{path}" is not a valid directory.' => 'ã¢ã¸ã¥ã¼ã«ãã¹{path}ã¯æå¹ãªãã£ã¬ã¯ããªã§ã¯ããã¾ããã',
  'The pattern for 12 hour format must be "h" or "hh".' => '12æéå¶ãã©ã¼ãããã®ãã¿ã¼ã³ã¯ "h" ã "hh" ã§ãã',
  'The pattern for 24 hour format must be "H" or "HH".' => '24æéå¶ãã©ã¼ãããã®ãã¿ã¼ã³ã¯ "H" ã "HH" ã§ãã',
  'The pattern for AM/PM marker must be "a".' => 'AM/PMã®ãã¿ã¼ã³ã¯ "a" ã§ãã',
  'The pattern for day in month must be "F".' => 'ã²ã¨æã®ä½åç®ã®ææ¥ãã®ãã¿ã¼ã³ã¯ "F" ã§ãã',
  'The pattern for day in year must be "D", "DD" or "DDD".' => 'ä¸å¹´ã®ä½æ¥ç®ãã®ãã¿ã¼ã³ã¯ "D" ã "DD" ã "DDD" ã§ãã',
  'The pattern for day of the month must be "d" or "dd".' => 'æ¥ã®ãã¿ã¼ã³ã¯ "d" ã "dd" ã§ãã',
  'The pattern for day of the week must be "E", "EE", "EEE", "EEEE", "EEEEE", "e", "ee", "eee", "eeee", "eeeee", "c", "cccc" or "ccccc".' => 'ææ¥ã®ãã¿ã¼ã³ã¯"E"ã"EE"ã"EEE"ã"EEEE"ã"EEEEE"ã"e"ã"ee"ã"eee"ã"eeee"ã"eeeee"ã"c"ã"cccc"ã"ccccc"ã®ããããã§ãã',
  'The pattern for era must be "G", "GG", "GGG", "GGGG" or "GGGGG".' => 'ç´åã®ãã¿ã¼ã³ã¯"G" ã "GG" ã "GGG" ã "GGGG" ã "GGGGG" ã§ãã',
  'The pattern for hour in AM/PM must be "K" or "KK".' => 'AM/PMã®æã®ãã¿ã¼ã³ã¯ "K" ã "KK" ã§ãã',
  'The pattern for hour in day must be "k" or "kk".' => 'ä¸æ¥ã®æã®ãã¿ã¼ã³ã¯ "k" ã "kk" ã§ãã',
  'The pattern for minutes must be "m" or "mm".' => 'åã®ãã¿ã¼ã³ã¯ "m" ã "mm" ã§ãã',
  'The pattern for month must be "M", "MM", "MMM", "MMMM", "L", "LL", "LLL" or "LLLL".' => 'æã®ãã¿ã¼ã³ã¯"M"ã"MM"ã"MMM""MMMM"ã"L"ã"LL"ã"LLL"ã"LLLL"ã®ããããã§ãã',
  'The pattern for seconds must be "s" or "ss".' => 'ç§ã®ãã¿ã¼ã³ã¯ "s" ã "ss" ã§ãã',
  'The pattern for time zone must be "z" or "v".' => 'ã¿ã¤ã ã¾ã¼ã³ã®ãã¿ã¼ã³ã¯ "z" ã "v" ã§ãã',
  'The pattern for week in month must be "W".' => 'ã²ã¨æã®é±ã®ãã¿ã¼ã³ã¯ "W" ã§ãã',
  'The pattern for week in year must be "w".' => 'ä¸å¹´ã®é±ã®ãã¿ã¼ã³ã¯ "w" ã§ãã',
  'The queue is empty.' => 'ã­ã¥ã¼ãç©ºã§ãã',
  'The relation "{relation}" in active record class "{class}" is not specified correctly: the join table "{joinTable}" given in the foreign key cannot be found in the database.' => 'ã¢ã¯ãã£ãã¬ã³ã¼ãã¯ã©ã¹ "{class}" ã®ãªã¬ã¼ã·ã§ã³ "{relation}" ã¯æ­£ããæå®ããã¦ãã¾ãããå¤é¨ã­ã¼ã§ä¸ããããã¸ã§ã¤ã³ãã¼ãã« "{joinTable}" ããã¼ã¿ãã¼ã¹ä¸­ã«è¦ã¤ããã¾ããã',
  'The relation "{relation}" in active record class "{class}" is specified with a foreign key "{key}" that does not point to the parent table "{table}".' => 'ã¢ã¯ãã£ãã¬ã³ã¼ãã¯ã©ã¹"{class}"ã®ãªã¬ã¼ã·ã§ã³"{relation}"ã«ã¯å¤é¨ã­ã¼"{key}"ãæå®ããã¦ãã¾ãããè¦ªãã¼ãã«"{table}"ãç¤ºãã¦ãã¾ããã',
  'The relation "{relation}" in active record class "{class}" is specified with an incomplete foreign key. The foreign key must consist of columns referencing both joining tables.' => 'ã¢ã¯ãã£ãã¬ã³ã¼ãã¯ã©ã¹ "{class}" ã®ãªã¬ã¼ã·ã§ã³ "{relation}" ã«ã¯ä¸å®å¨ãªå¤é¨ã­ã¼ãæå®ããã¦ãã¾ããå¤é¨ã­ã¼ã¯ä¸¡æ¹ã®ã¸ã§ã¤ã³ãã¼ãã«ãåç§ããã«ã©ã ã§æ§æããªããã°ããã¾ããã',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key "{key}". There is no such column in the table "{table}".' => 'ã¢ã¯ãã£ãã¬ã³ã¼ãã¯ã©ã¹"{class}"ã®ãªã¬ã¼ã·ã§ã³"{relation}"ã«ã¯ç¡å¹ãªå¤é¨ã­ã¼"{key}"ãæå®ããã¦ãã¾ãããã¼ãã«"{table}"ã«ã¯ãã®ãããªã«ã©ã ã¯å­å¨ãã¾ããã',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key. The columns in the key must match the primary keys of the table "{table}".' => 'ã¢ã¯ãã£ãã¬ã³ã¼ãã¯ã©ã¹"{class}"ã®ãªã¬ã¼ã·ã§ã³"{relation}"ã«ã¯ç¡å¹ãªå¤é¨ã­ã¼"{key}"ãæå®ããã¦ãã¾ããã­ã¼ä¸­ã®ã«ã©ã ã¯ãã¼ãã«"{table}"ã®ãã©ã¤ããªã­ã¼ã¨ä¸è´ããªããã°ããã¾ããã',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key. The format of the foreign key must be "joinTable(fk1,fk2,...)".' => 'ã¢ã¯ãã£ãã¬ã³ã¼ãã¯ã©ã¹ "{class}" ã®ãªã¬ã¼ã·ã§ã³ "{relation}" ã¯ç¡å¹ãªå¤é¨ã­ã¼ãæå®ããã¦ãã¾ããå¤é¨ã­ã¼ã®ãã©ã¼ãããã¯"joinTable(fk1,fk2,...)" ã§ãã',
  'The requested view "{name}" was not found.' => 'è¦æ±ããããã¥ã¼"{name}"ã¯è¦ã¤ããã¾ããã',
  'The stack is empty.' => 'ã¹ã¿ãã¯ãç©ºã§ãã',
  'The system is unable to find the requested action "{action}".' => 'ã·ã¹ãã ã¯è¦æ±ãããã¢ã¯ã·ã§ã³ "{action}" ãè¦ã¤ãããã¾ããã',
  'The system view path "{path}" is not a valid directory.' => 'ã·ã¹ãã ãã¥ã¼ãã¹ "{path}" ã¯æå¹ãªãã£ã¬ã¯ããªã§ã¯ããã¾ããã',
  'The table "{table}" for active record class "{class}" cannot be found in the database.' => 'ã¢ã¯ãã£ãã¬ã³ã¼ãã¯ã©ã¹ "{class}" ã®ãã¼ãã« "{table}" ããã¼ã¿ãã¼ã¹ã«ããã¾ããã',
  'The value for the column "{column}" is not supplied when querying the table "{table}".' => 'ãã¼ãã«"{table}"ã®ã¯ã¨ãªã«ã¤ãã¦ãã«ã©ã "{column}"ã®å¤ãè¨­å®ããã¦ãã¾ããã',
  'The verification code is incorrect.' => 'æ¤è¨¼ã³ã¼ããæ­£ããããã¾ããã',
  'The view path "{path}" is not a valid directory.' => 'ãã¥ã¼ãã¹ "{path}" ã¯æå¹ãªãã£ã¬ã¯ããªã§ã¯ããã¾ããã',
  'Theme directory "{directory}" does not exist.' => 'ãã¼ããã£ã¬ã¯ããª "{directory}" ãå­å¨ãã¾ããã',
  'This content requires the <a href="http://www.adobe.com/go/getflash/">Adobe Flash Player</a>.' => 'ãã®ã³ã³ãã³ãã¯ <a href="http://www.adobe.com/go/getflash/">Adobe Flash Player</a>ãå¿è¦ã¨ãã¾ãã',
  'Unable to add an item whose name is the same as an existing item.' => 'æ¢ã«å­å¨ããé ç®ã¨åãååã®é ç®ã¯è¿½å ã§ãã¾ããã',
  'Unable to change the item name. The name "{name}" is already used by another item.' => 'é ç®ã®ååãå¤æ´ã§ãã¾ããããã®åå "{name}" ã¯æ¢ã«å¥ã®é ç®ã§ä½¿ç¨ããã¦ãã¾ãã',
  'Unable to create application state file "{file}". Make sure the directory containing the file exists and is writable by the Web server process.' => 'ã¢ããªã±ã¼ã·ã§ã³ç¶æãã¡ã¤ã« "{file}" ãä½æã§ãã¾ããããã¡ã¤ã«ã®ãã£ã¬ã¯ããªãå­å¨ãã¦ã¦ã§ããµã¼ããã­ã»ã¹ãæ¸ãè¾¼ããããç¢ºèªãã¦ãã ããã',
  'Unable to find "{column}" in table "{table}".' => 'ãã¼ãã«"{table}"ä¸­ã«ã«ã©ã "{column}"ãè¦ã¤ããã¾ããã',
  'Unable to generate random string.' => 'ã©ã³ãã æå­åãçæã§ãã¾ããã',
  'Unable to lock file "{file}" for reading.' => 'ãã¡ã¤ã«  "{file}" ãèª­ã¿è¾¼ã¿ã­ãã¯ã§ãã¾ããã',
  'Unable to lock file "{file}" for writing.' => 'ãã¡ã¤ã«  "{file}" ãæ¸ãè¾¼ã¿ã­ãã¯ã§ãã¾ããã',
  'Unable to read file "{file}".' => 'ãã¡ã¤ã«  "{file}" ãèª­ã¿è¾¼ãã¾ããã',
  'Unable to replay the action "{object}.{method}". The method does not exist.' => 'ã¢ã¯ã·ã§ã³ "{object}.{method}" ããªãã¬ã¼ã§ãã¾ãããã¡ã½ãããå­å¨ãã¾ããã',
  'Unable to resolve the request "{route}".' => 'ãªã¯ã¨ã¹ã"{route}"ãè§£æ±ºã§ãã¾ããã',
  'Unable to upload the file "{file}" because of an unrecognized error.' => 'èªè­ã§ããªãã¨ã©ã¼ã«ããããã¡ã¤ã« "{file}" ãã¢ããã­ã¼ãåºæ¥ã¾ããã',
  'Unable to write file "{file}".' => 'ãã¡ã¤ã«  "{file}" ã«æ¸ãè¾¼ãã¾ããã',
  'Unknown authorization item "{name}".' => 'èªè¨¼é ç® "{name}" ã¯ä¸æã§ãã',
  'Unknown operator "{operator}".' => '"{operator}"ã¯ä¸æãªãªãã¬ã¼ã¿ã§ãã',
  'Unknown type "{type}".' => '"{type}"ã¯ä¸æãªåã§ãã',
  'Unrecognized locale "{locale}".' => 'ã­ã±ã¼ã« "{locale}" ãèªè­ã§ãã¾ããã',
  'View file "{file}" does not exist.' => 'ãã¥ã¼ãã¡ã¤ã« "{file}" ãå­å¨ãã¾ããã',
  'Yes' => 'ã¯ã',
  'Yii application can only be created once.' => 'Yiiã¢ããªã±ã¼ã·ã§ã³ã¯ä¸åº¦ããä½æã§ãã¾ããã',
  'You are not authorized to perform this action.' => 'ããªãã¯ãã®ã¢ã¯ã·ã§ã³ãå®è¡ããæ¨©éãããã¾ããã',
  'Your request is invalid.' => 'ç¡å¹ãªãªã¯ã¨ã¹ãã§ãã',
  '{attribute} "{value}" has already been taken.' => '{attribute} ã® "{value}" ã¯æ¢ã«ä½¿ããã¦ãã¾ãã',
  '{attribute} "{value}" is invalid.' => '{attribute}ã®å¤"{value}" ã¯æ­£ããããã¾ããã',
  '{attribute} cannot accept more than {limit} files.' => '{attribute}ã¯{limit}ãã¡ã¤ã«ã¾ã§ããåãåãã¾ããã',
  '{attribute} cannot be blank.' => '{attribute} ã¯ç©ºç½ã§ã¯ããã¾ããã',
  '{attribute} is in the list.' => '{attribute}ã¯ãªã¹ãã«ããã¾ãã',
  '{attribute} is invalid.' => '{attribute} ã¯ç¡å¹ã§ãã',
  '{attribute} is not a valid URL.' => '{attribute} ã¯æå¹ãª URL ã§ã¯ããã¾ããã',
  '{attribute} is not a valid email address.' => '{attribute} ã¯æå¹ãªã¡ã¼ã«ã¢ãã¬ã¹ã§ã¯ããã¾ããã',
  '{attribute} is not in the list.' => '{attribute} ã¯ãªã¹ãã«å­å¨ãã¾ããã',
  '{attribute} is of the wrong length (should be {length} characters).' => '{attribute} ã®é·ããééã£ã¦ãã¾ã({length}æå­ã§ããã¹ãã§ã)ã',
  '{attribute} is too big (maximum is {max}).' => '{attribute} ãå¤§ãããã¾ã(æå¤§{max})ã',
  '{attribute} is too long (maximum is {max} characters).' => '{attribute} ãé·ããã¾ã(æå¤§{max}æå­)ã',
  '{attribute} is too short (minimum is {min} characters).' => '{attribute} ãç­ããã¾ã(æå°{min}æå­)ã',
  '{attribute} is too small (minimum is {min}).' => '{attribute} ãå°ãããã¾ã(æå°{min})ã',
  '{attribute} must be a number.' => '{attribute} ã¯æ°å­ã«ãã¦ãã ããã',
  '{attribute} must be an integer.' => '{attribute} ã¯æ´æ°ã«ãã¦ãã ããã',
  '{attribute} must be either {true} or {false}.' => '{attribute}ã¯{true}ã{false}ã®ããããã®å¿è¦ãããã¾ãã',
  '{attribute} must be greater than "{compareValue}".' => '{attribute}ã¯"{compareValue}"ããå¤§ããå¿è¦ãããã¾ãã',
  '{attribute} must be greater than or equal to "{compareValue}".' => '{attribute}ã¯"{compareValue}"ä»¥ä¸ã§ããå¿è¦ãããã¾ãã',
  '{attribute} must be less than "{compareValue}".' => '{attribute}ã¯"{compareValue}"ããå°ããå¿è¦ãããã¾ãã',
  '{attribute} must be less than or equal to "{compareValue}".' => '{attribute}ã¯"{compareValue}"ä»¥ä¸ã§ããå¿è¦ãããã¾ãã',
  '{attribute} must be repeated exactly.' => '{attribute} ã¯æ­£ç¢ºã«ç¹°ãè¿ãã¦ãã ããã',
  '{attribute} must be {type}.' => '{attribute} ã¯ {type} ã«ãã¦ãã ããã',
  '{attribute} must be {value}.' => '{attribute}ã¯{value}ã§ããå¿è¦ãããã¾ãã',
  '{attribute} must not be equal to "{compareValue}".' => '{attribute}ã¯"{compareValue}"ã§ã¯ããã¾ããã',
  '{className} does not support add() functionality.' => '{className} ã¯ add() æ©è½ããµãã¼ããã¾ããã',
  '{className} does not support delete() functionality.' => '{className} ã¯ delete() æ©è½ããµãã¼ããã¾ããã',
  '{className} does not support flushValues() functionality.' => '{className}ã¯flushValues()æ©è½ããµãã¼ããã¾ããã',
  '{className} does not support get() functionality.' => '{className} ã¯ get() æ©è½ããµãã¼ããã¾ããã',
  '{className} does not support set() functionality.' => '{className} ã¯ set() æ©è½ããµãã¼ããã¾ããã',
  '{class} and its behaviors do not have a method or closure named "{name}".' => '{class} ããã®ããã¤ãã¢ã«ã¯ "{name}" ã¨ããååã®ã¡ã½ãããã¯ã­ã¼ã¸ã£ã¯ããã¾ããã',
  '{class} does not have relation "{name}".' => '{class} ã¯ "{name}" ã¨ãããªã¬ã¼ã·ã§ã³ãæã¡ã¾ããã',
  '{class} does not support fetching all table names.' => '{class} ã¯ãã¼ãã«åãå¨ã¦åãåºãæ©è½ã¯ãµãã¼ããã¾ããã',
  '{class} has an invalid validation rule. The rule must specify attributes to be validated and the validator name.' => '{class} ã®ããªãã¼ã·ã§ã³ã«ã¼ã«ã¯ééã£ã¦ãã¾ããã«ã¼ã«ã«ã¯æ¤è¨¼ãããå±æ§ã¨ããªãã¼ã¿åãæå®ãã¦ãã ããã',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} ã«ã¯ "model" ã¨ "attribute" ãã¾ãã¯ "name" ãã­ããã£ã«å¤ãè¨­å®ãã¦ãã ããã',
  '{class} requires the Blowfish option of the PHP crypt() function. This system does not have it.' => '{class} ã¯ PHP crypt() é¢æ°ã® Blowfish ãªãã·ã§ã³ãå¿è¦ã¨ãã¾ãããã®ã·ã¹ãã ã«ã¯ PHP crypt() é¢æ°ã® Blowfish ãªãã·ã§ã³ãã¤ã³ã¹ãã¼ã«ããã¦ãã¾ããã',
  '{class} requires the PHP crypt() function. This system does not have it.' => '{class} ã¯ PHP crypt() é¢æ°ãå¿è¦ã¨ãã¾ãããã®ã·ã¹ãã ã«ã¯ PHP crypt() é¢æ°ãã¤ã³ã¹ãã¼ã«ããã¦ãã¾ããã',
  '{class}.allowAutoLogin must be set true in order to use cookie-based authentication.' => 'ã¯ãã­ã¼ãã¼ã¹ã®èªè¨¼ãä½¿ç¨ããã«ã¯ {class}.allowAutoLogin ãè¨­å®ãã¦ãã ããã',
  '{class}::$cost must be a number.' => '{class}::$cost ã¯æ°å¤ã§ãªããã°ãªãã¾ããã',
  '{class}::$cost must be between 4 and 31.' => '{class}::$cost ã¯ 4 ä»¥ä¸ 30 ä»¥ä¸ã§ãªããã°ãªãã¾ããã',
  '{class}::authenticate() must be implemented.' => '{class}::authenticate() ãå®è£ãã¦ãã ããã',
  '{controller} cannot find the requested view "{view}".' => '{controller} ã¯ãªã¯ã¨ã¹ãããããã¥ã¼ "{view}" ãè¦ã¤ãããã¾ããã',
  '{controller} contains improperly nested widget tags in its view "{view}". A {widget} widget does not have an endWidget() call.' => '{controller} ã«ã¯ãã¥ã¼"{view}"ã®ä¸­ã«ä¸é©åã«ãã¹ããããã¦ã£ã¸ã§ããã¿ã°ãããã¾ãã{widget} ã¦ã£ã¸ã§ããã«ã¯ endWidget() å¼ã³åºããããã¾ããã',
  '{controller} has an extra endWidget({id}) call in its view.' => '{controller} ã®ãã¥ã¼ã«ã¯ä½åãª endWidget({id}) å¼ã³åºããããã¾ãã',
  '{n} B' => '{n} B',
  '{n} GB' => '{n} GB',
  '{n} KB' => '{n} KB',
  '{n} MB' => '{n} MB',
  '{n} TB' => '{n} TB',
  '{n} byte|{n} bytes' => '{n} ãã¤ã',
  '{n} gigabyte|{n} gigabytes' => '{n} ã®ã¬ãã¤ã',
  '{n} kilobyte|{n} kilobytes' => '{n} ã­ã­ãã¤ã',
  '{n} megabyte|{n} megabytes' => '{n} ã¡ã¬ãã¤ã',
  '{n} terabyte|{n} terabytes' => '{n} ãã©ãã¤ã',
  '{widget} cannot find the view "{view}".' => '{widget} ã¯ãã¥ã¼ "{view}" ãè¦ã¤ãããã¾ããã',
);
