<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Are you sure you want to delete this item?' => 'ãã®é ç®ãåé¤ãã¦ãããããã§ãã?',
  'Delete' => 'åé¤',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => '{count}åã®çµæã{start}ãã{end}ã¾ã§è¡¨ç¤ºãã¾ãã',
  'Either "name" or "value" must be specified for CDataColumn.' => 'CDataColumnã®"name"ã¾ãã¯"value"ãæå®ããªããã°ãªãã¾ããã',
  'Home' => 'ãã¼ã ',
  'No results found.' => 'çµæãå¾ããã¾ããã§ããã',
  'Not set' => 'ã»ããããã¦ãã¾ãã',
  'Please specify the "attributes" property.' => '"attributes"ãã­ããã£ãæå®ãã¦ãã ããã',
  'Please specify the "data" property.' => '"data"ãã­ããã£ãæå®ãã¦ãã ããã',
  'Sort by: ' => 'ã½ã¼ã:',
  'The "dataProvider" property cannot be empty.' => '"dataProvider"ãã­ããã£ã¯ç©ºã§ã¯ããã¾ããã',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'ã¢ããªãã¥ã¼ãã¯"Name:Type:Label"ã¨ããå½¢å¼ã§æå®ããªããã°ããã¾ããã"Type"ã¨"Label"ã¯çç¥å¯è½ã§ãã',
  'The button type "{type}" is not supported.' => 'ãã¿ã³ã¿ã¤ã"{type}"ã¯ãµãã¼ãããã¦ãã¾ããã',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'ã«ã©ã ã¯"Name:Type:Label"ã¨ããå½¢å¼ã§æå®ããªããã°ããã¾ããã"Type"ã¨"Label"ã¯çç¥å¯è½ã§ãã',
  'The property "itemView" cannot be empty.' => '"itemView"ãã­ããã£ã¯ç©ºã§ã¯ããã¾ããã',
  'The property filterSelector should be defined.' => 'filterSelector ãã­ããã£ãæå®ããªããã°ããã¾ããã',
  'The property updateSelector should be defined.' => 'updateSelector ãã­ããã£ãæå®ããªããã°ããã¾ããã',
  'Total 1 result.|Total {count} results.' => 'åè¨{count}å',
  'Update' => 'æ´æ°',
  'View' => 'è¡¨ç¤º',
  '{class} must specify "model" and "{attribute}" or "{name}" property values.' => '{class}ã¯"model"ã¨"{attribute}"ã¾ãã¯"{name}"ã®ãã­ããã£å¤ãæå®ããªããã°ããã¾ããã',
);
