<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '"{path}" is not a valid directory.' => '"{path}"ë ì¬ë°ë¥¸ ëë í ë¦¬ê° ìëëë¤.',
  '&lt; Previous' => '&lt; ì´ì ',
  '&lt;&lt; First' => '&lt;&lt; ì²ì',
  'Action class {class} must implement the "run" method.' => 'ì¡ì í´ëì¤ {class}ë "run" ë©ìëë¥¼ ë°ëì êµ¬íí´ì¼í©ëë¤.',
  'Active Record requires a "db" CDbConnection application component.' => 'Active Recordë "db" CDbConnection ìì©íë¡ê·¸ë¨ êµ¬ì±ììê° íìí©ëë¤.',
  'Active record "{class}" has an invalid configuration for relation "{relation}". It must specify the relation type, the related active record class and the foreign key.' => 'ì¡í°ë¸ ë ì½ë "{class}"ì ê´ê³ {relation}ì êµ¬ì±ì ì¤ë¥ê° ììµëë¤. ê´ê³ ì í, ê´ë ¨ë ì¡í°ë¸ ë ì½ë í´ëì¤ì ì¸ë í¤ë¥¼ ì§ì íì­ìì¤.',
  'Active record "{class}" is trying to select an invalid column "{column}". Note, the column must exist in the table or be an expression with alias.' => 'ì¡í°ë¸ ë ì½ë "{class}"ë ìëª»ë ì»¬ë¼ "{column}"ì ì ííë ¤ê³ íìµëë¤. íì´ë¸ììë ì»¬ë¼ ëë ë³ì¹­ì ì§ì íëìì´ ìëë©´ ìë©ëë¤.',
  'Adding a foreign key constraint to an existing table is not supported by SQLite.' => 'SQLiteë ê¸°ì¡´ íì´ë¸ì ì¸ë í¤ ì ì½ ì¡°ê±´ì ë¶ì¬íì§ ììµëë¤.',
  'Alias "{alias}" is invalid. Make sure it points to an existing PHP file and the file is readable.' => '"{alias}"ë ì¬ë°ë¥´ì§ììµëë¤. php íì¼ì´ ì½ê¸° ê°ë¥íì§ íì¸íì­ìì¤.',
  'Alias "{alias}" is invalid. Make sure it points to an existing directory or file.' => 'ê²½ë¡ ë³ì¹­ "{alias}"ê° ì¬ë°ë¥´ì§ììµëë¤. ì¤ì  ìë ëë í ë¦¬ì íì¼ì ê°ë¦¬ í¤ëì§ íì¸íì­ìì¤.',
  'Alias "{alias}" is invalid. Make sure it points to an existing directory.' => '"{alias}"ë ì¬ë°ë¥´ì§ììµëë¤. ëë í ë¦¬ê° ì¤ì  ìëì§ íì¸íì­ìì¤.',
  'Altering a DB column is not supported by SQLite.' => 'SQLiteë ë°ì´í°ë² ì´ì¤ì ì»¬ë¼ì ë³ê²½í  ì ììµëë¤.',
  'Application Log' => 'ìì© íë¡ê·¸ë¨ ë¡ê·¸',
  'Application base path "{path}" is not a valid directory.' => 'ìì© íë¡ê·¸ë¨ ê¸°ë³¸ ê²½ë¡ "{path}"ë ì¬ë°ë¥¸ ëë í ë¦¬ê° ìëëë¤.',
  'Application runtime path "{path}" is not valid. Please make sure it is a directory writable by the Web server process.' => 'ìì© íë¡ê·¸ë¨ ë°íì ê²½ë¡ "{path}"ë ì¬ë°ë¥´ì§ ììµëë¤. ì¹ ìë² íë¡ì¸ì¤ê° ì¸ ì ìëì§ íì¸íì­ìì¤.',
  'Authorization item "{item}" has already been assigned to user "{user}".' => 'ì¸ì¦ í­ëª© "{item}"ë ì´ë¯¸ ì¬ì©ì "{user}"ì í ë¹ëì´ììµëë¤.',
  'Base path "{path}" is not a valid directory.' => 'ê¸°ë³¸ ê²½ë¡ "{path}" ì¬ë°ë¥¸ ëë í ë¦¬ê° ìëëë¤.',
  'CApcCache requires PHP apc extension to be loaded.' => 'CApcCacheì PHP APC íì¥ì´ íìí©ëë¤.',
  'CAssetManager.basePath "{path}" is invalid. Please make sure the directory exists and is writable by the Web server process.' => 'CAssetManager.basePath "{path}"ë ì¬ë°ë¥´ì§ììµëë¤. ëë í ë¦¬ê° ì¤ì  ìê³  ì¹ ìë² íë¡ì¸ì¤ê° ì¸ ì ìëì§ë¥¼ íì¸íì­ìì¤.',
  'CCacheHttpSession.cacheID is invalid. Please make sure "{id}" refers to a valid cache application component.' => 'CCacheHttpSession.cacheIDì´ ì¬ë°ë¥´ì§ììµëë¤. "{id}"ê° ì¬ë°ë¥¸ ìºì ìì© íë¡ê·¸ë¨ êµ¬ì± ììë¥¼ ì°¸ì¡°íê³  ââìëì§ íì¸íì­ìì¤.',
  'CCaptchaValidator.action "{id}" is invalid. Unable to find such an action in the current controller.' => 'CCaptchaValidator.action "{id}"ì´ ì¬ë°ë¥´ì§ììµëë¤. íì¬ ì»¨í¸ë¡¤ë¬ì ê·¸ë° ì¡ìì´ ììµëë¤.',
  'CDbAuthManager.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbAuthManager.connectionID "{id}"ì´ ì¬ë°ë¥´ì§ììµëë¤. CDbConnection ìì© íë¡ê·¸ë¨ êµ¬ì± ììì IDë¥¼ ì°¸ì¡°íê³  âìëì§ íì¸íì­ìì¤.',
  'CDbCache.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbCache.connectionID "{id}"ì´ ì¬ë°ë¥´ì§ììµëë¤. CDbConnection ìì© íë¡ê·¸ë¨ êµ¬ì± ììì IDë¥¼ ì°¸ì¡°íê³  ìë ì§ íì¸íì­ìì¤.',
  'CDbCacheDependency.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbCacheDependency.connectionID "{id}"ë ì¬ë°ë¥´ì§ììµëë¤. CDbConnection ìì© íë¡ê·¸ë¨ êµ¬ì± ììì IDë¥¼ ê°ë¦¬í¤ë ì§ íì¸íì­ìì¤.',
  'CDbCacheDependency.sql cannot be empty.' => 'CDbCacheDependency.sqlë ê³µë°±ì ì¬ì©í  ì ììµëë¤.',
  'CDbCommand failed to execute the SQL statement: {error}' => 'CDbCommandì SQL ë¬¸ì ì¤íí  ì ììµëë¤: {error}',
  'CDbCommand failed to prepare the SQL statement: {error}' => 'CDbCommandë SQL ë¬¸ì ì¤ë¹íì§ ììµëë¤: {error}',
  'CDbCommand::execute() failed: {error}. The SQL statement executed was: {sql}.' => 'CDbCommand::execute()ì´ ì¤í¨íìµëë¤: {error}. ì¤íë SQL ë¬¸ì¥: {sql}',
  'CDbCommand::{method}() failed: {error}. The SQL statement executed was: {sql}.' => 'CDbCommand::{method}()ì´ ì¤í¨íìµëë¤: {error}. ì¤íë SQL ë¬¸ì¥: {sql}',
  'CDbConnection does not support reading schema for {driver} database.' => 'CDbConnectionì {driver} ë°ì´í°ë² ì´ì¤ì ëíì¬ ì¤í¤ë§ ì½ê¸°ë¥¼ ì§ìíì§ ììµëë¤.',
  'CDbConnection failed to open the DB connection.' => 'CDbConnection ë°ì´í°ë² ì´ì¤ì ì°ê²°í  ì ììµëë¤.',
  'CDbConnection failed to open the DB connection: {error}' => 'CDbConnection ë°ì´í°ë² ì´ì¤ì ì°ê²°í  ì ììµëë¤. {error}',
  'CDbConnection.connectionString cannot be empty.' => 'CDbConnection.connectionStringë ê³µë°±ì ì¬ì©í  ì ììµëë¤.',
  'CDbDataReader cannot rewind. It is a forward-only reader.' => 'CDbDataReaderë ëê°ì ì ììµëë¤. ì´ê²ì ìë°©í¥ ì ì© ë¦¬ëìëë¤.',
  'CDbHttpSession.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbHttpSession.connectionID "{id}"ì´ ì¬ë°ë¥´ì§ììµëë¤. CDbConnection ìì© íë¡ê·¸ë¨ êµ¬ì± ììì IDë¥¼ ì°¸ì¡°íê³  âìëì§ íì¸íì­ìì¤.',
  'CDbLogRoute.connectionID "{id}" does not point to a valid CDbConnection application component.' => 'CDbLogRoute.connectionID "{id}"ë ì¬ë°ë¥¸ CDbConnection ìì© íë¡ê·¸ë¨ êµ¬ì± ììë¥¼ ì°¸ì¡°íì§ ììµëë¤.',
  'CDbMessageSource.connectionID is invalid. Please make sure "{id}" refers to a valid database application component.' => 'CDbMessageSource.connectionIDì´ ì¬ë°ë¥´ì§ììµëë¤. "{id}"ê° ì¬ë°ë¥¸ ë°ì´í°ë² ì´ì¤ ìì© íë¡ê·¸ë¨ êµ¬ì± ììë¥¼ ì°¸ì¡°íê³  âìëì§ íì¸íì­ìì¤.',
  'CDbTestFixture.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbTestFixture.connectionID "{id}"ë ì¬ë°ë¥´ì§ ììµëë¤. CDbConnection ìì© íë¡ê·¸ë¨ êµ¬ì± ììì IDë¥¼ ê°ë¦¬í¤ëì§ íì¸íì­ìì¤.',
  'CDbTransaction is inactive and cannot perform commit or roll back operations.' => 'CDbTransaction ë¹íì±ì´ê³  ì»¤ë° ëë ë¡¤ë°± ììì ìíí  ì ììµëë¤.',
  'CDirectoryCacheDependency.directory cannot be empty.' => 'CDirectoryCacheDependency.directoryì ê³µë°±ì ì¬ì©í  ì ììµëë¤.',
  'CEAcceleratorCache requires PHP eAccelerator extension to be loaded, enabled or compiled with the "--with-eaccelerator-shared-memory" option.' => 'CEAcceleratorCacheì PHP eAccelerator íì¥ì´ íìí©ëë¤. "--with-eaccelerator-shared-memory" ìµìì ë¶ì¬ ì»´íì¼íì­ìì¤.',
  'CFileCacheDependency.fileName cannot be empty.' => 'CFileCacheDependency.fileNameì ê³µë°±ì ì¬ì©í  ì ììµëë¤.',
  'CFileLogRoute.logPath "{path}" does not point to a valid directory. Make sure the directory exists and is writable by the Web server process.' => 'CFileLogRoute.logPath "{path}"ë¥¼ ì¬ì©íë ëë í ë¦¬ê° ììµëë¤. ëë í ë¦¬ê° ì¤ì  ìëì§ ì¹ ìë² íë¡ì¸ì¤ê° ì¸ ììëì§ë¥¼ íì¸íì­ìì¤.',
  'CFilterChain can only take objects implementing the IFilter interface.' => 'CFilterChainë IFilter ì¸í°íì´ì¤ë¥¼ êµ¬ííë ê°ì²´ë§ ê°ì§ ì ììµëë¤.',
  'CFlexWidget.baseUrl cannot be empty.' => 'CFlexWidget.baseUrlë ê³µë°±ì ì¬ì©í  ì ììµëë¤.',
  'CFlexWidget.name cannot be empty.' => 'CFlexWidget.nameë ê³µë°±ì ì¬ì©í  ì ììµëë¤.',
  'CGlobalStateCacheDependency.stateName cannot be empty.' => 'CGlobalStateCacheDependency.stateNameë ê³µë°±ì ì¬ì©í  ì ììµëë¤.',
  'CHttpCookieCollection can only hold CHttpCookie objects.' => 'CHttpCookieCollectionì CHttpCookie ê°ì²´ë¥¼ ê°ì§ëë¤.',
  'CHttpRequest is unable to determine the entry script URL.' => 'CHttpRequestë í­ëª© ì¤í¬ë¦½í¸ì URLì íì¸í  ì ììµëë¤.',
  'CHttpRequest is unable to determine the path info of the request.' => 'CHttpRequest ìì²­ì ê²½ë¡ ì ë³´ë¥¼ íì¸í  ì ììµëë¤.',
  'CHttpRequest is unable to determine the request URI.' => 'CHttpRequest ìì²­ URIë¥¼ íì¸í  ì ììµëë¤.',
  'CHttpSession.cookieMode can only be "none", "allow" or "only".' => 'CHttpSession.cookieModeë "none", "allow" ëë "only" ê°ë§ ê°ì§ ì ììµëë¤.',
  'CHttpSession.gcProbability "{value}" is invalid. It must be an integer between 0 and 100.' => 'CHttpSession.gcProbability "{value}"ë ìëª»ëììµëë¤. 0ìì 100 ì¬ì´ì ì ìì´ì´ì¼ í©ëë¤.',
  'CHttpSession.savePath "{path}" is not a valid directory.' => 'CHttpSession.savePath "{path}"ë ì¬ë°ë¥¸ ëë í ë¦¬ê° ìëëë¤.',
  'CMemCache server configuration must be an array.' => 'CMemCache ìë² êµ¬ì±ì ë°°ì´ì´ì´ì¼ í©ëë¤.',
  'CMemCache server configuration must have "host" value.' => 'CMemCache ìë² êµ¬ì±ì host ê°ì´ ìì´ì¼ í©ëë¤.',
  'CProfileLogRoute found a mismatching code block "{token}". Make sure the calls to Yii::beginProfile() and Yii::endProfile() be properly nested.' => 'CProfileLogRouteê° ì¼ì¹íì§ ìë ì½ë ë¸ë¡ "{token}"ë¥¼ ì°¾ììµëë¤. Yii::beginProfile()ì Yii::endProfile() í¸ì¶ì´ ì¬ë°ë¥´ê² ì¤ì²©ëì´ ìëì§ íì¸íì­ìì¤.',
  'CProfileLogRoute.report "{report}" is invalid. Valid values include "summary" and "callstack".' => 'CProfileLogRoute.report "{report}"ì´ ìëª»ëììµëë¤. ì¬ë°ë¥¸ ê°ì "summary"ì "callstack"ë¥¼ í¬í¨í©ëë¤.',
  'CSecurityManager requires PHP mcrypt extension to be loaded in order to use data encryption feature.' => 'CSecurityManager ë°ì´í° ìí¸í ê¸°ë¥ì ì¬ì©íê¸° ìí´ìë PHPì mcrypt íì¥ì íìë¡í©ëë¤.',
  'CSecurityManager.encryptionKey cannot be empty.' => 'CSecurityManager.encryptionKeyë ê³µë°±ì ì¬ì©í  ì ììµëë¤.',
  'CSecurityManager.validationKey cannot be empty.' => 'CSecurityManager.validationKeyë ê³µë°±ì ì¬ì©í  ì ììµëë¤.',
  'CTypedList<{type}> can only hold objects of {type} class.' => 'CTypedList<{type}>ë {type} í´ëì¤ì ê°ì²´ë§ ê°ì§ ì ììµëë¤.',
  'CTypedMap<{type}> can only hold objects of {type} class.' => 'CTypedMap<{type}>ë {type} í´ëì¤ì ê°ì²´ë§ ê°ì§ ì ììµëë¤.',
  'CUrlManager.UrlFormat must be either "path" or "get".' => 'CUrlManager.UrlFormatì "path"ëë "get"ì¤ íëìëë¤.',
  'CWinCache requires PHP wincache extension to be loaded.' => 'CWinCacheë PHPì wincache íì¥ì´ íìí©ëë¤.',
  'CWinCache user cache is disabled. Please set wincache.ucenabled to On in your php.ini.' => 'CWinCache ì¬ì©ì ìºìë¥¼ ì¬ì©í  ì ììµëë¤. php.iniì wincache.ucenabledì Onì¼ë¡ ì¤ì íì­ìì¤.',
  'CXCache requires PHP XCache extension to be loaded.' => 'CXCacheì PHP XCache íì¥ì íìë¡í©ëë¤.',
  'CZendDataCache requires PHP Zend Data Cache extension to be loaded.' => 'CZendDataCacheë PHP Zend Data Cache íì¥ì´ íìí©ëë¤.',
  'Cannot add "{child}" as a child of "{name}". A loop has been detected.' => '"{name}"ì ììì¼ë¡ "{child}"ë¥¼ ì¶ê°í  ì ììµëë¤. ë£¨íê° ë°ê²¬ëììµëë¤.',
  'Cannot add "{child}" as a child of "{parent}". A loop has been detected.' => '"{parent}"ì ììì¼ë¡ "{child}"ë¥¼ ì¶ê°í  ì ììµëë¤. ë£¨íê° ë°ê²¬ëììµëë¤.',
  'Cannot add "{name}" as a child of itself.' => '"{name}" ìì ì ììì¼ë¡ ì¶ê°í  ì ììµëë¤.',
  'Cannot add an item of type "{child}" to an item of type "{parent}".' => '"{parent}" íì í­ëª©ìë "{child}" íìì í­ëª©ì ì¶ê°í  ì ììµëë¤.',
  'Column name must be either a string or an array.' => 'ì´ ì´ë¦ì ë¬¸ìì´ì´ë ë°°ì´ì´ì´ì´ì¼ í©ëë¤.',
  'Dropping DB column is not supported by SQLite.' => 'SQLiteë ë°ì´í°ë² ì´ì¤ ì»¬ë¼ì ì ê±°í  ì ììµëë¤.',
  'Dropping a foreign key constraint is not supported by SQLite.' => 'SQLiteë ì¸ë í¤ ì ì½ ì¡°ê±´ì ì­ì í  ì ììµëë¤.',
  'Either "{parent}" or "{child}" does not exist.' => '"{parent}" ëë "{child}"ê° ììµëë¤.',
  'Error: Table "{table}" does not have a primary key.' => 'ì¤ë¥ : íì´ë¸ "{table}"ì ê¸°ë³¸ í¤ê° ììµëë¤.',
  'Error: Table "{table}" has a composite primary key which is not supported by crud command.' => 'ì¤ë¥ : íì´ë¸ "{table}"ì ë³µí© ê¸°ë³¸ í¤ê° ì¡´ì¬íì§ë§, ì´ê²ì CRUD ëªë ¹ìì ì§ìíì§ ììµëë¤.',
  'Event "{class}.{event}" is attached with an invalid handler "{handler}".' => 'ì´ë²¤í¸ "{class}.{event}"ë ìëª»ë ì²ë¦¬ê¸° "{handler}"ë¡ ì°ê²°ëììµëë¤.',
  'Event "{class}.{event}" is not defined.' => 'ì´ë²¤í¸ "{class}.{event}"ë¥¼ ì ìíì§ ìììµëë¤.',
  'Extension path "{path}" does not exist.' => 'íì¥ ê²½ë¡ "{path}"ë ìë ê²½ë¡ìëë¤.',
  'Failed to initialize the mcrypt module.' => 'mcrypt ëª¨ëì ì´ê¸°ííì§ ëª»íìµëë¤.',
  'Failed to set unsafe attribute "{attribute}" of "{class}".' => '"{class}"ì ìì íì§ ìì ìì± "{attribute}"ë¥¼ ì¤ì í  ì ììµëë¤.',
  'Failed to start session.' => 'ì¸ìì ììí  ì ììµëë¤.',
  'Failed to write the uploaded file "{file}" to disk.' => 'ìë¡ëë íì¼ "{file}"ë¥¼ ëì¤í¬ì ì¸ ì ììµëë¤.',
  'File upload was stopped by extension.' => 'íì¼ ìë¡ëê° íì¥(?)ì ìí´ì ì¤ì§ëììµëë¤.',
  'Filter "{filter}" is invalid. Controller "{class}" does not have the filter method "filter{filter}".' => 'íí° "{filter}"ê° ìëª»ëììµëë¤. ì»¨í¸ë¡¤ë¬ "{class}"ë íí° ë©ìë "filter {filter}"ë¥¼ ê°ì§ê³  ìì§ììµëë¤.',
  'GD and FreeType PHP extensions are required.' => 'GDì FreeType PHP íì¥ì´ íìí©ëë¤.',
  'Get a new code' => 'ì ì½ë ê°ì ¸ì¤ê¸°',
  'Go to page: ' => 'íì´ì§:',
  'Invalid MO file revision: {revision}.' => 'ìëª»ë MO íì¼ ë²ì  ë²í¸ìëë¤: ({revision}).',
  'Invalid MO file: {file} (magic: {magic}).' => 'ìëª»ë MO íì¼ìëë¤: {file} (magic {magic}).',
  'Invalid enumerable value "{value}". Please make sure it is among ({enum}).' => 'ìëª»ë ì´ê±° ê° "{value}")ìëë¤. ({enum})ì ìëì§ íì¸íì­ìì¤.',
  'Invalid operator "{operator}".' => 'ì°ì°ì "{operator}"ì´ ìëª»ëììµëë¤.',
  'Last &gt;&gt;' => 'ë§ì§ë§ &gt;&gt;',
  'List data must be an array or an object implementing Traversable.' => 'ëª©ë¡ ë°ì´í°ë ë°°ì´ ëë Traversableë¥¼ êµ¬ííë ì¤ë¸ì í¸ì´ì´ì¼ í©ëë¤.',
  'List index "{index}" is out of bound.' => 'ëª©ë¡ ìì¸ "{index}"ë ë²ìë¥¼ ì´ê³¼í©ëë¤.',
  'Login Required' => 'ë¡ê·¸ì¸ì´ íìí©ëë¤.',
  'Map data must be an array or an object implementing Traversable.' => 'ë§µ ë°ì´í°ë ë°°ì´ ëë Traversableë¥¼ êµ¬ííë ì¤ë¸ì í¸ì´ì´ì¼ í©ëë¤.',
  'Missing the temporary folder to store the uploaded file "{file}".' => 'ìë¡ë íì¼ "{file}"ì ì ì¥í  ìì í´ëê° ììµëë¤.',
  'Next &gt;' => 'ë¤ì &gt;',
  'No columns are being updated for table "{table}".' => 'íì´ë¸ "{table}" ì»¬ë¼ì ìë¬´ê²ë ë³ê²½ëì§ ììµëë¤.',
  'No counter columns are being updated for table "{table}".' => 'íì´ë¸ "{table}" ì¹´ì´í° ì»¬ë¼ì ìë¬´ê²ë ë³ê²½ëì§ ììµëë¤.',
  'Object configuration must be an array containing a "class" element.' => 'ê°ì²´ êµ¬ì±ì "class" ììë¥¼ í¬í¨í ë°°ì´ì´ì´ì¼ í©ëë¤.',
  'Please fix the following input errors:' => 'ë¤ì ìë ¥ ì¤ë¥ë¥¼ ìì íì­ìì¤.',
  'Powered by {yii}.' => 'Powered by {yii}.',
  'Property "{class}.{property}" is not defined.' => 'ìì± "{class}.{property}"ë¥¼ ì ìíì§ ìììµëë¤.',
  'Property "{class}.{property}" is read only.' => 'ìì± "{class}.{property}"ì ì½ê¸° ì ì©ìëë¤.',
  'Property CMaskedTextField.mask cannot be empty.' => 'CMaskedTextField.mask ìì±ì ë¹ì´ìì¼ë©´ ìë©ëë¤.',
  'Queue data must be an array or an object implementing Traversable.' => 'í ë°ì´í°ë ë°°ì´ ëë Traversableë¥¼ êµ¬ííë ì¤ë¸ì í¸ì´ì´ì¼ í©ëë¤.',
  'Relation "{name}" is not defined in active record class "{class}".' => 'ê´ê³ "{name}"ë ì¡í°ë¸ ë ì½ë í´ëì¤ "{class}"ë¡ ì ìëì§ ììµëë¤.',
  'Renaming a DB column is not supported by SQLite.' => 'SQLiteë ë°ì´í°ë² ì´ì¤ ì»¬ë¼ì ì´ë¦ì ë³ê²½í  ì ììµëë¤. ',
  'Stack data must be an array or an object implementing Traversable.' => 'ì¤í ë°ì´í°ë ë°°ì´ ëë Traversableë¥¼ êµ¬ííë ì¤ë¸ì í¸ì´ì´ì¼ í©ëë¤.',
  'Table "{table}" does not exist.' => 'íì´ë¸ "{table}"ì ììµëë¤.',
  'Table "{table}" does not have a column named "{column}".' => 'íì´ë¸ "{table}"ìë "{column}"ì´ë¼ë ì´ë¦ì ì»¬ë¼ì´ ììµëë¤.',
  'The "db" application component must be configured to be a CDbConnection object.' => '"db" ìì© íë¡ê·¸ë¨ ì»´í¬ëí¸ë CDbConnection ê°ì²´ë¡ êµ¬ì±ëì´ì¼í©ëë¤.',
  'The "filter" property must be specified with a valid callback.' => '"filter" ìì± ê°ì ì¬ë°ë¥¸ ì½ë°±ì ì§ì í´ì¼í©ëë¤.',
  'The "pattern" property must be specified with a valid regular expression.' => '"pattern" ìì± ê°ì ì¬ë°ë¥¸ ì ê·ìì ì§ì í´ì¼í©ëë¤.',
  'The "range" property must be specified with a list of values.' => '"range" ìì± ê°ì ëª©ë¡ì¼ë¡ ì§ì í´ì¼í©ëë¤.',
  'The CSRF token could not be verified.' => 'CSRF í í°ì íì¸í  ì ììµëë¤.',
  'The DB query must contain the "from" portion.' => 'ë°ì´í°ë² ì´ì¤ ì¿¼ë¦¬ë "from" ë¶ë¶ì í¬í¨í´ì¼ í©ëë¤.',
  'The STAT relation "{name}" cannot have child relations.' => 'STAT ê´ê³ "{name}"ì ìì ê´ê³ë¥¼ ê°ì§ ì ììµëë¤.',
  'The URL pattern "{pattern}" for route "{route}" is not a valid regular expression.' => 'ë£¨í¸ "{route}"ì ëí URL í¨í´ "{pattern}"ì ì¬ë°ë¥¸ ì ê·ìì´ ìëëë¤.',
  'The active record cannot be deleted because it is new.' => 'ì¡í°ë¸ ë ì½ëë¥¼ ì­ì í  ì ììµëë¤. ì ê²ì´ê¸° ëë¬¸ìëë¤.',
  'The active record cannot be inserted to database because it is not new.' => 'ì¡í°ë¸ ë ì½ëë¥¼ ë°ì´í°ë² ì´ì¤ì ì½ìí  ì ììµëë¤. ì ê²ì´ ìëê¸° ëë¬¸ìëë¤.',
  'The active record cannot be updated because it is new.' => 'ì¡í°ë¸ ë ì½ëë¥¼ ìë°ì´í¸í  ì ììµëë¤. ì ê²ì´ê¸° ëë¬¸ìëë¤.',
  'The asset "{asset}" to be published does not exist.' => 'ìì° "{asset}"ë ì¡´ì¬íì§ ììµëë¤.',
  'The command path "{path}" is not a valid directory.' => 'ëªë ¹ ê²½ë¡ "{path}"ë ì¬ë°ë¥¸ ëë í ë¦¬ê° ìëëë¤.',
  'The controller path "{path}" is not a valid directory.' => 'ì»¨í¸ë¡¤ë¬ ê²½ë¡ "{path}"ë ì¬ë°ë¥¸ ëë í ë¦¬ê° ìëëë¤.',
  'The file "{file}" cannot be uploaded. Only files with these extensions are allowed: {extensions}.' => 'íì¼ "{file}"ì ìë¡ëí  ì ììµëë¤. ë¤ì íì¥ìë¥¼ ê°ì§ íì¼ë§ íì©ë©ëë¤.: {extensions}',
  'The file "{file}" is too large. Its size cannot exceed {limit} bytes.' => 'íì¼ "{file}"ì´ ëë¬´ í½ëë¤. í¬ê¸°ë {limit} ë°ì´í¸ë¥¼ ëì ì ììµëë¤.',
  'The file "{file}" is too small. Its size cannot be smaller than {limit} bytes.' => 'íì¼ "{file}"ì´ ëë¬´ ììµëë¤. í¬ê¸°ë {limit} ë°ì´í¸ë³´ë¤ ìì ì ììµëë¤.',
  'The file "{file}" was only partially uploaded.' => 'íì¼ "{file}"ì ì¼ë¶ë§ ìë¡ëëììµëë¤.',
  'The first element in a filter configuration must be the filter class.' => 'íí° êµ¬ì±ì ì²« ë²ì§¸ ììë íí° í´ëì¤ì´ì´ì¼ í©ëë¤.',
  'The format of {attribute} is invalid.' => '{attribute}ì íìì´ ì¬ë°ë¥´ì§ ììµëë¤.',
  'The item "{name}" does not exist.' => 'í­ëª© "{name}"ì ììµëë¤.',
  'The item "{parent}" already has a child "{child}".' => 'í­ëª© "{parent}"ì ì´ë¯¸ ìì "{child}"ì ê°ì§ê³  ììµëë¤.',
  'The layout path "{path}" is not a valid directory.' => 'ë ì´ìì ê²½ë¡ "{path}"ë ì¬ë°ë¥¸ ëë í ë¦¬ê° ìëëë¤.',
  'The list is read only.' => 'ë¦¬ì¤í¸ë ì½ê¸° ì ì©ìëë¤.',
  'The map is read only.' => 'ì§ëë ì½ê¸° ì ì©ìëë¤.',
  'The module path "{path}" is not a valid directory.' => 'ëª¨ë ê²½ë¡ {path}ì ì í¨í ëë í ë¦¬ê° ìëëë¤.',
  'The pattern for 12 hour format must be "h" or "hh".' => '12 ìê°ì  íì í¨í´ "h" ëë "hh"ìëë¤.',
  'The pattern for 24 hour format must be "H" or "HH".' => '24 ìê°ì  íì í¨í´ "H" ëë "HH"ìëë¤.',
  'The pattern for AM/PM marker must be "a".' => 'AM/PM í¨í´ì "a"ìëë¤.',
  'The pattern for day in month must be "F".' => 'íë¬ ëª ë²ì§¸ ìì¼ ê°ì§ í¨í´ì "F"ìëë¤.',
  'The pattern for day in year must be "D", "DD" or "DDD".' => 'í í´ ì¤ ë ì§ì í¨í´ì "D"ëë "DD"ëë "DDD"ìëë¤.',
  'The pattern for day of the month must be "d" or "dd".' => 'íë¬ ì¤ ë ì§ì í¨í´ì "d"ëë "dd"ìëë¤.',
  'The pattern for day of the week must be "E", "EE", "EEE", "EEEE", "EEEEE", "e", "ee", "eee", "eeee", "eeeee", "c", "cccc" or "ccccc".' => 'ìì¼ í¨í´ì "E", "EE", "EEE", "EEEE", "EEEEE", "e", "ee", "eee", "eeee", "eeeee", "c", "cccc ""ccccc "ì¤ íëìëë¤.',
  'The pattern for era must be "G", "GG", "GGG", "GGGG" or "GGGGG".' => 'ê´ê³  í¨í´ì "G"ëë "GG"ëë "GGG"ëë "GGGG"ëë "GGGGG"ìëë¤.',
  'The pattern for hour in AM/PM must be "K" or "KK".' => 'AM/PMì í¨í´ì "K"ëë "KK"ìëë¤.',
  'The pattern for hour in day must be "k" or "kk".' => 'íë£¨ì ìê° í¨í´ì "k"ëë "kk"ìëë¤.',
  'The pattern for minutes must be "m" or "mm".' => 'ë¶ í¨í´ì "m"ëë "mm"ìëë¤.',
  'The pattern for month must be "M", "MM", "MMM", "MMMM", "L", "LL", "LLL" or "LLLL".' => 'ì í¨í´ì "M", "MM", "MMM" "MMMM", "L", "LL" "LLL", "LLLL"ì¤ íëìëë¤.',
  'The pattern for seconds must be "s" or "ss".' => 'ì´ í¨í´ì "s" ëë "ss"ìëë¤.',
  'The pattern for time zone must be "z" or "v".' => 'ìê°ë í¨í´ì "z" ëë "v"ìëë¤.',
  'The pattern for week in month must be "W".' => 'íë¬ì ì£¼ í¨í´ì "W"ì´ì´ì¼ í©ëë¤.',
  'The pattern for week in year must be "w".' => 'íí´ì ì£¼ í¨í´ì "w"ì´ì´ì¼ í©ëë¤.',
  'The queue is empty.' => 'ëê¸°ì´ì´ ë¹ì´ ììµëë¤.',
  'The relation "{relation}" in active record class "{class}" is not specified correctly. The join table "{joinTable}" given in the foreign key cannot be found in the database.' => 'ì¡í°ë¸ ë ì½ë í´ëì¤ "{class}"ê´ê³ "{relation}"ì ì¬ë°ë¥´ê² ì§ì ëì§ ììµëë¤. ì¸ë í¤ ì£¼ì´ì§ ì¡°ì¸ íì´ë¸ "{joinTable}"ë°ì´í°ë² ì´ì¤ì ì¡´ì¬íì§ ììµëë¤.',
  'The relation "{relation}" in active record class "{class}" is not specified correctly: the join table "{joinTable}" given in the foreign key cannot be found in the database.' => 'ì¡í°ë¸ ë ì½ë í´ëì¤ "{class}"ê´ê³ "{relation}"ì ì¬ë°ë¥´ê² ì§ì ëì§ ììµëë¤. ì¸ë í¤ ì£¼ì´ì§ ì¡°ì¸ íì´ë¸ "{joinTable}"ë°ì´í°ë² ì´ì¤ì ììµëë¤.',
  'The relation "{relation}" in active record class "{class}" is specified with a foreign key "{key}" that does not point to the parent table "{table}".' => 'ì¡í°ë¸ ë ì½ë í´ëì¤ "{class}"ê´ê³ "{relation}"ë ì¸ë í¤ "{key}"ê° ì§ì ëì´ ìì§ë§ ë¶ëª¨ íì´ë¸ "{table}"ë¥¼ íìíì§ ììµëë¤.',
  'The relation "{relation}" in active record class "{class}" is specified with an incomplete foreign key. The foreign key must consist of columns referencing both joining tables.' => 'ì¡í°ë¸ ë ì½ë í´ëì¤ "{class}"ê´ê³ "{relation}"ë ë¶ìì í ì¸ë¶ í¤ê° ì§ì ëì´ ììµëë¤. ì¸ë¶ í¤ë ëª¨ë ì¡°ì¸ íì´ë¸ì ì°¸ì¡°íë ì»¬ë¼ì¼ë¡ êµ¬ì±í´ì¼ ìë©ëë¤.',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key "{key}". There is no such column in the table "{table}".' => 'ì¡í°ë¸ ë ì½ë í´ëì¤ "{class}"ê´ê³ "{relation}"ì ìëª»ë ì¸ë í¤ "{key}"ê° ì§ì ëì´ ììµëë¤. íì´ë¸ "{table}"ìë ê·¸ë¬í ì»¬ë¼ì´ ì¡´ì¬íì§ ììµëë¤.',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key. The columns in the key must match the primary keys of the table "{table}".' => 'ì¡í°ë¸ ë ì½ë í´ëì¤ "{class}"ê´ê³ "{relation}"ì ìëª»ë ì¸ë í¤ "{key}"ê° ì§ì ëì´ ììµëë¤. í¤ì ì»¬ë¼ì íì´ë¸ "{table}"ê¸°ë³¸ í¤ì ì¼ì¹í´ì¼í©ëë¤.',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key. The format of the foreign key must be "joinTable(fk1,fk2,...)".' => 'ì¡í°ë¸ ë ì½ë í´ëì¤ "{class}" ê´ê³ "{relation}"ì ìëª»ë ì¸ë¶ í¤ê° ì§ì ëì´ ììµëë¤. ì¸ë í¤ í¬ë§·ì "joinTable (fk1, fk2, ...)"ìëë¤.',
  'The requested view "{name}" was not found.' => 'ìì²­í view "{name}"ë¥¼ ì°¾ì ì ììµëë¤.',
  'The stack is empty.' => 'ì¤íì´ ë¹ì´ ììµëë¤.',
  'The system is unable to find the requested action "{action}".' => 'ìì¤íì ìì²­ë ìì "{action}"ë¥¼ ì°¾ì ì ììµëë¤.',
  'The system view path "{path}" is not a valid directory.' => 'ìì¤í ë·° ê²½ë¡ "{path}"ë ì¬ë°ë¥¸ ëë í ë¦¬ê° ìëëë¤.',
  'The table "{table}" for active record class "{class}" cannot be found in the database.' => 'ì¡í°ë¸ ë ì½ë í´ëì¤ "{class}"ë¥¼ ìí íì´ë¸ "{table}"ì ë°ì´í°ë² ì´ì¤ìì ì°¾ì ì ììµëë¤.',
  'The value for the column "{column}" is not supplied when querying the table "{table}".' => 'íì´ë¸ "{table}" ì¿¼ë¦¬ì ëíì¬ ì´ "{column}" ê°ì´ ì¤ì ëì´ ìì§ ììµëë¤.',
  'The verification code is incorrect.' => 'ê²ì¦ ì½ëê° ì¬ë°ë¥´ì§ ììµëë¤.',
  'The view path "{path}" is not a valid directory.' => 'ë·° í¨ì¤ "{path}"ë ì¬ë°ë¥¸ ëë í ë¦¬ê° ìëëë¤.',
  'Theme directory "{directory}" does not exist.' => 'íë§ ëë í°ë¦¬ "{directory}"ê° ì¡´ì¬íì§ ììµëë¤.',
  'This content requires the <a href="http://www.adobe.com/go/getflash/">Adobe Flash Player</a>.' => 'ì´ ì½íì¸ ë <a href="http://www.adobe.com/go/getflash/"> Adobe Flash Player </a>ê° íìí©ëë¤.',
  'Unable to add an item whose name is the same as an existing item.' => 'ì´ë¯¸ ìë í­ëª©ê³¼ ê°ì ì´ë¦ì í­ëª©ì ì¶ê°í  ì ììµëë¤.',
  'Unable to change the item name. The name "{name}" is already used by another item.' => 'í­ëª©ì ì´ë¦ì ë³ê²½í  ì ììµëë¤. ê·¸ ì´ë¦ "{name}"ì ì´ë¯¸ ë¤ë¥¸ í­ëª©ì¼ë¡ ì¬ì©ëê³  ììµëë¤.',
  'Unable to create application state file "{file}". Make sure the directory containing the file exists and is writable by the Web server process.' => 'ìì© íë¡ê·¸ë¨ ìí íì¼ "{file}"ë¥¼ ë§ë¤ ì ììµëë¤. íì¼ ëë í ë¦¬ê° ìëì§, ì¹ ìë² íë¡ì¸ì¤ê° ì¸ ì ìëì§ë¥¼ íì¸íì­ìì¤.',
  'Unable to find "{column}" in table "{table}".' => 'íì´ë¸ "{table}" ìì ì»¬ë¼ "{column}"ê° ììµëë¤.',
  'Unable to lock file "{file}" for reading.' => 'íì¼ "{file}"ì ì½ê¸° ì ê¸í  ì ììµëë¤.',
  'Unable to lock file "{file}" for writing.' => 'íì¼ "{file}"ë¥¼ ì°ê¸° ì ê¸í  ì ììµëë¤.',
  'Unable to read file "{file}".' => 'íì¼ "{file}"ì ì½ì ì ììµëë¤.',
  'Unable to replay the action "{object}.{method}". The method does not exist.' => 'ì¡ì "{object}.{method}"ì ë¦¬íë ì´ ì ììµëë¤. ë©ìëê° ììµëë¤.',
  'Unable to resolve the request "{route}".' => 'ìì²­ "{route}"ë¥¼ í´ê²°í  ì ììµëë¤.',
  'Unable to write file "{file}".' => 'íì¼ "{file}"ì ì¸ ì ììµëë¤.',
  'Unknown authorization item "{name}".' => '"{name}"ì ì ì ìë ì¸ì¦í­ëª©ìëë¤.',
  'Unknown operator "{operator}".' => '"{operator}"ë ì ì ìë ì°ì°ììëë¤.',
  'Unknown type "{type}".' => '"{type}"ì ì ì ìë íììëë¤.',
  'Unrecognized locale "{locale}".' => 'ë¡ì¼ì¼ "{locale}"ë¥¼ ì¸ìí  ì ììµëë¤.',
  'View file "{file}" does not exist.' => 'ë·° íì¼ "{file}"ë ììµëë¤.',
  'Yii application can only be created once.' => 'Yii ìì© íë¡ê·¸ë¨ì í ë²ë§ ë§ë¤ ì ììµëë¤.',
  'You are not authorized to perform this action.' => 'ë¹ì ì ì´ ììì ìíí  ê¶íì´ ììµëë¤.',
  'Your request is invalid.' => 'ìëª»ë ìì²­ìëë¤.',
  '{attribute} "{value}" has already been taken.' => '{attribute}ì ê° "{value}"ë ì´ë¯¸ ì¬ì©ëê³  ììµëë¤.',
  '{attribute} "{value}" is invalid.' => '{attribute}ì ê°ì¼ë¡ "{value}"ë ì¬ë°ë¥´ì§ ììµëë¤.',
  '{attribute} cannot accept more than {limit} files.' => '{attribute}ë {limit} íì¼ ì´ì ë°ì ì ììµëë¤.',
  '{attribute} cannot be blank.' => '{attribute}ë ê³µë°±ì´ì´ìë ìë©ëë¤.',
  '{attribute} is in the list.' => '{attribute} ëª©ë¡ì ììµëë¤.',
  '{attribute} is invalid.' => '{attribute}ë ì í¨íì§ ììµëë¤.',
  '{attribute} is not a valid URL.' => '{attribute}ì ì í¨í URLì´ ìëëë¤.',
  '{attribute} is not a valid email address.' => '{attribute}ì ì í¨í ì´ë©ì¼ ì£¼ìê° ìëëë¤.',
  '{attribute} is not in the list.' => '{attribute}ë ëª©ë¡ì ììµëë¤.',
  '{attribute} is of the wrong length (should be {length} characters).' => '{attribute}ì ê¸¸ì´ê° ìëª»ëììµëë¤ ({length} ë¬¸ìì´ì´ì¼ í©ëë¤).',
  '{attribute} is too big (maximum is {max}).' => '{attribute}ë ëë¬´ í½ëë¤ (ìµë {max}).',
  '{attribute} is too long (maximum is {max} characters).' => '{attribute}ë ëë¬´ ê¹ëë¤ (ìµë {max} ì)',
  '{attribute} is too short (minimum is {min} characters).' => '{attribute}ë ëë¬´ ì§§ìµëë¤ (ìµì {min} ë¬¸ì).',
  '{attribute} is too small (minimum is {min}).' => '{attribute}ë ëë¬´ ììµëë¤ (ìµì {min}).',
  '{attribute} must be a number.' => '{attribute}ë ì«ìì´ì´ì¼ í©ëë¤.',
  '{attribute} must be an integer.' => '{attribute}ë ì ìì´ì´ì¼ í©ëë¤.',
  '{attribute} must be either {true} or {false}.' => '{attribute}ë {true}ì´ê±°ë {false}ì´ì´ì¼ í©ëë¤.',
  '{attribute} must be greater than "{compareValue}".' => '{attribute}ë "{compareValue}" ë³´ë¤ ì»¤ì¼ í©ëë¤.',
  '{attribute} must be greater than or equal to "{compareValue}".' => '{attribute}ë "{compareValue}" ë³´ë¤ í¬ê±°ë ê°ìì¼ í©ëë¤.',
  '{attribute} must be less than "{compareValue}".' => '{attribute}ë "{compareValue}" ë³´ë¤ ììì¼ í©ëë¤.',
  '{attribute} must be less than or equal to "{compareValue}".' => '{attribute}ë "{compareValue}" ë³´ë¤ ìê±°ë ê°ìì¼ í©ëë¤.',
  '{attribute} must be repeated exactly.' => '{attribute}ì ì ííê² ë°ë³µí´ì¼í©ëë¤.',
  '{attribute} must be {type}.' => '{attribute}ë {type}ì´ì´ì¼í©ëë¤.',
  '{attribute} must be {value}.' => '{attribute}ë {value}ì´ì´ì¼í©ëë¤.',
  '{attribute} must not be equal to "{compareValue}".' => '{attribute}ë "{compareValue}"ì ê°ì¼ë©´ ìë©ëë¤.',
  '{className} does not support add() functionality.' => '{className}ë add() ê¸°ë¥ì ì§ìíì§ ììµëë¤.',
  '{className} does not support delete() functionality.' => '{className}ë delete() ê¸°ë¥ì ì§ìíì§ ììµëë¤.',
  '{className} does not support flushValues() functionality.' => '{className}ë flushValues() ê¸°ë¥ì ì§ìíì§ ììµëë¤.',
  '{className} does not support get() functionality.' => '{className}ë get() ê¸°ë¥ì ì§ìíì§ ììµëë¤.',
  '{className} does not support set() functionality.' => '{className}ë set() ê¸°ë¥ì ì§ìíì§ ììµëë¤.',
  '{class} and its behaviors do not have a method or closure named "{name}".' => '{class}ì ê·¸ íëìë "{name}"ë¼ë ë©ìë ë° í´ë¡ì ë ììµëë¤.',
  '{class} does not have relation "{name}".' => '{class}ë "{name}"ê³¼ ê´ê³ê° ììµëë¤.',
  '{class} does not support fetching all table names.' => '{class}ë íì´ë¸ ì´ë¦ ê²ì ê¸°ë¥ì ì§ìíì§ ììµëë¤.',
  '{class} has an invalid validation rule. The rule must specify attributes to be validated and the validator name.' => '{class} ê²ì¦ ê·ì¹ì ìëª»ë ê²ìëë¤. ê·ì¹ì ê²ì¬íê³ ìíë ìì±ê³¼ ì í¨ì± ì´ë¦ì ì§ì íì­ìì¤.',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class}ìë "model"ê³¼ "attribute" ëë "name" ìì± ê°ì ì¤ì íì­ìì¤.',
  '{class}.allowAutoLogin must be set true in order to use cookie-based authentication.' => 'ì¿ í¤ ê¸°ë° ì¸ì¦ì ì¬ì©íë ¤ë©´ {class}.allowAutoLoginë¥¼ ì¤ì íì­ìì¤.',
  '{class}::authenticate() must be implemented.' => '{class}::authenticate()ë ë°ëì êµ¬íí´ì¼ í©ëë¤.',
  '{controller} cannot find the requested view "{view}".' => '{controller}ë ìì²­í view "{view}"ë¥¼ ì°¾ì ì ììµëë¤.',
  '{controller} contains improperly nested widget tags in its view "{view}". A {widget} widget does not have an endWidget() call.' => '{controller}ë view "{view}"ìì ìëª» ì¤ì²©ë ìì ¯ íê·¸ë¥¼ ê°ì§ê³  ììµëë¤. {widget} ìì ¯ì endWidget() í¸ì¶ì ê°ì§ê³  ìì§ììµëë¤.',
  '{controller} has an extra endWidget({id}) call in its view.' => '{controller}ë viewë¥¼ ìí´ ì¬ë¶ì endWidget ({id})ë¥¼ í¸ì¶í©ëë¤.',
  '{widget} cannot find the view "{view}".' => '{widget}ë view "{view}"ë¥¼ ì°¾ì ì ììµëë¤.',
);

