<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Home' => 'í',
  'The button type "{type}" is not supported.' => 'ë²í¼ íì "{type}"ì ì§ìíì§ ììµëë¤.',
  'Are you sure you want to delete this item?' => 'ì´ í­ëª©ì ì­ì íê² ìµëê¹?',
  'Delete' => 'ì­ì ',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => '{count}ê°ì ê²°ê³¼ ì¤ìì {start}-{end}ë¥¼ íìí©ëë¤.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'CDataColumnì "name" ëë "value"ë ë°ëì ì ìëì´ì¼ í©ëë¤.',
  'No results found.' => 'ê²°ê³¼ê° ììµëë¤.',
  'Not set' => 'ì§ì ëì§ ìììµëë¤.',
  'Please specify the "attributes" property.' => '"attributes"ë¥¼ ì ìíì­ìì¤.',
  'Please specify the "data" property.' => '"data"ë¥¼ ì ìíì­ìì¤.',
  'Sort by: ' => 'ì ë ¬:',
  'The "dataProvider" property cannot be empty.' => '"dataProvider"ë¥¼ ë¹ìë ì ììµëë¤.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'ìì±ì "Name:Type:Label" íìì¼ë¡ ì§ì í´ì¼í©ëë¤. "Type"ê³¼ "Label"ì ì í ì¬í­ìëë¤.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'ì»¬ë¼ì "Name:Type:Label" íìì¼ë¡ ì§ì í´ì¼í©ëë¤. "Type"ê³¼ "Label"ì ì í ì¬í­ìëë¤.',
  'The property "itemView" cannot be empty.' => '"itemView" ìì±ì ë¹ìë ì ììµëë¤.',
  'Total 1 result.|Total {count} results.' => 'ì´{count}ê°',
  'Update' => 'ìì ',
  'View' => 'íì',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class}ë "model"ì "attribute" ëë "name" ìì± ê°ì¼ë¡ ì§ì í´ì¼ í©ëë¤.',
);
