<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Home' => 'Pagina principalÄ',
  'The button type "{type}" is not supported.' => 'Tipul de buton â{type}â nu este suportat.',
  'Are you sure you want to delete this item?' => 'ConfirmaÅ£i Återgerea acestui element?',
  'Delete' => 'Återgere',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'Se afiÅeazÄ 1 rezultat.|Se afiÅeazÄ {start}-{end} din {count} rezultate.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'Trebuie sÄ specificaÅ£i "name" sau "value" pentru CDataColumn.',
  'No results found.' => 'Nu sunt rezultate pentru afiÅare.',
  'Not set' => 'Nu este definit(Ä)',
  'Please specify the "attributes" property.' => 'DefiniÅ£i proprietatea âattributesâ.',
  'Please specify the "data" property.' => 'DefiniÅ£i proprietatea âdataâ.',
  'Sort by: ' => 'Sortare dupÄ: ',
  'The "dataProvider" property cannot be empty.' => 'Proprietatea âdataProviderâ nu poate fi nulÄ.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Atributul trebuie definit Ã®n formatul âName:Type:Labelâ, unde âTypeâ Åi âLabelâ sunt opÅ£ionale.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Coloana trebuie definitÄ Ã®n formatul âName:Type:Labelâ, unde âTypeâ et âLabelâ sunt opÅ£ionale.',
  'The property "itemView" cannot be empty.' => 'Proprietatea âitemViewâ nu poate fi nulÄ',
  'Total 1 result.|Total {count} results.' => 'Total 1 rezultat.|Total {count} rezultate.',
  'Update' => 'Actualizare',
  'View' => 'Vizualizare',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} trebuie sÄ defineascÄ valori pentru proprietÄÅ£ile âmodelâ Åi âattributeâ sau ânameâ.',
);
