<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Are you sure you want to delete this item?' => 'Ar tikrai norite paÅ¡alinti Å¡Ä¯ elementÄ?',
  'Delete' => 'Å alinti',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'Rodomi Ä¯raÅ¡ai {start}-{end} iÅ¡ {count}.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'CDataColumn turi bÅ«ti nurodytas ânameâ arba âvalueâ.',
  'Home' => 'PradÅ¾ia',
  'No results found.' => 'NÄra duomenÅ³.',
  'Not set' => 'Nenustatyta',
  'Please specify the "attributes" property.' => 'PraÅ¡ytume nurodyti savybÄ âattributesâ.',
  'Please specify the "data" property.' => 'PraÅ¡ytume nurodyti savybÄ âdataâ.',
  'Sort by: ' => 'Rikiuoti pagal: ',
  'The "dataProvider" property cannot be empty.' => 'SavybÄ âdataProviderâ negali bÅ«ti tuÅ¡Äia.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Atributas turi bÅ«ti nurodytas formatu âName:Type:Labelâ, kur âTypeâ ir âLabelâ â neprivalomi.',
  'The button type "{type}" is not supported.' => 'Mygtuko tipas â{type}" nÄra realizuotas.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Laukas turi bÅ«ti nurodytas formatu âName:Type:Labelâ, kur âTypeâ ir âLabelâ â neprivalomi.',
  'The property "itemView" cannot be empty.' => 'SavybÄ âitemViewâ negali bÅ«ti tuÅ¡Äia.',
  'Total 1 result.|Total {count} results.' => 'Viso: {count}.',
  'Update' => 'Redaguoti',
  'View' => 'PerÅ¾iÅ«rÄti',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} turi nurodyti âmodelâ ir savybiÅ³ âattributeâ arba ânameâ reikÅ¡mes.',
);
