<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'The property filterSelector should be defined.' => 'filterSelector ÒÐ°ÑÐ¸ÐµÑÑ Ð°Ð½ÑÒÑÐ°Ð»ÒÐ°Ð½ Ð±Ð¾Ð»ÑÑ ÑÐ¸ÑÑ.',
  'The property updateSelector should be defined.' => 'updateSelector ÒÐ°ÑÐ¸ÐµÑÑ Ð°Ð½ÑÒÑÐ°Ð»ÒÐ°Ð½ Ð±Ð¾Ð»ÑÑ ÑÐ¸ÑÑ.',
  'Are you sure you want to delete this item?' => 'ÐÒ±Ð» Ð½ÓÑÑÐµÐ½Ñ Ó©ÑÑÑÑÐ´Ñ ÑÑÐ½ÑÐ¼ÐµÐ½ ÒÐ°Ð»Ð°Ð¹ÑÑÐ· Ð±Ð°?',
  'Delete' => 'Ó¨ÑÑÑÑ',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => '{start}â{end} Ð½ÓÑÑÐµ, Ð±Ð°ÑÐ»ÑÒÑ {count}.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'CDataColumn Ò¯ÑÑÐ½ "name" Ð½Ðµ "value" ÐºÓ©ÑÑÐµÑÑ ÐºÐµÑÐµÐº.',
  'Home' => 'ÐÐ°ÑÑÑ',
  'No results found.' => 'ÐÓÑÐ¸Ð¶ÐµÐ»ÐµÑÑ Ð¶Ð¾Ò.',
  'Not set' => 'ÐÑÐ½Ð°ÑÑÐ»Ð¼Ð°ÒÐ°Ð½',
  'Please specify the "attributes" property.' => '"attributes" ÒÐ°ÑÐ¸ÐµÑÑÐ½ Ð¾ÑÐ½Ð°ÑÑÒ£ÑÐ·.',
  'Please specify the "data" property.' => '"data" ÒÐ°ÑÐ¸ÐµÑÑÐ½ Ð¾ÑÐ½Ð°ÑÑÒ£ÑÐ·.',
  'Sort by: ' => 'Ð¡Ò±ÑÑÐ¿ÑÐ°Ñ: ',
  'The "dataProvider" property cannot be empty.' => '"dataProvider" ÒÐ°ÑÐ¸ÐµÑÑ Ð±Ð¾Ñ Ð±Ð¾Ð»Ð¼Ð°ÑÑ ÑÐ¸ÑÑ.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'ÐÑÑÐ¸Ð±ÑÑ "ÐÑÑ:Ð¢Ò¯ÑÑ:Ð¢Ð°ÒÑÑÑÐ¿ÑÐ°Ð¼Ð°ÑÑ" Ð¿ÑÑÑÐ¼ÑÐ½Ð´Ðµ ÐºÓ©ÑÑÐµÑÑÐ»ÑÑ ÑÐ¸ÑÑ. "Ð¢Ò¯ÑÑ" Ð¼ÐµÐ½ "Ð¢Ð°ÒÑÑÑÐ¿ÑÐ°Ð¼Ð°ÑÑ" Ð¼ÑÐ½Ð´ÐµÑÑÑ ÐµÐ¼ÐµÑ.',
  'The button type "{type}" is not supported.' => 'ÐÐ°ÑÑÑÐ¼Ð°Ð½ÑÒ£ "{type}" ÑÒ¯ÑÑÐ½Ðµ ÒÐ¾Ð»Ð´Ð°Ñ Ð¶Ð¾Ò.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'ÐÐ°ÒÐ°Ð½ "ÐÑÑ:Ð¢Ò¯ÑÑ:Ð¢Ð°ÒÑÑÑÐ¿ÑÐ°Ð¼Ð°ÑÑ" Ð¿ÑÑÑÐ¼ÑÐ½Ð´Ðµ ÐºÓ©ÑÑÐµÑÑÐ»ÑÑ ÑÐ¸ÑÑ. "Ð¢Ò¯ÑÑ" Ð¼ÐµÐ½ "Ð¢Ð°ÒÑÑÑÐ¿ÑÐ°Ð¼Ð°ÑÑ" Ð¼ÑÐ½Ð´ÐµÑÑÑ ÐµÐ¼ÐµÑ.',
  'The property "itemView" cannot be empty.' => '"itemView" ÒÐ°ÑÐ¸ÐµÑÑ Ð±Ð¾Ñ Ð±Ð¾Ð»Ð¼Ð°ÑÑ ÑÐ¸ÑÑ.',
  'Total 1 result.|Total {count} results.' => 'ÐÐ°ÑÐ»ÑÒ Ð½ÓÑÐ¸Ð¶Ðµ ÑÐ°Ð½Ñ: {count}.',
  'Update' => 'ÐÐ°Ò£Ð°ÑÑÑ',
  'View' => 'ÒÐ°ÑÐ°Ñ',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} ÐºÐ»Ð°ÑÑÐ½Ð´Ð° "model" Ð¸ "attribute" ÒÐ°ÑÐ¸ÐµÑÑÐµÑÑÐ½ÑÒ£ Ð¼ÓÐ½Ð´ÐµÑÑ, Ð½ÐµÐ¼ÐµÑÐµ "name" Ð¼ÓÐ½Ñ Ð±ÐµÑÑÐ»ÑÑ ÐºÐµÑÐµÐº.',
);
