<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Home' => 'é¦é¡µ',
  'The button type "{type}" is not supported.' => 'æé®ç±»å "{type}" ä¸æ¯æã',
  'Are you sure you want to delete this item?' => 'ç¡®å®è¦å é¤è¿æ¡æ°æ®å?',
  'Delete' => 'å é¤',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'ç¬¬ {start}-{end} æ¡, å± {count} æ¡.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'CDataColumn å¿é¡»æå® "name" æ "value" è³å°ä¸é¡¹.',
  'No results found.' => 'æ²¡ææ¾å°æ°æ®.',
  'Not set' => 'æªè®¾ç½®',
  'Please specify the "attributes" property.' => 'è¯·æå® "attributes" å±æ§.',
  'Please specify the "data" property.' => 'è¯·æå® "data" å±æ§.',
  'Sort by: ' => 'æåº: ',
  'The "dataProvider" property cannot be empty.' => '"dataProvider" å±æ§ä¸è½ä¸ºç©º.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'å±æ§æ ¼å¼ "Name:Type:Label", "Type" å "Label" ä¸ºå¯éé¡¹.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'æ ä½æ ¼å¼ "Name:Type:Label", "Type" å "Label" ä¸ºå¯éé¡¹.',
  'The property "itemView" cannot be empty.' => 'å¿é¡»æå® "itemView" å±æ§.',
  'Total 1 result.|Total {count} results.' => 'å± {count} æ¡.',
  'Update' => 'æ´æ°',
  'View' => 'æ¥ç',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} å¿é¡»ç»å® "model" ä¸ "attribute" æ "name" å±æ§å¼.',
);
