<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '{class} must specify "model" and "{attribute}" or "{name}" property values.' => '{class} musÃ­ Å¡pecifikovaÅ¥ "model" a hodnotu pre "{attribute}" alebo "{name}".',
  'Are you sure you want to delete this item?' => 'OdstrÃ¡niÅ¥ zÃ¡znam?',
  'Delete' => 'OdstrÃ¡niÅ¥',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'ZobrazenÃ½ch {start}-{end} z 1 zÃ¡znamu.|ZobrazenÃ½ch {start}-{end} z celkovo {count} zÃ¡znamov.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'UveÄte prosÃ­m  "name" alebo "value" pre CDataColumn.',
  'Home' => 'Ãvod',
  'No results found.' => 'Neboli nÃ¡jdenÃ© Å¾iadne zÃ¡znamy.',
  'Not set' => 'Nie je nastavenÃ©',
  'Please specify the "attributes" property.' => 'Zadajte prosÃ­m vlastnosti pre "attributes".',
  'Please specify the "data" property.' => 'Zadajte prosÃ­m vlastnosti pre "data".',
  'Sort by: ' => 'ZoradiÅ¥ podÄ¾a:',
  'The "dataProvider" property cannot be empty.' => 'VlastnosÅ¥ "dataProvider" nesmie byÅ¥ prÃ¡zdna.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'AtribÃºt musÃ­ byÅ¥ Å¡pecifikovanÃ½ v tvare "Name:Type:Label", priÄom "Type" a "Label" sÃº nepovinnÃ©.',
  'The button type "{type}" is not supported.' => 'TlaÄidlo typu "{type}" nie je podporovanÃ©.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'StÄºpec musÃ­ byÅ¥ Å¡pecifikovanÃ½ v tvare "Name:Type:Label", priÄom "Type" a "Label" sÃº nepovinnÃ©.',
  'The property "itemView" cannot be empty.' => 'VlastnosÅ¥ "itemView" nesmie byÅ¥ prÃ¡zdna.',
  'The property filterSelector should be defined.' => 'Je potrebnÃ© definovaÅ¥ vlastnosÅ¥ filterSelector.',
  'The property updateSelector should be defined.' => 'Je potrebnÃ© definovaÅ¥ vlastnosÅ¥ updateSelector.',
  'Total 1 result.|Total {count} results.' => 'NÃ¡jdenÃ½ 1 zÃ¡znam.|NÃ¡jdenÃ½ch {count} zÃ¡znamov.',
  'Update' => 'UpraviÅ¥',
  'View' => 'NÃ¡hÄ¾ad',
);
