<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Home' => 'FÅoldal',
  'The button type "{type}" is not supported.' => 'A "{type}" tÃ­pusÃº gomb nem tÃ¡mogatott',
  'Are you sure you want to delete this item?' => 'Biztos benne hogy tÃ¶rli?',
  'Delete' => 'TÃ¶rlÃ©s',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'EredmÃ©nyek megjelenÃ­tÃ©se {start}-tÅl {end}-ig {count} talÃ¡latbÃ³l.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'Vagy a "name", vagy a "value" paramÃ©tert be kell Ã¡llÃ­tani a CDataColum rÃ©szÃ©re.',
  'No results found.' => 'Nincs talÃ¡lat!',
  'Not set' => 'Nincs beÃ¡llÃ­tva!',
  'Please specify the "attributes" property.' => 'Meg kell adni az "attributes" vÃ¡ltozÃ³t.',
  'Please specify the "data" property.' => 'Meg kell adni a "data" vÃ¡ltozÃ³t.',
  'Sort by: ' => 'RendezÃ©s:',
  'The "dataProvider" property cannot be empty.' => 'A "dataProvider" vÃ¡ltozÃ³ nem lehet Ã¼res.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Az Ã©rtÃ©keket az alÃ¡bbi formÃ¡ban kell megadni "Name:Type:Label" a "Type" Ã©s a "Label" nem kÃ¶telezÅ.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Az oszlopot az alÃ¡bbi formÃ¡ban kell megadni "Name:Type:Label". A "Type" Ã©s a "Label" nem kÃ¶telezÅ.',
  'The property "itemView" cannot be empty.' => 'Az "itemView" vÃ¡ltozÃ³ nem lehet Ã¼res.',
  'Total 1 result.|Total {count} results.' => 'Ãsszesen {count} talÃ¡lat.',
  'Update' => 'Szerkeszt',
  'View' => 'Mutat',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} meg kell hatÃ¡rozni a "model" Ã©s a "attribute" vagy "name" Ã©rtÃ©kÃ©t.',
);
