<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Home' => 'ÐÐ¾ÑÐµÑÐ½Ð°',
  'The button type "{type}" is not supported.' => 'ÐÑÐ³Ð¼Ðµ ÑÐ¸Ð¿Ð° "{type}" Ð½Ð¸ÑÐµ Ð¿Ð¾Ð´ÑÐ¶Ð°Ð½Ð¾.',
  'Are you sure you want to delete this item?' => 'ÐÐ° Ð»Ð¸ ÑÑÐµ ÑÐ¸Ð³ÑÑÐ½Ð¸ Ð´Ð° Ð¶ÐµÐ»Ð¸ÑÐµ Ð´Ð° Ð¾Ð±ÑÐ¸ÑÐµÑÐµ Ð¾Ð²Ñ ÑÑÐ°Ð²ÐºÑ?',
  'Delete' => 'ÐÐ±ÑÐ¸ÑÐ¸',
  'Displaying {start}-{end} of {count} result(s).' => 'ÐÑÐ¸ÐºÐ°Ð·Ð°Ð½Ð¾ {start}-{end} Ð¾Ð´ {count} ÑÐµÐ·ÑÐ»ÑÐ°ÑÐ°.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'ÐÐ¾ÑÐ°ÑÐµ Ð¿Ð¾ÑÑÐ°Ð²Ð¸ÑÐ¸ Ð²ÑÐµÐ´Ð½Ð¾ÑÑ "name" Ð¸Ð»Ð¸ "value" Ð¿ÑÐ¾Ð¼ÐµÑÐ¸Ð²Ðµ Ð·Ð° CDataColumn.',
  'No results found.' => 'ÐÐµÐ¼Ð° ÑÐµÐ·ÑÐ»ÑÐ°ÑÐ°.',
  'Not set' => 'ÐÐµÐ· Ð²ÑÐµÐ´Ð½Ð¾ÑÑÐ¸',
  'Please specify the "attributes" property.' => 'ÐÐ¾ÑÐ°ÑÐµ Ð¿Ð¾ÑÑÐ°Ð²Ð¸ÑÐ¸ Ð²ÑÐµÐ´Ð½Ð¾ÑÑ "attributes" Ð¿ÑÐ¾Ð¼ÐµÑÐ¸Ð²Ðµ.',
  'Please specify the "data" property.' => 'ÐÐ¾ÑÐ°ÑÐµ Ð¿Ð¾ÑÑÐ°Ð²Ð¸ÑÐ¸ Ð²ÑÐµÐ´Ð½Ð¾ÑÑ "data" Ð¿ÑÐ¾Ð¼ÐµÑÐ¸Ð²Ðµ.',
  'Sort by: ' => 'Ð¡Ð¾ÑÑÐ¸ÑÐ°Ñ Ð¿Ð¾:',
  'The "dataProvider" property cannot be empty.' => '"dataProvider" Ð°ÑÑÐ¸Ð±ÑÑ Ð¼Ð¾ÑÐ° Ð±Ð¸ÑÐ¸ Ð¿Ð¾ÑÑÐ°Ð²ÑÐµÐ½.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'ÐÑÑÐ¸Ð±ÑÑÐ¸ ÑÐµ Ð¼Ð¾ÑÐ°ÑÑ ÑÐ½ÐµÑÐ¸ Ñ ÑÐ¾ÑÐ¼Ð°ÑÑ "Name:Type:Label", Ð³Ð´Ðµ ÑÑ "Type" Ð¸ "Label" Ð½ÐµÐ¾Ð±Ð°Ð²ÐµÐ·Ð½Ð° Ð¿Ð¾ÑÐ°.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'ÐÐ¾Ð»Ð¾Ð½Ð° Ð¼Ð¾ÑÐ° Ð±Ð¸ÑÐ¸ Ñ ÑÐ¾ÑÐ¼Ð°ÑÑ "Name:Type:Label", Ð³Ð´Ðµ ÑÑ "Type" Ð¸ "Label" Ð½ÐµÐ¾Ð±Ð°Ð²ÐµÐ·Ð½Ð° Ð¿Ð¾ÑÐ°.',
  'The property "itemView" cannot be empty.' => 'ÐÑÑÐ¸Ð±ÑÑ "itemView" Ð½Ðµ ÑÐ¼Ðµ Ð±Ð¸ÑÐ¸ Ð¿ÑÐ°Ð·Ð°Ð½.',
  'Total {count} result(s).' => 'Ð£ÐºÑÐ¿Ð½Ð¾ {count} ÑÐµÐ·ÑÐ»ÑÐ°ÑÐ°.',
  'Update' => 'ÐÑÐµÐ¿ÑÐ°Ð²Ð¸',
  'View' => 'ÐÐ¾Ð³Ð»ÐµÐ´Ð°Ñ',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} Ð¼Ð¾ÑÐ° Ð¿Ð¾ÑÑÐ°Ð²Ð¸ÑÐ¸ "model" Ð¸ "attribute" Ð¸Ð»Ð¸ "name" Ð²ÑÐµÐ´Ð½Ð¾ÑÑÐ¸ Ð°ÑÑÐ¸Ð±ÑÑÐ°.',
);
