<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '{class} and its behaviors do not have a method or closure named "{name}".' => 'Klasa {class} i jej zachowania nie posiadajÄ metody lub domkniÄcia "{name}".',
  '"{path}" is not a valid directory.' => 'ÅcieÅ¼ka "{path}" nie jest poprawnym katalogiem.',
  '&lt; Previous' => '&lt; Poprzednia',
  '&lt;&lt; First' => '&lt;&lt; Pierwsza',
  'Action class {class} must implement the "run" method.' => 'Klasa akcji {class} musi implementowaÄ metodÄ "run".',
  'Active Record requires a "db" CDbConnection application component.' => 'Active Record wymaga komponentu aplikacji "db" CDbConnection.',
  'Active record "{class}" has an invalid configuration for relation "{relation}". It must specify the relation type, the related active record class and the foreign key.' => 'Konfiguracja rekordu aktywnego "{class}" jest niewÅaÅciwa dla relacji "{relation}". Musi definiowaÄ typ relacji, odnoszÄcÄ siÄ do niej klasÄ rekordu aktywnego i klucz obcy.',
  'Active record "{class}" is trying to select an invalid column "{column}". Note, the column must exist in the table or be an expression with alias.' => 'Active record "{class}" prÃ³buje wybraÄ nieodpowiedniÄ kolumnÄ "{column}". PamiÄtaj, Å¼e kolumna musi istnieÄ w tabeli lub musi byÄ wyraÅ¼ona aliasem.',
  'Adding a foreign key constraint to an existing table is not supported by SQLite.' => 'SQLite nie wspiera dodawanie ograniczenia klucza obcego do istniejÄcej tabeli.',
  'Alias "{alias}" is invalid. Make sure it points to an existing PHP file and the file is readable.' => 'NieprawidÅowy alias "{alias}". Upewnij siÄ, Å¼e wskazuje na istniejÄcy plik PHP.',
  'Alias "{alias}" is invalid. Make sure it points to an existing directory or file.' => 'NieprawidÅowy alias "{alias}". Upewnij siÄ, Å¼e wskazuje na istniejÄcy katalog lub plik.',
  'Alias "{alias}" is invalid. Make sure it points to an existing directory.' => 'NieprawidÅowy "{alias}". Upewnij siÄ, Å¼e wskazuje na istniejÄcy katalog.',
  'Altering a DB column is not supported by SQLite.' => 'SQLite nie wspiera zmian kolumn bazy danych.',
  'Application Log' => 'Log aplikacji',
  'Application base path "{path}" is not a valid directory.' => 'Podstawowa ÅcieÅ¼ka aplikacji "{path}" nie jest poprawnym katalogiem.',
  'Application runtime path "{path}" is not valid. Please make sure it is a directory writable by the Web server process.' => 'ÅcieÅ¼ka uruchomieniowa aplikacji "{path}" jest nieprawidÅowa. Upewnij siÄ, Å¼e ten katalog jest dostÄpny do zapisu dla procesu serwera.',
  'Authorization item "{item}" has already been assigned to user "{user}".' => 'Å»eton "{item}" zostaÅ juÅ¼ przypisany uÅ¼ytkownikowi "{user}".',
  'Base path "{path}" is not a valid directory.' => 'ÅcieÅ¼ka bazowa "{path}" nie jest poprawnym katalogiem.',
  'CApcCache requires PHP apc extension to be loaded.' => 'CApcCache wymaga zaÅadowanego rozszerzenia PHP apc.',
  'CAssetManager.basePath "{path}" is invalid. Please make sure the directory exists and is writable by the Web server process.' => 'ÅcieÅ¼ka CAssetManager.basePath "{path}" jest nieprawidÅowa. Upewnij siÄ, Å¼e ten katalog istnieje i jest dostÄpny do zapisu dla procesu serwera.',
  'CCacheHttpSession.cacheID is invalid. Please make sure "{id}" refers to a valid cache application component.' => 'Identyfikator CCacheHttpSession.cacheID jest niepoprawny. Upewnij siÄ, Å¼e "{id}" odnosi siÄ do istniejÄcego komponentu buforujÄcego aplikacji.',
  'CCaptchaValidator.action "{id}" is invalid. Unable to find such an action in the current controller.' => 'Metoda CCaptchaValidator.action "{id}" jest nieprawidÅowa. Nie mogÄ znaleÅºÄ takiej metody w bieÅ¼Äcym kontrolerze.',
  'CDbAuthManager.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'Identyfikator CDbAuthManager.connectionID "{id}" jest niewÅaÅciwy. Upewnij siÄ, Å¼e odnosi siÄ do ID komponentu aplikacji CDbConnection.',
  'CDbCache.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'Identyfikator CDbCache.connectionID "{id}" jest nieprawidÅowy. Upewnij siÄ, Å¼e odnosi siÄ do ID komponentu aplikacji CDbConnection.',
  'CDbCacheDependency.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'DbCacheDependency.connectionID "{id}" jest nierpawidÅowy. Upewnij siÄ, Å¼e wskazuje na ID komponentu aplikacji CDbConnection.',
  'CDbCacheDependency.sql cannot be empty.' => 'WyraÅ¼enie CDbCacheDependency.sql nie moÅ¼e byÄ puste.',
  'CDbCommand failed to execute the SQL statement: {error}' => 'CDbCommand nie zdoÅaÅ wykonaÄ instrukcji SQL: {error}',
  'CDbCommand failed to prepare the SQL statement: {error}' => 'CDbCommand nie zdoÅaÅ przygotowaÄ instrukcji SQL: {error}',
  'CDbCommand::execute() failed: {error}. The SQL statement executed was: {sql}.' => 'WywoÅanie CDbCommand::execute() nie powiodÅo siÄ: {error}. Wykonywana instrukcja SQL to: {sql}.',
  'CDbCommand::{method}() failed: {error}. The SQL statement executed was: {sql}.' => 'WywoÅanie CDbCommand::{method}() nie powiodÅo siÄ: {error}. Wykonywana instrukcja SQL to: {sql}.',
  'CDbConnection does not support reading schema for {driver} database.' => 'CDbConnection nie wspiera odczytu schematu bazy danych {driver}.',
  'CDbConnection failed to open the DB connection.' => 'CDbConnection nie zdoÅaÅ otworzyÄ poÅÄczenia DB.',
  'CDbConnection failed to open the DB connection: {error}' => 'CDbConnection nie zdoÅaÅ otworzyÄ poÅÄczenia DB: {error}',
  'CDbConnection.connectionString cannot be empty.' => 'WyraÅ¼enie CDbConnection.connectionString nie moÅ¼e byÄ puste.',
  'CDbDataReader cannot rewind. It is a forward-only reader.' => 'CDbDataReader nie moÅ¼e przewijaÄ wstecz. Czyta tylko naprzÃ³d.',
  'CDbHttpSession.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'Identyfikator CDbHttpSession.connectionID "{id}" jest niepoprawny. Upewnij siÄ, Å¼e odnosi siÄ on do ID komponentu aplikacji CDbConnection.',
  'CDbLogRoute.connectionID "{id}" does not point to a valid CDbConnection application component.' => 'Identyfikator CDbLogRoute.connectionID "{id}" nie wskazuje na wÅaÅciwy komponent CDbConnection aplikacji.',
  'CDbMessageSource.connectionID is invalid. Please make sure "{id}" refers to a valid database application component.' => 'Identyfikator CDbMessageSource.connectionID jest nieprawidÅowy. Upewnij siÄ, Å¼e "{id}" odnosi siÄ do wÅaÅciwego komponentu bazodanowego aplikacji.',
  'CDbTestFixture.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbTestFixture.connectionID "{id}" jest nieprawdiÅowy. Uperwnij siÄ, Å¼e wskazuje on na ID komponentu aplikacji CDbConnection.',
  'CDbTransaction is inactive and cannot perform commit or roll back operations.' => 'CDbTransaction jest nieaktywny i nie moÅ¼e wykonaÄ poleceÅ COMMIT lub ROLLBACK.',
  'CDirectoryCacheDependency.directory cannot be empty.' => 'Katalog CDirectoryCacheDependency.directory nie moÅ¼e byÄ pusty.',
  'CEAcceleratorCache requires PHP eAccelerator extension to be loaded, enabled or compiled with the "--with-eaccelerator-shared-memory" option.' => 'CEAcceleratorCache wymaga zaÅadowanego, dostÄpnego lub skompilowanego z opcjÄ "--with-eaccelerator-shared-memory" rozszerzenia PHP eAccelerator',
  'CFileCacheDependency.fileName cannot be empty.' => 'Nazwa pliku CFileCacheDependency.fileName nie moÅ¼e byÄ pusta.',
  'CFileLogRoute.logPath "{path}" does not point to a valid directory. Make sure the directory exists and is writable by the Web server process.' => 'ÅcieÅ¼ka CFileLogRoute.logPath "{path}" nie wskazuje na wÅaÅciwy katalog. Upewnij siÄ, Å¼e ten katalog istnieje i jest dostÄpny do zapisu dla procesu serwera.',
  'CFilterChain can only take objects implementing the IFilter interface.' => 'CFilterChain moÅ¼e przyjmowaÄ tylko obiekty implementujÄce interfejs IFilter.',
  'CFlexWidget.baseUrl cannot be empty.' => 'Url CFlexWidget.baseUrl nie moÅ¼e byÄ pusty.',
  'CFlexWidget.name cannot be empty.' => 'Nazwa CFlexWidget.name nie moÅ¼e byÄ pusta.',
  'CGlobalStateCacheDependency.stateName cannot be empty.' => 'Nazwa stanu CGlobalStateCacheDependency.stateName nie moÅ¼e byÄ pusta.',
  'CHttpCookieCollection can only hold CHttpCookie objects.' => 'Kolekcja CHttpCookieCollection moÅ¼e przechowywaÄ tylko obiekty CHttpCookie.',
  'CHttpRequest is unable to determine the entry script URL.' => 'CHttpRequest nie moÅ¼e okreÅliÄ adresu URL skryptu wejÅciowego.',
  'CHttpRequest is unable to determine the path info of the request.' => 'CHttpRequest nie moÅ¼e okreÅliÄ ÅcieÅ¼ki Å¼Ädania.',
  'CHttpRequest is unable to determine the request URI.' => 'CHttpRequest nie moÅ¼e okreÅliÄ URI Å¼Ädania.',
  'CHttpSession.cookieMode can only be "none", "allow" or "only".' => 'CHttpSession.cookieMode moÅ¼e przyjmowaÄ tylko wartoÅci "none", "allow" lub "only".',
  'CHttpSession.gcProbability "{value}" is invalid. It must be an integer between 0 and 100.' => 'WartoÅÄ CHttpSession.gcProbability "{value}" jest nieprawidÅowa. Musi byÄ liczbÄ caÅkowitÄ z przedziaÅu 0 do 100.',
  'CHttpSession.savePath "{path}" is not a valid directory.' => 'ÅcieÅ¼ka CHttpSession.savePath "{path}" nie jest prawidÅowym katalogiem.',
  'CMemCache server configuration must be an array.' => 'Konfiguracja serwera CMemCache musi byÄ tablicÄ.',
  'CMemCache server configuration must have "host" value.' => 'Konfiguracja serwera CMemCache musi zawieraÄ wartoÅÄ "host".',
  'CProfileLogRoute found a mismatching code block "{token}". Make sure the calls to Yii::beginProfile() and Yii::endProfile() be properly nested.' => 'CProfileLogRoute natrafiÅ na bÅÄdny blok kodu "{token}". Upewnij siÄ, Å¼e wywoÅania Yii::beginProfile() i Yii::endProfile() sÄ poprawnie zagnieÅ¼dÅ¼one.',
  'CProfileLogRoute.report "{report}" is invalid. Valid values include "summary" and "callstack".' => 'WartoÅÄ CProfileLogRoute.report "{report}" jest nieprawidÅowa. WÅaÅciwe wartoÅci zawierajÄ "summary" i "callstack".',
  'CSecurityManager requires PHP mcrypt extension to be loaded in order to use data encryption feature.' => 'Do zaÅadowania CSecurityManager wymagane jest rozszerzenie PHP mcrypt .',
  'CSecurityManager.encryptionKey cannot be empty.' => 'Klucz CSecurityManager.encryptionKey nie moÅ¼e byÄ pusty.',
  'CSecurityManager.validationKey cannot be empty.' => 'Klucz CSecurityManager.validationKey nie moÅ¼e byÄ pusty.',
  'CTypedList<{type}> can only hold objects of {type} class.' => 'Lista CTypedList<{type}> moÅ¼e przechowywaÄ tylko obiekty klasy {type}.',
  'CTypedMap<{type}> can only hold objects of {type} class.' => 'Mapa CTypedMap<{type}> moÅ¼e posiadaÄ jedynie obiekty klasy {type}.',
  'CUrlManager.UrlFormat must be either "path" or "get".' => 'WartoÅÄ CUrlManager.UrlFormat musi zawieraÄ "path" lub "get".',
  'CWinCache requires PHP wincache extension to be loaded.' => 'CWinCache wymaga zaÅadowanego rozszerzenia PHP wincache.',
  'CWinCache user cache is disabled. Please set wincache.ucenabled to On in your php.ini.' => 'Bufor uÅ¼ytkownika CWinCache jest wyÅÄczony. Ustaw wincache.ucenabled na wartoÅÄ On w Twoim pliku php.ini.',
  'CXCache requires PHP XCache extension to be loaded.' => 'CXCache wymaga zaÅadowanego rozszerzenie PHP XCache.',
  'CZendDataCache requires PHP Zend Data Cache extension to be loaded.' => 'CZendDataCache wymaga zaÅadowanego rozszerzenia PHP Zend Data Cache.',
  'Cannot add "{child}" as a child of "{name}". A loop has been detected.' => 'Nie mogÄ dodaÄ "{child}" jako potomka "{name}". Wykryto zapÄtlenie.',
  'Cannot add "{child}" as a child of "{parent}". A loop has been detected.' => 'Nie mogÄ dodaÄ "{child}" jako potomka rodzica "{parent}". Wykryto zapÄtlenie.',
  'Cannot add "{name}" as a child of itself.' => 'Nie mogÄ dodaÄ "{name}" jako potomka samego siebie.',
  'Cannot add an item of type "{child}" to an item of type "{parent}".' => 'Nie mogÄ dodaÄ pozycji typu "{child}" do pozycji typu "{parent}".',
  'Column name must be either a string or an array.' => 'Nazwa kolumny musi byÄ stringiem lub tablicÄ.',
  'Dropping DB column is not supported by SQLite.' => 'Usuwanie kolumny bazy danych nie jest wspierane przez SQLite',
  'Dropping a foreign key constraint is not supported by SQLite.' => 'Usuwanie ograniczenia klucza obcego nie jest wpierane przez SQLite',
  'Either "{parent}" or "{child}" does not exist.' => 'ZarÃ³wno "{parent}" jak i "{child}" nie istniejÄ.',
  'Error: Table "{table}" does not have a primary key.' => 'BÅÄd: tabela "{table}" nie ma klucza gÅÃ³wnego.',
  'Error: Table "{table}" has a composite primary key which is not supported by crud command.' => 'BÅÄd: tabela "{table}" zawiera zÅoÅ¼ony klucz gÅÃ³wny, ktÃ³ry nie jest wspierany przez polecenie crud.',
  'Event "{class}.{event}" is attached with an invalid handler "{handler}".' => 'Zdarzenie "{class}.{event}" jest poÅÄczone z niewÅaÅciwym uchwytem "{handler}".',
  'Event "{class}.{event}" is not defined.' => 'Zdarzenie "{class}.{event}" nie jest zdefiniowane.',
  'Extension path "{path}" does not exist.' => 'ÅcieÅ¼ka rozszerzenia "{path}" nie istnieje.',
  'Failed to initialize the mcrypt module.' => 'Inicjalizacja moduÅu mcrypt nie powiodÅa siÄ.',
  'Failed to set unsafe attribute "{attribute}" of "{class}".' => 'Ustawianie niebezpiecznego (ang. unsafe) atrybutu "{attribute}" klasy "{class}" nie powiodÅo siÄ',
  'Failed to start session.' => 'Uruchamianie sesji nie powiodÅo siÄ',  
  'Failed to write the uploaded file "{file}" to disk.' => 'Zapis przesÅanego pliku "{file}" na dysk nie powiÃ³dÅ siÄ.',  
  'File upload was stopped by extension.' => 'PrzesyÅanie pliku zostaÅo zatrzymane przez rozszerzenie.',
  'Filter "{filter}" is invalid. Controller "{class}" does not have the filter method "filter{filter}".' => 'Filtr "{filter}" jest niepoprawny. Kontroler "{class}" nie posiada metody filtru "filter{filter}".',
  'GD and FreeType PHP extensions are required.' => 'Rozszerzenia GD oraz FreeType PHP sÄ wymagane.',
  'Get a new code' => 'Pobierz nowy kod',
  'Go to page: ' => 'PrzejdÅº do strony: ',
  'Invalid MO file revision: {revision}.' => 'NieprawidÅowa zmiana pliku MO: {revision}.',
  'Invalid MO file: {file} (magic: {magic}).' => 'NieprawidÅowy plik MO: {file} (liczba magiczna: {magic}).',
  'Invalid enumerable value "{value}". Please make sure it is among ({enum}).' => 'NieprawidÅowa wartoÅÄ typu wyliczeniowego "{value}". Upewnij siÄ, Å¼e jest wÅrÃ³d wartoÅci typu ({enum}).',
  'Invalid operator "{operator}".' => 'NieprawidÅowy operator "{operator}".',
  'Last &gt;&gt;' => 'Ostatnia &gt;&gt;',
  'List data must be an array or an object implementing Traversable.' => 'WartoÅÄ listy musi byÄ tablicÄ lub obiektem implementujÄcym interfejs Traversable.',
  'List index "{index}" is out of bound.' => 'Indeks listy "{index}" znajduje siÄ poza zakresem.',
  'Login Required' => 'Wymagane logowanie',
  'Map data must be an array or an object implementing Traversable.' => 'Dane mapy muszÄ byÄ tablicÄ lub obiektem implementujÄcym interfejs Traversable.',
  'Missing the temporary folder to store the uploaded file "{file}".' => 'Brak tymczasowego katalogu do zapisania wczytywanego pliku "{file}".',
  'Next &gt;' => 'NastÄpna&gt;',
  'No columns are being updated for table "{table}".' => 'Å»adna kolumna nie zostaÅa zaktualizowana w tabeli "{table}".',
  'No counter columns are being updated for table "{table}".' => 'Å»adna kolumna licznika nie zostaÅa zaktualizowana w tabeli "{table}".',
  'Object configuration must be an array containing a "class" element.' => 'Konfiguracja obiektu musi byÄ tablicÄ zawierajÄcÄ element "class".',
  'Please fix the following input errors:' => 'Popraw nastÄpujÄce bÅÄdy:',
  'Powered by {yii}.' => 'Powered by {yii}',  
  'Property "{class}.{property}" is not defined.' => 'WÅaÅciwoÅÄ "{class}.{property}" nie jest zdefiniowana.',
  'Property "{class}.{property}" is read only.' => 'WÅaÅciwoÅÄ "{class}.{property}" jest tylko do odczytu.',
  'Property CMaskedTextField.mask cannot be empty.' => 'WÅaÅciwoÅÄ CMaskedTextField.mask nie moÅ¼e byÄ pusta.',
  'Queue data must be an array or an object implementing Traversable.' => 'Dane kolejki muszÄ byÄ tablicÄ lub muszÄ byÄ obiektem implementujÄcym interfejs Traversable.',
  'Relation "{name}" is not defined in active record class "{class}".' => 'Relacja "{name}" nie jest zdefiniowana w klasie rekordu aktywnego "{class}".',
  'Renaming a DB column is not supported by SQLite.' => 'Zmiana nazwy kolumny bazy danych nie jest wspierana przez SQL.',
  'Stack data must be an array or an object implementing Traversable.' => 'Dane stosu muszÄ byÄ tablicÄ lub muszÄ byÄ obiektem implementujÄcym interfejs Traversable.',
  'Table "{table}" does not exist.' => 'Tabela "{table}" nie istnieje.',
  'Table "{table}" does not have a column named "{column}".' => 'Tabela "{table}" nie posiada kolumny o nazwie "{column}".',
  'The "db" application component must be configured to be a CDbConnection object.' => 'Komponent aplikacji "db" musi byÄ skonfigurowany jako obiekt CDbConnection',
  'The "filter" property must be specified with a valid callback.' => 'WÅaÅciwoÅÄ "filter" musi byÄ okreÅlona wraz z poprawnym odwoÅaniem.',
  'The "pattern" property must be specified with a valid regular expression.' => 'WÅaÅciwoÅÄ "pattern" musi byÄ okreÅlona z wÅaÅciwym wyraÅ¼eniem regularnym.',
  'The "range" property must be specified with a list of values.' => 'WÅaÅciowÅÄ "range" musi byÄ zdefiniowana jako lista wartoÅci.',
  'The CSRF token could not be verified.' => 'Å»eton CSRF nie mÃ³gÅ zostaÄ zweryfikowany.',
  'The DB query must contain the "from" portion.' => 'Zapytanie bazodanowe musi zawieraÄ czÄÅÄ "from".',
  'The STAT relation "{name}" cannot have child relations.' => 'Relacja statystyczna STAT "{name}" nie moÅ¼e posiadaÄ relacji potomnych.',
  'The URL pattern "{pattern}" for route "{route}" is not a valid regular expression.' => 'Wzorzec URL "{pattern}" dla trasy "{route}" nie jest poprawnym wyraÅ¼eniem regularnym.',
  'The active record cannot be deleted because it is new.' => 'BieÅ¼Äcy rekord nie moÅ¼e zostaÄ usuniÄty poniewaÅ¼ jest nowy.',
  'The active record cannot be inserted to database because it is not new.' => 'BieÅ¼Äcy rekord nie moÅ¼e zostaÄ wstawiony poniewaÅ¼ nie jest nowy.',
  'The active record cannot be updated because it is new.' => 'BieÅ¼Äcy rekord nie moÅ¼e zostaÄ zaktualizowany poniewaÅ¼ jest nowy.',
  'The asset "{asset}" to be published does not exist.' => 'ZasÃ³b "{asset}" przeznaczony do opublikowania nie istnieje.',
  'The command path "{path}" is not a valid directory.' => 'ÅcieÅ¼ka polecenia "{path}" nie jest wÅaÅciwym katalogiem.',
  'The controller path "{path}" is not a valid directory.' => 'ÅcieÅ¼ka kontrolera "{path}" nie jest wÅaÅciwym katalogiem.',
  'The file "{file}" cannot be uploaded. Only files with these extensions are allowed: {extensions}.' => 'Plik "{file}" nie moÅ¼e byÄ zaÅadowany. Dopuszczalne sÄ tylko pliki z nastÄpujÄcymi rozszerzeniami: {extensions}.',
  'The file "{file}" is too large. Its size cannot exceed {limit} bytes.' => 'Plik "{file}" jest zbyt wielki. Rozmiar nie moÅ¼e przekraczaÄ {limit} bajtÃ³w.',
  'The file "{file}" is too small. Its size cannot be smaller than {limit} bytes.' => 'Plik "{file}" jest zbyt maÅy. Rozmiar nie moÅ¼e byÄ mniejszy niÅ¼ {limit} bajtÃ³w.',
  'The file "{file}" was only partially uploaded.' => 'Plik "{file}" zostaÅ tylko czÄÅciowo przesÅany.',
  'The first element in a filter configuration must be the filter class.' => 'Pierwszy element konfiguracji filtra musi byÄ klasÄ filtra.',
  'The format of {attribute} is invalid.' => 'Format atrybutu {attribute} jest niepoprawny.',
  'The item "{name}" does not exist.' => 'Element "{name}" nie istnieje.',
  'The item "{parent}" already has a child "{child}".' => 'Element "{parent}" posiada juÅ¼ potomka "{child}".',
  'The layout path "{path}" is not a valid directory.' => 'ÅcieÅ¼ka ukÅadu "{path}" nie jest prawidÅowym katalogiem.',
  'The list is read only.' => 'TÄ listÄ moÅ¼na tylko odczytywaÄ.',
  'The map is read only.' => 'Te mapÄ moÅ¼na tylko odczytywaÄ.',
  'The module path "{path}" is not a valid directory.' => 'ÅcieÅ¼ka moduÅu "{path}" nie jest poprawnym katalogiem.',
  'The pattern for 12 hour format must be "h" or "hh".' => 'Wzorcem formatowania kodowania godzin dla doby 12 godzinnej jest "h" lub "hh".',
  'The pattern for 24 hour format must be "H" or "HH".' => 'Wzorcem formatowania kodowania godzin dla doby 24 godzinnej jest "H" lub "HH".',
  'The pattern for AM/PM marker must be "a".' => 'Wzorcem formatowania kodowania znacznika AM/PM jest "a".',
  'The pattern for day in month must be "F".' => 'Wzorcem formatowania dnia w miesiÄcu jest "F".',
  'The pattern for day in year must be "D", "DD" or "DDD".' => 'Wzorcem formatowania dnia w roku jest "D", "DD" lub "DDD".',
  'The pattern for day of the month must be "d" or "dd".' => 'Wzorcem formatowania dnia miesiÄca jest "d" lub "dd".',
  'The pattern for day of the week must be "E", "EE", "EEE", "EEEE", "EEEEE", "e", "ee", "eee", "eeee", "eeeee", "c", "cccc" or "ccccc".' => 'Wzorcem formatowania dnia tygodnia jest jeden z: "E", "EE", "EEE", "EEEE", "EEEEE", "e", "ee", "eee", "eeee", "eeeee", "c", "cccc" lub "ccccc".',
  'The pattern for era must be "G", "GG", "GGG", "GGGG" or "GGGGG".' => 'Wzorcem formatowania ery jest "G", "GG", "GGG", "GGGG" lub "GGGGG".',
  'The pattern for hour in AM/PM must be "K" or "KK".' => 'Wzorcem formatowania godziny przed- lub popoÅudniowej (AM/PM) jest "K" lub "KK".',
  'The pattern for hour in day must be "k" or "kk".' => 'Wzorcem formatowania godziny w ciÄgu dnia jest "k" or "kk".',
  'The pattern for minutes must be "m" or "mm".' => 'Wzorcem formatowania minut jest "m" lub "mm".',
  'The pattern for month must be "M", "MM", "MMM", "MMMM", "L", "LL", "LLL" or "LLLL".' => 'Wzorcem formatowania miesiÄca jest jeden z: "M", "MM", "MMM", "MMMM", "L", "LL", "LLL" lub "LLLL".',
  'The pattern for seconds must be "s" or "ss".' => 'Wzorcem formatowania sekund jest "s" lub "ss".',
  'The pattern for time zone must be "z" or "v".' => 'Wzorcem formatowania strefy czasowej jest "z" lub "v".',
  'The pattern for week in month must be "W".' => 'Wzorcem formatowania numeru tygodnia w miesiÄcu jest be "W".',
  'The pattern for week in year must be "w".' => 'Wzorcem formatowania numeru tygodnia w roku jest be "w".',
  'The queue is empty.' => 'Kolejka jest pusta.',
  'The relation "{relation}" in active record class "{class}" is not specified correctly. The join table "{joinTable}" given in the foreign key cannot be found in the database.' => 'Relacja "{relation}" w klasie rekordu aktywnego "{class}" jest zdefiniowana nieprawidÅowo. Tabeli doÅÄczanej "{joinTable}" zdefiniowanej w kluczu obcym nie moÅ¼na odnaleÅºÄ w bazie danych.',
  'The relation "{relation}" in active record class "{class}" is not specified correctly: the join table "{joinTable}" given in the foreign key cannot be found in the database.' => 'Relacja "{relation}" w klasie rekordu aktywnego "{class}" jest zdefiniowana nieprawidÅowo: w bazie danych nie moÅ¼na odnaleÅºÄ doÅÄczanej tabeli "{joinTable}" podanej w kluczu obcym.',
  'The relation "{relation}" in active record class "{class}" is specified with a foreign key "{key}" that does not point to the parent table "{table}".' => 'Relacja "{relation}" w klasie rekordu aktywnego "{class}" jest zdefiniowana z kluczem obcym "{key}", ktÃ³ry nie wskazuje na tabelÄ rodzica "{table}".',
  'The relation "{relation}" in active record class "{class}" is specified with an incomplete foreign key. The foreign key must consist of columns referencing both joining tables.' => 'Relacja "{relation}" w klasie rekordu aktywnego "{class}" jest opisana niekompletnym kluczem obcym. Klucz obcy musi skÅadaÄ siÄ z odpowiednich kolumn obu ÅÄczonych tabel.',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key "{key}". There is no such column in the table "{table}".' => 'Relacja "{relation}" w klasie rekordu aktywnego "{class}" jest zdefiniowana z nieprawidÅowym kluczem obcym"{key}". Nie istnieje taka kolumna w tabeli "{table}".',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key. The columns in the key must match the primary keys of the table "{table}".' => 'Relacja "{relation}" w klasie rekordu aktywnego "{class}" jest okreÅlona z nierpawidÅowym kluczem obcym. Kolumny w kluczu muszÄ zgadzaÄ siÄ z kluczami gÅÃ³wnymi tabeli "{table}".',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key. The format of the foreign key must be "joinTable(fk1,fk2,...)".' => 'Relacja "{relation}" klasie rekordu aktywnego "{class}" jest opisana nieprawidÅowym kluczem obcym. Format klucza obcego musi byÄ postaci "joinTable(fk1,fk2,...)".',
  'The requested view "{name}" was not found.' => 'Å»Ädany widok "{name}" nie zostaÅ znaleziony.',
  'The stack is empty.' => 'Stos jest pusty.',
  'The system is unable to find the requested action "{action}".' => 'System nie moÅ¼e odnaleÅºÄ Å¼Ädanej akcji "{action}".',
  'The system view path "{path}" is not a valid directory.' => 'ÅcieÅ¼ka widoku systemowego "{path}" nie jest prawidÅowym katalogiem.',
  'The table "{table}" for active record class "{class}" cannot be found in the database.' => 'Tabela "{table}" dla bieÅ¼Äcego rekordu klasy "{class}" nie zostaÅa znaleziona w bazie danych.',
  'The value for the column "{column}" is not supplied when querying the table "{table}".' => 'WartoÅÄ kolumny "{column}" nie zostaÅa dostarczona podczas wykonywania zapytania na tabeli "{table}".',
  'The verification code is incorrect.' => 'Wpisany kod weryfikujÄcy jest niepoprawny.',
  'The view path "{path}" is not a valid directory.' => 'ÅcieÅ¼ka widoku "{path}" nie jest poprawnym katalogiem.',
  'Theme directory "{directory}" does not exist.' => 'Katalog tematÃ³w "{directory}" nie istnieje.',
  'This content requires the <a href="http://www.adobe.com/go/getflash/">Adobe Flash Player</a>.' => 'Ta zawartoÅÄ wymaga zainstalowanego <a href="http://www.adobe.com/go/getflash/">Adobe Flash Player</a>.',
  'Unable to add an item whose name is the same as an existing item.' => 'Nie moÅ¼na dodaÄ elementu o nazwie identycznej z juÅ¼ istniejÄcym elementem.',
  'Unable to change the item name. The name "{name}" is already used by another item.' => 'Nie moÅ¼na zmieniÄ nazwy elementu. Nazwa "{name}" jest juÅ¼ uÅ¼ywana przez inny element.',
  'Unable to create application state file "{file}". Make sure the directory containing the file exists and is writable by the Web server process.' => 'Nie moÅ¼na utworzyÄ pliku stanu aplikacji "{file}". Upewnij siÄ, Å¼e katalog zawierajÄcy ten plik istnieje i jest dostÄpny do zapisu dla procesu serwera.',
  'Unable to find "{column}" in table "{table}".' => 'Nie moÅ¼na znaleÅºÄ kolumny "{column}" w tabeli "{table}"',
  'Unable to lock file "{file}" for reading.' => 'Nie moÅ¼na zablokowaÄ pliku "{file}" do odczytu.',
  'Unable to lock file "{file}" for writing.' => 'Nie moÅ¼na zablokowaÄ pliku "{file}" do zapisu.',
  'Unable to read file "{file}".' => 'Nie moÅ¼na czytaÄ pliku "{file}".',
  'Unable to replay the action "{object}.{method}". The method does not exist.' => 'Nie moÅ¼na ponowiÄ akcji "{object}.{method}". Ta metoda nie istnieje.',
  'Unable to resolve the request "{route}".' => 'Nie moÅ¼na ustaliÄ Å¼Ädania "{route}".',
  'Unable to write file "{file}".' => 'Nie moÅ¼na zapisaÄ do pliku "{file}".',
  'Unknown authorization item "{name}".' => 'Nieznany element autoryzacji "{name}".',
  'Unknown operator "{operator}".' => 'Nieznany operator "{operator}',
  'Unknown type "{type}".' => 'Nieznany typ "{type}".',
  'Unrecognized locale "{locale}".' => 'Nierozpoznana lokalizacja "{locale}".',
  'View file "{file}" does not exist.' => 'Plik widoku "{file}" nie istnieje.',
  'Yii application can only be created once.' => 'Aplikacja Yii moÅ¼e byÄ utworzona tyko raz.',
  'You are not authorized to perform this action.' => 'Nie jesteÅ upowaÅ¼niony do wykonania tej akcji.',
  'Your request is invalid.' => 'Twoje Å¼Ädanie jest nieprawidÅowe.',
  '{attribute} "{value}" has already been taken.' => '{attribute} "{value}" zostaÅ juÅ¼ wykorzystany.',
  '{attribute} "{value}" is invalid.' => 'WartoÅÄ "{value}" atrybutu {attribute} jest nieprawidÅowa.',
  '{attribute} cannot accept more than {limit} files.' => 'Atrybut {attribute} nie zezwala na wiÄcej niÅ¼ {limit} pliki(Ã³w).',
  '{attribute} cannot be blank.' => 'Pole {attribute} nie moÅ¼e byÄ puste.',
  '{attribute} is in the list.' => 'Atrybut {attribute} znajduje siÄ w liÅcie.',
  '{attribute} is invalid.' => 'ZawartoÅÄ pola {attribute} jest nieprawidÅowa.',
  '{attribute} is not a valid URL.' => 'ZawartoÅÄ pola {attribute} nie jest poprawnym adresem URL.',
  '{attribute} is not a valid email address.' => 'ZawartoÅÄ pola {attribute} nie jest poprawnym adresem e-mail.',
  '{attribute} is not in the list.' => '{attribute} nie wystÄpuje na tej liÅcie.',
  '{attribute} is of the wrong length (should be {length} characters).' => 'Pole {attribute} posiada niepoprawnÄ dÅugoÅÄ (powinno posiadaÄ {length} znakÃ³w).',
  '{attribute} is too big (maximum is {max}).' => 'WartoÅÄ w polu {attribute} jest za duÅ¼a (maksimum stanowi {max}).',
  '{attribute} is too long (maximum is {max} characters).' => 'WartoÅÄ w polu {attribute} jest za dÅuga (maksymalna liczba znakÃ³w to {max}).',
  '{attribute} is too short (minimum is {min} characters).' => 'WartoÅÄ w polu {attribute} jest za krÃ³tka (minimalna liczba znakÃ³w to {min}).',
  '{attribute} is too small (minimum is {min}).' => 'WartoÅÄ w polu {attribute} jest za maÅa (minimum stanowi {min}).',
  '{attribute} must be a number.' => 'ZawartoÅÄ pola {attribute} musi byÄ liczbÄ.',
  '{attribute} must be an integer.' => 'ZawartoÅÄ pola {attribute} musi byÄ liczbÄ caÅkowitÄ.',
  '{attribute} must be either {true} or {false}.' => 'Atrybut {attribute} musi posiadaÄ wartoÅÄ {true} lub {false}.',
  '{attribute} must be greater than "{compareValue}".' => 'Atrybut {attribute} musi byÄ wiÄkszy od "{compareValue}".',
  '{attribute} must be greater than or equal to "{compareValue}".' => 'Atrybut {attribute} musi byÄ wiÄkszy lub rÃ³wny "{compareValue}".',
  '{attribute} must be less than "{compareValue}".' => 'Atrybut {attribute} musi byÄ mniejszy od "{compareValue}".',
  '{attribute} must be less than or equal to "{compareValue}".' => 'Atrybut {attribute} musi byÄ mniejszy lub rÃ³wny "{compareValue}".',
  '{attribute} must be repeated exactly.' => 'Atrybut {attribute} musi byÄ dokÅadnie powtÃ³rzony.',
  '{attribute} must be {type}.' => 'ZawartoÅÄ pola {attribute} musi byÄ typu {type}.',
  '{attribute} must be {value}.' => 'Pole {attribute} musi posiadaÄ wartoÅÄ {value}.',
  '{attribute} must not be equal to "{compareValue}".' => 'Pole {attribute} nie moÅ¼e byÄ rÃ³wny "{compareValue}".',
  '{className} does not support add() functionality.' => 'Klasa {className} nie wspiera funkcjonalnoÅci add().',
  '{className} does not support delete() functionality.' => 'Klasa {className} nie wspiera funkcjonalnoÅci delete().',
  '{className} does not support flushValues() functionality.' => 'Klasa {className} nie wspiera funkcjonalnoÅci flushValues().',
  '{className} does not support get() functionality.' => 'Klasa {className} nie wspiera funkcjonalnoÅci get().',
  '{className} does not support set() functionality.' => 'Klasa {className} nie wspiera funkcjonalnoÅci set().',
  '{class} does not have relation "{name}".' => 'Klasa {class} nie posiada relacji o nazwie "{name}".',
  '{class} does not support fetching all table names.' => 'Klasa {class} nie wspiera pobierania wszystkich nazw tabeli.',
  '{class} has an invalid validation rule. The rule must specify attributes to be validated and the validator name.' => 'Klasa {class} ma niewÅaÅciwÄ reguÅÄ sprawdzania poprawnoÅci. ReguÅa musi okreÅlaÄ atrybuty, ktÃ³re majÄ zostaÄ zweryfikowane i nazwÄ walidatora.',
  '{class} must specify "model" and "attribute" or "name" property values.' => 'Klasa {class} musi okreÅlaÄ wartoÅci wÅaÅciwoÅci "model" i "attribute" lub "name".',
  '{class}.allowAutoLogin must be set true in order to use cookie-based authentication.' => 'Parametr {class}.allowAutoLogin musi byÄ ustawiony na true aby mÃ³c uÅ¼yÄ autoryzacji opartej o cookie.',
  '{class}::authenticate() must be implemented.' => 'Metoda {class}::authenticate() musi byÄ zaimplementowana.',
  '{controller} cannot find the requested view "{view}".' => 'Kontroler {controller} nie moÅ¼e znaleÅºÄ wymaganego widoku "{view}".',
  '{controller} contains improperly nested widget tags in its view "{view}". A {widget} widget does not have an endWidget() call.' => 'Kontroler {controller} zawiera niewÅaÅciwie zagnieÅ¼dÅ¼one tagi widgetÃ³w w swoim widoku "{view}". WidÅ¼et {widget} nie ma wywoÅania endWidget().',
  '{controller} has an extra endWidget({id}) call in its view.' => 'Kontroler {controller} ma dodatkowe wywoÅanie endWidget({id}) w swoim widoku.',
  '{widget} cannot find the view "{view}".' => 'WidÅ¼et {widget} nie moÅ¼e odnaleÅºÄ widoku "{view}".',
);
