<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Home' => 'Start',
  'The button type "{type}" is not supported.' => 'Typ przycisku "{type}" nie jest obsÅugiwany.',
  'Are you sure you want to delete this item?' => 'Czy na pewno usunÄÄ ten element?',
  'Delete' => 'UsuÅ',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'WyÅwietlono rezultaty {start}-{end} z {count}.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'W CDataColumn pole "name" lub "value" musi byÄ zadeklarowane.',
  'No results found.' => 'Nie znaleziono wynikÃ³w.',
  'Not set' => 'Nie ustawiony',
  'Please specify the "attributes" property.' => 'ProszÄ okreÅliÄ pole "attributes".',
  'Please specify the "data" property.' => 'ProszÄ okreÅliÄ pole "data".',
  'Sort by: ' => 'Sortuj wg:',
  'The "dataProvider" property cannot be empty.' => 'Pole "dataProvider" nie moÅ¼e byÄ puste.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Atrybut musi byÄ okreÅlony w formacie "Name:Type:Label", gdzie "Type" i "Label" sÄ opcjonalne.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Kolumna musi byÄ okreÅlona w formacie "Name:Type:Label", gdzie "Type" i "Label" sÄ opcjonalne.',
  'The property "itemView" cannot be empty.' => 'Pole "itemView" nie moÅ¼e byÄ puste.',
  'Total 1 result.|Total {count} results.' => 'Znaleziono {count} wynik(Ã³w)',
  'Update' => 'Aktualizuj',
  'View' => 'PodglÄd',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} musi okreÅlaÄ pola "model" i "attribute" lub "name".',
);
