<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Are you sure you want to delete this item?' => 'Báº¡n cÃ³ cháº¯c lÃ  muá»n xÃ³a?',
  'Either "name" or "value" must be specified for CDataColumn.' => '"name" hoáº·c "value" pháº£i ÄÆ°á»£c quy Äá»nh cho CDataColumn.',
  'Home' => 'Trang Chá»§',
  'Please specify the "data" property.' => 'HÃ£y chá» Äá»nh cho thuá»c tÃ­nh "data".',
  'The button type "{type}" is not supported.' => 'Loáº¡i button "{type}" khÃ´ng ÄÆ°á»£c há» trá»£.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Cá»t pháº£i ÄÆ°á»£c quy Äá»nh trong dáº¡ng "Name:Type:Label", vá»i "Type" vÃ  "Label" lÃ  tÃ¹y chá»n.',
  'Delete' => 'XÃ³a',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'Hiá»n thá» {start}-{end} cá»§a {count} káº¿t quáº£.',
  'No results found.' => 'KhÃ´ng cÃ³ dá»¯ liá»u.',
  'Not set' => 'ChÆ°a cÃ³ thÃ´ng tin',
  'Please specify the "attributes" property.' => 'Xin hÃ£y chá» rÃµ ná»i dung "attributes".',
  'Sort by: ' => 'Sáº¯p theo:',
  'The "dataProvider" property cannot be empty.' => '"dataProvider" khÃ´ng ÄÆ°á»£c phÃ©p rá»ng.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Thuá»c tÃ­nh pháº£i ÄÆ°á»£c Äá»nh nghÄ©a theo dáº¡ng "Name:Type:Label", vá»i "Type" vÃ  "Label" lÃ  tÃ¹y chá»n.',
  'The property "itemView" cannot be empty.' => 'Thuá»c tÃ­nh "itemView" khÃ´ng ÄÆ°á»£c phÃ©p rá»ng.',
  'Total 1 result.|Total {count} results.' => 'Táº¥t cáº£ {count} káº¿t quáº£',
  'Update' => 'Cáº­p nháº­t',
  'View' => 'Xem',
  '{class} must specify "model" and "attribute" or "name" property values.' => 'Lá»i {class} pháº£i xÃ¡c Äá»nh rÃµ giÃ¡ trá» "model" vÃ  "attribute" hoáº·c "name".',
);
