<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'The property filterSelector should be defined.' => 'Ð¡Ð²Ð¾Ð¹ÑÑÐ²Ð¾ filterSelector Ð´Ð¾Ð»Ð¶Ð½Ð¾ Ð±ÑÑÑ Ð¾Ð¿ÑÐµÐ´ÐµÐ»ÐµÐ½Ð¾.',
  'The property updateSelector should be defined.' => 'Ð¡Ð²Ð¾Ð¹ÑÑÐ²Ð¾ updateSelector Ð´Ð¾Ð»Ð¶Ð½Ð¾ Ð±ÑÑÑ Ð¾Ð¿ÑÐµÐ´ÐµÐ»ÐµÐ½Ð¾.',
  'Are you sure you want to delete this item?' => 'ÐÑ ÑÐ²ÐµÑÐµÐ½Ñ, ÑÑÐ¾ ÑÐ¾ÑÐ¸ÑÐµ ÑÐ´Ð°Ð»Ð¸ÑÑ Ð´Ð°Ð½Ð½ÑÐ¹ ÑÐ»ÐµÐ¼ÐµÐ½Ñ?',
  'Delete' => 'Ð£Ð´Ð°Ð»Ð¸ÑÑ',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'Ð­Ð»ÐµÐ¼ÐµÐ½ÑÑ {start}â{end} Ð¸Ð· {count}.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'ÐÐ»Ñ CDataColumn Ð½ÐµÐ¾Ð±ÑÐ¾Ð´Ð¸Ð¼Ð¾ ÑÐºÐ°Ð·Ð°ÑÑ "name" Ð¸Ð»Ð¸ "value".',
  'Home' => 'ÐÐ»Ð°Ð²Ð½Ð°Ñ',
  'No results found.' => 'ÐÐµÑ ÑÐµÐ·ÑÐ»ÑÑÐ°ÑÐ¾Ð².',
  'Not set' => 'ÐÐµ Ð·Ð°Ð´Ð°Ð½',
  'Please specify the "attributes" property.' => 'ÐÐ°Ð´Ð°Ð¹ÑÐµ ÑÐ²Ð¾Ð¹ÑÑÐ²Ð¾ "attributes".',
  'Please specify the "data" property.' => 'ÐÐ°Ð´Ð°Ð¹ÑÐµ ÑÐ²Ð¾Ð¹ÑÑÐ²Ð¾ "data".',
  'Sort by: ' => 'Ð¡Ð¾ÑÑÐ¸ÑÐ¾Ð²ÐºÐ°: ',
  'The "dataProvider" property cannot be empty.' => 'Ð¡Ð²Ð¾Ð¹ÑÑÐ²Ð¾ "dataProvider" Ð½Ðµ Ð¼Ð¾Ð¶ÐµÑ Ð±ÑÑÑ Ð¿ÑÑÑÑÐ¼.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'ÐÑÑÐ¸Ð±ÑÑ Ð´Ð¾Ð»Ð¶ÐµÐ½ Ð±ÑÑÑ ÑÐºÐ°Ð·Ð°Ð½ Ð² ÑÐ¾ÑÐ¼Ð°ÑÐµ "ÐÐ¼Ñ:Ð¢Ð¸Ð¿:ÐÐ°Ð³Ð¾Ð»Ð¾Ð²Ð¾Ðº". "Ð¢Ð¸Ð¿" Ð¸ "ÐÐ°Ð³Ð¾Ð»Ð¾Ð²Ð¾Ðº" Ð½Ðµ Ð¾Ð±ÑÐ·Ð°ÑÐµÐ»ÑÐ½Ñ.',
  'The button type "{type}" is not supported.' => 'Ð¢Ð¸Ð¿ ÐºÐ½Ð¾Ð¿ÐºÐ¸ "{type}" Ð½Ðµ Ð¿Ð¾Ð´Ð´ÐµÑÐ¶Ð¸Ð²Ð°ÐµÑÑÑ.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Ð¡ÑÐ¾Ð»Ð±ÐµÑ Ð´Ð¾Ð»Ð¶ÐµÐ½ Ð±ÑÑÑ ÑÐºÐ°Ð·Ð°Ð½ Ð² ÑÐ¾ÑÐ¼Ð°ÑÐµ "Name:Type:Label". "Ð¢Ð¸Ð¿" Ð¸ "ÐÐ°Ð³Ð¾Ð»Ð¾Ð²Ð¾Ðº" Ð½Ðµ Ð¾Ð±ÑÐ·Ð°ÑÐµÐ»ÑÐ½Ñ.',
  'The property "itemView" cannot be empty.' => 'Ð¡Ð²Ð¾Ð¹ÑÑÐ²Ð¾ "itemView" Ð½Ðµ Ð¼Ð¾Ð¶ÐµÑ Ð±ÑÑÑ Ð¿ÑÑÑÑÐ¼.',
  'Total 1 result.|Total {count} results.' => 'ÐÑÐµÐ³Ð¾ {count} ÑÐµÐ·ÑÐ»ÑÑÐ°Ñ.|ÐÑÐµÐ³Ð¾ {count} ÑÐµÐ·ÑÐ»ÑÑÐ°ÑÐ°.|{count} ÑÐµÐ·ÑÐ»ÑÑÐ°ÑÐ¾Ð².|{count} ÑÐµÐ·ÑÐ»ÑÑÐ°ÑÐ°.',
  'Update' => 'Ð ÐµÐ´Ð°ÐºÑÐ¸ÑÐ¾Ð²Ð°ÑÑ',
  'View' => 'ÐÑÐ¾ÑÐ¼Ð¾ÑÑÐµÑÑ',
  '{class} must specify "model" and "{attribute}" or "{name}" property values.' => 'Ð ÐºÐ»Ð°ÑÑÐµ {class} Ð´Ð¾Ð»Ð¶Ð½Ñ Ð±ÑÑÑ Ð·Ð°Ð´Ð°Ð½Ñ Ð·Ð½Ð°ÑÐµÐ½Ð¸Ñ ÑÐ²Ð¾Ð¹ÑÑÐ² "model" Ð¸ "{attribute}", Ð»Ð¸Ð±Ð¾ Ð·Ð½Ð°ÑÐµÐ½Ð¸Ðµ "{name}".',
);
