<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Are you sure you want to delete this item?' => 'BekrÃ¤fta att borttagning skall utfÃ¶ras',
  'Home' => 'Hem',
  'The button type "{type}" is not supported.' => 'Knapptypen "{type}" stÃ¶ds inte.',
  'Delete' => 'Ta bort',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'Visar {start}-{end} av totalt 1 post.|Visar {start}-{end} av totalt {count} poster.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'Antingen "name" eller "value" mÃ¥ste specificeras fÃ¶r CDataColumn.',
  'No results found.' => 'Inget hittades',
  'Not set' => 'Ej Ã¥satt',
  'Please specify the "attributes" property.' => 'Var god specificera propertyn "attributes".',
  'Please specify the "data" property.' => 'Var god specificera propertyn "data".',
  'Sort by: ' => 'Sorterat pÃ¥: ',
  'The "dataProvider" property cannot be empty.' => 'Propertyn "dataProvider" kan inte vara blank.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Attributet mÃ¥ste specificeras pÃ¥ formatet "Name:Type:Label", dÃ¤r "Type" och "Label" kan utelÃ¤mnas.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Kolumnen mÃ¥ste specificeras pÃ¥ formatet "Name:Type:Label", dÃ¤r "Type" och "Label" kan utelÃ¤mnas.',
  'The property "itemView" cannot be empty.' => 'Propertyn "itemView" kan inte vara blank.',
  'Total 1 result.|Total {count} results.' => 'Totalt 1 post.|Totalt {count} poster.',
  'Update' => 'Uppdatera',
  'View' => 'Visa',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} mÃ¥ste specificera propertyvÃ¤rden "model" och "attribute" eller "name".',
);
