<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '"{path}" is not a valid directory.' => '"{path}" ÙÙ Ø¯ÙÙÙ ØºÙØ± ØµØ§ÙØ­.',
  '&lt; Previous' => '&gt; Ø§ÙØ³Ø§Ø¨Ù',
  '&lt;&lt; First' => '&gt;&gt; Ø§ÙØ£ÙÙ',
  'A PHP extension stopped the file upload.' => 'ÙÙØ­Ù PHP ÙØ§Ù Ø¨Ø¥ÙÙØ§Ù ØªØ­ÙÙÙ Ø§ÙÙÙÙ.',
  'Action class {class} must implement the "run" method.' => 'ÙØ¦Ø© Ø§ÙØ¥Ø¬Ø±Ø§Ø¡ {class} ÙØ¬Ø¨ Ø£Ù ØªÙÙØ° Ø·Ø±ÙÙØ© "run".',
  'Active Record requires a "db" CDbConnection application component.' => 'Ø§ÙØ³Ø¬Ù Ø§ÙÙØ´Ø· ÙØªØ·ÙØ¨ ÙÙÙÙ ØªØ·Ø¨ÙÙ "db" CDbConnection.',
  'Active record "{class}" has an invalid configuration for relation "{relation}". It must specify the relation type, the related active record class and the foreign key.' => 'Ø§ÙØ³Ø¬Ù Ø§ÙÙØ´Ø· "{class}" ÙØ¯ÙÙ ØªÙÙÙÙ ØºÙØ± ØµØ§ÙØ­ ÙÙØ¹ÙØ§ÙØ© "{relation}". ÙØ¬Ø¨ Ø£Ù ÙØªÙ ØªØ­Ø¯ÙØ¯ ÙÙØ¹ Ø§ÙØ¹ÙØ§ÙØ©Ø ÙØ¦Ø© Ø§ÙØ³Ø¬Ù Ø§ÙÙØ´Ø· Ø°Ø§Øª Ø§ÙØ¹ÙØ§ÙØ© ÙØ§ÙÙÙØªØ§Ø­ Ø§ÙØ®Ø§Ø±Ø¬Ù.',
  'Active record "{class}" is trying to select an invalid column "{column}". Note, the column must exist in the table or be an expression with alias.' => 'Ø§ÙØ³Ø¬Ù Ø§ÙÙØ´Ø· "{class}" ÙÙÙÙ Ø¨ÙØ­Ø§ÙÙØ© Ø§Ø®ØªÙØ§Ø± Ø§ÙØ¹ÙÙØ¯ Ø§ÙØºÙØ± ØµØ§ÙØ­ "{column}". ÙÙØ§Ø­Ø¸Ø©Ø Ø§ÙØ¹ÙÙØ¯ ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ ÙÙØ¬ÙØ¯Ø§Ù ÙÙ ÙØ§Ø¹Ø¯Ø© Ø§ÙØ¨ÙØ§ÙØ§Øª Ø£Ù Ø£Ù ÙØªÙ Ø§ÙØªØ¹Ø¨ÙØ± Ø¹ÙÙ Ø¨Ø§Ø³Ù ÙØ³ØªØ¹Ø§Ø±.',
  'Adding a foreign key constraint to an existing table is not supported by SQLite.' => 'Ø¥Ø¶Ø§ÙØ© ÙÙØ¯ ÙÙØªØ§Ø­ Ø®Ø§Ø±Ø¬Ù Ø¥ÙÙ Ø¬Ø¯ÙÙ ÙÙØ¬ÙØ¯ ØºÙØ± ÙØ¯Ø¹Ù Ø¨ÙØ§Ø³Ø·Ø© SQLite.',
  'Adding a primary key after table has been created is not supported by SQLite.' => 'Ø¥Ø¶Ø§ÙØ© ÙÙØªØ§Ø­ Ø£Ø³Ø§Ø³Ù Ø¨Ø¹Ø¯ Ø£Ù ØªÙ Ø¥ÙØ´Ø§Ø¡ Ø§ÙØ¬Ø¯ÙÙ ØºÙØ± ÙØ¯Ø¹ÙÙ Ø¨ÙØ§Ø³Ø·Ø© SQLite.',
  'Alias "{alias}" is invalid. Make sure it points to an existing PHP file and the file is readable.' => 'Ø§ÙØ§Ø³Ù Ø§ÙÙØ³ØªØ¹Ø§Ø± "{alias}" ØºÙØ± ØµØ§ÙØ­. ØªØ£ÙØ¯ ÙÙ Ø£ÙÙ ÙØ´ÙØ± Ø¥ÙÙ ÙÙÙ PHP ÙÙØ¬ÙØ¯ ÙØ£Ù Ø§ÙÙÙÙ ÙÙÙÙ ÙØ±Ø§Ø¡ØªÙ.',
  'Alias "{alias}" is invalid. Make sure it points to an existing directory or file.' => 'Ø§ÙØ§Ø³Ù Ø§ÙÙØ³ØªØ¹Ø§Ø± "{alias}" ØºÙØ± ØµØ§ÙØ­. ØªØ£ÙØ¯ Ø£ÙÙ ÙØ´ÙØ± Ø¥ÙÙ Ø¯ÙÙÙ Ø£Ù ÙÙÙ ÙÙØ¬ÙØ¯.',
  'Altering a DB column is not supported by SQLite.' => 'ØªØºÙÙØ± Ø¹ÙÙØ¯ ÙÙ ÙØ§Ø¹Ø¯Ø© Ø§ÙØ¨ÙØ§ÙØ§Øª ØºÙØ± ÙØ¯Ø¹ÙÙ Ø¨ÙØ§Ø³Ø·Ø© SQLite.',
  'Application Log' => 'Ø³Ø¬Ù Ø§ÙØªØ·Ø¨ÙÙ',
  'Application base path "{path}" is not a valid directory.' => 'Ø§ÙÙØ³Ø§Ø± Ø§ÙØ£Ø³Ø§Ø³Ù ÙÙØªØ·Ø¨ÙÙ "{path}" ÙÙ Ø¯ÙÙÙ ØºÙØ± ØµØ§ÙØ­.',
  'Application runtime path "{path}" is not valid. Please make sure it is a directory writable by the Web server process.' => 'ÙØ³Ø§Ø± Ø²ÙÙ ØªØ´ØºÙÙ Ø§ÙØªØ·Ø¨ÙÙ "{path}" ØºÙØ± ØµØ§ÙØ­. Ø§ÙØ±Ø¬Ø§Ø¡ Ø§ÙØªØ£ÙØ¯ ÙÙ Ø£Ù Ø§ÙØ¯ÙÙÙ ÙÙØ¬ÙØ¯ ÙØ£ÙÙ ÙÙÙÙ Ø§ÙÙØªØ§Ø¨Ø© Ø¹ÙÙÙ Ø¨ÙØ§Ø³Ø·Ø© Ø¹ÙÙÙØ§Øª Ø§ÙÙÙØ¨ Ø§ÙØ®Ø§ØµØ© Ø¨Ø§ÙØ®Ø§Ø¯Ù.',
  'Authorization item "{item}" has already been assigned to user "{user}".' => 'Ø¹ÙØµØ± Ø§ÙØªÙÙÙØ¶ "{item}" ÙØ¯ ØªÙ Ø¨Ø§ÙÙØ¹Ù ØªØ¹ÙÙÙÙ ÙÙÙØ³ØªØ®Ø¯Ù "{user}".',
  'Base path "{path}" is not a valid directory.' => 'Ø§ÙÙØ³Ø§Ø± Ø§ÙØ£Ø³Ø§Ø³Ù "{path}" ÙÙ Ø¯ÙÙÙ ØºÙØ± ØµØ§ÙØ­.',
  'CApcCache requires PHP apc extension to be loaded.' => 'CApcCache ÙØªØ·ÙØ¨ ÙÙØ­Ù PHP apc Ø£Ù ÙÙÙÙ ÙØ¯ ØªÙ ØªØ­ÙÙÙÙ.',
  'CAssetManager.basePath "{path}" is invalid. Please make sure the directory exists and is writable by the Web server process.' => 'Ø§ÙÙØ³Ø§Ø± "{path}" Ø§ÙØ®Ø§Øµ Ø¨Ù CAssetManager.basePath ØºÙØ± ØµØ§ÙØ­. Ø§ÙØ±Ø¬Ø§Ø¡ Ø§ÙØªØ£ÙØ¯ ÙÙ Ø£Ù Ø§ÙØ¯ÙÙÙ ÙÙØ¬ÙØ¯ ÙØ£ÙÙ ÙÙÙÙ Ø§ÙÙØªØ§Ø¨Ø© Ø¹ÙÙÙ Ø¨ÙØ§Ø³Ø·Ø© Ø¹ÙÙÙØ§Øª Ø§ÙÙÙØ¨ Ø§ÙØ®Ø§ØµØ© Ø¨Ø§ÙØ®Ø§Ø¯Ù.',
  'CCacheHttpSession.cacheID is invalid. Please make sure "{id}" refers to a valid cache application component.' => 'CCacheHttpSession.cacheID ØºÙØ± ØµØ§ÙØ­. Ø§ÙØ±Ø¬Ø§Ø¡ Ø§ÙØªØ£ÙØ¯ ÙÙ Ø£Ù "{id}" ÙØ´ÙØ± Ø¥ÙÙ ÙÙÙÙ ØªØ·Ø¨ÙÙ ÙØ§Ø¹Ø¯Ø© Ø¨ÙØ§ÙØ§Øª ØµØ§ÙØ­.',
  'CCaptchaValidator.action "{id}" is invalid. Unable to find such an action in the current controller.' => 'Ø§ÙÙØ¹Ø±Ù "{id}" Ø§ÙØ®Ø§Øµ Ø¨Ù CCaptchaValidator.action ØºÙØ± ØµØ§ÙØ­. ØºÙØ± ÙØ§Ø¯Ø± Ø¹ÙÙ Ø§ÙØ¹Ø«ÙØ± Ø¹ÙÙ Ø¥Ø¬Ø±Ø§Ø¡ ÙÙØ§Ø«Ù ÙÙ Ø§ÙÙØªØ­ÙÙ Ø§ÙØ­Ø§ÙÙ.',
  'CDbAuthManager.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'Ø§ÙÙØ¹Ø±Ù "{id}" Ø§ÙØ®Ø§Øµ Ø¨Ù CDbAuthManager.connectionID ØºÙØ± ØµØ§ÙØ­. ØºÙØ± ØµØ§ÙØ­. Ø§ÙØ±Ø¬Ø§Ø¡ Ø§ÙØªØ£ÙØ¯ ÙÙ Ø£ÙÙ ÙØ´ÙØ± Ø¥ÙÙ ÙÙÙÙ ØªØ·Ø¨ÙÙ CDbConnection ØµØ§ÙØ­.',
  'CDbCache.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'Ø§ÙÙØ¹Ø±Ù "{id}" Ø§ÙØ®Ø§Øµ Ø¨Ù CDbCache.connectionID ØºÙØ± ØµØ§ÙØ­. Ø§ÙØ±Ø¬Ø§Ø¡ Ø§ÙØªØ£ÙØ¯ ÙÙ Ø£ÙÙ ÙØ´ÙØ± Ø¥ÙÙ ÙÙÙÙ ØªØ·Ø¨ÙÙ CDbConnection ØµØ§ÙØ­.',
  'CDbCacheDependency.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'Ø§ÙÙØ¹Ø±Ù "{id}" Ø§ÙØ®Ø§Øµ Ø¨Ù CDbCacheDependency.connectionID ØºÙØ± ØµØ§ÙØ­. Ø§ÙØ±Ø¬Ø§Ø¡ Ø§ÙØªØ£ÙØ¯ ÙÙ Ø£ÙÙ ÙØ´ÙØ± Ø¥ÙÙ ÙÙÙÙ ØªØ·Ø¨ÙÙ CDbConnection ØµØ§ÙØ­.',
  'CDbCacheDependency.sql cannot be empty.' => 'CDbCacheDependency.sql ÙØ§ ÙÙÙÙ Ø£Ù ÙÙÙÙ ÙØ§Ø±ØºØ§Ù.',
  'CDbCommand failed to execute the SQL statement: {error}' => 'CDbCommand ÙØ´Ù ÙÙ ØªÙÙÙØ° Ø¨ÙØ§Ù SQL: {error}',
  'CDbCommand failed to prepare the SQL statement: {error}' => 'CDbCommand ÙØ´Ù ÙÙ ØªØ­Ø¶ÙØ± Ø¨ÙØ§Ù SQL: {error}',
  'CDbCommand::execute() failed: {error}. The SQL statement executed was: {sql}.' => 'CDbCommand::execute() ÙØ´Ù: {error}. Ø¨ÙØ§Ù SQL Ø§ÙÙÙÙØ° ÙØ§Ù: {sql}.',
  'CDbCommand::{method}() failed: {error}. The SQL statement executed was: {sql}.' => 'CDbCommand::{method}() ÙØ´Ù: {error}. Ø¨ÙØ§Ù SQL Ø§ÙÙÙÙØ° ÙØ§Ù: {sql}.',
  'CDbConnection does not support reading schema for {driver} database.' => 'CDbConnection ÙØ§ ÙØ¯Ø¹Ù ÙØ±Ø§Ø¡Ø© ÙØ®Ø·Ø· ÙØ§Ø¹Ø¯Ø© Ø§ÙØ¨ÙØ§ÙØ§Øª {driver}.',
  'CDbConnection failed to open the DB connection.' => 'CDbConnection ÙØ´Ù ÙÙ ÙØªØ­ Ø§ØªØµØ§Ù ÙØ¹ ÙØ§Ø¹Ø¯Ø© Ø§ÙØ¨ÙØ§ÙØ§Øª.',
  'CDbConnection is unable to find PDO class "{className}". Make sure PDO is installed correctly.' => 'CDbConnection ØºÙØ± ÙØ§Ø¯Ø± Ø¹ÙÙ Ø§ÙØ¹Ø«ÙØ± Ø¹ÙÙ ÙØ¦Ø© PDO "{className}". ØªØ£ÙØ¯ Ø£Ù PDO ÙØ¯ ØªÙ ØªÙØµÙØ¨Ù Ø¨Ø´ÙÙ ØµØ­ÙØ­.',
  'CDbDataReader cannot rewind. It is a forward-only reader.' => 'CDbDataReader ÙØ§ ÙÙÙÙ ÙÙÙ ÙÙØ®ÙÙ. Ø¥ÙÙ ÙØ§Ø±Ø¦ ÙÙØ£ÙØ§Ù ÙÙØ·.',
  'CDbHttpSession.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'Ø§ÙÙØ¹Ø±Ù "{id}" Ø§ÙØ®Ø§Øµ Ø¨Ù CDbHttpSession.connectionID ØºÙØ± ØµØ§ÙØ­. Ø§ÙØ±Ø¬Ø§Ø¡ Ø§ÙØªØ£ÙØ¯ ÙÙ Ø£ÙÙ ÙØ´ÙØ± Ø¥ÙÙ ÙØ¹Ø±Ù ÙÙÙÙ ØªØ·Ø¨ÙÙ CDbConnection.',
  'CDbLogRoute.connectionID "{id}" does not point to a valid CDbConnection application component.' => 'Ø§ÙÙØ¹Ø±Ù "{id}" Ø§ÙØ®Ø§Øµ Ø¨Ù CDbLogRoute.connectionID ÙØ§ ÙØ´ÙØ± Ø¥ÙÙ ÙÙÙÙ ØªØ·Ø¨ÙÙ CDbConnection ØµØ§ÙØ­.',
  'CDbMessageSource.connectionID is invalid. Please make sure "{id}" refers to a valid database application component.' => 'CDbMessageSource.connectionID ØºÙØ± ØµØ§ÙØ­. Ø§ÙØ±Ø¬Ø§Ø¡ Ø§ÙØªØ£ÙØ¯ ÙÙ Ø£Ù "{id}" ÙØ´ÙØ± Ø¥ÙÙ ÙÙÙÙ ØªØ·Ø¨ÙÙ ÙØ§Ø¹Ø¯Ø© Ø¨ÙØ§ÙØ§Øª ØµØ§ÙØ­.',
  'CDbTestFixture.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'Ø§ÙÙØ¹Ø±Ù "{id}" Ø§ÙØ®Ø§Øµ Ø¨Ù CDbTestFixture.connectionID ØºÙØ± ØµØ§ÙØ­. Ø§ÙØ±Ø¬Ø§Ø¡ Ø§ÙØªØ£ÙØ¯ ÙÙ Ø£ÙÙ ÙØ´ÙØ± Ø¥ÙÙ ÙÙÙÙ ØªØ·Ø¨ÙÙ CDbConnection ØµØ§ÙØ­.',
  'CDbTransaction is inactive and cannot perform commit or roll back operations.' => 'CDbTransaction ØºÙØ± ÙØ´Ø· ÙÙØ§ ÙÙÙÙ ØªÙÙÙØ° Ø¹ÙÙÙØ§Øª commit Ø£Ù roll back.',
  'CDirectoryCacheDependency.directory cannot be empty.' => 'CDirectoryCacheDependency.directory ÙØ§ ÙÙÙÙ Ø£Ù ÙÙÙÙ ÙØ§Ø±ØºØ§Ù.',
  'CEAcceleratorCache requires PHP eAccelerator extension to be loaded, enabled or compiled with the "--with-eaccelerator-shared-memory" option.' => 'CEAcceleratorCache ÙØªØ·ÙØ¨ ÙÙØ­Ù PHP eAccelerator Ø£Ù ÙÙÙÙ ÙØ¯ ØªÙ ØªØ­ÙÙÙÙØ ØªÙÙÙÙÙ Ø£Ù ØªØ±Ø¬ÙØªÙ Ø¨Ø±ÙØ¬ÙØ§Ù ÙØ¹ Ø®ÙØ§Ø± "--with-eaccelerator-shared-memory".',
  'CFileCacheDependency.fileName cannot be empty.' => 'CFileCacheDependency.fileName ÙØ§ ÙÙÙÙ Ø£Ù ÙÙÙÙ ÙØ§Ø±ØºØ§Ù.',
  'CFileLogRoute.logPath "{path}" does not point to a valid directory. Make sure the directory exists and is writable by the Web server process.' => 'Ø§ÙÙØ³Ø§Ø± "{path}" CFileLogRoute.logPath ÙØ§ ÙØ´ÙØ± Ø¥ÙÙ Ø¯ÙÙÙ ØµØ§ÙØ­. ØªØ£ÙØ¯ Ø£Ù Ø§ÙØ¯ÙÙÙ ÙÙØ¬ÙØ¯ ÙØ£ÙÙ ÙÙÙÙ Ø§ÙÙØªØ§Ø¨Ø© Ø¹ÙÙÙ Ø¨ÙØ§Ø³Ø·Ø© Ø¹ÙÙÙØ§Øª Ø§ÙÙÙØ¨ Ø§ÙØ®Ø§ØµØ© Ø¨Ø§ÙØ®Ø§Ø¯Ù.',
  'CFilterChain can only take objects implementing the IFilter interface.' => 'CFilterChain ÙÙÙÙ ÙÙØ· Ø£Ù ÙØ£Ø®Ø° Ø§ÙÙÙØ§Ø¦Ù Ø§ÙØªÙ ØªÙÙØ° ÙØ§Ø¬ÙØ© IFilter.',
  'CFlexWidget.baseUrl cannot be empty.' => 'CFlexWidget.baseUrl ÙØ§ ÙÙÙÙ Ø£Ù ÙÙÙÙ ÙØ§Ø±ØºØ§Ù.',
  'CFlexWidget.name cannot be empty.' => 'CFlexWidget.name ÙØ§ ÙÙÙÙ Ø£Ù ÙÙÙÙ ÙØ§Ø±ØºØ§Ù.',
  'CGlobalStateCacheDependency.stateName cannot be empty.' => 'CGlobalStateCacheDependency.stateName ÙØ§ ÙÙÙÙ Ø£Ù ÙÙÙÙ ÙØ§Ø±ØºØ§Ù.',
  'CHttpCacheFilter.lastModified contained a value that could not be understood by strtotime()' => 'CHttpCacheFilter.lastModified ÙØ­ØªÙÙ Ø¹ÙÙ ÙÙÙØ© ÙØªØ¹Ø°Ø± ÙÙÙØ§ Ø¨ÙØ§Ø³Ø·Ø© strtotime()',
  'CHttpCookieCollection can only hold CHttpCookie objects.' => 'CHttpCookieCollection ÙÙÙÙÙ ÙÙØ· Ø§ÙØ§Ø­ØªÙØ§Ø¸ Ø¨ÙÙØ§Ø¦Ù CHttpCookie.',
  'CHttpRequest is unable to determine the entry script URL.' => 'CHttpRequest ØºÙØ± ÙØ§Ø¯Ø± Ø¹ÙÙ ØªØ­Ø¯ÙØ¯ Ø¹ÙÙØ§Ù URL ÙØ³ÙØ±ÙØ¨Øª Ø§ÙØ¥Ø¯Ø®Ø§Ù.',
  'CHttpRequest is unable to determine the path info of the request.' => 'CHttpRequest ØºÙØ± ÙØ§Ø¯Ø± Ø¹ÙÙ ØªØ­Ø¯ÙØ¯ ÙØ¹ÙÙÙØ§Øª ÙØ³Ø§Ø± Ø§ÙØ·ÙØ¨.',
  'CHttpRequest is unable to determine the request URI.' => 'CHttpRequest ØºÙØ± ÙØ§Ø¯Ø± Ø¹ÙÙ ØªØ­Ø¯ÙØ¯ ÙØ¹Ø±Ù URI Ø§ÙÙØ·ÙÙØ¨.',
  'CHttpSession.cookieMode can only be "none", "allow" or "only".' => 'CHttpSession.cookieMode ÙÙÙÙÙ ÙÙØ· Ø£Ù ÙÙÙÙ "none"Ø "allow" Ø£Ù "only".',
  'CHttpSession.gcProbability "{value}" is invalid. It must be a float between 0 and 100.' => 'Ø§ÙÙÙÙØ© "{value}" Ø§ÙØ®Ø§ØµØ© Ø¨Ù CHttpSession.gcProbability ØºÙØ± ØµØ§ÙØ­Ø©. ÙØ¬Ø¨ Ø£Ù ØªÙÙÙ Ø±ÙÙØ§Ù Ø¨ÙÙ 0 Ù 100.',
  'CHttpSession.savePath "{path}" is not a valid directory.' => 'CHttpSession.savePath "{path}" ÙÙ Ø¯ÙÙÙ ØºÙØ± ØµØ§ÙØ­.',
  'CMemCache requires PHP {extension} extension to be loaded.' => 'CMemCache ÙØªØ·ÙØ¨ ÙÙØ­Ù PHP {extension} Ø£Ù ÙÙÙÙ ÙØ¯ ØªÙ ØªØ­ÙÙÙÙ.',
  'CMemCache server configuration must be an array.' => 'ØªÙÙÙÙ Ø§ÙØ®Ø§Ø¯Ù Ø§ÙØ®Ø§Øµ Ø¨Ù CMemCache ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ ÙØµÙÙÙØ©.',
  'CMemCache server configuration must have "host" value.' => 'ØªÙÙÙÙ Ø§ÙØ®Ø§Ø¯Ù Ø§ÙØ®Ø§Øµ Ø¨Ù CMemCache ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ ÙØ¯ÙÙ ÙÙÙØ© "host".',
  'CProfileLogRoute found a mismatching code block "{token}". Make sure the calls to Yii::beginProfile() and Yii::endProfile() be properly nested.' => 'CProfileLogRoute Ø¹Ø«Ø± Ø¹ÙÙ Ø§ÙÙØªÙØ© Ø§ÙØ¨Ø±ÙØ¬ÙØ© "{token}" Ø§ÙØºÙØ± ÙØ·Ø§Ø¨ÙØ©. ØªØ£ÙØ¯ ÙÙ Ø£Ù Ø§ÙÙØ¯Ø§Ø¡Ø§Øª Ø¥ÙÙ Yii::beginProfile() Ù Yii::endProfile() ÙØªØ¯Ø§Ø®ÙØ© Ø¨Ø´ÙÙ ØµØ­ÙØ­.',
  'CProfileLogRoute.report "{report}" is invalid. Valid values include "summary" and "callstack".' => 'Ø§ÙØªÙØ±ÙØ± "{report}" Ø§ÙØ®Ø§Øµ Ø¨Ù CProfileLogRoute.report ØºÙØ± ØµØ§ÙØ­. Ø§ÙÙÙÙ Ø§ÙØµØ§ÙØ­Ø© ØªØ´ÙÙ "summary" Ù "callstack".',
  'CSecurityManager requires PHP mcrypt extension to be loaded in order to use data encryption feature.' => 'CSecurityManager ÙØªØ·ÙØ¨ ÙÙØ­Ù PHP mcrypt Ø£Ù ÙÙÙÙ ÙØ¯ ØªÙ ØªØ­ÙÙÙÙ ÙÙ Ø£Ø¬Ù Ø§Ø³ØªØ®Ø¯Ø§Ù ÙÙØ²Ø© ØªØ´ÙÙØ± Ø§ÙØ¨ÙØ§ÙØ§Øª.',
  'CSecurityManager.encryptionKey cannot be empty.' => 'CSecurityManager.encryptionKey ÙØ§ ÙÙÙÙ Ø£Ù ÙÙÙÙ ÙØ§Ø±ØºØ§Ù.',
  'CSecurityManager.validationKey cannot be empty.' => 'CSecurityManager.validationKey ÙØ§ ÙÙÙÙ Ø£Ù ÙÙÙÙ ÙØ§Ø±ØºØ§Ù.',
  'CSecurityManager::generateRandomString() cannot generate random string in the current environment.' => 'CSecurityManager::generateRandomString() ÙØ§ ÙÙÙÙÙ ØªÙÙÙØ¯ Ø³ÙØ³ÙØ© ÙØ­Ø§Ø±Ù Ø¹Ø´ÙØ§Ø¦ÙØ© ÙÙ Ø§ÙØ¨ÙØ¦Ø© Ø§ÙØ­Ø§ÙÙØ©.',
  'CTypedList<{type}> can only hold objects of {type} class.' => 'CTypedList<{type}> ÙÙÙÙÙ ÙÙØ· Ø§ÙØ§Ø­ØªÙØ§Ø¸ Ø¨ÙÙØ§Ø¦Ù Ø§ÙÙØ¦Ø© Ø°Ø§Øª Ø§ÙÙÙØ¹ {type}.',
  'CTypedMap<{type}> can only hold objects of {type} class.' => 'CTypedMap<{type}> ÙÙÙÙÙ ÙÙØ· Ø§ÙØ§Ø­ØªÙØ§Ø¸ Ø¨ÙÙØ§Ø¦Ù Ø§ÙÙØ¦Ø© Ø°Ø§Øª Ø§ÙÙÙØ¹ {type}.',
  'CUrlManager.UrlFormat must be either "path" or "get".' => 'CUrlManager.UrlFormat ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ Ø¥ÙØ§ "path" Ø£Ù "get".',
  'CWinCache requires PHP wincache extension to be loaded.' => 'CWinCache ÙØªØ·ÙØ¨ ÙÙØ­Ù PHP wincache Ø£Ù ÙÙÙÙ ÙØ¯ ØªÙ ØªØ­ÙÙÙÙ.',
  'CWinCache user cache is disabled. Please set wincache.ucenabled to On in your php.ini.' => 'CWinCache Ø§ÙÙØ§Ø´ Ø§ÙØ®Ø§Øµ Ø¨Ø§ÙÙØ³ØªØ®Ø¯Ù ÙØ¹Ø·Ù. Ø§ÙØ±Ø¬Ø§Ø¡ Ø¥Ø¹Ø¯Ø§Ø¯ wincache.ucenabled ÙÙÙÙÙ ÙÙ ÙØ¶Ø¹ Ø§ÙØªØ´ØºÙÙ ÙÙ ÙÙÙ php.ini.',
  'CXCache requires PHP XCache extension to be loaded.' => 'CXCache ÙØªØ·ÙØ¨ ÙÙØ­Ù PHP XCache Ø£Ù ÙÙÙÙ ÙØ¯ ØªÙ ØªØ­ÙÙÙÙ.',
  'CZendDataCache requires PHP Zend Data Cache extension to be loaded.' => 'CZendDataCache ÙØªØ·ÙØ¨ ÙÙØ­Ù PHP Zend Data Cache Ø£Ù ÙÙÙÙ ÙØ¯ ØªÙ ØªØ­ÙÙÙÙ.',
  'Cannot add "{child}" as a child of "{name}". A loop has been detected.' => 'ÙØ§ ÙÙÙÙ Ø¥Ø¶Ø§ÙØ© "{child}" ÙØªØ§Ø¨Ø¹ ÙÙ "{name}". ØªÙ Ø§ÙÙØ´Ù Ø¹Ù Ø­ÙÙØ©.',
  'Cannot add "{child}" as a child of "{parent}". A loop has been detected.' => 'ÙØ§ ÙÙÙÙ Ø¥Ø¶Ø§ÙØ© "{child}" ÙØªØ§Ø¨Ø¹ ÙÙ "{parent}". ØªÙ Ø§ÙÙØ´Ù Ø¹Ù Ø­ÙÙØ©.',
  'Cannot add "{name}" as a child of itself.' => 'ÙØ§ ÙÙÙÙ Ø¥Ø¶Ø§ÙØ© "{name}" ÙØªØ§Ø¨Ø¹ ÙÙÙØ³Ù.',
  'Cannot add an item of type "{child}" to an item of type "{parent}".' => 'ÙØ§ ÙÙÙÙ Ø¥Ø¶Ø§ÙØ© Ø¹ÙØµØ± ÙÙ Ø§ÙÙÙØ¹ "{child}" ÙØ¹ÙØµØ± ÙÙ Ø§ÙÙÙØ¹ "{parent}".',
  'Class name "{class}" does not match class file "{file}".' => 'Ø§Ø³Ù Ø§ÙÙØ¦Ø© "{class}" ÙØ§ ÙØªØ·Ø§Ø¨Ù ÙØ¹ ÙÙÙ Ø§ÙÙØ¦Ø© "{file}".',
  'Column name must be either a string or an array.' => 'Ø§Ø³Ù Ø§ÙØ¹ÙÙØ¯ ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ Ø¥ÙØ§ Ø³ÙØ³ÙØ© Ø£Ù ÙØµÙÙÙØ©.',
  'Dropping DB column is not supported by SQLite.' => 'Ø¥Ø³ÙØ§Ø· Ø¹ÙÙØ¯ ÙÙ ÙØ§Ø¹Ø¯Ø© Ø§ÙØ¨ÙØ§ÙØ§Øª ÙÙ ØºÙØ± ÙØ¯Ø¹ÙÙ Ø¨ÙØ§Ø³Ø·Ø© SQLite.',
  'Dropping a foreign key constraint is not supported by SQLite.' => 'Ø¥Ø³ÙØ§Ø· ÙÙØ¯ ÙÙØªØ§Ø­ Ø®Ø§Ø±Ø¬Ù ÙÙ ØºÙØ± ÙØ¯Ø¹ÙÙ Ø¨ÙØ§Ø³Ø·Ø© by SQLite.',
  'Either "{parent}" or "{child}" does not exist.' => 'Ø¥ÙØ§ "{parent}" Ø£Ù "{child}" ØºÙØ± ÙÙØ¬ÙØ¯.',
  'Error: Table "{table}" does not have a primary key.' => 'Ø®Ø·Ø£: Ø§ÙØ¬Ø¯ÙÙ "{table}" ÙØ§ ÙØ­ØªÙÙ Ø¹ÙÙ ÙÙØªØ§Ø­ Ø£Ø³Ø§Ø³Ù.',
  'Error: Table "{table}" has a composite primary key which is not supported by crud command.' => 'Ø®Ø·Ø£: Ø§ÙØ¬Ø¯ÙÙ "{table}" ÙØ¯ÙÙ ÙÙØªØ§Ø­ Ø£Ø³Ø§Ø³Ù ÙØ±ÙØ¨ ÙÙÙ ØºÙØ± ÙØ¯Ø¹ÙÙ Ø¨ÙØ§Ø³Ø·Ø© Ø£ÙØ± crud.',
  'Event "{class}.{event}" is attached with an invalid handler "{handler}".' => 'Ø§ÙØ­Ø¯Ø« "{class}.{event}" ÙØ±ÙÙ ÙØ¹ Ø§ÙÙØ§Ø¨Ø¶ Ø§ÙØºÙØ± ØµØ§ÙØ­ "{handler}".',
  'Event "{class}.{event}" is not defined.' => 'Ø§ÙØ­Ø¯Ø« "{class}.{event}" ØºÙØ± ÙØ¹Ø±Ù.',
  'Extension path "{path}" does not exist.' => 'ÙØ³Ø§Ø± Ø§ÙÙÙØ­Ù "{path}" ØºÙØ± ÙÙØ¬ÙØ¯.',
  'Failed to initialize the mcrypt module.' => 'ÙØ´Ù ÙÙ Ø¨Ø¯Ø¡ Ø§ÙÙÙÙÙ mcrypt.',
  'Failed to set unsafe attribute "{attribute}" of "{class}".' => 'ÙØ´Ù ÙÙ Ø¥Ø¹Ø¯Ø§Ø¯ Ø§ÙØ³ÙØ© Ø§ÙØºÙØ± Ø¢ÙÙØ© "{attribute}" ÙÙ "{class}".',
  'Failed to start session.' => 'ÙØ´Ù ÙÙ Ø¨Ø¯Ø¡ Ø§ÙØ¬ÙØ³Ø©.',
  'Failed to write the uploaded file "{file}" to disk.' => 'ÙØ´Ù ÙÙ ÙØªØ§Ø¨Ø© Ø§ÙÙÙÙ Ø§ÙØ°Ù ØªÙ ØªØ­ÙÙÙÙ "{file}" Ø¥ÙÙ Ø§ÙÙØ±Øµ.',
  'Filter "{filter}" is invalid. Controller "{class}" does not have the filter method "filter{filter}".' => 'Ø§ÙÙØ±Ø´Ø­ "{filter}" ØºÙØ± ØµØ§ÙØ­. Ø§ÙÙØªØ­ÙÙ "{class}" ÙØ§ ÙØ­ØªÙÙ Ø·Ø±ÙÙØ© Ø§ÙÙØ±Ø´Ø­ "filter{filter}".',
  'GD with FreeType or ImageMagick PHP extensions are required.' => 'ÙÙØ­ÙØ§Øª PHP Ø§ÙÙØ³ÙØ§Ø© GD ÙØ¹ FreeType Ø£Ù ImageMagick ÙØ·ÙÙØ¨Ø©.',
  'Get a new code' => 'Get a new code',
  'Go to page: ' => 'Go to page: ',
  'In order to use MIME-type validation provided by CFileValidator fileinfo PECL extension should be installed.' => 'ÙÙ Ø£Ø¬Ù Ø£Ù ØªØ³ØªØ®Ø¯Ù ØªØ£ÙÙØ¯ MIME-type Ø§ÙÙÙØ¯Ù Ø¨ÙØ§Ø³Ø·Ø© CFileValidator ÙÙØ­Ù fileinfo PECL ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ ÙÙØµØ¨Ø§Ù.',
  'Internal error while generating hash.' => 'Ø®Ø·Ø£ Ø¯Ø§Ø®ÙÙ Ø£Ø«ÙØ§Ø¡ ØªÙÙÙØ¯ Ø§ÙØªÙØ´ÙØ±.',
  'Invalid MO file revision: {revision}.' => 'Ø¥ØµØ¯Ø§Ø± ØºÙØ± ØµØ§ÙØ­ ÙÙÙÙ MO: {revision}.',
  'Invalid MO file: {file} (magic: {magic}).' => 'ÙÙÙ MO ØºÙØ± ØµØ§ÙØ­: {file} (magic: {magic}).',
  'Invalid enumerable value "{value}". Please make sure it is among ({enum}).' => 'Ø§ÙÙÙÙØ© Ø§ÙÙØ§Ø¨ÙØ© ÙÙØ¹Ø¯ "{value}" ØºÙØ± ØµØ§ÙØ­Ø©. Ø§ÙØ±Ø¬Ø§Ø¡ Ø§ÙØªØ£ÙØ¯ ÙÙ Ø£ÙÙØ§ Ø¶ÙÙ ({enum}).',
  'Invalid expression for CHttpCacheFilter.lastModifiedExpression: The evaluation result "{value}" could not be understood by strtotime()' => 'ØªØ¹Ø¨ÙØ± ØºÙØ± ØµØ§ÙØ­ ÙÙ CHttpCacheFilter.lastModifiedExpression: Ø§ÙÙØªÙØ¬Ø© Ø§ÙØªÙÙÙÙÙØ© "{value}" ØªØ¹Ø°Ø± ÙÙÙÙØ§ Ø¨ÙØ§Ø³Ø·Ø© strtotime()',
  'Invalid operator "{operator}".' => '"{operator}" ÙØ´ØºÙ ØºÙØ± ØµØ§ÙØ­.',
  'Last &gt;&gt;' => '&lt;&lt; Ø§ÙØ£Ø®ÙØ±',
  'List data must be an array or an object implementing Traversable.' => 'Ø¨ÙØ§ÙØ§Øª Ø§ÙÙØ§Ø¦ÙØ© ÙØ¬Ø¨ Ø£Ù ØªÙÙÙ ÙØµÙÙÙØ© Ø£Ù ÙØ§Ø¦Ù Ø¹Ø¨Ø± ØªÙÙÙØ° Traversable.',
  'List index "{index}" is out of bound.' => 'ÙØ¤Ø´Ø± Ø§ÙÙØ§Ø¦ÙØ© "{index}" ÙÙ Ø®Ø§Ø±Ø¬ Ø§ÙÙØ·Ø§Ù.',
  'Login Required' => 'ØªØ³Ø¬ÙÙ Ø§ÙØ¯Ø®ÙÙ ÙØ·ÙÙØ¨',
  'Map data must be an array or an object implementing Traversable.' => 'Ø¨ÙØ§ÙØ§Øª Ø§ÙØ®Ø±ÙØ·Ø© ÙØ¬Ø¨ Ø£Ù ØªÙÙÙ ÙØµÙÙÙØ© Ø£Ù ÙØ§Ø¦Ù Ø¹Ø¨Ø± ØªÙÙÙØ° Traversable.',
  'Missing the temporary folder to store the uploaded file "{file}".' => 'ÙÙ ÙØªÙ Ø§ÙØ¹Ø«ÙØ± Ø¹Ù Ø§ÙÙØ¬ÙØ¯ Ø§ÙÙØ¤ÙØª ÙØªØ®Ø²ÙÙ Ø§ÙÙÙÙ Ø§ÙØ°Ù ØªÙ ØªØ­ÙÙÙÙ "{file}".',
  'Next &gt;' => '&lt; Ø§ÙØªØ§ÙÙ',
  'No' => 'ÙØ§',
  'No columns are being updated for table "{table}".' => 'ÙØ§ ÙØªÙ Ø­Ø§ÙÙØ§Ù ØªØ­Ø¯ÙØ« Ø£Ù Ø£Ø¹ÙØ¯Ø© ÙÙØ¬Ø¯ÙÙ "{table}".',
  'No counter columns are being updated for table "{table}".' => 'ÙØ§ ÙØªÙ Ø­Ø§ÙÙØ§Ù ØªØ­Ø¯ÙØ« Ø²Ù Ø£Ø¹ÙØ¯Ø© ÙØ¶Ø§Ø¯Ø© ÙÙØ¬Ø¯ÙÙ "{table}".',
  'Object configuration must be an array containing a "class" element.' => 'ØªÙÙÙÙ Ø§ÙÙØ§Ø¦Ù ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ Ø¹Ø¨Ø§Ø±Ø© Ø¹Ù ÙØµÙÙÙØ© ØªØ­ØªÙÙ Ø§ÙØ¹ÙØµØ± "class".',
  'Only SHA1 and MD5 hashing algorithms are supported when using PHP 5.1.1 or below.' => 'ÙÙØ· ÙÙØºØ§Ø±ÙØªÙÙØ§Øª Ø§ÙØªÙØ´ÙØ± SHA1 Ù MD5 ØªÙÙÙ ÙØ¯Ø¹ÙÙØ© Ø¹ÙØ¯ Ø§Ø³ØªØ®Ø¯Ø§Ù PHP 5.1.1 Ø£Ù Ø£ÙÙ.',
  'Please fix the following input errors:' => 'Ø§ÙØ±Ø¬Ø§Ø¡ Ø¥ØµÙØ§Ø­ Ø£Ø®Ø·Ø§Ø¡ Ø§ÙØ¥Ø¯Ø®Ø§Ù Ø§ÙØªØ§ÙÙØ©:',
  'Powered by {yii}.' => 'ÙØ´ØºÙ Ø¨ÙØ§Ø³Ø·Ø© {yii}.',
  'Property "{class}.{property}" is not defined.' => 'Ø§ÙØ®Ø§ØµÙØ© "{class}.{property}" ØºÙØ± ÙØ¹Ø±ÙØ©.',
  'Property "{class}.{property}" is read only.' => 'Ø§ÙØ®Ø§ØµÙØ© "{class}.{property}" ÙÙÙØ±Ø§Ø¡Ø© ÙÙØ·.',
  'Property CMaskedTextField.mask cannot be empty.' => 'Ø§ÙØ®Ø§ØµÙØ© CMaskedTextField.mask ÙØ§ ÙÙÙÙ Ø£Ù ØªÙÙÙ ÙØ§Ø±ØºØ©.',
  'Queue data must be an array or an object implementing Traversable.' => 'Ø¨ÙØ§ÙØ§Øª Ø§ÙØ§ÙØªØ¸Ø§Ø± ÙØ¬Ø¨ Ø£Ù ØªÙÙÙ ÙØµÙÙÙØ© Ø£Ù ÙØ§Ø¦Ù Ø¹Ø¨Ø± ØªÙÙÙØ° Traversable.',
  'Relation "{name}" is not defined in active record class "{class}".' => 'Ø§ÙØ¹ÙØ§ÙØ© "{name}" ØºÙØ± ÙØ¹Ø±ÙØ© ÙÙ ÙØ¦Ø© Ø§ÙØ³Ø¬Ù Ø§ÙÙØ´Ø· "{class}".',
  'Removing a primary key after table has been created is not supported by SQLite.' => 'Ø­Ø°Ù ÙÙØªØ§Ø­ Ø£Ø³Ø§Ø³Ù Ø¨Ø¹Ø¯ Ø£Ù ØªÙ Ø¥ÙØ´Ø§Ø¡ Ø§ÙØ¬Ø¯ÙÙ ØºØ¨Ø± ÙØ¯Ø¹ÙÙ Ø¨ÙØ§Ø³Ø·Ø© SQLite.',
  'Renaming a DB column is not supported by SQLite.' => 'Ø¥Ø¹Ø§Ø¯Ø© ØªØ³ÙÙØ© Ø¹ÙÙØ¯ ÙÙ ÙØ§Ø¹Ø¯Ø© Ø§ÙØ¨ÙØ§ÙØ§Øª ØºÙØ± ÙØ¯Ø¹ÙÙ Ø¨ÙØ§Ø³Ø·Ø© SQLite.',
  'Script HTML options are not allowed for "CClientScript::POS_LOAD" and "CClientScript::POS_READY".' => 'Ø®ÙØ§Ø±Ø§Øª Ø³ÙØ±ÙØ¨Øª HTML ØºÙØ± ÙØ³ÙÙØ­ Ø¨ÙØ§ ÙÙ "CClientScript::POS_LOAD" Ù "CClientScript::POS_READY".',
  'Stack data must be an array or an object implementing Traversable.' => 'Ø¨ÙØ§ÙØ§Øª Ø§ÙØ±ØµÙ ÙØ¬Ø¨ Ø£Ù ØªÙÙÙ ÙØµÙÙÙØ© Ø£Ù ÙØ§Ø¦Ù Ø¹Ø¨Ø± ØªÙÙÙØ° Traversable.',
  'Table "{table}" does not exist.' => 'Ø§ÙØ¬Ø¯ÙÙ "{table}" ØºÙØ± ÙÙØ¬ÙØ¯',
  'Table "{table}" does not have a column named "{column}".' => 'Ø§ÙØ¬Ø¯ÙÙ "{table}" ÙØ§ ÙØ­ØªÙÙ Ø¹ÙÙ Ø¹ÙÙØ¯ Ø¨Ø§ÙØ§Ø³Ù "{column}".',
  'The "db" application component must be configured to be a CDbConnection object.' => 'ÙÙÙÙ Ø§ÙØªØ·Ø¨ÙÙ "db" ÙØ¬Ø¨ Ø£Ù ÙØªÙ ØªÙÙÙÙÙ ÙÙÙÙÙ ÙØ§Ø¦Ù CDbConnection.',
  'The "filter" property must be specified with a valid callback.' => 'Ø®Ø§ØµÙØ© "filter" ÙØ¬Ø¨ Ø£Ù ØªÙÙÙ ÙØ­Ø¯Ø¯Ø© Ø¨Ø±Ø¯ ÙØ¯Ø§Ø¡ ØµØ§ÙØ­.',
  'The "forceCopy" and "linkAssets" cannot be both true.' => 'ÙØ§ ÙÙÙÙ ÙÙÙ ÙÙ "forceCopy" Ù "linkAssets" Ø£Ù ÙÙÙÙØ§ Ø°Ø§Øª ÙÙÙØ© ØµÙØ§Ø¨.',
  'The "pattern" property must be specified with a valid regular expression.' => 'Ø®Ø§ØµÙØ© "pattern" ÙØ¬Ø¨ Ø£Ù ØªÙÙÙ ÙØ­Ø¯Ø¯Ø© Ø¨ØªØ¹Ø¨ÙØ± ÙÙØ·Ù ØµØ§ÙØ­.',
  'The "range" property must be specified with a list of values.' => 'Ø®Ø§ØµÙØ© "range" ÙØ¬Ø¨ Ø£Ù ØªÙÙÙ ÙØ­Ø¯Ø¯Ø© Ø¨ÙØ§Ø¦ÙØ© ÙÙ Ø§ÙÙÙÙ.',
  'The $converter argument must be a valid callback or null.' => 'Ø§ÙÙØ¹Ø·Ù $converter ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ Ø±Ø¯ ÙØ¯Ø§Ø¡ ØµØ§ÙØ­ Ø£Ù ÙØ§Ø±Øº.',
  'The CSRF token could not be verified.' => 'ØªØ¹Ø°Ø± Ø§ÙØªØ£ÙØ¯ ÙÙ ØµØ­Ø© Ø±ÙØ² CSRF.',
  'The STAT relation "{name}" cannot have child relations.' => 'Ø¹ÙØ§ÙØ© STAT "{name}" ÙØ§ ÙÙÙÙ Ø£Ù ØªØ­ØªÙÙ Ø¹ÙØ§ÙØ§Øª ØªØ§Ø¨Ø¹Ø©.',
  'The URL pattern "{pattern}" for route "{route}" is not a valid regular expression.' => 'ÙÙØ· URL "{pattern}" ÙÙÙØ³Ø§Ø± "{route}" ÙÙ ØªØ¹Ø¨ÙØ± ÙÙØ·Ù ØºÙØ± ØµØ§ÙØ­.',
  'The active record cannot be deleted because it is new.' => 'ÙØ§ ÙÙÙÙ Ø­Ø°Ù Ø§ÙØ³Ø¬Ù Ø§ÙÙØ´Ø· ÙØ£ÙÙ Ø¬Ø¯ÙØ¯.',
  'The active record cannot be inserted to database because it is not new.' => 'ÙØ§ ÙÙÙÙ Ø¥Ø¯Ø±Ø§Ø¬ Ø§ÙØ³Ø¬Ù Ø§ÙÙØ´Ø· ÙÙ ÙØ§Ø¹Ø¯Ø© Ø§ÙØ¨ÙØ§ÙØ§Øª ÙØ£ÙÙ ÙÙØ³ Ø¨Ø¬Ø¯ÙØ¯.',
  'The active record cannot be updated because it is new.' => 'ÙØ§ ÙÙÙÙ ØªØ­Ø¯ÙØ« Ø§ÙØ³Ø¬Ù Ø§ÙÙØ´Ø· ÙØ£ÙÙ Ø¬Ø¯ÙØ¯.',
  'The asset "{asset}" to be published does not exist.' => 'Ø§ÙØ£ØµÙ "{asset}" Ø§ÙÙØ±Ø§Ø¯ ÙØ´Ø±Ù ØºÙØ± ÙÙØ¬ÙØ¯.',
  'The command path "{path}" is not a valid directory.' => 'ÙØ³Ø§Ø± Ø§ÙØ£ÙØ± "{path}" ÙÙ Ø¯ÙÙÙ ØºÙØ± ØµØ§ÙØ­.',
  'The controller path "{path}" is not a valid directory.' => 'ÙØ³Ø§Ø± Ø§ÙÙØªØ­ÙÙ "{path}" ÙÙ Ø¯ÙÙÙ ØºÙØ± ØµØ§ÙØ­.',
  'The file "{file}" cannot be uploaded. Only files of these MIME-types are allowed: {mimeTypes}.' => 'Ø§ÙÙÙÙ "{file}" ÙØ§ ÙÙÙÙ ØªØ­ÙÙÙÙ. ÙÙØ· ÙØ³ÙÙØ­ Ø¨Ø§ÙÙÙÙØ§Øª Ø°Ø§Øª Ø§ÙØ£ÙÙØ§Ø¹ Ø§ÙØªØ§ÙÙØ©: {mimeTypes}.',
  'The file "{file}" cannot be uploaded. Only files with these extensions are allowed: {extensions}.' => 'Ø§ÙÙÙÙ "{file}" ÙØ§ ÙÙÙÙ ØªØ­ÙÙÙÙ. ÙÙØ· ÙØ³ÙÙØ­ Ø¨Ø§ÙÙÙÙØ§Øª Ø°Ø§Øª Ø§ÙØ§ÙØªØ¯Ø§Ø¯Ø§Øª Ø§ÙØªØ§ÙÙØ©: {extensions}.',
  'The file "{file}" is too large. Its size cannot exceed {limit} bytes.' => 'Ø§ÙÙÙÙ "{file}" ÙØ¨ÙØ± Ø¬Ø¯Ø§Ù. ÙØ§ ÙÙÙÙ ÙØ­Ø¬Ù Ø§ÙÙÙÙ Ø£Ù ÙØªØ¬Ø§ÙØ² {limit} Ø¨Ø§ÙØª.',
  'The file "{file}" is too small. Its size cannot be smaller than {limit} bytes.' => 'Ø§ÙÙÙÙ "{file}" ØµØºÙØ± Ø¬Ø¯Ø§Ù. ÙØ§ ÙÙÙÙ ÙØ­Ø¬Ù Ø§ÙÙÙÙ Ø£Ù ÙÙÙÙ Ø£ØµØºØ± ÙÙ {limit} Ø¨Ø§ÙØª.',
  'The file "{file}" was only partially uploaded.' => 'Ø§ÙÙÙÙ "{file}" ØªÙ ØªØ­ÙÙÙ Ø¬Ø²Ø¡ ÙÙÙ ÙÙØ·.',
  'The first element in a filter configuration must be the filter class.' => 'Ø§ÙØ¹ÙØµØ± Ø§ÙØ£ÙÙ ÙÙ ØªÙÙÙÙ Ø£Ù ÙØ±Ø´Ø­ ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ ÙØ¦Ø© Ø§ÙÙØ±Ø´Ø­.',
  'The format of {attribute} is invalid.' => 'ØªÙØ³ÙÙ {attribute} ØºÙØ± ØµØ§ÙØ­.',
  'The item "{name}" does not exist.' => 'Ø§ÙØ¹ÙØµØ± "{name}" ØºÙØ± ÙÙØ¬ÙØ¯.',
  'The item "{parent}" already has a child "{child}".' => 'Ø§ÙØ¹ÙØµØ± "{parent}" ÙØ¯ÙÙ Ø¨Ø§ÙÙØ¹Ù ØªØ§Ø¨Ø¹ "{child}".',
  'The layout path "{path}" is not a valid directory.' => 'ÙØ³Ø§Ø± Ø§ÙÙØ®Ø·Ø· "{path}" ÙÙ Ø¯ÙÙÙ ØºÙØ± ØµØ§ÙØ­.',
  'The list is read only.' => 'Ø§ÙÙØ§Ø¦ÙØ© ÙÙÙØ±Ø§Ø¡ ÙÙØ·.',
  'The map is read only.' => 'Ø§ÙØ®Ø±ÙØ·Ø© ÙÙÙØ±Ø§Ø¡Ø© ÙÙØ·.',
  'The module path "{path}" is not a valid directory.' => 'ÙØ³Ø§Ø± Ø§ÙÙØ­Ø¯Ø© "{path}" ÙÙ Ø¯ÙÙÙ ØºÙØ± ØµØ§ÙØ­.',
  'The pattern for 12 hour format must be "h" or "hh".' => 'Ø§ÙÙÙØ· ÙØªÙØ³ÙÙ 12 Ø³Ø§Ø¹Ø© ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ "h" Ø£Ù "hh".',
  'The pattern for 24 hour format must be "H" or "HH".' => 'Ø§ÙÙÙØ· ÙØªÙØ³ÙÙ 24 Ø³Ø§Ø¹Ø© ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ "H" Ø£Ù "HH".',
  'The pattern for AM/PM marker must be "a".' => 'Ø§ÙÙÙØ· ÙØ¹ÙØ§ÙØ© Øµ/Ù ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ "a".',
  'The pattern for day in month must be "F".' => 'Ø§ÙÙÙØ· ÙÙÙÙÙ ÙÙ Ø§ÙØ´ÙØ± ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ "F".',
  'The pattern for day in year must be "D", "DD" or "DDD".' => 'Ø§ÙÙÙØ· ÙÙÙÙÙ ÙÙ Ø§ÙØ³ÙØ© ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ "D", "DD" or "DDD".',
  'The pattern for day of the month must be "d" or "dd".' => 'Ø§ÙÙÙØ· ÙÙÙÙ Ø§ÙØ´ÙØ± ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ "d" Ø£Ù "dd".',
  'The pattern for day of the week must be "E", "EE", "EEE", "EEEE", "EEEEE", "e", "ee", "eee", "eeee", "eeeee", "c", "cccc" or "ccccc".' => 'Ø§ÙÙÙØ· ÙÙÙÙ Ø§ÙØ£Ø³Ø¨ÙØ¹ ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ "E"Ø "EE"Ø "EEE"Ø "EEEE"Ø "EEEEE"Ø "e"Ø "ee"Ø "eee"Ø "eeee"Ø "eeeee"Ø "c"Ø "cccc" Ø£Ù "ccccc".',
  'The pattern for era must be "G", "GG", "GGG", "GGGG" or "GGGGG".' => 'Ø§ÙÙÙØ· ÙÙØ¹ØµØ± ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ "G"Ø "GG"Ø "GGG"Ø "GGGG" Ø£Ù "GGGGG".',
  'The pattern for hour in AM/PM must be "K" or "KK".' => 'Ø§ÙÙÙØ· ÙÙØ³Ø§Ø¹Ø© ÙÙ Øµ/Ù ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ "K" Ø£Ù "KK".',
  'The pattern for hour in day must be "k" or "kk".' => 'Ø§ÙÙÙØ· ÙÙØ³Ø§Ø¹Ø© ÙÙ Ø§ÙÙÙÙ ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ "k" Ø£Ù "kk".',
  'The pattern for minutes must be "m" or "mm".' => 'Ø§ÙÙÙØ· ÙÙØ¯ÙØ§Ø¦Ù ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ "m" Ø£Ù "mm".',
  'The pattern for month must be "M", "MM", "MMM", "MMMM", "L", "LL", "LLL" or "LLLL".' => 'Ø§ÙÙÙØ· ÙÙØ´ÙØ± ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ "M"Ø "MM"Ø "MMM"Ø "MMMM"Ø "L"Ø "LL"Ø "LLL" Ø£Ù "LLLL".',
  'The pattern for seconds must be "s" or "ss".' => 'Ø§ÙÙÙØ· ÙÙØ«ÙØ§ÙÙ ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ "s" Ø£Ù "ss".',
  'The pattern for time zone must be "z" or "v".' => 'Ø§ÙÙÙØ· ÙÙÙÙØ·ÙØ© Ø§ÙØ²ÙÙÙØ© ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ "z" Ø£Ù "v".',
  'The pattern for week in month must be "W".' => 'Ø§ÙÙÙØ· ÙÙØ£Ø³Ø¨ÙØ¹ ÙÙ Ø§ÙØ´ÙØ± ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ "W".',
  'The pattern for week in year must be "w".' => 'Ø§ÙÙÙØ· ÙÙØ£Ø³Ø¨ÙØ¹ ÙÙ Ø§ÙØ³ÙØ© ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ "w".',
  'The queue is empty.' => 'Ø§ÙØµÙ ÙØ§Ø±Øº.',
  'The relation "{relation}" in active record class "{class}" is not specified correctly. The join table "{joinTable}" given in the foreign key cannot be found in the database.' => 'Ø§ÙØ¹ÙØ§ÙØ© "{relation}" ÙÙ ÙØ¦Ø© Ø§ÙØ³Ø¬Ù Ø§ÙÙØ´Ø· "{class}" ØºÙØ± ÙØ­Ø¯Ø¯Ø© Ø¨Ø´ÙÙ ØµØ­ÙØ­. Ø¬Ø¯ÙÙ Ø§ÙØµÙØ© "{joinTable}" Ø§ÙÙØ¹Ø·Ù ÙÙ Ø§ÙÙÙØªØ§Ø­ Ø§ÙØ®Ø§Ø±Ø¬Ù ÙØ§ ÙÙÙÙ Ø§ÙØ¹Ø«ÙØ± Ø¹ÙÙÙ ÙÙ ÙØ§Ø¹Ø¯Ø© Ø§ÙØ¨ÙØ§ÙØ§Øª.',
  'The relation "{relation}" in active record class "{class}" is not specified correctly: the join table "{joinTable}" given in the foreign key cannot be found in the database.' => 'Ø§ÙØ¹ÙØ§ÙØ© "{relation}" ÙÙ ÙØ¦Ø© Ø§ÙØ³Ø¬Ù Ø§ÙÙØ´Ø· "{class}" ØºÙØ± ÙØ­Ø¯Ø¯Ø© Ø¨Ø´ÙÙ ØµØ­ÙØ­: Ø¬Ø¯ÙÙ Ø§ÙØµÙØ© "{joinTable}" Ø§ÙÙØ¹Ø·Ù ÙÙ Ø§ÙÙÙØªØ§Ø­ Ø§ÙØ®Ø§Ø±Ø¬Ù ÙØ§ ÙÙÙÙ Ø§ÙØ¹Ø«ÙØ± Ø¹ÙÙÙ ÙÙ ÙØ§Ø¹Ø¯Ø© Ø§ÙØ¨ÙØ§ÙØ§Øª.',
  'The relation "{relation}" in active record class "{class}" is specified with a foreign key "{key}" that does not point to the parent table "{table}".' => 'Ø§ÙØ¹ÙØ§ÙØ© "{relation}" ÙÙ ÙØ¦Ø© Ø§ÙØ³Ø¬Ù Ø§ÙÙØ´Ø· "{class}" ÙØ­Ø¯Ø¯Ø© Ø¨Ø§ÙÙÙØªØ§Ø­ Ø§ÙØ®Ø§Ø±Ø¬Ù "{key}" Ø§ÙØ°Ù ÙØ§ ÙØ´ÙØ± Ø¥ÙÙ Ø§ÙØ¬Ø¯ÙÙ Ø§ÙØ£ØµÙ "{table}".',
  'The relation "{relation}" in active record class "{class}" is specified with an incomplete foreign key. The foreign key must consist of columns referencing both joining tables.' => 'Ø§ÙØ¹ÙØ§ÙØ© "{relation}" ÙÙ ÙØ¦Ø© Ø§ÙØ³Ø¬Ù Ø§ÙÙØ´Ø· "{class}" ÙØ­Ø¯Ø¯Ø© Ø¨ÙÙØªØ§Ø­ Ø®Ø§Ø±Ø¬Ù ØºÙØ± ÙÙØªÙÙ. Ø§ÙÙÙØªØ§Ø­ Ø§ÙØ®Ø§Ø±Ø¬Ù ÙØ¬Ø¨ Ø£Ù ÙØ­ØªÙÙ Ø¹ÙÙ Ø§ÙØ£Ø¹ÙØ¯Ø© Ø§ÙØªÙ ØªØ´ÙØ± Ø¥ÙÙ Ø§ÙØ¬Ø¯ÙÙÙÙ Ø§ÙÙØªØµÙØ©.',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key "{key}". There is no such column in the table "{table}".' => 'Ø§ÙØ¹ÙØ§ÙØ© "{relation}" ÙÙ ÙØ¦Ø© Ø§ÙØ³Ø¬Ù Ø§ÙÙØ´Ø· "{class}" ÙØ­Ø¯Ø¯Ø© Ø¨ÙÙØªØ§Ø­ Ø®Ø§Ø±Ø¬Ù ØºÙØ± ØµØ§ÙØ­ "{key}". ÙØ§ ÙÙØ¬Ø¯ ÙØ«Ù ÙØ°Ø§ Ø§ÙØ¹ÙÙØ¯ ÙÙ Ø§ÙØ¬Ø¯ÙÙ "{table}".',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key. The columns in the key must match the primary keys of the table "{table}".' => 'Ø§ÙØ¹ÙØ§ÙØ© "{relation}" ÙÙ ÙØ¦Ø© Ø§ÙØ³Ø¬Ù Ø§ÙÙØ´Ø· "{class}" ÙØ­Ø¯Ø¯Ø© Ø¨ÙÙØªØ§Ø­ Ø®Ø§Ø±Ø¬Ù ØºÙØ± ØµØ§ÙØ­. ÙØ¬Ø¨ Ø£Ù ØªØªØ·Ø§Ø¨Ù Ø§ÙØ£Ø¹ÙØ¯Ø© ÙÙ Ø§ÙÙÙØªØ§Ø­ ÙØ¹ Ø§ÙÙÙØ§ØªÙØ­ Ø§ÙØ£Ø³Ø§Ø³ÙØ© ÙÙ Ø§ÙØ¬Ø¯ÙÙ "{table}".',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key. The format of the foreign key must be "joinTable(fk1,fk2,...)".' => 'Ø§ÙØ¹ÙØ§ÙØ© "{relation}" ÙÙ ÙØ¦Ø© Ø§ÙØ³Ø¬Ù Ø§ÙÙØ´Ø· "{class}" ÙØ­Ø¯Ø¯Ø© Ø¨ÙÙØªØ§Ø­ Ø®Ø§Ø±Ø¬Ù ØºÙØ± ØµØ§ÙØ­. ØªÙØ³ÙÙ Ø§ÙÙÙØªØ§Ø­ Ø§ÙØ®Ø§Ø±Ø¬Ù ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ ÙØ«Ù "joinTable(fk1,fk2,...)".',
  'The requested view "{name}" was not found.' => 'Ø§ÙØ¹Ø±Ø¶ Ø§ÙÙØ·ÙÙØ¨ "{name}" ÙÙ ÙØªÙ Ø§ÙØ¹Ø«ÙØ± Ø¹ÙÙÙ.',
  'The stack is empty.' => 'Ø§ÙØ±ØµÙ ÙØ§Ø±ØºØ©.',
  'The system is unable to find the requested action "{action}".' => 'ØªØ¹Ø°Ø± Ø¹ÙÙ Ø§ÙÙØ¸Ø§Ù Ø§ÙØ¹Ø«ÙØ± Ø¹ÙÙ Ø§ÙØ¥Ø¬Ø±Ø§Ø¡ Ø§ÙÙØ·ÙÙØ¨ "{action}".',
  'The system view path "{path}" is not a valid directory.' => 'ÙØ³Ø§Ø± Ø¹Ø±Ø¶ Ø§ÙÙØ¸Ø§Ù "{path}" ÙÙ Ø¯ÙÙÙ ØºÙØ± ØµØ§ÙØ­.',
  'The table "{table}" for active record class "{class}" cannot be found in the database.' => 'Ø§ÙØ¬Ø¯ÙÙ "{table}" ÙÙØ¦Ø© Ø§ÙØ³Ø¬Ù Ø§ÙÙØ´Ø· "{class}" ÙØ§ ÙÙÙÙ Ø§ÙØ¹Ø«ÙØ± Ø¹ÙÙÙ ÙÙ ÙØ§Ø¹Ø¯Ø© Ø§ÙØ¨ÙØ§ÙØ§Øª.',
  'The value for the column "{column}" is not supplied when querying the table "{table}".' => 'ÙÙÙØ© Ø§ÙØ¹ÙÙØ¯ "{column}" ÙÙ ÙØªÙ ØªÙÙÙØ±ÙØ§ Ø¹ÙØ¯ Ø§Ø³ØªØ¹ÙØ§Ù Ø§ÙØ¬Ø¯ÙÙ "{table}".',
  'The verification code is incorrect.' => 'Ø±ÙØ² Ø§ÙØªØ£ÙÙØ¯ ØºÙØ± ØµØ­ÙØ­.',
  'The view path "{path}" is not a valid directory.' => 'ÙØ³Ø§Ø± Ø§ÙØ¹Ø±Ø¶ "{path}" ÙÙ Ø¯ÙÙÙ ØºÙØ± ØµØ§ÙØ­.',
  'Theme directory "{directory}" does not exist.' => 'Ø¯ÙÙÙ Ø§ÙØ³ÙØ© "{directory}" ØºÙØ± ÙÙØ¬ÙØ¯.',
  'This content requires the <a href="http://www.adobe.com/go/getflash/">Adobe Flash Player</a>.' => 'ÙØ°Ø§ Ø§ÙÙØ­ØªÙÙ ÙØªØ·ÙØ¨ <a href="http://www.adobe.com/go/getflash/">Adobe Flash Player</a>.',
  'Unable to add an item whose name is the same as an existing item.' => 'ØªØ¹Ø°Ø±Øª Ø¥Ø¶Ø§ÙØ© Ø¹ÙØµØ± Ø§Ø³ÙÙ ÙØ·Ø§Ø¨Ù ÙØ§Ø³Ù Ø¹ÙØµØ± Ø¢Ø®Ø±.',
  'Unable to change the item name. The name "{name}" is already used by another item.' => 'ØªØ¹Ø°Ø± ØªØºÙÙØ± Ø§Ø³Ù Ø§ÙØ¹ÙØµØ±. Ø§ÙØ§Ø³Ù "{name}" ÙØ³ØªØ®Ø¯Ù Ø¨Ø§ÙÙØ¹Ù ÙÙ ÙØ¨Ù Ø¹ÙØµØ± Ø¢Ø®Ø±.',
  'Unable to create application state file "{file}". Make sure the directory containing the file exists and is writable by the Web server process.' => 'ØªØ¹Ø°Ø± Ø¥ÙØ´Ø§Ø¡ ÙÙÙ Ø­Ø§ÙØ© Ø§ÙØªØ·Ø¨ÙÙ "{file}". ØªØ£ÙØ¯ ÙÙ ÙØ¬ÙØ¯ Ø§ÙØ¯ÙÙÙ Ø§ÙØ°Ù ÙØ­ØªÙÙ Ø§ÙÙÙÙ ÙØ£ÙÙ ÙØ§Ø¨Ù ÙÙÙØªØ§Ø¨Ø© Ø¹Ø¨Ø± Ø¹ÙÙÙØ§Øª Ø®Ø§Ø¯Ù Ø§ÙÙÙØ¨.',
  'Unable to find "{column}" in table "{table}".' => 'ØªØ¹Ø°Ø± Ø§ÙØ¹Ø«ÙØ± Ø¹ÙÙ "{column}" ÙÙ Ø§ÙØ¬Ø¯ÙÙ "{table}".',
  'Unable to generate random string.' => 'ØªØ¹Ø°Ø± ØªÙÙÙØ¯ Ø³ÙØ³ÙØ© Ø¹Ø´ÙØ§Ø¦ÙØ©.',
  'Unable to lock file "{file}" for reading.' => 'ØªØ¹Ø°Ø± ÙÙÙ Ø§ÙÙÙÙ "{file}" Ø¹Ù Ø§ÙÙØ±Ø§Ø¡Ø©.',
  'Unable to lock file "{file}" for writing.' => 'ØªØ¹Ø°Ø± ÙÙÙ Ø§ÙÙÙÙ "{file}" Ø¹Ù Ø§ÙÙØªØ§Ø¨Ø©.',
  'Unable to read file "{file}".' => 'ØªØ¹Ø°Ø±Øª ÙØ±Ø§Ø¡Ø© Ø§ÙÙÙÙ "{file}".',
  'Unable to replay the action "{object}.{method}". The method does not exist.' => 'ØªØ¹Ø°Ø±Øª Ø¥Ø¹Ø§Ø¯Ø© ÙØ±Ø§Ø¡Ø© Ø§ÙØ¥Ø¬Ø±Ø§Ø¡ "{object}.{method}". Ø§ÙØ·Ø±ÙÙØ© ØºÙØ± ÙÙØ¬ÙØ¯Ø©.',
  'Unable to resolve the request "{route}".' => 'ØªØ¹Ø°Ø± Ø­Ù Ø§ÙØ·ÙØ¨ "{route}".',
  'Unable to write file "{file}".' => 'ØªØ¹Ø°Ø±Øª ÙØªØ§Ø¨Ø© Ø§ÙÙÙÙ "{file}".',
  'Unknown authorization item "{name}".' => '"{name}" Ø¹ÙØµØ± ØªØ®ÙÙÙ ØºÙØ± ÙØ¹Ø±ÙÙ.',
  'Unknown operator "{operator}".' => '"{operator}" Ø¹Ø§ÙÙ ØªØ´ØºÙÙ ØºÙØ± ÙØ¹Ø±ÙÙ.',
  'Unknown type "{type}".' => '"{type}" ÙÙØ¹ ØºÙØ± ÙØ¹Ø±ÙÙ.',
  'Unrecognized locale "{locale}".' => '"{locale}" ÙØºØ© ØºÙØ± ÙØ¹Ø±ÙÙØ©.',
  'View file "{file}" does not exist.' => 'ÙÙÙ Ø§ÙØ¹Ø±Ø¶ "{file}" ØºÙØ± ÙÙØ¬ÙØ¯.',
  'Yes' => 'ÙØ¹Ù',
  'Yii application can only be created once.' => 'ØªØ·Ø¨ÙÙ Yii ÙÙÙÙ Ø¥ÙØ´Ø§Ø¤Ù ÙØ±Ø© ÙØ§Ø­Ø¯Ø© ÙÙØ·.',
  'You are not authorized to perform this action.' => 'Ø£ÙØª ØºÙØ± ÙØ®ÙÙ ÙÙÙÙØ§Ù Ø¨ÙØ°Ø§ Ø§ÙØ¥Ø¬Ø±Ø§Ø¡.',
  'Your request is invalid.' => 'Ø·ÙØ¨Ù ØºÙØ± ØµØ§ÙØ­.',
  '{attribute} "{value}" has already been taken.' => '{attribute} "{value}" ØªÙ Ø¨Ø§ÙÙØ¹Ù Ø£Ø®Ø°Ù.',
  '{attribute} "{value}" is invalid.' => '{attribute} "{value}" ØºÙØ± ØµØ­ÙØ­.',
  '{attribute} cannot accept more than {limit} files.' => '{attribute} ÙØ§ ÙÙÙÙ ÙØ¨ÙÙ Ø£ÙØ«Ø± ÙÙ {limit} ÙÙÙ.',
  '{attribute} cannot be blank.' => '{attribute} ÙØ§ ÙÙÙÙ Ø£Ù ÙÙÙÙ ÙØ§Ø±ØºØ§Ù.',
  '{attribute} is in the list.' => '{attribute} ÙÙØ¬ÙØ¯ ÙÙ Ø§ÙÙØ§Ø¦ÙØ©.',
  '{attribute} is invalid.' => '{attribute} ØºÙØ± ØµØ­ÙØ­.',
  '{attribute} is not a valid URL.' => '{attribute} ÙÙØ³ Ø¹ÙÙØ§Ù URL ØµØ­ÙØ­.',
  '{attribute} is not a valid email address.' => '{attribute} ÙÙØ³ Ø¹ÙÙØ§Ù Ø¨Ø±ÙØ¯ Ø¥ÙÙØªØ±ÙÙÙ ØµØ­ÙØ­.',
  '{attribute} is not in the list.' => '{attribute} ÙÙØ³ ÙÙ Ø§ÙÙØ§Ø¦ÙØ©.',
  '{attribute} is of the wrong length (should be {length} characters).' => '{attribute} Ø·ÙÙÙ Ø®Ø§Ø·Ø¦ (ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ {length} Ø­Ø±ÙØ§Ù).',
  '{attribute} is too big (maximum is {max}).' => '{attribute} ÙØ¨ÙØ± Ø¬Ø¯Ø§Ù (Ø§ÙØ­Ø¯ Ø§ÙØ£Ø¹ÙÙ {max}).',
  '{attribute} is too long (maximum is {max} characters).' => '{attribute} Ø·ÙÙÙ Ø¬Ø¯Ø§Ù (Ø§ÙØ­Ø¯ Ø§ÙØ£Ø¹ÙÙ {max} Ø­Ø±ÙØ§Ù).',
  '{attribute} is too short (minimum is {min} characters).' => '{attribute} ÙØµØ± Ø¬Ø¯Ø§Ù (Ø§ÙØ­Ø¯ Ø§ÙØ£Ø¯ÙÙ {min} Ø­Ø±ÙØ§Ù).',
  '{attribute} is too small (minimum is {min}).' => '{attribute} ÙÙÙÙ Ø¬Ø¯Ø§Ù (Ø§ÙØ­Ø¯ Ø§ÙØ£Ø¯ÙÙ {min}).',
  '{attribute} must be a number.' => '{attribute} ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ Ø±ÙÙØ§Ù.',
  '{attribute} must be an integer.' => '{attribute} ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ Ø±ÙÙØ§Ù ØµØ­ÙØ­Ø§Ù.',
  '{attribute} must be either {true} or {false}.' => '{attribute} ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ Ø¥ÙØ§ {true} Ø£Ù {false}.',
  '{attribute} must be greater than "{compareValue}".' => '{attribute} ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ Ø£ÙØ«Ø± ÙÙ "{compareValue}".',
  '{attribute} must be greater than or equal to "{compareValue}".' => '{attribute} ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ Ø£ÙØ«Ø± ÙÙ Ø£Ù ØªØ³Ø§ÙÙ "{compareValue}".',
  '{attribute} must be less than "{compareValue}".' => '{attribute} ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ Ø£ÙÙ ÙÙ "{compareValue}".',
  '{attribute} must be less than or equal to "{compareValue}".' => '{attribute} ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ Ø£ÙÙ ÙÙ Ø£Ù ØªØ³Ø§ÙÙ "{compareValue}".',
  '{attribute} must be repeated exactly.' => '{attribute} ÙØ¬Ø¨ Ø£Ù ØªÙÙÙ ÙÙØ±Ø±Ø© Ø¨Ø§ÙØ¶Ø¨Ø·.',
  '{attribute} must be {type}.' => '{attribute} ÙØ¬Ø¨ Ø£Ù ØªÙÙÙ {type}.',
  '{attribute} must be {value}.' => '{attribute} ÙØ¬Ø¨ Ø£Ù ØªÙÙÙ {value}.',
  '{attribute} must not be equal to "{compareValue}".' => '{attribute} ÙØ¬Ø¨ Ø£ÙØ§ ÙØªØ³Ø§ÙÙ ÙØ¹ "{compareValue}".',
  '{className} does not support add() functionality.' => '{className} ÙØ§ ÙØ¯Ø¹Ù ÙØ¸ÙÙØ© add().',
  '{className} does not support delete() functionality.' => '{className} ÙØ§ ÙØ¯Ø¹Ù ÙØ¸ÙÙØ© delete().',
  '{className} does not support flushValues() functionality.' => '{className} ÙØ§ ÙØ¯Ø¹Ù ÙØ¸ÙÙØ© flushValues().',
  '{className} does not support get() functionality.' => '{className} ÙØ§ ÙØ¯Ø¹Ù ÙØ¸ÙÙØ© get().',
  '{className} does not support set() functionality.' => '{className} ÙØ§ ÙØ¯Ø¹Ù ÙØ¸ÙÙØ© set().',
  '{class} and its behaviors do not have a method or closure named "{name}".' => '{class} ÙØ³ÙÙÙÙØ§ØªÙ ÙÙØ³ ÙØ¯ÙÙØ§ Ø·Ø±ÙÙØ© Ø£Ù Ø¥ØºÙØ§Ù Ø¨Ø§ÙØ§Ø³Ù "{name}".',
  '{class} does not have relation "{name}".' => '{class} ÙÙØ³ ÙØ¯ÙÙ Ø§ÙØ¹ÙØ§ÙØ© "{name}".',
  '{class} does not support fetching all table names.' => '{class} ÙØ§ ÙØ¯Ø¹Ù Ø§ÙØ­ØµÙÙ Ø¹ÙÙ Ø¬ÙÙØ¹ Ø£Ø³ÙØ§Ø¡ Ø§ÙØ¬Ø¯Ø§ÙÙ.',
  '{class} has an invalid validation rule. The rule must specify attributes to be validated and the validator name.' => '{class} ÙØ¯ÙÙØ§ ÙØ§Ø¹Ø¯Ø© ØªØ­ÙÙ ØºÙØ± ØµØ§ÙØ­Ø©. Ø§ÙÙØ§Ø¹Ø¯Ø© ÙØ¬Ø¨ Ø£Ù ØªØ­Ø¯Ø¯ Ø§ÙØ³ÙØ§Øª Ø§ÙÙØ·ÙÙØ¨ Ø§ÙØªØ­ÙÙ ÙÙÙØ§ ÙØ§Ø³Ù Ø§ÙÙØ­ÙÙ.',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} ÙØ¬Ø¨ ØªØ­Ø¯ÙØ¯ ÙÙÙ Ø§ÙØ®ØµØ§Ø¦Øµ "model" Ù "attribute" Ø£Ù "name".',
  '{class} requires the Blowfish option of the PHP crypt() function. This system does not have it.' => '{class} ÙØªØ·ÙØ¨ Ø®ÙØ§Ø± Blowfish ÙÙ ÙØ¸ÙÙØ© PHP crypt(). ÙØ°Ø§ Ø§ÙÙØ¸Ø§Ù ÙÙØ³ ÙØ¯ÙÙ.',
  '{class} requires the PHP crypt() function. This system does not have it.' => '{class} ÙØªØ·ÙØ¨ ÙØ¸ÙÙØ© PHP crypt(). ÙØ°Ø§ Ø§ÙÙØ¸Ø§Ù ÙÙØ³Øª ÙØ¯ÙÙ.',
  '{class}.allowAutoLogin must be set true in order to use cookie-based authentication.' => '{class}.allowAutoLogin ÙØ¬Ø¨ ØªØ¹ÙÙÙÙ Ø¨ÙÙÙØ© ØµÙØ§Ø¨ ÙÙ Ø£Ø¬Ù Ø§Ø³ØªØ®Ø¯Ø§Ù Ø§ÙØªØ®ÙÙÙ Ø§ÙÙØ¨ÙÙ Ø¹ÙÙ ÙÙÙ ØªØ¹Ø±ÙÙ Ø§ÙØ§Ø±ØªØ¨Ø§Ø·.',
  '{class}::$cost must be a number.' => '{class}::$cost ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ Ø±ÙÙØ§Ù.',
  '{class}::$cost must be between 4 and 31.' => '{class}::$cost ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ Ø¨ÙÙ 4 Ù 31.',
  '{class}::authenticate() must be implemented.' => '{class}::authenticate() ÙØ¬Ø¨ Ø£Ù ÙÙÙÙ ÙØ·Ø¨Ù.',
  '{controller} cannot find the requested view "{view}".' => '{controller} ÙØ§ ÙÙÙÙÙ Ø§ÙØ¹Ø«ÙØ± Ø¹ÙÙ Ø§ÙØ¹Ø±Ø¶ Ø§ÙÙØ·ÙÙØ¨ "{view}".',
  '{controller} contains improperly nested widget tags in its view "{view}". A {widget} widget does not have an endWidget() call.' => '{controller} ÙØ­ØªÙÙ Ø¹ÙÙ Ø¹ÙØ§ÙØ§Øª ÙØªØ¯Ø§Ø®ÙØ© ÙÙØ§Ø¬ÙØ© Ø§ÙÙØ³ØªØ®Ø¯Ù ÙÙ Ø¹Ø±Ø¶Ù "{view}". ÙØ§Ø¬ÙØ© Ø§ÙÙØ³ØªØ®Ø¯Ù {widget} ÙÙØ³ ÙØ¯ÙÙØ§ Ø§Ø³ØªØ¯Ø¹Ø§Ø¡ endWidget().',
  '{controller} has an extra endWidget({id}) call in its view.' => '{controller} ÙØ¯ÙÙ endWidget({id}) Ø§Ø³ØªØ¯Ø¹Ø§Ø¡ Ø²Ø§Ø¦Ø¯ ÙÙ Ø¹Ø±Ø¶Ù.',
  '{n} B' => '{n} B',
  '{n} GB' => '{n} GB',
  '{n} KB' => '{n} KB',
  '{n} MB' => '{n} MB',
  '{n} TB' => '{n} TB',
  '{n} byte|{n} bytes' => '{n} Ø¨Ø§ÙØª',
  '{n} gigabyte|{n} gigabytes' => '{n} Ø¬ÙØ¬Ø§Ø¨Ø§ÙØª',
  '{n} kilobyte|{n} kilobytes' => '{n} ÙÙÙÙØ¨Ø§ÙØª',
  '{n} megabyte|{n} megabytes' => '{n} ÙÙØ¬Ø§Ø¨Ø§ÙØª',
  '{n} terabyte|{n} terabytes' => '{n} ØªÙØ±Ø§Ø¨Ø§ÙØª',
  '{widget} cannot find the view "{view}".' => '{widget} ÙØ§ ÙÙÙÙÙ Ø§ÙØ¹Ø«ÙØ± Ø¹ÙÙ Ø§ÙØ¹Ø±Ø¶ "{view}".',
);
