<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '"{path}" is not a valid directory.' => '"{path}" ä¸æ¯ä¸ååæ³çç®é.',
  'Active Record requires a "db" CDbConnection application component.' => 'Active Record éè¦ä¸ååçº "db" ç CDbConnection æç¨ç¨å¼åä»¶.',
  'Active record "{class}" has an invalid configuration for relation "{relation}". It must specify the relation type, the related active record class and the foreign key.' => 'Active record "{class}" å°æ¼éè¯ "{relation}" æä¸åç¡æççµæè¨­å®. å¿é çµ¦å®éè¯ç¨®é¡, ç¸éç active record class ä»¥å foreign key.',
  'Active record "{class}" is trying to select an invalid column "{column}". Note, the column must exist in the table or be an expression with alias.' => 'Active record "{class}" æ­£åè©¦é¸æä¸åç¡æçæ¬ä½ "{column}". æ³¨æ, è©²æ¬ä½å¿é å­å¨æ¼ table ä¸­æèæ¯ä¸åå·å¥åç expression.',
  'Alias "{alias}" is invalid. Make sure it points to an existing directory or file.' => 'å¥å "{alias}" æ¯ç¡æç. è«ç¢ºå®å®æåä¸åå·²å­å¨çç®éææªæ¡.',
  'Application base path "{path}" is not a valid directory.' => 'æç¨ç¨å¼åºæºè·¯å¾ "{path}" æ¯ç¡æçç®é.',
  'Application runtime path "{path}" is not valid. Please make sure it is a directory writable by the Web server process.' => 'æç¨ç¨å¼å·è¡æçè·¯å¾ "{path}" æ¯ç¡æç. è«ç¢ºå®å®æ¯ä¸åå¯è¢« Web server process å¯«å¥è³æçç®é.',
  'Authorization item "{item}" has already been assigned to user "{user}".' => 'ææ¬é ç® "{item}" å·²ç¶è¢«ææ´¾çµ¦ä½¿ç¨è "{user}".',
  'CApcCache requires PHP apc extension to be loaded.' => 'CApcCache è¦æ± PHP apc extension å¿é åè¢«è¼å¥.',
  'CAssetManager.basePath "{path}" is invalid. Please make sure the directory exists and is writable by the Web server process.' => 'CAssetManager.basePath "{path}" æ¯ç¡æç. è«ç¢ºå®å®æ¯ä¸åå¯è¢« Web server process å¯«å¥è³æçç®é.',
  'CCacheHttpSession.cacheID is invalid. Please make sure "{id}" refers to a valid cache application component.' => 'CCacheHttpSession.cacheID æ¯ç¡æç. è«ç¢ºå® "{id}" åç§å°ä¸åææçå¿«åæç¨ç¨å¼åä»¶.',
  'CCaptchaValidator.action "{id}" is invalid. Unable to find such an action in the current controller.' => 'CCaptchaValidator.action "{id}" æ¯ç¡æç. ç¡æ³å¨ç®åçæ§å¶å¨ä¸­æ¾å°æ­¤ä¸åä½.',
  'CDbAuthManager.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbAuthManager.connectionID "{id}" æ¯ç¡æç. è«ç¢ºå®å®åç§å°ä¸å CDbConnection æç¨ç¨å¼åä»¶ç ID.',
  'CDbCache.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbCache.connectionID "{id}" æ¯ç¡æç. è«ç¢ºå®å®åç§å°ä¸å CDbConnection æç¨ç¨å¼åä»¶ç ID.',
  'CDbCacheDependency.sql cannot be empty.' => 'CDbCacheDependency.sql ä¸è½æ¯ç©ºç.',
  'CDbCommand failed to execute the SQL statement: {error}' => 'CDbCommand ç¡æ³å·è¡ SQL é³è¿°: {error}',
  'CDbCommand failed to prepare the SQL statement: {error}' => 'CDbCommand ç¡æ³æºå SQL é³è¿°: {error}',
  'CDbConnection does not support reading schema for {driver} database.' => 'CDbConnection ä¸æ¯æ´å° {driver} è³æåº« schema çè®å.',
  'CDbConnection failed to open the DB connection: {error}' => 'CDbConnection ç¡æ³éåè³æåº«é£ç·: {error}',
  'CDbConnection is inactive and cannot perform any DB operations.' => 'CDbConnection çæçºæªåç¨, ç¡æ³é²è¡ä»»ä½è³æåº«åä½.',
  'CDbConnection.connectionString cannot be empty.' => 'CDbConnection.connectionString ä¸è½æ¯ç©ºç.',
  'CDbDataReader cannot rewind. It is a forward-only reader.' => 'CDbDataReader ç¡æ³åå, åªåè¨±ååè®å.',
  'CDbHttpSession.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbHttpSession.connectionID "{id}" æ¯ç¡æç. è«ç¢ºå®å®åç§å°ä¸å CDbConnection æç¨ç¨å¼åä»¶ç ID.',
  'CDbLogRoute requires database table "{table}" to store log messages.' => 'CDbLogRoute è¦æ±è³æåº« table "{table}" å²å­æ¥èªè¨æ¯.',
  'CDbLogRoute.connectionID "{id}" does not point to a valid CDbConnection application component.' => 'CDbLogRoute.connectionID "{id}" æªæåä¸åææç CDbConnection æç¨ç¨å¼åä»¶.',
  'CDbMessageSource.connectionID is invalid. Please make sure "{id}" refers to a valid database application component.' => 'CDbMessageSource.connectionID æ¯ç¡æç. è«ç¢ºå® "{id}" åç§å°ä¸åææçè³æåº«æç¨ç¨å¼åä»¶.',
  'CDbTransaction is inactive and cannot perform commit or roll back operations.' => 'CDbTransaction çæçºæªåç¨, ç¡æ³é²è¡ commit æ roll back åä½.',
  'CDirectoryCacheDependency.directory cannot be empty.' => 'CDirectoryCacheDependency.directory ä¸è½æ¯ç©ºç.',
  'CFileCacheDependency.fileName cannot be empty.' => 'CFileCacheDependency.fileName ä¸è½æ¯ç©ºç.',
  'CFileLogRoute.logPath "{path}" does not point to a valid directory. Make sure the directory exists and is writable by the Web server process.' => 'CFileLogRoute.logPath "{path}" does not point to a valid directory. è«ç¢ºå®ç®éå­å¨ä¸¦ä¸åè¨± Web server process å¯«å¥.',
  'CFilterChain can only take objects implementing the IFilter interface.' => 'CFilterChain åªè½åå¾æå¯¦ä½ IFilter ä»é¢çç©ä»¶.',
  'CFlexWidget.baseUrl cannot be empty.' => 'CFlexWidget.baseUrl ä¸è½æ¯ç©ºç.',
  'CFlexWidget.name cannot be empty.' => 'CFlexWidget.name ä¸è½æ¯ç©ºç.',
  'CGlobalStateCacheDependency.stateName cannot be empty.' => 'CGlobalStateCacheDependency.stateName ä¸è½æ¯ç©ºç.',
  'CHttpCookieCollection can only hold CHttpCookie objects.' => 'CHttpCookieCollection åªè½ææ CHttpCookie ç©ä»¶.',
  'CHttpRequest is unable to determine the entry script URL.' => 'CHttpRequest ä¸è½ç¢ºèªå¥å£è³æ¬ç URL.',
  'CHttpRequest is unable to determine the path info of the request.' => 'CHttpRequest ä¸è½ç¢ºèªè«æ±çè·¯å¾è³è¨.',
  'CHttpRequest is unable to determine the request URI.' => 'CHttpRequest ä¸è½ç¢ºèªè«æ±ç URI.',
  'CHttpSession.cookieMode can only be "none", "allow" or "only".' => 'CHttpSession.cookieMode åªè½æ¯ "none", "allow" æ "only".',
  'CHttpSession.gcProbability "{value}" is invalid. It must be an integer between 0 and 100.' => 'CHttpSession.gcProbability "{value}" æ¯ç¡æç. å®å¿é æ¯ä»æ¼ 0 è 100ä¹éçæ´æ¸.',
  'CHttpSession.savePath "{path}" is not a valid directory.' => 'CHttpSession.savePath "{path}" ä¸æ¯ä¸åææçç®é.',
  'CMemCache requires PHP memcache extension to be loaded.' => 'CMemCache è¦æ± PHP memcache æä»¶å¿é åè¢«è¼å¥.',
  'CMemCache server configuration must be an array.' => 'CMemCache ä¼ºæå¨çµæè¨­å®å¿é æ¯ä¸åé£å.',
  'CMemCache server configuration must have "host" value.' => 'CMemCache ä¼ºæå¨çµæè¨­å®å¿é æ "host" çå¼.',
  'CMultiFileUpload.name is required.' => 'CMultiFileUpload.name æ¯å¿è¦ç.',
  'CProfileLogRoute found a mismatching code block "{token}". Make sure the calls to Yii::beginProfile() and Yii::endProfile() be properly nested.' => 'CProfileLogRoute found a mismatching code block "{token}". è«ç¢ºå®å°æ¼ Yii::beginProfile() è Yii::endProfile() çå¼å«æ¯é©ç¶å°å·¢çå¥çç.',
  'CProfileLogRoute.report "{report}" is invalid. Valid values include "summary" and "callstack".' => 'CProfileLogRoute.report "{report}" æ¯ç¡æç. ææå¼åå« "summary" è "callstack".',
  'CSecurityManager requires PHP mcrypt extension to be loaded in order to use data encryption feature.' => 'CSecurityManager è¦æ± PHP mcrypt extension å¿é åè¢«è¼å¥ä»¥ä¾¿ä½¿ç¨è³æå å¯åè½.',
  'CSecurityManager.encryptionKey cannot be empty.' => 'CSecurityManager.encryptionKey ä¸è½æ¯ç©ºç.',
  'CSecurityManager.validation must be either "MD5" or "SHA1".' => 'CSecurityManager.validation å¿é æ¯ "MD5" æ "SHA1".',
  'CSecurityManager.validationKey cannot be empty.' => 'CSecurityManager.validationKey ä¸è½æ¯ç©ºç.',
  'CTypedList<{type}> can only hold objects of {type} class.' => 'CTypedList<{type}> åªè½ææ {type} é¡å¥çç©ä»¶.',
  'CUrlManager.UrlFormat must be either "path" or "get".' => 'CUrlManager.UrlFormat å¿é æ¯ "path" æ "get".',
  'CXCache requires PHP XCache extension to be loaded.' => 'CXCache è¦æ± PHP XCache æä»¶å¿é åè¢«è¼å¥.',
  'Cache table "{tableName}" does not exist.' => 'Cache table "{tableName}" ä¸å­å¨.',
  'Cannot add "{child}" as a child of "{name}". A loop has been detected.' => 'ç¡æ³æ°å¢ "{child}" æçº "{name}" çå­é . åµæ¸¬å°æè¿´åç¢ç.',
  'Cannot add "{child}" as a child of "{parent}". A loop has been detected.' => 'ç¡æ³æ°å¢ "{child}" æçº "{parent}" çå­é . åµæ¸¬å°æè¿´åç¢ç.',
  'Cannot add "{name}" as a child of itself.' => 'ç¡æ³æ°å¢ "{name}" æçºå®èªå·±çå­é .',
  'Cannot add an item of type "{child}" to an item of type "{parent}".' => 'ç¡æ³æ°å¢ä¸åç¨®é¡çº "{child}" çé ç®å°ä¸åç¨®é¡çº "{parent}" çé ç®.',
  'Either "{parent}" or "{child}" does not exist.' => '"{parent}" æ "{child}" ä¸å­å¨.',
  'Error: Table "{table}" does not have a primary key.' => 'é¯èª¤: Table "{table}" æ²æå®ç¾©ä¸»éµ.',
  'Error: Table "{table}" has a composite primary key which is not supported by crud command.' => 'é¯èª¤: Table "{table}" æä¸åä¸è¢« crud å½ä»¤ææ¯æ´çåæä¸»éµ.',
  'Event "{class}.{event}" is attached with an invalid handler "{handler}".' => 'äºä»¶ "{class}.{event}" éå äºä¸åç¡æç handler "{handler}".',
  'Event "{class}.{event}" is not defined.' => 'äºä»¶ "{class}.{event}" æªå®ç¾©.',
  'Failed to write the uploaded file "{file}" to disk.' => 'ç¡æ³å°å·²ä¸å³çæªæ¡ "{file}" å¯«å¥ç£ç¢.',
  'File upload was stopped by extension.' => 'æªæ¡ä¸å³è¢«æä»¶æåæ­¢.',
  'Filter "{filter}" is invalid. Controller "{class}" does have the filter method "filter{filter}".' => 'ç¯©é¸å¨ "{filter}" æ¯ç¡æç. æ§å¶å¨ "{class}" æ²æåçº "filter{filter}" çç¯©é¸å¨æ¹æ³.',
  'Get a new code' => 'åå¾ä¸çµæ°ä»£ç¢¼',
  'Invalid MO file revision: {revision}.' => 'ç¡æç MO æªæ¡ä¿®è¨: {revision}.',
  'Invalid MO file: {file} (magic: {magic}).' => 'ç¡æç MO æªæ¡: {file} (magic: {magic}).',
  'Invalid enumerable value "{value}". Please make sure it is among ({enum}).' => 'ç¡æç enumerable å¼ "{value}". è«ç¢ºå®å®å¨ ({enum}) ä¹ä¸­.',
  'List data must be an array or an object implementing Traversable.' => 'è¡¨åè³æå¿é æ¯ä¸åé£åææ¯æå¯¦ä½ Traversable çä¸åç©ä»¶.',
  'List index "{index}" is out of bound.' => 'è¡¨åç´¢å¼ "{index}" è¶åºç¯å.',
  'Login Required' => 'éè¦åç»å¥ç³»çµ±',
  'Map data must be an array or an object implementing Traversable.' => 'å°ç§è¡¨è³æå¿é æ¯ä¸åé£åæä¸åå¯¦ä½ Traversable çç©ä»¶.',
  'Missing the temporary folder to store the uploaded file "{file}".' => 'ç¼ºä¹æ«å­ç®éä¾å²å­å·²ä¸å³çæªæ¡ "{file}".',
  'No columns are being updated for table "{table}".' => 'table "{table}" æ²æä»»ä½æ¬ä½å°è¢«æ´æ°.',
  'No counter columns are being updated for table "{table}".' => 'table "{table}" æ²æä»»ä½è¨æ¸å¨æ¬ä½å°è¢«æ´æ°.',
  'Object configuration must be an array containing a "class" element.' => 'ç©ä»¶çµæè¨­å®å¿é æ¯å§å«æä¸å "class" åç´ çä¸åé£å.',
  'Please fix the following input errors:' => 'è«æ´æ­£ä¸åè¼¸å¥é¯èª¤:',
  'Property "{class}.{property}" is not defined.' => 'å±¬æ§ "{class}.{property}" æªè¢«å®ç¾©.',
  'Property "{class}.{property}" is read only.' => 'å±¬æ§ "{class}.{property}" æ¯å¯è®ç.',
  'Queue data must be an array or an object implementing Traversable.' => 'ä½åè³æå¿é æ¯ä¸åé£åæä¸åå¯¦ä½ Traversable çç©ä»¶.',
  'Relation "{name}" is not defined in active record class "{class}".' => 'éè¯ "{name}" æªè¢«å®ç¾©å¨ active record class "{class}" ä¸­.',
  'Stack data must be an array or an object implementing Traversable.' => 'å çè³æå¿é æ¯ä¸åé£åæä¸åå¯¦ä½ Traversable çç©ä»¶.',
  'Table "{table}" does not have a column named "{column}".' => 'Table "{table}" æ²æåçº "{column}" çæ¬ä½.',
  'Table "{table}" does not have a primary key defined.' => 'Table "{table}" æ²æå®ç¾©ä¸»éµ.',
  'The "filter" property must be specified with a valid callback.' => 'å±¬æ§ "filter" å¿é ä»¥ä¸åææç callback ææ.',
  'The "pattern" property must be specified with a valid regular expression.' => 'å±¬æ§ "pattern" å¿é ä»¥ä¸åææç regular expression ææ.',
  'The "view" property is required.' => 'éè¦ "view" å±¬æ§',
  'The CSRF token could not be verified.' => 'CSRF token ç¡æ³è¢«é©è­.',
  'The URL pattern "{pattern}" for route "{route}" is not a valid regular expression.' => 'route "{route}" ä¸­ç URL æ¨£å¼ "{pattern}" ä¸æ¯ææç regular expression.',
  'The active record cannot be deleted because it is new.' => 'active record ç±æ¼æ¯æ°ç, ç¡æ³è¢«åªé¤.',
  'The active record cannot be inserted to database because it is not new.' => 'active record ç±æ¼ä¸æ¯æ°ç, ç¡æ³è¢«æ°å¢å°è³æåº«.',
  'The active record cannot be updated because it is new.' => 'active record ç±æ¼æ¯æ°ç, ç¡æ³è¢«æ´æ°.',
  'The asset "{asset}" to be pulished does not exist.' => 'æ¬²ç¼ä½ç asset "{asset}" ä¸å­å¨.',
  'The column "{column}" is not a foreign key in table "{table}".' => 'æ¬ä½ "{column}" ä¸¦ä¸æ¯ table "{table}" ä¸­çä¸å foreign key.',
  'The command path "{path}" is not a valid directory.' => 'å½ä»¤è·¯å¾ "{path}" ä¸æ¯ä¸åææçç®é.',
  'The controller path "{path}" is not a valid directory.' => 'æ§å¶å¨è·¯å¾ "{path}" ä¸æ¯ä¸åææçç®é.',
  'The file "{file}" cannot be uploaded. Only files with these extensions are allowed: {extensions}.' => 'æªæ¡ "{file}" ç¡æ³è¢«ä¸å³. åªæéæªåå¦ä¸çæªæ¡æ¯è¢«åè¨±ç: {extensions}.',
  'The file "{file}" is too large. Its size cannot exceed {limit} bytes.' => 'æªæ¡ "{file}" å¤ªå¤§. æªæ¡å¤§å°ä¸è½è¶é {limit} ä½åçµ.',
  'The file "{file}" is too small. Its size cannot be smaller than {limit} bytes.' => 'æªæ¡ "{file}" å¤ªå°. æªæ¡å¤§å°ä¸è½å°æ¼ {limit} ä½åçµ.',
  'The file "{file}" was only partially uploaded.' => 'æªæ¡ "{file}" ä¸å³ä¸å®å¨.',
  'The first element in a filter configuration must be the filter class.' => 'ç¯©é¸å¨çµæè¨­å®ä¸­çç¬¬ä¸ååç´ å¿é æ¯ç¯©é¸å¨é¡å¥.',
  'The item "{name}" does not exist.' => 'é ç® "{name}" ä¸å­å¨.',
  'The item "{parent}" already has a child "{child}".' => 'é ç® "{parent}" å·²æå­é ç® "{child}".',
  'The layout path "{path}" is not a valid directory.' => 'ä½å±è·¯å¾ "{path}" ä¸æ¯ä¸åææçç®é.',
  'The list is read only.' => 'è¡¨åæ¯å¯è®ç.',
  'The map is read only.' => 'å°ç§è¡¨æ¯å¯è®ç.',
  'The pattern for 12 hour format must be "h" or "hh".' => 'ä»£è¡¨12å°æå¶çæ¨£å¼å¿é æ¯ "h" æ "hh".',
  'The pattern for 24 hour format must be "H" or "HH".' => 'ä»£è¡¨24å°æå¶çæ¨£å¼å¿é æ¯ "H" æ "HH".',
  'The pattern for AM/PM marker must be "a".' => 'ä»£è¡¨ AM/PM æ¨è¨çæ¨£å¼å¿é æ¯ "a".',
  'The pattern for day in month must be "F".' => 'ä»£è¡¨ä»¥ææ¸åä»£å¤©æ¸çæ¨£å¼å¿é æ¯ "F".',
  'The pattern for day in year must be "D", "DD" or "DDD".' => 'ä»£è¡¨è©²å¹´çç¬¬å¹¾å¤©çæ¨£å¼å¿é æ¯ "D", "DD" æ "DDD".',
  'The pattern for day of the month must be "d" or "dd".' => 'ä»£è¡¨è©²æçæ¥å­çæ¨£å¼å¿é æ¯ "d" æ "dd".',
  'The pattern for day of the week must be "E", "EE", "EEE", "EEEE" or "EEEEE".' => 'ä»£è¡¨è©²ææçç¬¬å¹¾å¤©çæ¨£å¼å¿é æ¯ "E", "EE", "EEE", "EEEE" æ "EEEEE".',
  'The pattern for era must be "G", "GG", "GGG", "GGGG" or "GGGGG".' => 'ä»£è¡¨å¹´ä»£çæ¨£å¼å¿é æ¯ "G", "GG", "GGG", "GGGG" æ "GGGGG".',
  'The pattern for hour in AM/PM must be "K" or "KK".' => 'ä»£è¡¨æ(AM/PMæ ¼å¼)çæ¨£å¼å¿é æ¯ "K" æ "KK".',
  'The pattern for hour in day must be "k" or "kk".' => 'ä»£è¡¨è©²å¤©ç¬¬å¹¾å°æçæ¨£å¼å¿é æ¯ "k" æ "kk".',
  'The pattern for minutes must be "m" or "mm".' => 'ä»£è¡¨åéçæ¨£å¼å¿é æ¯ "m" æ "mm".',
  'The pattern for month must be "M", "MM", "MMM", or "MMMM".' => 'ä»£è¡¨æä»½çæ¨£å¼å¿é æ¯ "M", "MM", "MMM", æ "MMMM".',
  'The pattern for seconds must be "s" or "ss".' => 'ä»£è¡¨ç§çæ¨£å¼å¿é æ¯ "s" æ "ss".',
  'The pattern for time zone must be "z" or "v".' => 'ä»£è¡¨æåçæ¨£å¼å¿é æ¯ "z" æ "v".',
  'The pattern for week in month must be "W".' => 'ä»£è¡¨ä»¥ææ¸åä»£æææ¸çæ¨£å¼å¿é æ¯ "W".',
  'The pattern for week in year must be "w".' => 'ä»£è¡¨ä»¥å¹´æ¸åä»£æææ¸çæ¨£å¼å¿é æ¯ "w".',
  'The queue is empty.' => 'ä½åçæçºç©º.',
  'The relation "{relation}" in active record class "{class}" is not specified correctly: the join table "{joinTable}" given in the foreign key cannot be found in the database.' => 'active record class "{class}" ä¸­çéè¯ "{relation}" æªè¢«æ­£ç¢ºææ: è³æåº«ä¸­ç¡æ³æ¾å° foreign key ä¸­æçµ¦ç join table "{joinTable}".',
  'The relation "{relation}" in active record class "{class}" is specified with an incomplete foreign key. The foreign key must consist of columns referencing both joining tables.' => 'active record class "{class}" ä¸­çéè¯ "{relation}" æä¸åä¸å®æ´ç foreign key. foreign key å¿é æ¯åç§ joining tables ä¸­çæ¬ä½ææ§æ.',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key "{key}". The foreign key does not point to either joining table.' => 'active record class "{class}" ä¸­çéè¯ "{relation}" æä¸åç¡æç foreign key "{key}". foreign key æªæå°ä»»ä¸å joining table.',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key. The format of the foreign key must be "joinTable(fk1,fk2,...)".' => 'active record class "{class}" ä¸­çéè¯ "{relation}" æä¸åç¡æç foreign key. foreign key çæ ¼å¼å¿é æ¯ "joinTable(fk1,fk2,...)".',
  'The requested controller "{controller}" does not exist.' => 'è«æ±çæ§å¶å¨ "{controller}" ä¸å­å¨.',
  'The requested view "{name}" is not found.' => 'è«æ±ç view "{name}" æªæ¾å°.',
  'The stack is empty.' => 'å ççæçºç©º.',
  'The system is unable to find the requested action "{action}".' => 'ç³»çµ±ç¡æ³æ¾å°è«æ±ç "{action}" åä½.',
  'The system view path "{path}" is not a valid directory.' => 'ç³»çµ± view è·¯å¾ "{path}" ä¸æ¯ä¸åææçç®é.',
  'The table "{table}" for active record class "{class}" cannot be found in the database.' => 'è³æåº«ä¸­ç¡æ³æ¾å° active record class "{class}" å°æç table "{table}".',
  'The value for the primary key "{key}" is not supplied when querying the table "{table}".' => 'æ¥è©¢ table "{table}" ææªæä¾ primary key "{key}" çå¼.',
  'The verification code is incorrect.' => 'é©è­ç¢¼ä¸æ­£ç¢º.',
  'The view path "{path}" is not a valid directory.' => 'view è·¯å¾ "{path}" ä¸æ¯ä¸åææçç®é.',
  'Theme directory "{directory}" does not exist.' => 'Theme ç®é "{directory}" ä¸å­å¨.',
  'This content requires the <a href="http://www.adobe.com/go/getflash/">Adobe Flash Player</a>.' => 'å§å®¹éæ <a href="http://www.adobe.com/go/getflash/">Adobe Flash Player</a>.',
  'Unable to add an item whose name is the same as an existing item.' => 'ç¡æ³æ°å¢èå·²å­å¨é ç®åç¨±ç¸åçæ°é ç®.',
  'Unable to change the item name. The name "{name}" is already used by another item.' => 'ç¡æ³è®æ´é ç®åç¨±. åç¨± "{name}" å·²è¢«å¶å®é ç®ä½¿ç¨.',
  'Unable to create application state file "{file}". Make sure the directory containing the file exists and is writable by the Web server process.' => 'ç¡æ³ç¢çæç¨ç¨å¼çææªæ¡ "{file}". è«ç¢ºèªå­æ¾æ­¤æªæ¡çç®éå­å¨ä¸¦ä¸åè¨± Web server process å¯«å¥.',
  'Unable to find the decorator view "{view}".' => 'ç¡æ³æ¾å° decorator view "{view}".',
  'Unable to find the list item.' => 'ç¡æ³æ¾å°è¡¨åé ç®.',
  'Unable to lock file "{file}" for reading.' => 'ç¡æ³å°éæªæ¡ "{file}" é²è¡è®å.',
  'Unable to lock file "{file}" for writing.' => 'ç¡æ³å°éæªæ¡ "{file}" é²è¡å¯«å¥.',
  'Unable to read file "{file}".' => 'ç¡æ³è®åæªæ¡ "{file}".',
  'Unable to replay the action "{object}.{method}". The method does not exist.' => 'ç¡æ³åæ¬¡éæ¼ "{object}.{method}" åä½. éåæ¹æ³ä¸å­å¨.',
  'Unable to write file "{file}".' => 'ç¡æ³å¯«å¥æªæ¡ "{file}".',
  'Unknown authorization item "{name}".' => 'æªç¥çææ¬é ç® "{name}".',
  'Unrecognized locale "{locale}".' => 'ç¡æ³è¾¨è­çå°åè¨­å® "{locale}".',
  'View file "{file}" does not exist.' => 'åçº "{file}" ç View æªä¸å­å¨.',
  'Yii application can only be created once.' => 'Yii æç¨ç¨å¼åªè½è¢«ç¢çä¸æ¬¡.',
  'You are not authorized to perform this action.' => 'æ¨æªè¢«ææ¬å·è¡éååä½',
  'Your request is not valid.' => 'æ¨çè«æ±ç¡æ',
  '{attribute} "{value}" has already been taken.' => '{attribute} "{value}" å·²è¢«åç¨.',
  '{attribute} cannot be blank.' => '{attribute} ä¸å¯çºç©ºç½.',
  '{attribute} is invalid.' => '{attribute} ç¡æ.',
  '{attribute} is not a valid URL.' => '{attribute} ä¸æ¯ææç URL.',
  '{attribute} is not a valid email address.' => '{attribute} ä¸æ¯ææçé»å­éµä»¶å°å.',
  '{attribute} is not in the list.' => '{attribute} ä¸å¨è¡¨åä¹ä¸­.',
  '{attribute} is of the wrong length (should be {length} characters).' => '{attribute} é·åº¦é¯èª¤ (æçº {length} å­å).',
  '{attribute} is too big (maximum is {max}).' => '{attribute} æ¸å¼å¤ªå¤§ (æå¤§å¼çº {max}).',
  '{attribute} is too long (maximum is {max} characters).' => '{attribute} å¤ªé· (æå¤§å¼çº {max} å­å).',
  '{attribute} is too short (minimum is {min} characters).' => '{attribute} å¤ªç­ (æå°å¼çº {min} å­å).',
  '{attribute} is too small (minimum is {min}).' => '{attribute} æ¸å¼å¤ªå° (æå°å¼çº {min}).',
  '{attribute} must be a number.' => '{attribute} å¿é çºæ¸å­.',
  '{attribute} must be an integer.' => '{attribute} å¿é çºæ´æ¸.',
  '{attribute} must be repeated exactly.' => '{attribute} å¿é è¢«éè¦.',
  '{attribute} must be {type}.' => '{attribute} å¿é çº {type}.',
  '{className} does not support add() functionality.' => '{className} ä¸æ¯æ´ add() åè½.',
  '{className} does not support delete() functionality.' => '{className} ä¸æ¯æ´ delete() åè½.',
  '{className} does not support flush() functionality.' => '{className} ä¸æ¯æ´ flush() åè½.',
  '{className} does not support get() functionality.' => '{className} ä¸æ¯æ´ get() åè½.',
  '{className} does not support set() functionality.' => '{className} ä¸æ¯æ´ set() åè½.',
  '{class} does not have attribute "{name}".' => '{class} ä¸­æ²æåçº "{name}" çå±¬æ§.',
  '{class} does not have relation "{name}".' => '{class} ä¸­æ²æåçº "{name}" çéè¯.',
  '{class} does not support fetching all table names.' => '{class} ä¸æ¯æ´æ·åææ table åç¨±.',
  '{class} has an invalid validation rule. The rule must specify attributes to be validated and the validator name.' => '{class} æä¸åç¡æçç¢ºèªè¦å. è¦åå¿é ææè¦è¢«ç¢ºèªçå±¬æ§ä»¥åç¢ºèªå¨åç¨±.',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} å¿é çµ¦å® "model" è "attribute" æ "name" å±¬æ§å¼.',
  '{class}.allowAutoLogin must be set true in order to use cookie-based authentication.' => '{class}.allowAutoLogin å¿é è¨­çº true æè½ä½¿ç¨ cookie-based èªè­.',
  '{class}::authenticate() must be implemented.' => '{class}::authenticate() å¿é è¢«å¯¦ä½.',
  '{controller} cannot find the requested view "{view}".' => '{controller} ç¡æ³æ¾å°è«æ±ç "{view}" view.',
  '{controller} contains improperly nested widget tags in its view "{view}". A {widget} widget does not have an endWidget() call.' => '{controller} å¨å®ç view "{view}" ä¸­å«ææªè¢«é©ç¶å·¢çå¥çç widget æ¨ç±¤. {widget} widget ä¸­æ²æå¼å« endWidget().',
  '{controller} has an extra endWidget({id}) call in its view.' => '{controller} å¨å®ç view ä¸­æä¸åé¡å¤ç endWidget({id}) å¼å«.',
  '{widget} cannot find the view "{view}".' => '{widget} ç¡æ³æ¾å°éå view "{view}".',
);
