<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Home' => 'é¦é ',
  'The button type "{type}" is not supported.' => 'æéé¡å "{type}" ä¸æ¯æ´ã',
  'Are you sure you want to delete this item?' => 'ç¢ºå®è¦åªé¤éç­é ç®åï¼',
  'Delete' => 'åªé¤',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'é¡¯ç¤º {start}-{end} ç­, å± {count} ç­ã',
  'Either "name" or "value" must be specified for CDataColumn.' => 'å¿é çµ¦å® "name" æ "value" çµ¦ CDataColumnã',
  'No results found.' => 'æ²¡æç¬¦åçè³æã',
  'Not set' => 'æªè¨­ç½®',
  'Please specify the "attributes" property.' => 'è«çµ¦å® "attributes" å±æ§ã',
  'Please specify the "data" property.' => 'è«çµ¦å® "data" å±æ§ã',
  'Sort by: ' => 'æåºï¼',
  'The "dataProvider" property cannot be empty.' => '"dataProvider" å±¬æ§ä¸è½çºç©ºå¼ã',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'å±æ§æ ¼å¼ "Name:Type:Label", "Type" å "Label" çºéå¿é çã',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'æ¬ä½æ ¼å¼ "Name:Type:Label", "Type" å "Label" çºéå¿é çã',
  'The property "itemView" cannot be empty.' => '"itemView" å±¬æ§ä¸è½çºç©ºå¼ã',
  'Total 1 result.|Total {count} results.' => 'å± {count} ç­ã',
  'Update' => 'æ´æ°',
  'View' => 'æª¢è¦',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} å¿é çµ¦å® "model" è "attribute" æ "name" å±æ§å¼ã',
);
